### ISSUE TITLE
Monitor block missing

### ISSUE THREAD

**Issue by jhagrid77** [SquidDev-CC/CC-Tweaked#10]
Crash Log: 

- [https://pastebin.com/K9BAWMY0](https://pastebin.com/K9BAWMY0)

When I crash:

- Like sometimes it's a grayish blue (kind of like Discord's dark theme. BTW it's not discord showing because I don't use discord on that computer while playing MC). The game also doesn't respond. It sits there for maybe 20 seconds before CTD (Crash To Desktop).

If any additional information is required please let me know.

**Comment by SquidDev** [comment]
I'm 99% sure this is a vanilla ComputerCraft issue though I'll see what I can do. Might be possible to fix as part of #507.

**Comment by apemanzilla** [comment]
I've been getting this same crash pretty frequently, although I can't seem to reproduce it reliably. It seems to happen most frequently after using a teleport to an area that has monitors (On switchcraft 2 specifically), often crashing several seconds later.

**Comment by SquidDev** [comment]
I've recently rewritten most of the monitor code, which should fix this issue.
