### ISSUE TITLE
Make http.get coroutine safe

### ISSUE THREAD

**Issue by kepler155c** [SquidDev-CC/CC-Tweaked#104]
Calling http.get within different coroutines for the same URL will give unexpected results.

http.get will return the same file handle to both. When closed by the first routine, the second routine will error.

```
parallel.waitForAll(
  function()
    local h = http.get('https://pastebin.com/raw/YPWgiFFW')
    if h then
      local c = h.readAll()
      h.close()
      print('fn 1')
      print(c and #c or 'nil')
    end
  end,
  function()
    local h = http.get('https://pastebin.com/raw/YPWgiFFW')
    if h then
      local c = h.readAll()
      h.close()
      print('fn 2')
      print(c and #c or 'nil')
    end
  end
)
```

![screenshot from 2019-02-06 17-58-01](https://user-images.githubusercontent.com/16342516/52379734-4e7f9f80-2a39-11e9-8a4b-6446aab2a13b.png)

**Comment by Lemmmy** [comment]
For now, you could mitigate this by adding a cache buster to your URLs, a random string at the end with a URL fragment on each request like #abcd on one and #1234 on another

**Comment by SquidDev** [comment]
`http_success`/`http_failure` identifies the events via their URLs, meaning that `http.get`/`http.post` cannot distinguish between requests, and so just return on the first one.

The obvious solution here is to use numeric IDs, like `os.startTimer`/`os.startAlarm`. However, the only backwards compatible way is to chuck this on the very end, which is a tad grot - hence my reluctance to do this so far.

**Comment by osmarks** [comment]
I ran into this working on skynet, it's quite annoying but can be worked around.
