### ISSUE TITLE
Cannot equip items with NBT in turtles

### ISSUE THREAD

**Issue by osmarks** [SquidDev-CC/CC-Tweaked#106]
Minecraft 1.12.2, whatever CC: Tweaked is on Switchcraft.

It seems that if an item has any NBT, it can't be equipped on turtles.
To reproduce: name a laser in an anvil, attempt to equip it on a turtle - it doesn't work.

**Comment by SquidDev** [comment]
Working as intended.

**Comment by osmarks** [comment]
Um... why? This causes significant problems with stuff like introspection modules, which keep NBT data forever if bound.

**Comment by SquidDev** [comment]
Introspection modules keeping NBT data when they shouldn't is a separate bug, and already has an issue filed on the CC:T repo.

As far as changing NBT by enchanting, setting the label, etc... - this has always been a limitation of CC. Equipping and then unequipping an item should give leave you with the original, and that is no longer the case when you start ignoring NBT.

**Comment by osmarks** [comment]
Maybe it should keep the NBT instead of ignoring it, then? Or is that not possible?
