### ISSUE TITLE
Add chunkloading features to the Command Computer.

### ISSUE THREAD

**Issue by fatboychummy** [SquidDev-CC/CC-Tweaked#107]
The command computer is such a useful tool for many things, but one thing that might be really helpful for players would be to add a feature which allows for chunkloading, remotely.

Why?  Simple, really.  Say you make an adventure map, and you need to summon an entity somewhere that triggers some elaborate redstone contraption...  but the player's render distance is lower than the setting you used while testing, and that chunk isn't loaded!  The chunk isn't loaded, and the entity isn't summoned.  

Now you may say, "there are other mods for that."  And you would be telling the truth.  However, why should I use a mod which *permanently* loads a chunk, just to load a chunk I may only need loaded for 5 seconds?  It just causes unnecessary resource usage, and possibly lag if your computer is not the greatest.

What I propose is a way to load a chunk, remotely, through two (or three) simple commands.

1. `commands.loadChunk(<int coord_x>,<int coord_z>)`

2. `commands.unloadChunk(<int coord_x>,<in coord_z>)`

The last command may be unneeded, but eh why not include it.

3. `commands.isChunkLoaded(<int coord bla you get it x>,<z>)`

The idea behind the "how" of the loading:

`loadChunk`:  Immediately loads a chunk at the position specified (either chunk-specific coordinates, or block position coordinates, you decide).

`unloadChunk`: Remove the chunk from the active loading "list" (or whatever).  ie: dont unload it immediately, as if a player is currently occupying it it may cause errors.  Just let minecraft take care of it.  Optionally, there could be an override to immediately unload it, or not.

`isChunkLoaded`: Returns 2 if a chunk is loaded by a player, 1 if it is loaded via commands, and 0 if it is not.  Optionally, just a boolean yes or no.

**Comment by vpontin** [comment]
An option in config (similar to use or not fuel/enabling http) to auto load nXn chunks (different values for turtles and computers) could be VERY interesting.

**Comment by SquidDev** [comment]
[Added in Minecraft 1.13.1](https://minecraft.gamepedia.com/Commands/forceload).
