### ISSUE TITLE
Ability to copy new computers within a disk drive

### ISSUE THREAD

**Issue by kepler155c** [SquidDev-CC/CC-Tweaked#108]
To quickly duplicate computers, turtles, etc. It would be nice if you were able to label a computer in a disk drive. Right now, to duplicate a turtle, you have to place the turtle, label the turtle, then put in a drive to copy over files.

**Comment by Lemmmy** [comment]
I thought you could label them like disks?

**Comment by Lemmmy** [comment]
![](https://shitty.download/CIU0I.png)
![](https://shitty.download/rdz9x.png)

**Comment by kepler155c** [comment]
Since the computer does not have an ID yet, it doesn't give you a mount where you can copy files.

**Comment by Lemmmy** [comment]
Yeah, I remember talking with SquidDev about this back in PB2 days; I can't remember exactly what he said but perhaps a solution would be to give a computer an ID once it is labelled.

**Comment by zachary-D** [comment]
Couldn't you also fill up all the IDs on a server by using a turtle to place a computer, start it (`computer.turnOn()`), break it and repeat?

**Comment by kepler155c** [comment]
What is the purpose of having to label a computer before it saves files? There are very few occasions where this could be useful - but I've seen many people lose work due to forgetting to label a computer.

IMO - labels should be optional. This would also reduce confusion for new users as they will not lose work the first time they attempt to program something (not knowing about the label command).

**Comment by SquidDev** [comment]
@kepler155c Yeah, this is something I've been thinking for a while. It's a really weird design decision to reset them, given that CC has always strived to be beginner friendly.

That said, it's not a change I want to take lightly. People who have used the mod before expect it to act in a specific way, so I definitely want to make sure it's something people agree with first :).

**Comment by lupus590** [comment]
You could always bundle [autolabel](https://github.com/CC-Hive/Main/blob/master/src/AutoLabel.lua) with CC, perhaps with a config option to not have it run on startup.

**Comment by nevercast** [comment]
This also affects Neural Computers from Plethora.
