### ISSUE TITLE
`run code` function does not work in the editor when using it on floppy disk .lua file

### ISSUE THREAD

**Issue by Skreperiukas** [SquidDev-CC/CC-Tweaked#1094]
### Minecraft Version

1.16.x

### Version

1.100.3

### Details

Everything is told in the title so I will proceed with recreation:
1. Place computer (I used advanced one) and a disk drive next to it.
2. Insert the floppy disk.
3. `cd disk` - > `edit hi`.
4. Type any code which should work. Example: `term.write("Hello")`.
5. Press `run` function.
6. It gives: "No such program" inside the editor.
![adawdfawfafd](https://user-images.githubusercontent.com/40837822/167625649-591dd650-83fc-4920-a5dd-2f04257bdf6a.PNG)

**Comment by Wojbie** [comment]
I can't do better testing on phone but i determined what if you run
`cd disk - > edit hi.` then this issue will happen but if one does
`edit disk/hi` while at root folder then it will not. I must have missed something with current directory when updating run option in edit in last commit.

EDIT: My dummy. Forgot to prepend path given to shell.openTab with `/` to indicate its absolute path.

**Comment by Wojbie** [comment]
I stand corrected. I didn't forget.

https://github.com/cc-tweaked/CC-Tweaked/pull/723/commits/afc67ec85fb71b71a4e19e6a7f5d232ac5d3bdf6
