### ISSUE TITLE
Pocket Computers Auto-Start

### ISSUE THREAD

**Issue by Flexico** [SquidDev-CC/CC-Tweaked#1097]
Just like computers and turtles that were running when the chunks unload start back up when it's reloaded, if a player logs out with a pocket computer running in their inventory, that pocket computer should start back up when they log back in!

**Comment by Lupus590** [comment]
I believe that it should, which might make this a bug.

It needs to be in a player's inventory otherwise it will turn itself off after a few seconds, a bag in the player's inventory is likely not good enough, a chest or such will not work.

**Comment by Flexico** [comment]
I've had it happen many times, I have to flip it to my hotbar and click it every time I log in! Pretty sure it's never turned on by itself at all!
