### ISSUE TITLE
How to make a .nft image

### ISSUE THREAD

**Issue by Pain80** [SquidDev-CC/CC-Tweaked#1098]
I want to draw things using cc.image.nft, but i can't figur out how to make images using this format. I can't search about .nft because there is just a bunch of crypto stuff on google.

**Comment by Lupus590** [comment]
The built-in paint program makes them.

Also, GitHub's discussions feature is a better place for this type of question than issues.

**Comment by Pain80** [comment]
Thanks, and also sorry im pretty new to github
