### ISSUE TITLE
/computercraft commands don't work in sponge

### ISSUE THREAD

**Issue by Lemmmy** [SquidDev-CC/CC-Tweaked#11]
They just print track <help> or computercraft <help:track> - another potentially useful thing would be to print the coords of the pc when doing track in console, since otherwise there is literally no way to find where the laggy computers are

**Comment by SquidDev** [comment]
> They just print track or computercraft help:track

Can you provide a screenshot? Setting up a Sponge in a dev env is a bit of a faff, so I'd like to know what I'm looking for first.

> print the coords of the pc when doing track in console

I'll look into adding something like this - I left if of the chat display as there isn't really room. You can always do `/computercraft dump #<id>` (note the `#`). It should display some info (including coords) on the provided computer.

**Comment by Lemmmy** [comment]
![](https://shitty.download/smk1.png)
![](https://shitty.download/G3sy.png)

**Comment by Lemmmy** [comment]
sry mouse in way

**Comment by SquidDev** [comment]
This was an issue with LuckPerms. Running `/lp user SquidDev permission set computercraft.command.computercraft true` appears to fix it.
