### ISSUE TITLE
AgriCraft CCSA Peripheral Not Working

### ISSUE THREAD

**Issue by thehappybub** [SquidDev-CC/CC-Tweaked#110]
## Problem

CC: Tweaked Computers and Turtles are unable to wrap to adjacent Computer Controlled Seed Analyzers (CCSA). Not a problem with regular CC. I do not see the issue posted on the AgriCraft GitHub issues page, but I will post it there too.

## Reproduction

peripherals.getNames() yields "attempt to index global 'peripherals' (a nil value)

Similarly, a program 'startup' on a computer placed on top of the CCSA block:

analyzer = peripheral.wrap("bottom")
analyzer.analyze()

Returns "attempt to index global 'analyzer' (a nil value)

## Useful information to include:
 - Minecraft version 1.12.2
 - CC: Tweaked version 1.14

**Comment by SquidDev** [comment]
That's really weird that you're able to get it working with normal ComputerCraft - it looks like the CC integration was removed some time ago, and only OC support remains. I'll have a fiddle and see what I can find.

**Comment by thehappybub** [comment]
Thanks! Such speedy replies!

**Comment by fatboychummy** [comment]
```peripherals.getNames() yields "attempt to index global 'peripherals' (a nil value)```

This is expected, the proper command is `peripheral.getNames()`

Remember that being exact is important when coding, and small issues (like adding an s where it shouldn't be) will cause errors like that to appear.

**Comment by SquidDev** [comment]
Closing as sadly there is nothing I can do here - Agricraft needs to add back their ComputerCraft compatibility.
