### ISSUE TITLE
adding the ability to have your turtle click on blocks like tinker's castingtable and interact like a player would

### ISSUE THREAD

**Issue by LoneWolfGmer** [SquidDev-CC/CC-Tweaked#1102]
I'm thinking of an interact command. or some kinda function that allows you to interact with the tinker's construct mod. for instance, you got a tinker's craft or TC for short. tank and your drawling stuff out of it. what if you could program the turtle. with like a turtle.RightClick or turtle.LeftClick  API or something so that you could have the turtle collect the cast or empty the basin and store it within its inventory. this would remove the need to have say a player stand in front of it clicking 2-3 times for one block or something over and over. you could make it for gold turtles for all I care. just it would be really useful and help make it so turtles could interact with TC casting tables and basins a lot easier. if there is some way to do this already then I'm not aware of it and just ignore all this XD

## Useful information to include:
 - Explanation of how the feature/change should work.
 - Some rationale/use case for a feature. My general approach to designing new features is to ask yourself "what issue are we trying to solve" and _then_ "is this the best way to solve this issue?".

**Comment by SquidDev** [comment]
I'm afraid this won't be added. See https://github.com/cc-tweaked/CC-Tweaked/issues/125.

**Comment by Lupus590** [comment]
For tinkers smelteries, you can already use the generic item and fluid APIs to move items into the smelter, fluids out of that into the casting table and items out of the table into your storage system. A turtle doesn't need to do it with a click method.

**Comment by SirEdvin** [comment]
btw, for fabric and forge there is mods that provides right click for turtles (or even left click in case of fabric). [Advanced Peripherals](https://www.curseforge.com/minecraft/mc-mods/advanced-peripherals) for forge and [Turtlematic](https://www.curseforge.com/minecraft/mc-mods/turtlematic) for fabric respectively.

**Comment by LoneWolfGmer** [comment]
> btw, for fabric and forge there is mods that provides right click for turtles (or even left click in case of fabric). [Advanced Peripherals](https://www.curseforge.com/minecraft/mc-mods/advanced-peripherals) for forge and [Turtlematic](https://www.curseforge.com/minecraft/mc-mods/turtlematic) for fabric respectively.

None of those are for 1.12 though.

**Comment by LoneWolfGmer** [comment]
> For tinkers smelteries, you can already use the generic item and fluid APIs to move items into the smelter, fluids out of that into the casting table and items out of the table into your storage system. A turtle doesn't need to do it with a click method.

What might someone do to get said actions to work ?

**Comment by Lupus590** [comment]
> None of those are for 1.12 though.

Even if a clicking turtle gets added to CC:T, CC:T is no longer going to MC 1.12 so you're not going to get your clicking turtle from here anyways.

> > For tinkers smelteries, you can already use the generic item and fluid APIs to move items into the smelter, fluids out of that into the casting table and items out of the table into your storage system. A turtle doesn't need to do it with a click method.
> 
> What might someone do to get said actions to work ?

You said you are on 1.12, which means that you don't have CC:T's generic peripherals. Instead, you can use Plethora's generic peripherals. The API is very simular, but you will want to look at [Plethora's website](https://plethora.madefor.cc/) for docs instead.
