### ISSUE TITLE
Pakui for cc:tweaked

### ISSUE THREAD

**Issue by KaziiTheAvali** [SquidDev-CC/CC-Tweaked#1103]
A computercraft documentation pakui book would be neet with the ability to optionally have pakui mod included. this will contain all the up to date documentation at least. maby some tips and tricks aswell for using some of the items. this will help for offline play aswell as those who doesn't want to go to a wiki for stuff.

**Comment by SquidDev** [comment]
Do you mean [Patchouli](https://www.curseforge.com/minecraft/mc-mods/patchouli)?

**Comment by SirEdvin** [comment]
If you talk about patchouli, I wouldn't recommend this, because patchouli are pretty bad at dealing with code and lot of texts.

Probably, alternative is something more specific like https://www.curseforge.com/minecraft/mc-mods/markdownmanual

**Comment by Lupus590** [comment]
> Probably, alternative is something more specific like https://www.curseforge.com/minecraft/mc-mods/markdownmanual

This would be more ideal since CC:T's docs already use markdown.
