### ISSUE TITLE
Crash on Startup with Enchantment Descriptions

### ISSUE THREAD

**Issue by NielsPilgaard** [SquidDev-CC/CC-Tweaked#1108]
### Minecraft Version

1.18.x

### Version

1.19-1.100.6

### Details

Make a Minecraft 1.19 Forge instance with both Enchantment Descriptions and CC: Tweaked

`Exception in thread "main" java.lang.module.ResolutionException: Modules io.netty.common and computercraft export package io.netty.util.collection to module enchdesc`

Removing CC: Tweaked resolves the issue.

**Comment by SquidDev** [comment]
I think we probably need to wait until Jar in Jar is merged into Forge and use that to bundle netty instead.

**Comment by SquidDev** [comment]
I take it back. JiJ is a better long-term fix, but I'm also an idiot.

**Comment by NielsPilgaard** [comment]
lol alright then 😄
