### ISSUE TITLE
Computers are not receiving all modem messages

### ISSUE THREAD

**Issue by kepler155c** [SquidDev-CC/CC-Tweaked#111]
Turtles and neurals work fine. Computers only receive a subset of modem traffic (possibly some other related issues as well as GPS seems to be non--reliable lately.

To test: I opened port 999 on the modem and listened for traffic (on the switchcraft server, about 25 computers send out a beacon on that port every 10 seconds). The computer was only able to see traffic from 8 computers while the turtles and neurals can see 25.

**Comment by SquidDev** [comment]
I've gotta say, this is the weirdest bug - the code for computer-based modems is pretty much identical to that for turtle upgrades or neural interfaces.

**Comment by SquidDev** [comment]
Kepler also mentioned that "turtles with standard modems were no longer able to get GPS positioning". This is probably related, so worth looking into at the same time.
