### ISSUE TITLE
NPE Crash on world creation

### ISSUE THREAD

**Issue by NielsPilgaard** [SquidDev-CC/CC-Tweaked#1111]
### Minecraft Version

1.18.x

### Version

cc-tweaked-1.19-1.100.7

### Details

When I tried to create a new world, my game crashed.

https://gist.github.com/NielsPilgaard/67ee5acd70aa87e2ebc04f51c474a302

**Comment by SquidDev** [comment]
Would you be able to post your full log? Not expecting anything, but this definitely worked a few days ago and I don't see anything obvious in the Forge changelog at least.

**Comment by NielsPilgaard** [comment]
Sure, once I manage to reproduce this again 😅 Please consider this invalid for now, I'll reopen if it happens again.
