### ISSUE TITLE
Printer and Disk Drive UI is Inaccessible

### ISSUE THREAD

**Issue by promitheas-nikou** [SquidDev-CC/CC-Tweaked#1113]
### Minecraft Version

1.18.x

### Version

1.100.6

### Details

[2022-06-16-3.log](https://github.com/cc-tweaked/CC-Tweaked/files/8917889/2022-06-16-3.log)

Cannot access printer and disk drive UI (but they still work, items can be inserted with hoppers and they interact as expected with computers).
Tested with forge 40.1.0 with no other mods.

**Comment by SquidDev** [comment]
Thanks for reporting! I believe this is the same behaviour as #1109. Hoping to get a release out soonish, but downgrading to 1.100.5 should also fix it.
