### ISSUE TITLE
Error spam due to - "this.lockCode" is null

### ISSUE THREAD

**Issue by IceFoxyy** [SquidDev-CC/CC-Tweaked#1118]
### Minecraft Version

1.18.x

### Version

1.100.6

### Details

Hey,

i am running a Multiplayer Server, i dont know what caused the error, but it kinda spamms my log dramaticly. 
Its persistent after a reboot

here is the Paste bin to the Log: https://pastebin.com/aqaWKZmY

How to get rid of the error?

**Comment by SquidDev** [comment]
Thanks for reporting! I believe this is the same behaviour as #1109. Hoping to get a release out soonish, but downgrading to 1.100.5 should also fix it.

**Comment by IceFoxyy** [comment]
> Thanks for reporting! I believe this is the same behaviour as #1109. Hoping to get a release out soonish, but downgrading to 1.100.5 should also fix it.

Thank you very much, i wish you the best of luck in doing so :D
