### ISSUE TITLE
Reconfigurable terminal sizes

### ISSUE THREAD

**Issue by Lemmmy** [SquidDev-CC/CC-Tweaked#112]
This was previously mentioned on https://github.com/dan200/ComputerCraft/issues/188 and https://github.com/dan200/ComputerCraft/issues/213, though both ideas were quickly tossed out. I think that the latter issue there is referring more to increased pixel density, rather than an increased terminal size.

I think that, at the very least, the maximum monitor size should be reconfigurable server-side (in blocks). Regular terminals (Computers and Pocket Computers, in characters) would be nice too, though with the obvious note that they may get too large for users' screens. Turtles (and Plethora's Neural Interfaces) are obviously unconfigurable (or rather, pointlessly difficult to implement) due to their GUI.

If I recall correctly, the terminal size used to be reconfigurable, though I'm unsure why that functionality was removed (if it ever existed in the first place). 

To be clear: I am not requesting that terminals can be dynamically resized in any way, but rather, configurable server-side.

**Comment by SquidDev** [comment]
As mentioned in the second issue there, it's definitely something I'd like to add, but I'd quite like to optimise the network traffic of monitors and computers first. We currently send the whole terminal each time, which ends up being rather expensive.

**Comment by SquidDev** [comment]
As discussed elsewhere, it would be nice to have configuration options for the the maximum size of a monitor (albeit in blocks, rather than pixels). Again, something I'd like to delay until terminal syncing is more efficient.

**Comment by Jummit** [comment]
Is this possible as of #453 ?

**Comment by SquidDev** [comment]
Yeah, I guess?
