### ISSUE TITLE
Rewriting our README

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaked#113]
When development of CC:T first started I added several points to the README.

> For a more stable experience, I recommend checking out the original mod.
> 
> In fact, CC:T aims to be a nurturing ground for various features, with a pull request against the original mod being the end goal.

CC:T was never really meant to be a long term thing, it was always a stop-gap solution until development of the original mod was more steady. However, 15 months later <sub>(I think, I've never been good at counting)</sub>, I think it's probably time to re-evaluate this position.

<details>
<summary>Me blithering on about rationale</summary>
As far as stability goes, CC:T has fixed an awful lot of bugs which plague the original mod (well, at least plagued SwitchCraft). For instance - monitor threading safety, dupe bugs with shulkers, interaction with permissions plugins. While CC:T has had (and still has) its fair share of issues, I don't think it's fair to describe CC as substantially more stable any more.

6 months ago, I added issue and PR templates to the repo which asked people to submit PR/issues against the original mod where at all possible. While this was probably a reasonable request then, and was even 3 months ago, I've done a lot of cleanup of CC's internals since then, which means merging a PR targetting CC into CC:T (or vice virsa) is getting pretty hard. As we update to 1.13, this situation is only going to get worse.

If CC development ever kicks up again, I will try my utmost hardest to get the important changes merged, but for now I don't think this is worth mentioning.
</details>

## Changes to make
 - Remove the whole "use CC for a more stable thing". I still want to link towards the original mod, but with different words.
 - Remove the "please submit to CC" section of the issue/PR templates and contributing section of the README.
 - Reword the entire **What?** paragraph. The first half is now inaccurate, the second half feels a little disingenuous.

As part of this, I think it's worth re-evaluting what our README actually says. What's the point of this mod, do we have any "killer features". It would be possible just to say "an actively-developed fork of CC", but I feel there's more to it.

Anyway, I suck at words, so feedback welcome from all!

**Comment by SquidDev** [comment]
On a related note, might be worth picking a new versioning scheme - I don't really want to be stuck on `1.80pr1.*` forever.

**Comment by Lustyn** [comment]
Dropping the 1.80pr versioning scheme and possibly changing names to something more fitting than "CC Tweaked" (CC Next? Reloaded? It isn't just a tweak now.) might be worth doing upon the move to 1.13 (if we come to that). Definitely worth rewording most of the README as most of that information isn't true now and I don't think we'll see a time that it is true again.

Time to move on from unforked CC, I guess.

**Comment by Lemmmy** [comment]
> I still want to link towards the original mod, but with different words.

CC: Tweaked is a fork of [ComputerCraft](https://github.com/dan200/ComputerCraft)

> do we have any "killer features"

The 'Features' section is pretty great. The only minor change I can suggest is "the latest alpha" → "[the latest alpha](https://minecraft.curseforge.com/projects/computercraft/files/2478952/download) of the original mod"

> On a related note, might be worth picking a new versioning scheme

I think starting over on something more in line with other mod versioning, possibly even semver, and starting on 2.0.0, would be nice. I think for 1.13 trying to pretend to still be anywhere close to the original versioning scheme for the mod would be inappropriate.

> but we'd need to check this works with mods which have dependencies on specific CC versions.

I don't think this will be a problem for 1.13.

> possibly changing names

To be honest, I personally still think that 'CC: Tweaked' is accurate. Unless you _do_ want to take the mod in a vastly different direction (with lots of new features, or complete overhauls to existing ones), it's still similar in nature to CCTweaks.


Overall, I think there's a lot that could be said with regards to the original mod, still. I think there are some valuable points raised in the [first post](https://forums.computercraft.cc/index.php?topic=4.msg5#msg5) on the new forums - explaining how the inactivity of the original project has lead to certain changes in design and attitude in the fork, etc.
