### ISSUE TITLE
Drag & Drop not working

### ISSUE THREAD

**Issue by superjaja05** [SquidDev-CC/CC-Tweaked#1130]
### Minecraft Version

1.18.x

### Version

1.100.8

### Details

Hey! So drag&drop doesn't seem to work for me , every times i try to do it, i get errors in the logs and nothing appears in-game

Also it seems to work with other people using the same modpack

logs:
[latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/9066906/latest.log)
(check line 1392 for the last error before i sent logs)

**Comment by SquidDev** [comment]
Haha, that's embarrassing. Thank you for reporting!

**Comment by superjaja05** [comment]
Any idea of when the version with the fix will be available on curseforge?

_sorry i dunno if its gonna re-open the issue or not lmao i don't use github often_

**Comment by SquidDev** [comment]
No clue I'm afraid. It's really a it happens when it happens.

**Comment by superjaja05** [comment]
Ah i see, alrighty then, hopefully it'll be on curseforge soon
