### ISSUE TITLE
Rubidium and CC causes a monitor rendering issue

### ISSUE THREAD

**Issue by VenomiXeD** [SquidDev-CC/CC-Tweaked#1132]
### Minecraft Version

1.18.x

### Version

1.100.8

### Details

![ccbug](https://user-images.githubusercontent.com/32819948/178086352-b4b9d4be-b35f-40da-95d2-c11851f8a516.png)
There is an issue with Rubidium. Simply putting 2 different monitors with two separate monitors. The content from a screen is duplicated from one screen to all other screens. Running any clear command or such does not appear to work. And removing the monitors will give a very weird stretched screen.

Reproduction should be relatively easy. Install rubidium and CC. Then proceed to set up a computer, hook a monitor and write something to it. Then construct a new monitor. Attaching a computer to it and the bug should be seen.

**Comment by SquidDev** [comment]
Monitors and mods which mess with Minecraft's rendering tend not to work well together. You might get better results by switching the monitor renderer (see https://github.com/cc-tweaked/CC-Tweaked/wiki/Monitor-renderers) to use VBOs.
