### ISSUE TITLE
[1.19] Game Crashes on launch

### ISSUE THREAD

**Issue by Saereth** [SquidDev-CC/CC-Tweaked#1134]
### Minecraft Version

1.19.x

### Version

cc-tweaked-1.19-1.100.8

### Details

Re added CCTweaked to the pack and it's crashing on load up. Forge version 41.0l.98, here is the crashlog

https://www.toptal.com/developers/hastebin/qevetemuwo.rb

Let me know if I can provide any additional info, thanks!

**Comment by SquidDev** [comment]
Forge have made several breaking changes in recent builds and I haven't updated to them yet. Downgrading to Forge 41.0.63 should fix things.

**Comment by SquidDev** [comment]
Fixed in 4a273ae8e5e3bbdb5addce0364f361c68ddc1990.
