### ISSUE TITLE
Are turtles abled to use/equip/act with/on things or not?

### ISSUE THREAD

**Issue by Nebdir** [SquidDev-CC/CC-Tweaked#1135]
Hey there,
I'm opening this request to combine multiple issues around this case to get a new discussion to find a solution or refuse this, but generally find an answer to these questions for the future.

## Historical
#58 suggested an API to improve the interaction of turtles with the environment. This issue was cloned to dan200/ComputerCraft#564.
cc-tweaked/cc-tweaked#1008 also suggests the use of buckets with cauldrons. 
cc-tweaked/cc-tweaked#854 is suggesting to use places with glass bottles.
In cc-tweaked/cc-tweaked#627 a discussion is running about adding an option to configure redstone parts.

## use cases
since the grass path came out and bee's appeared, more and more cases are popping up, where turtles can't interact with things or blocks. 

Another place is modding, skyblock is working around this with other mods to use items like hammers in automation.
Many Mod items are not player bound and could be helpful in automation. Still many of them would be overpowered, like using tinkers stuff, I mean come on? 5x5 hammering through the ground is not enough? 

another approaching need is to configure contraptions. Often some blocks are used to create special action by hitting or interacting.
I remember a mod uses redstone hit on a block of coal to create a special redstone dust for crafting. Another thing was about hitting a portal controller with colored wool to change destinations, I remember that this where possible I cc, but I'm unsure if this was another mod that made this possible. 

## Things to be aware of
Fabric and Forge are orbiting each other, both are used and have reasons for their existence.  But both do things differently. The Fluid API is a good example of this case. a decision here is affecting fabric too. The clear line is: does the API has to change or not, this would also affect scripts greatly.

## What to do to maybe resolve this In a good 

First of all the restrictions on the usage of tools do have a good reason, but what about opening the possibilities a little for modpacks?
Like default should be the vanilla tools. In modpacks the creators could decide themself if this makes sense here. 

About using items, it's clear that turtles are robots, nothing too intelligent. therefore complex actions won't be theirs. But simple right-click with a block or item from their inventory can be in range. 

## What is that that would be changed?
that's to be discussed.

**Comment by SquidDev** [comment]
My stance has always been that this is best served by a peripheral mod, such as [Plethora](https://plethora.madefor.cc) or [Advanced Peripherals](https://docs.srendi.de/). Using arbitrary items or blocks is a sufficiently powerful feature that it should be gated behind an upgrade, and I don't want to add such a thing to core CC:T.
