### ISSUE TITLE
Placing Monitors Crashes Client

### ISSUE THREAD

**Issue by StriderTR** [SquidDev-CC/CC-Tweaked#1137]
### Minecraft Version

1.19.x

### Version

1.19-1.100.8

### Details

First off, fantastic mod, been using CC a VERY long time, and followed it over to Tweaked. It has long been on my top mods list and just feels wrong playing without it. Sadly, I ran into this same issue I can't seem to correct.

I just installed CC "cc-tweaked-1.19-1.100.8" and placing a monitor crashes the game every time and does not allow the world to be loaded again until CC is removed. 

Putting CC back in after loading the world with it removed loads fine, until you enter the area where the monitor you originally placed that caused the initial crash, then the game crashes again.

Crash started on Forge 41.0.63. Currently trying different forge versions but some other mods I use don't play well with forge versions beyond 41.0.63.

Original crash and exit report attached (single file).

Any ideas?

Thank you in advance!

[crash-2022-07-20_03.11.15-client.txt](https://github.com/cc-tweaked/CC-Tweaked/files/9147895/crash-2022-07-20_03.11.15-client.txt)

**Comment by SquidDev** [comment]
```
java.lang.NullPointerException: Cannot invoke "com.mojang.blaze3d.vertex.VertexFormat.m_86020_()" because "vf" is null
	at net.optifine.shaders.SVertexBuilder.preDrawArrays(SVertexBuilder.java:390) ~[preview_OptiFine_1.19_HD_U_H8_pre10.jar%23192!/:?] {re:classloading}
```

Looks like Optifine broke things again. Removing it should fix things for the time being.

**Comment by StriderTR** [comment]
Yeah, I can't believe I missed that, was staring me right in the face. In my defense it was very late after a very long day. lol

I just did a bit of messing around before I have to go to work and got a few more details, just in case their useful to anyone.

1. The game crashes with both the standard and advanced monitors. 

2. However, it only crashes IF you connect those monitors to a computer. Just placing a monitor in the world does nothing, the game runs just fine. As soon as you place a computer in contact with it, that generates the crash. 

3. If you don't place any monitors, CC runs just fine in all other aspects that I can see so far. 

4. Both current OptiFine versions for 1.19 cause the crash. Removing OptiFine does indeed fix it.

5. If you accidentally place a connected monitor in your world, and you don't want to remove OptiFine bust still want CC, just take out CC, load back in, go to where you placed the monitor and place any other block in that space. Log out, put CC back in, and then load back into your world. 

I am going to continue using CC without the monitor until the issue gets worked out, I like CC too much to play without it, I can live without the monitors for now. :) 

Thanks for pointing out the snake that would have bit me SquidDev. My observational skills at that time of night seem to be suffering in my old age. lol
