### ISSUE TITLE
Peripheral Crash

### ISSUE THREAD

**Issue by ElBullet** [SquidDev-CC/CC-Tweaked#1138]
### Minecraft Version

1.16.x

### Version

1.99.0

### Details

I was playing Sky Factory One Version 1.0.4 and placed a Chest next to my Turtle. Then the game crashed. It also crashes when I place the Chest first and then the turtle next to it.

Crash Report: [crash-2022-07-20_20.02.47-server.txt](https://github.com/cc-tweaked/CC-Tweaked/files/9152633/crash-2022-07-20_20.02.47-server.txt)

Screenshot taken from Amulet Editor after Crash:
It doesn't load textures from mods so the turtle has the fallback texture.
Below the Turtle is a half slab just like the rest of the floor. Below the slabs is just void.

![image](https://user-images.githubusercontent.com/24289499/180052289-56236b99-5a97-46bb-90f5-3b7ef5c9357b.png)

If you need any more information, i'll gladly provide it.
Thanks in advance for looking into this.

**Comment by SquidDev** [comment]
See https://github.com/cc-tweaked/CC-Tweaked/issues/972. Please update Supplementaries to the latest version.
