### ISSUE TITLE
Issue with CC: Tweaked and Rubidium + Oculus shaders

### ISSUE THREAD

**Issue by matpratta** [SquidDev-CC/CC-Tweaked#1140]
### Minecraft Version

1.18.x

### Version

1.100.8

### Details

So I'm using Rubidium and Oculus in place of Optifine on my 1.18.2 install, and Monitors have a glitch where I can see through the map instead of viewing their contents. I tried changing it to VBO, but it didn't work either, I could see some outline where text was supposed to be, but it was broken.

Tried the same with CC: Restitched, Sodium and Iris and it worked just fine. I'm not sure if there was any change done on CC: Restitched to support this, but the I noticed there were some differences on the `MonitorTextureBufferShader.java` file between the two mods.

This is how it looks like on CC: Restitched
![2022-07-22_16 54 33](https://user-images.githubusercontent.com/532195/180518666-3707fffa-7142-4716-a0a1-6fa51ccd9eae.png)

This is how it looks like on CC: Tweaked
![2022-07-22_16 54 29](https://user-images.githubusercontent.com/532195/180518745-ddafb730-f3ec-4fb5-917a-ec080fcfe20c.png)

Also, I noticed that there's some logic that detects Optifine and fallbacks into VBO mode, it's not on by default but maybe that could be related? I know from experience that on 1.16.5 CC: Tweaked was working just fine with Optifine.

**Comment by SquidDev** [comment]
>  I noticed there were some differences on the MonitorTextureBufferShader.java file between the two mods.

Yeah, the monitor changes CC:R have made are incompatible with Optifine, so it's a bit of a pick your poison.

We might be able to use the Iris's text sink API in CC:T too, which might fix the colour issues. Everything else, no clue I'm afraid.

**Comment by matpratta** [comment]
Hmmm since Optifine is incompatible with both Rubidium and Oculus, what if you detect the presence of Rubidium (or Oculus) and then use the Restitched way of rendering? I'm not familiar with Java or how MC modding works, but maybe it could alleviate the issue?

**Comment by SquidDev** [comment]
> Hmmm since Optifine is incompatible with both Rubidium and Oculus, what if you detect the presence of Rubidium (or Oculus) and then use the Restitched way of rendering?

So some bits we absolutely can (like the aforementioned text sink API). Other bits (especially the different implementation of `DirectVertexBuffer`) are much harder to do without duplicating lots of code and becoming a maintenance nightmare, so I need to evaluate if it's worth it.

**Comment by matpratta** [comment]
Got it, thanks for looking at the issue though! I really like CC: Tweaked and recently switched to 1.18.2 with ATM7, so couldn't use Optifine. I'm sure others are on same boat too...

**Comment by SquidDev** [comment]
Had a look at this, and made little progress. I'm not going to dedicate any more time to this, but will happily merge a PR if someone can get it working - I've left the code on the [feature/forge-iris](https://github.com/cc-tweaked/CC-Tweaked/tree/feature/forge-iris) branch.

**Edit:** I lied. Should now work.

**Comment by matpratta** [comment]
@SquidDev where is the branch? I want to give it a shot but couldn't find the branch you mentioned... Also, thanks for taking a look at it! 😄 

**Edit:** just pulled the code from the 1.18.X branch and built it myself, worked perfectly! Great work there!

**Comment by matpratta** [comment]
@SquidDev spent a bit of extra time testing this on the mc-1.18.x branch and it seems to be working quite well, didn't notice any significant performance differences to be fair (at least none compared to normal gameplay with shaders on). Is there anything I can help on this to increase its chances of going live?

Again, thank you so much for the work you did here, having CC:T working with shaders on Oculus is amazing, specially with Optifine currently not working on the latest 1.18.2 Forge... :)

**Comment by chiconanni** [comment]
Hey @MatheusMK3, can you share the solution? Im on the same boat! Thanks in advance! (by the way  are you Brazilian?)

**Comment by matpratta** [comment]
Hi @chiconanni! This issues should be fixed on the latest release of CC: Tweaked by now (1.100.10).
And yep, I'm Brazilian :)

**Comment by chiconanni** [comment]
Oi @MatheusMK3, obrigado pelo retorno. Então, eu testei ontem com esta versao usando as ultimas versoes do oculus e rubidium no MC 1.19.2, e estava transparente, alterando o refresh hate. Em Best ele simplesmente crasha o jogo, em tbo ele funciona mas fica transparente e em vbo ele fica piscando. Isso tudo usando forge 43.1.47 e Complementary Shaders 4.6 (mas qualquer outro que testei deu o mesmo problema). Se tu não te importares, poderia me passar (isso se nao for muito complicado, mas tenho uma boa base de programação), o que tu fizeste para atingir este resultado? A propósito, sou de Porto Alegre! Obrigado desde já!

**Comment by SquidDev** [comment]
Yeah, 1.19 is borked in the currently released version. Only 1.18 works.

**Comment by chiconanni** [comment]
Ty both for your reply!
