### ISSUE TITLE
[1.19] Crash on load due to mixins- Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: net.minecraftforge.client.model.data.IModelData

### ISSUE THREAD

**Issue by ProsperCraft** [SquidDev-CC/CC-Tweaked#1141]
### Minecraft Version

1.19.x

### Version

cc-tweaked-1.19-1.100.8

### Details

Crash-
https://gist.githubusercontent.com/ProsperCraft/30e8acf4724961e442a9168050829e9c/raw/0c8be058fbfa26ee56dfe3cca8e475a5cd59c9ee/gistfile1.txt
Logs-
[latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/9177005/latest.log)
[debug.log](https://github.com/cc-tweaked/CC-Tweaked/files/9177006/debug.log)

Reproduced with only CC

**Comment by ToddRundgren** [comment]
What version of Forge are you using?

I can confirm that I get the same issue with the latest build on anything above 41.0.63. Running it with any Forge 1.19 version above that leads to a crash.

**Comment by ProsperCraft** [comment]
40.10.110...

I guess they made a breaking change in .63 and .93

I will just remove it from the pack and add it back when CC updates.

**Comment by ToddRundgren** [comment]
For now, that would be the most prudent course, unless you want to compile the mod from source. I'm going to be doing that, so I'll update everyone on whether or not I was able to get that to work.

**Comment by ToddRundgren** [comment]
Just compiled from source. Can confirm that it works in Forge 41.0.110.

**Comment by ProsperCraft** [comment]
Nice, now we just need to get a release on curseforge.

**Comment by PhamKun** [comment]
> Just compiled from source. Can confirm that it works in Forge 41.0.110.

Hi can you share the compiled file for 1.19.
