### ISSUE TITLE
Mod wont load with 1.19 (not 1.19.1) newest forge version

### ISSUE THREAD

**Issue by PhamKun** [SquidDev-CC/CC-Tweaked#1143]
### Minecraft Version

1.19.x

### Version

cc-tweaked-1.19-1.100.8.jar

### Details

Need an update so it can run on newer version of Forge, Currently, it keeps give out error that mod isnt loading correctly.

Reproduce: Just install the mod with forge newest version to 1.19 (not 1.19.1)

**Comment by SquidDev** [comment]
1.100.8 was targetted at a pre-release build of Forge. You'll either need to downgrade to Forge 41.0.63 or update to 1.19.1.
