### ISSUE TITLE
Option to disable turtle waterlogging?

### ISSUE THREAD

**Issue by Justinjah91** [SquidDev-CC/CC-Tweaked#1152]
I like that we have the ability to waterlog turtles now, but I would also love to have an option to disable it. Preferably, this would be done via the settings API so it could be done per turtle (or even per program), but I have no idea if that would be possible.

My mining program is set up to block off holes in the tunnel so that mobs cant get into the mine from natural caverns and stuff. This includes blocking off water and lava sources. But when the turtle hits a big pocket of water like an aquifer, the sheer number of source blocks present means that the turtle itself becomes waterlogged, generating a new source block INSIDE my mining tunnel. This subsequently washes away all of the torches, allowing mobs to spawn (which kinda defeats the purpose).

**Comment by SquidDev** [comment]
I'm afraid it's staying as is. I don't think it makes much sense to have a setting which changes how physics works.

**Comment by Justinjah91** [comment]
Not even as a server wide config option?

**Comment by SquidDev** [comment]
Oh, definitely not! The problem then is that programs then rely on specific config options, and suddenly you can no longer reuse code - it's just a nightmare for everyone.

**Comment by SirEndii** [comment]
Time for a fork
`CC:T no waterlog` 😄

**Comment by piprett** [comment]
> Time for a fork `CC:T no waterlog` 😄

Gonna be hard due to all the 1.13 stuff beeing mashed into one commit

**Comment by SirEndii** [comment]
You can just disable the block state
No need for commit cherry picking
