### ISSUE TITLE
`os.date` format issues

### ISSUE THREAD

**Issue by Ocawesome101** [SquidDev-CC/CC-Tweaked#1157]
### Minecraft Version

1.19.x

### Version

1.100.9

### Details

The [CC:T Wiki](https://tweaked.cc/module/os.html#v:date) page for `os.date` notes that "The format string takes the same formats as C's strftime function."  However, while this is _mostly_ true, `%l` (and perhaps others) are missing.

`%l` is relative to the current timezone; the UTC-only `%I` format _is_ present.  Curiously, CC:T's implementation of `%I` appears to behave like `%l` when the date format is not prefixed with a `!`.

The 24-hour equivalents `%k` and `%H` are identically incorrect - `%k` is nonexistent while `%H` only behaves correctly with `!` in the format string.

**Comment by Ocawesome101** [comment]
it appears this is more relevant to the [Cobalt](/squiddev-cc/cobalt) repository?

**Comment by SquidDev** [comment]
Nah, CC:T [has its own implementation](https://github.com/cc-tweaked/CC-Tweaked/blob/mc-1.16.x/src/main/java/dan200/computercraft/core/apis/LuaDateTime.java).

**Comment by Ocawesome101** [comment]
ok so i've started looking at this and i don't understand what the `offset` parameter to `LuaDateTime.format` even _does_ - it isn't used except in recursive calls to the same method.

**Comment by SquidDev** [comment]
I honestly have no clue either. I probably added thinking it'd be needed, and then failed to remove it.

**Comment by SquidDev** [comment]
@Ocawesome101 Did you have an opportunity to look any further at this?

Do you have any documentation for `%l` and `%k`? They don't appear [in the C standard](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf) and PUC Lua doesn't support them - are you sure they're not a glibc extension or something?

**Comment by SquidDev** [comment]
Would you also be able to clarify what you meant with `%I` and `%H` (would be useful to have a test case!). I just compared against PUC Lua and they appear the same.

![A screenshot of calling `os.date` on PUC Lua and CCEmuX, with the result of %H and %I being the same.](https://user-images.githubusercontent.com/4346137/198855352-7df3d68a-8bf9-49e6-a0b6-7f5afe9ba32e.png)

**Comment by Ocawesome101** [comment]
huh, TIL that PUC Lua supports prefixing with a `!`.  i don't recall that being in the manual, but then again i haven't looked at that section in great detail.

**Comment by SquidDev** [comment]
Yep, just done some more tests in other timezones. The current behaviour is correct.
