### ISSUE TITLE
1 Peripheral shows up as 2 on a Computer

### ISSUE THREAD

**Issue by GravityCY** [SquidDev-CC/CC-Tweaked#1161]
### Minecraft Version

1.18.x

### Version

1.100.9

### Details

**LOGS**: https://mclo.gs/Ew8zF8i

I have no idea how to recreate this, but I've been playing with this exact modpack for a while and just now I've noticed this bug. I did have some other wacky bugs in this same modpack;
Singular chests were detected as double chests as a peripheral and I couldn't fix it unless I broke the chests and modem and replaced everything

![1](https://user-images.githubusercontent.com/49225419/188614845-53f41ff9-d45d-4e50-8dcd-6d139750264c.png)
![2](https://user-images.githubusercontent.com/49225419/188614864-229f412b-a6b8-4112-8b64-8537870c5d97.png)
![3](https://user-images.githubusercontent.com/49225419/188615161-3e84ce92-d13a-4c9b-966c-f086465dd3b0.png)
![4a](https://user-images.githubusercontent.com/49225419/188614878-fa3b2a6b-d408-4f86-88eb-ecbe2510d670.png)

**Comment by SquidDev** [comment]
What does the output of the `peripherals` program show?

**Comment by GravityCY** [comment]
I figured out what's causing it, is this an intended feature?
Should multiple modems do this, cause this feels wrong

![image](https://user-images.githubusercontent.com/49225419/188668170-869f94ea-fff7-41bd-94b5-836ec0171c2c.png)
![image](https://user-images.githubusercontent.com/49225419/188668217-12b69d53-35f2-4d2f-a75b-9be20c72ab56.png)
![image](https://user-images.githubusercontent.com/49225419/188668306-7ac2a84a-caaf-4071-8fb3-aaa3f38e9a5a.png)
![image](https://user-images.githubusercontent.com/49225419/188668339-f59c7473-7da0-4ae2-b198-ba77aab9d7e6.png)

**Comment by SquidDev** [comment]
Thanks! I did wonder if this was the case.

Yeah, the `peripheral` API doesn't de-duplicate peripherals, so having multiple modems will show them multiple times.

**Comment by GravityCY** [comment]
Okay, thank you. I guess that's my bad then, although that is a bit weird I feel, but maybe that's just me.
