### ISSUE TITLE
snowy grass isn't updating

### ISSUE THREAD

**Issue by DragonCraft5** [SquidDev-CC/CC-Tweaked#1167]
### Minecraft Version

1.18.x

### Version

1.100.9

### Details

if you move a turtle over snowy grass it will not update and wont make it too normal grass
![Minecraft_ 1 18 2 - Singleplayer 12 09 2022 17_53_05](https://user-images.githubusercontent.com/113373665/189705696-630e3e67-12bc-495c-90ac-6c3fc590effa.png)

**Comment by roland-a** [comment]
I'd like to be able to try fixing this bug.

**Comment by roland-a** [comment]
I believe I fixed it now with this new pull request
