### ISSUE TITLE
Using monitors with Oculus causes crash

### ISSUE THREAD

**Issue by ThePotato97** [SquidDev-CC/CC-Tweaked#1184]
### Minecraft Version

1.19.x

### Version

1.100.10

## Log

https://mclo.gs/ohvmKqI

## Installed Mods

Rubidium 0.6.2
Oculus 1.2.8

## Repro

1. Place a Computer.
2. Place a Monitor adjacent to the Computer.
3. Crash.

**Comment by SquidDev** [comment]
Odd! I'm not able to reproduce the crash (though Oculus is broken on 1.19 for other reasons apparently). Would you be able to grab the hs_err_pid49552.log file mentioned in those logs?

**Comment by ThePotato97** [comment]
> Odd! I'm not able to reproduce the crash (though Oculus is broken on 1.19 for other reasons apparently). Would you be able to grab the hs_err_pid49552.log file mentioned in those logs?

https://mclo.gs/IlAMOBe

**Comment by ThePotato97** [comment]
Fixed by https://github.com/cc-tweaked/CC-Tweaked/commit/c8e15f201c3c9a74524f3adc4dd9a89d96fbefb8
![javaw_AWYhnvgf9x](https://user-images.githubusercontent.com/10260415/196042392-d392b12f-be9c-4f66-b015-f6076c922bef.jpg)
