### ISSUE TITLE
Add please Cyrillic symbols support

### ISSUE THREAD

**Issue by zimavi** [SquidDev-CC/CC-Tweaked#1186]
Add Cyrillic symbols support as in another mod “Open Computers”. I think it would be helpful for Russian-speaking people!

**Comment by Lupus590** [comment]
Related: #860

**Comment by SquidDev** [comment]
As Lupus says, there's been some discussion about this before in #860. I'd definitely love to see it in CC:T, but was never able to work out an API which wouldn't end up a little messy.
