### ISSUE TITLE
file reading behaving weird when running in edit

### ISSUE THREAD

**Issue by Walle123** [SquidDev-CC/CC-Tweaked#1192]
### Minecraft Version

1.18.x

### Version

1.100.10

## This bug only appears when the code is run in ingame ide
The following code should read the file and print the content:
```
file = fs.open("myFile","r")
print(file.readAll())
file.close()
```
but it **does not**

To make it print the content of the file i need to add any print statement anywhere before the printing of the file content.
Like this:
```
file = fs.open("myFile","r")
print("hello world")
print(file.readAll())
file.close()
```

The first print will actually not be visible on the screen.

**Comment by SquidDev** [comment]
![A screenshot of a ComputerCraft computer with the code from the OP running.](https://user-images.githubusercontent.com/4346137/198681095-e130c6ef-d639-49f2-9b8b-84036d1e33ec.png)

I'm afraid I can't reproduce this at all. I assume you're not running a custom OS or shell at all?

**Comment by Walle123** [comment]
![grafik](https://user-images.githubusercontent.com/80287602/198871686-c283d38b-6e66-41f0-b36c-e309a793c367.png)
So i tested it again. This only occurs on my advanced turtle.

**Comment by SquidDev** [comment]
Ahhhhhhhh. Because it the text overflows and pushes everything up! Fantastic, thank you!

**Comment by Wojbie** [comment]
Opse. Didn't consider this might happen on pockets and turtles.. I guess this text will need to be shortened.
