### ISSUE TITLE
[1.13.2] Crash holding a pocket computer

### ISSUE THREAD

**Issue by vpontin** [SquidDev-CC/CC-Tweaked#122]
## Useful information:
 - Minecraft version: 1.13.2
 - Forge version: 25.0.44
 - CC: Tweaked version: cc-tweaked-1.13.2-1.80pr1.14.jar
 
Well i tried today to test what was working on 1.13.2 beta build, created a large biomes world in creative, put a advanced computer and a turtle and tried to right click each one. Nothing happens.

Then i got a pocket computer (from creative menu) and tried to put in main hand. Crash.

The report: https://paste.dimdev.org/iletomuhix.coffeescript (weird url)
Latest.log: https://paste.dimdev.org/udunutiyav.sql

**Comment by vpontin** [comment]
Tried the new build on curse (cc-tweaked-1.13.2-1.81.0.jar), when i tried to hover into a pocket computer, got this crash:

https://paste.dimdev.org/mewelahoqu.coffeescript

**Comment by SquidDev** [comment]
Should be fixed.
