### ISSUE TITLE
Config option for speaker volume

### ISSUE THREAD

**Issue by folke13** [SquidDev-CC/CC-Tweaked#1223]
I suggest adding a config option to allow louder speakers in the world. Current limit is 3 which does work if you're close to the speaker but if you want to create something that resembles a loudspeaker or warning system it is not close to enough. A config field (default to 3) but increasable to a much greater value would be perfect.

**Comment by SquidDev** [comment]
I'm afraid I won't be adding this. I generally try to avoid adding config options which change how computers or peripherals behave, as that means programs start relying on specific config options being set, which is a bit of a compatibility nightmare.

**Comment by SquidDev** [comment]
Let us ignore that button mashing.
