### ISSUE TITLE
Show turtles on JourneyMap

### ISSUE THREAD

**Issue by ejm554** [SquidDev-CC/CC-Tweaked#1228]
- I'd love to be able to see my turtles on JourneyMap. 
- Although turtles seems to be more akin to special furnaces & redstone devices, Turtles _move_ like mobs. It, therefore, seems reasonable that they could be visible on JourneyMap and similar mods. 
- Indeed, I find sometimes find myself looking for my turtles on my maps!
- This option would be very helpful for observing the status of a program that makes the turtle cover a lot of ground. It would also be nice to be reminded (or simply informed) where my turtle is at without the use of the `/computercraft` commands.
- Someone on JM's Discord suggested this same idea a couple months ago, and one of the mods/devs said that this feature would probably come from the CC end of things.

![Screenshot of Discord conversation](https://user-images.githubusercontent.com/26723535/204019458-dce05d64-9421-4d1d-9993-46b4f767dd97.png)

**Comment by Lemmmy** [comment]
I believe CC typically shies away from addings other mod APIs to the build process, even as soft-dependencies, unless absolutely necessary. I could imagine the behaviour for a JourneyMap integration would become increasingly complex (for example, how do you manage who sees which turtles? How would this work in multiplayer?) - and that it may be better suited for an external peripheral mod that bridges the two mods together.

**Comment by Twisted-Code** [comment]
I would consider this a "Nice to have", but the other two comments (above and below this one) have said pretty much everything else I have to say currently.

**Comment by SquidDev** [comment]
I'm going to tag this as "wontfix" for now. I want to think about this a bit more. As Lem says, there's a lot of design decisions here, and I feel this could spiral into a lot of work for a pretty niche feature.

I wonder if a more useful feature would be a separate JourneyMap mod which can just highlight user-configured list of block entities? It's a _little_ cheaty (would could abuse it as a limited x-ray mod), but would be more generic than something CC-specific.
