### ISSUE TITLE
speaker plays distorted static noises instead of real sounds

### ISSUE THREAD

**Issue by De8264** [SquidDev-CC/CC-Tweaked#1230]

**Comment by Wojbie** [comment]
This is not really a bug.. i feel this should be in discussions not issues.. Anyhow.

You are attempting to play non-audio file as audio file? `rom/startup.lua` is normal lua program so trying to play it like audio file will lead to issues. 
You can use [music.madefor.cc](https://music.madefor.cc/) to convert your music files to dfpwm to then play with `speaker` program. CC does not come with any sounds in rom folder. It is up to player to get them.
