### ISSUE TITLE
New operators request

### ISSUE THREAD

**Issue by norperz** [SquidDev-CC/CC-Tweaked#1234]
New operators support?
+=
-=
/=
Makes doing some simple math easier
(instead of fuel = fuel + 1, I could do fuel += 1)

**Comment by MCJack123** [comment]
Unfortunately this is impossible without rewriting a major part of the Lua language, which is out of scope for the mod. Go play Roblox if you're looking for a Lua dialect with combined operation assignment operators.

If you *really* want it, [PRs welcome (to Cobalt, the Lua VM)](https://github.com/SquidDev/Cobalt/pulls).

**Comment by norperz** [comment]
funny you say that, I actually develop stuff on roblox that's really the reason why I asked for it. Thank you though.
