### ISSUE TITLE
Tweaked.cc source links not working

### ISSUE THREAD

**Issue by Commandcracker** [SquidDev-CC/CC-Tweaked#1238]
### Minecraft Version

1.19.x

### Version

*

### Details

I didn't know where to put this issue so i made it here.

Currently source links for the section "Generic Peripherals" and "Peripherals" in the [documentation](https://tweaked.cc) are pointing to a 404 page.

**Comment by SquidDev** [comment]
This appears to affect all Java source files - we're spitting out the wrong file path!
