### ISSUE TITLE
Crash viewing CCTweaked items/blocks in UI with Optifine installed

### ISSUE THREAD

**Issue by MrFuzzihead** [SquidDev-CC/CC-Tweaked#1239]
### Minecraft Version

1.19.x

### Version

1.101.1

### Details

Only occurs with Optifine also installed as far as I can tell. Either in creative mode or using JEI, try to go to either ComputerCraft creative tab or search @cctweaked and game will crash
[crash-2022-12-02_13.53.36-client.txt](https://github.com/cc-tweaked/CC-Tweaked/files/10143954/crash-2022-12-02_13.53.36-client.txt)

**Comment by SquidDev** [comment]
```
java.lang.NoSuchMethodError: 'boolean net.minecraft.client.renderer.block.model.BakedQuad.hasAmbientOcclusion()'
	at net.minecraftforge.client.model.IQuadTransformer.copy(IQuadTransformer.java:95) ~[forge-1.19.2-43.1.43-universal.jar%23173!/:?] {re:classloading}
```

This is an Optifine bug: they don't support the latest version of Forge. You can probably downgrade to Forge 43.1.1, though really I'd recommend [switching to Occulus](https://modrinth.com/mod/oculus) instead.

**Comment by User3624** [comment]
one thing;
all these issues marked as duplicate to this issue are technically a different issue, this one is talking about even clicking on the computercraft TAB, but the other ones are talking about placing down a turtle. They are different issues caused by the same reason.

**Comment by SquidDev** [comment]
Yeah, my bad - it does appear that the original Optifine crash was fixed in OptiFine HD U I1. The last few are a separate issue and only occur when running Forge 43.2.0 (https://github.com/sp614x/optifine/issues/7261).
