### ISSUE TITLE
`os.date` 12 hour formatting

### ISSUE THREAD

**Issue by MikaylaFischler** [SquidDev-CC/CC-Tweaked#1243]
### Minecraft Version

1.16.x

### Version

1.100.8

### Details

`os.date` formatting is incorrect for 12 hour options

Examples for 12:16:20 PM:

- `os.date("%r")` returns incorrectly `00:16:20 PM` when it should return `12:16:20 PM` (which it does correctly in CraftOS-PC 1.100.5 v2.6.6)
- `os.date("%I")` returns incorrectly `00` when it should return `12` (which it does correctly in CraftOS-PC 1.100.5 v2.6.6)

**Comment by SquidDev** [comment]
Fixed! Thanks for the report.
