### ISSUE TITLE
`loadfile` should read files with binary mode

### ISSUE THREAD

**Issue by walksanatora** [SquidDev-CC/CC-Tweaked#1246]
this small change would bring CC-T a bit closer to the real lua intepreter because modules and scripts keep their binary data instead of replacing it all with `?`

just replace
`r` with `rb` in [bios.lua](https://github.com/cc-tweaked/CC-Tweaked/blob/mc-1.19.x/projects/core/src/main/resources/data/computercraft/lua/bios.lua#L467)

**Comment by walksanatora** [comment]
interesting
even opening in rb mode is not consistent with lua
because `0x00` is replaced with \000
nvm that was `cc.pretty` formatting it since nul has no charachter

**Comment by walksanatora** [comment]
but after running a few CraftOS programs with this small change
it would appear nothing breaks
(though a full test should probally be conducted)

**Comment by SquidDev** [comment]
Unfortunately, this breaks program behaviour whenever a program uses a non-ASCII character. For instance, here's a program which creates an `image.lua` file which contains some of the drawing characters:

```lua
local out = fs.open("image.lua", "w")
out.write([[print("]])
out.write("\x87\x83\x8b")
out.write([[")]])
out.close()

local function run(path, mode)
  local h = fs.open(path, mode)
  local contents = h.readAll()
  h.close()
  local ok, err = load(contents, "@" .. path)
  if ok then ok, err = pcall(ok) end
  if not ok then printError(err) end
end

run("image.lua", "r")
run("image.lua", "rb")
```

When running the resulting program under text and binary mode, we get the following output:

![A screenshot of a ComputerCraft terminal running the above program. The first line displays a continuous line of drawing characters, while the second line is interspersed with UTF decoding errors](https://user-images.githubusercontent.com/4346137/207011520-800f1010-ee82-4f1e-a9d7-75b044980f48.png).

I've vaguely mentioned this in #1233, but I think the correct solution here really is just to remove text mode entirely, and have binary mode be the only mode. This is pretty much how Lua works on UNIX systems anyway. But that is a breaking change, and I'm not sure how large the repercussions of that would be, so unlikely to happen any time soon.

**Comment by walksanatora** [comment]
write in text mode, read in binary mode
write in binary mode, read in text mode
(the source of all pains of the world)

**Comment by walksanatora** [comment]
also by modifying the example you gave (replacing `w` with `wb`)
the `r` prints `???` and `rb` prints the properly formatted string

**Comment by walksanatora** [comment]
![image](https://user-images.githubusercontent.com/47339836/207073578-7f076ef9-f787-4404-90c1-cf4c8c087fbe.png)
