### ISSUE TITLE
Issue with starting the new 1.19.3 version in a dev environment

### ISSUE THREAD

**Issue by SirEndii** [SquidDev-CC/CC-Tweaked#1247]
### Minecraft Version

1.19.x

### Version

1.19.3 1.102.0-SNAPSHOT maven repo

### Details

Heyo
I started porting AP, so I updated CC to the latest 1.19.3 version I found on the squiddev repository.
But I have issues with mixins errors when I try to run `runClient`. 
This is my log: https://gist.github.com/SirEndii/47933c4c60c832e4ab84c2671cf43b96

I know that CC is currently not public available. But yeah - just curios.

**Comment by SquidDev** [comment]
Oh wow, this really was broken. I'm sure I tested this all at some point, but that was possibly on my older multi-loader branch. Thank you for reporting!

I've pushed new jars for Forge/Fabric. I think `./gradlew assemble --refresh-dependencies` will pick this up, or if not I'm afraid you'll have to dig around in the Gradle cache.

**Comment by SirEndii** [comment]
Thanks, I'll quick try it

**Comment by Lordmau5** [comment]
I know this issue is closed but since I have the exact same one but on **1.19.2** I thought I'd pop on by.

Any chance it could get fixed for that version as well or is that considered EOL?

**Comment by SquidDev** [comment]
Which version of CC:T were you using? I just set up a development environment which depends on CC:T 1.101.1, and it appears to run fine.

**Comment by Lordmau5** [comment]
1.19.2-forge only has the 1.102.0-SNAPSHOT on your maven, so that's the one I tried with

Should've mentioned Forge beforehand, sorry 😁

**Comment by SquidDev** [comment]
Oh, don't use the snapshot versions. Those contain the multi-loader work, which was never stabilised for 1.19.2. [Here's the old using instructions](https://github.com/cc-tweaked/CC-Tweaked/tree/v1.19.2-1.101.1#using).

**Comment by Lordmau5** [comment]
Oh sweet, thank you! I'll get that tested in a bit then :D - Kinda makes sense that I can't find the old 1.19.2 version within `cc.tweaked` when it's actually in `org.squiddev` haha

**Comment by Lordmau5** [comment]
Yep that worked! Thank you so much! I'm not sure if this might be worth putting in a pinned Discussions thread in case others get a similar issue?
