### ISSUE TITLE
Textutils unable to serialize a specific lua table

### ISSUE THREAD

**Issue by Shiranuit** [SquidDev-CC/CC-Tweaked#1248]
### Minecraft Version

1.19.x

### Version

[1.19.2] 1.101.1

### Details

This issue is related to a bug in Cobalt, see this PR [Cobalt #61](https://github.com/SquidDev/Cobalt/pull/61)

Textutils is unable to serialize the table in the following example
```lua
local table = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,[24]={}}
local serialized = textutils.serialize(table) -- Error: Cannot serialize table with repeated entries
```

It might be good to also include the PR [Cobalt #62](https://github.com/SquidDev/Cobalt/pull/62) since this reduces inconcistency with the table length operator.

**Comment by SquidDev** [comment]
Have merged both PRs on the Cobalt side (thank you so much Shiranuit for those!). Leaving this issue open until we update Cobalt on the CC side.

Probably worth doing a maintenance release for 1.16.5/1.18.2/1.19.2 with this fix bundled.
