### ISSUE TITLE
turtle.use() revival

### ISSUE THREAD

**Issue by fatboychummy** [SquidDev-CC/CC-Tweaked#125]
[So this was requested a while ago, but moved to dan200's CC repo](https://github.com/SquidDev-CC/CC-Tweaked/issues/58).  However, dan200's repo is kind of... dead now, and I figured this could use a revival.  

A useful feature for us turtle users would be a `turtle.use` function.  Why?

Well, first off, it helps the newbies out a lot.  When I first started in computercraft and I was making a farmer bot, I didnt know that you had to call `turtle.dig` above the block I wanted to hoe.

Also, it can open up some opportunities for more features in the future.  If you set it up so it acts like a right-click, you could also right-click on blocks to change their configuration.  

`turtle.dig` could keep it's normal function, so backwards compatibility is still good.  I just feel it would be much easier to understand if there was `turtle.use`

**Comment by znepb** [comment]
This would be great if it would act as right-clicking. Like placing a turtle, and using `turtle.use` and turning a bucket to milk, if there is a cow in front. This would also be good as a replacement to `turtle.place` for water and lava buckets.

**Comment by SquidDev** [comment]
My stance has always been that this is best served by a peripheral mod, such as plethora. Using arbitrary items is a sufficiently powerful feature that it should be gated behind an upgrade, and I don't want to add such a thing to core CC:T.
