### ISSUE TITLE
Turtles cannot equip netherite tools

### ISSUE THREAD

**Issue by Voxelstice** [SquidDev-CC/CC-Tweaked#1254]
### Minecraft Version

1.18.x

### Version

cc-tweaked-1.18.2-1.101.0

### Details

Turtles can equip diamond tools, but not netherite tools.

Reproduction steps:
- Place a turtle anywhere.
- Right click on the turtle.
- Put any netherite item on the slot the turtle has currently selected.
- Run the following on the computer: `equip 1 left`
- The computer will return: `Item not equippable`

**Comment by SquidDev** [comment]
This is intended. By default, the only tools which can be used with turtles are diamond ones. There's not really much point, on the basis that turtles instabreak blocks anyway.

It is possible to add new tools via a datapack (see for instance [how the current tools are defined](https://github.com/cc-tweaked/CC-Tweaked/blob/mc-1.19.x/projects/forge/src/generated/resources/data/minecraft/computercraft/turtle_upgrades/diamond_pickaxe.json)). Will try to create a full datapack today with everything in.

**Comment by SquidDev** [comment]
[And done!](https://github.com/cc-tweaked/netherite-tools/)

**Comment by Merith-TK** [comment]
Yeah currently the Netherite Tools is only default in CC:R (quilt/fabric) due it slipping in there somewhere (I don't even know where the original commit is at this point despite it slipping in when I was actively maintaining it)

They are effectively the exact same as an Diamond tool turtle, just bragging rights that you have enough netherite to spare on an turtle carelessly
