### ISSUE TITLE
term.blit() will interpret " " as white in text argument

### ISSUE THREAD

**Issue by LDDestroier** [SquidDev-CC/CC-Tweaked#126]
When using term.blit() in CC:Tweaked, all instances of " " in the text argument will default to white, whereas all instances of " " in the background argument will default to black.

The expected behavior is for both to default to black. In fact, that's how CCEmuX handles it.

## Useful information to include:
 - Minecraft 1.12.2 (SwitchCraft)
 - CC: Tweaked 1.80pr1.12 (SwitchCraft)
 - How to reproduce:
1. Open minecraft with CC:Tweaked mod
2. Type in term.blit("text", "    ", "    ") into the lua interpreter
3. Do the same, but in CCEmuX.

This is in SwithCraft:
![blitbug-switchcraft](https://user-images.githubusercontent.com/10407518/53292095-99185000-378b-11e9-94d2-7518fa4983e2.png)

This is in CCEmuX:
![blitbug-ccemux](https://user-images.githubusercontent.com/10407518/53292100-a0d7f480-378b-11e9-8a62-3db0dbf40c9d.png)

**Comment by SquidDev** [comment]
Not strictly invalid, but I don't have the ability to move this issue across organisations.
