### ISSUE TITLE
Crashing when rendering a turtle

### ISSUE THREAD

**Issue by DeltaGlitch** [SquidDev-CC/CC-Tweaked#1263]
### Minecraft Version

1.19.x

### Version

1.101.1

### Details

My game keeps crashing when ever I'm in near a turtle, like a crafty turtle, or mining turtle. My friend found this issue out when he went to a village and got booted out of the server. I had Not Enough Crashes so I can see that it said CC: Tweaked was the issue. I tested it in creative and it was correct. I placed down a crafty turtle and I crashed. Here's my crash log https://bytebin.lucko.me/ebSktopR1F

It seems like only a client thing, since the server never crashed. I'll provide a modlist once I've typed them all out.

I do have Optifine, but I don't have Supplementaries. I've tried downgrading my optifine version from preview4 to preview3 and it has not worked. I've downgraded cc tweaked to 1.101.0 and it has not work, and I don't think any further downgrading of either mod would work. I would very much appreciate some help with this.

**Comment by Wojbie** [comment]
Does it crash when you remove Optifine?

**Comment by DeltaGlitch** [comment]
I'm not sure actually. When I tried joining a world without optifine, it gave me an error about something. I forgot what it was though, sorry. I don't think it's optifine though however. I've played cc: tweaked with optifine multiple times and I've never crashed even if there was turtle right in front of me.

**Comment by DeltaGlitch** [comment]
Here's my list of mods. I'm using Forge 43.2.0 and Minecraft 1.19.2 if that helps.

Ad_Astra-Forge-1.19.2-1.11.9  additional-guns-0.7.2.1.19  additional-guns-0.7.2.1.19  AdvancementPlaques-1.19.2-1.4.7 
AkashicTome-1.6-22  alexsmobs-1.21.0  allurement-1.19-3.0.0  apexcore-1.19.2-7.3.0  appleskin-forge-mc1.19-2.4.2
architectury-6.3.49-forge  areas_1.19.2-3.1  ArmorStatues-v4.0.2-1.19.2-Forge  ars_creo-1.19.2-3.1.0  ars_nouveau-1.19.2-3.5.1
AutoRegLib-1.8-54  balm-4.5.3  BarteringStation-v4.0.2-1.19.2-Forge  bendy-lib-forge-2.1.1  bettercombat-forge-1.4.5+1.19
blueprint-1.19.2-6.1.0  Bookshelf-Forge-1.19.2-16.1.10  Botania-1.19.2-436-FORGE  botarium-forge-1.19.2-1.7.12
caelus-forge-1.19.2-3.0.0.6  catalogue-1.6.3-1.19  cc-tweaked-1.19.2-1.101.1  celesteconfig-1.19.2-1.0.0  cgm-1.2.8-1.19
ChickenChunks-1.19.2-2.9.4.97-universal  citadel-2.1.1-1.19  ClearDespawn-forge-1.19.2-1.1.10  cloth-config-8.2.88-forge
CodeChickenLib-1.19.2-4.3.0.470-universal  Coins-Forge-1.19.2-10.1.5  collective-1.19.2-5.25  compactmachines-5.1.0
configured-2.0.1-1.19.2  connectivity-1.19.2-3.4  Controlling-forge-1.19.2-10.0+7  CosmeticArmorReworked-1.19.2-v1a
CraftPresence-2.0.0-alpha.1+1.19.2-universal  CraftTweaker-forge-1.19.2-10.0.22  crashutilities-6.0
create_enchantment_industry-1.19.2-for-create-0.5.0.f-1.1.6  create-1.19.2-0.5.0.f  createaddition-1.19.2-20221106a
createbb-2.0.1  createcafe-1.0.1-1.19.2  createchunkloading-1.3.0-forge  create-confectionary1.19.2_v1.0.8
create-stuff-additions1.19.2_v2.0.1c  curios-forge-1.19.2-5.1.1.0  Decorative+Blocks-forge-1.19.2-3.0.0
dimdungeons-168-forge-1.19.0  Dimensional=Paintings-1.19.2-1.4.0  Ding-1.19.2-1.3.0  dragonfight-1.19.2-2.4
dummmmmmy-1.19-1.5.5  easy_villagers-1.19.2-1.0.0  EasyAnvils-v4.0.5-1.19.2-Forge  EnchantingInfuser-v4.2.2-1.19.2-Forge
EnchantmentDescriptions-Forge-1.19.2-13.0.8  endrem_forge-5.2.1-R-1.19.X  entityculling-forge-1.5.2-mc1.19.2
fantasydice-1.19.2-7.2.0  FarmersDelight-1.19-1.2.0  farsight-1.19.2-2.1  ferritecore-5.0.2-forge  FpsReducer2-forge-1.19.2-2.1
framework-0.3.3-1.19  GatewaysToEternity-1.19.2-3.0.2  geckolib-forge-1.19-3.1.36  goblintraders-1.8.0-1.19.2
gravestone-1.19.2-1.0.1  GreaterEye-Forge-1.19.2-1.4.6  hexcasting-forge-1.19.2-0.10.2  Highlighter-1.19.1-1.1.4
Iceberg-1.19.2-forge-1.0.49  immersive_armors-1.4.2  infusedfoods-1.19.2-7.2.0  ironchest-1.19.2-14.2.7
ItemLocks-Forge-1.19.2-1.3  iwannaskate-1.0.1  Jade-1.19.1-forge-8.4.1  JadeAddons-1.19.2-forge-3.2.0  jeed-1.19.2-1.17
jei-1.19.2-forge-11.4.0.285  JustEnoughResources-1.19.2-1.1.1.185  kotlinforforge-3.7.1-obf  locallooks-1.3.0-1.19.2
lootbeams-1.19.2-beta-sept1322  lootr-1.19-0.3.21.58  LuckPerms-Forge-5.4.46  mahoutsukai-1.19.2-v1.34.35
majrusz-library-1.19.2-2.17.0  majruszs-enchantments-1.19.2-1.7.6  Mekanism-1.19.2-10.3.5.473  moreoverlays-1.21.3-mc1.19
NaturesCompass-1.19.2-1.9.7-forge  NekosEnchantedBooks-1.19-1.8.0  NoChatReports-FORGE-1.19.2-v1.5.0
notenoughcrashes-4.1.8+1.19.2-forge  Nullscape_v1.2a  NyfsQuiver-1.19.2-0.7.4  open-parties-and-claims-forge-1.19.2-0.15.1
origins-classes-forge-1.2.0  origins-forge-1.19.2-1.5.0.6-all  origins-plus-plus-1.7.1  out_of_sight-1.19.2-1.0.2
Paraglider-1.19.2-1.7.0.1  Patchouli-1.19.2-77  paucal-forge-1.19.2-0.5.0  Pehkui-3.6.0+1.19.2-forge  Placebo-1.19.2-7.0.1
player-animation-lib-forge-0.4.0-test1  polylib-forge-1900.0.2-build.27  polymorph-forge-0.45.0+1.19.2
portabletanks-1.1.6-forge-mc1.19  preview_OptiFine_1.19.2_HD_U_I1_pre4  PuzzlesLib-v4.3.12-1.19.2-Forge  Quark-3.3-371
rebind_narrator-forge-1.19.2-2.0.0  repurposed_structures_forge-6.3.5+1.19.2  resourcefulconfig-forge-1.19.2-1.0.14
resourcefullib-forge-1.1.17  secondchangeforge-1.19-1.5.1  shieldexp-1.19.2-1.0.2  ShoulderSurfing-Forge-1.19.2-2.2.14
simplyswords-forge-1.32-1.19.x  skillcloaks-1.19.2-1.0.8  sliceanddice-2.0.0  sophisticatedbackpacks-1.19.2-3.18.29.719
sophisticatedcore-1.19.2-0.5.15.142  soulshards-1.19-1.3.3  spiderstpo-1.19.2-2.0.4  Strictly+Origins+1.19.2+v3.2.5
StylishEffects-v4.3.2-1.19.2-Forge  supermartijn642configlib-1.1.6b-forge-mc1.19  supermartijn642corelib-1.0.19a-forge-mc1.19
TerraBlender-forge-1.19.2-2.0.1.129  ToastControl-1.19.2-7.0.0  ToolBelt-1.19-1.19.6  TravelersTitles-1.19.2-Forge-3.1.2
trofers-1.19.2-3.1.0  unstructured-0.5.6-FORGE  upgradedcore-1.19.2-4.1.0.0-release  upgradednetherite-1.19.2-5.1.0.5-release
voicechat-forge-1.19.2-2.3.13  waystones-forge-1.19-11.1.0  worldedit-mod-7.2.12  WWOO-FORGE-3.1.9+1.19.x.jar
Xaeros_Minimap_FP22.16.0_Forge_1.19.1  xercamusic-1.19.2-1.0.0  YungsApi-1.19.2-Forge-3.8.1

**Comment by SquidDev** [comment]
See #1239. This is an Optifine bug: they don't support the latest version of Forge. You can probably downgrade to Forge 43.1.1, though really I'd recommend [switching to Occulus](https://modrinth.com/mod/oculus) instead.
