### ISSUE TITLE
Remote full block modems do not expose peripherals

### ISSUE THREAD

**Issue by Lemmmy** [SquidDev-CC/CC-Tweaked#1278]
### Minecraft Version

1.19.x

### Version

1.102.0-fabric

### Details

(Tested on 3047e3cdf42607a873ed326dfcdce80448067453)

Peripherals cannot be wrapped via remote full block modems, or at least they are not reporting adjacent peripherals sometimes.

![image](https://user-images.githubusercontent.com/858456/210001533-acf26c83-2bff-47cc-9c16-987213e640a4.png)

It works correctly with wired modems:

![image](https://user-images.githubusercontent.com/858456/210001668-1d040726-6ee6-4ee5-b61d-e978e3f31f3c.png)

But when breaking the cable adjacent to the full block modem (when the modem is already turned on), the peripheral *does* show up:

![image](https://user-images.githubusercontent.com/858456/210001833-646b43d9-2911-4d18-a3cb-a2d845f0bc0f.png)

In this case, right clicking the modem twice will not cause the peripherals to disappear.

**Comment by SquidDev** [comment]
The problem here is that wired network connections here are not correctly established. Placing a computer directly next to the modem shows the peripherals are present.

**Comment by SquidDev** [comment]
Reopening this to remind me to write a test.

**Comment by Lemmmy** [comment]
Thank you!
