### ISSUE TITLE
vm error: java.lang.IllegalStateException: Resuming from unknown instruction

### ISSUE THREAD

**Issue by nothjarnan** [SquidDev-CC/CC-Tweaked#128]
Was running my OS on SwitchCraft, and I encountered this error. 
Was also told by Lemmmy that this error may have been caused by a recent LuaJ rewrite.

The error gets thrown in the section of my OS that handles the coroutines, which means that it's system level. 
Attached below is an installer of the OS that I encountered the error on.
[installer.zip](https://github.com/SquidDev-CC/CC-Tweaked/files/2898362/installer.zip)

![Screenshot](https://user-images.githubusercontent.com/15698707/53304896-aa885780-3872-11e9-97a0-4b62473b4ae7.png)

Minecraft version 1.12.2, Forge 14.23.4.2759

**Comment by nothjarnan** [comment]
Update: My code does not work in CCEmuX either. Latest version

**Comment by SquidDev** [comment]
Yeah, CCEmuX is using CC:T so that makes sense.

**Comment by nothjarnan** [comment]
I've made a workaround in my OS, so please keep your current files and *do not* update them if you still need them.
