### ISSUE TITLE
Turtle drop out everything on move

### ISSUE THREAD

**Issue by zsoltrego** [SquidDev-CC/CC-Tweaked#1281]
### Minecraft Version

1.19.x

### Version

1.19.3-forge-1.102.0

### Details

Dear Developer Team,

The mining turtle drop out all items from his inventory when he leave his position (e.g. forward). I know, it is only an alpha release. :)

I wasn't find any relevant problem in the logs.

Have a nice day!

[latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/10323964/latest.log)
[rei.log](https://github.com/cc-tweaked/CC-Tweaked/files/10323965/rei.log)
[rei-issues.log](https://github.com/cc-tweaked/CC-Tweaked/files/10323966/rei-issues.log)

**Comment by SquidDev** [comment]
Fixed in #1276. Hoping to get a release out with this fix in the next few days.
