### ISSUE TITLE
Floppies don't save their ID in item.

### ISSUE THREAD

**Issue by Wojbie** [SquidDev-CC/CC-Tweaked#1282]
### Minecraft Version

1.19.x

### Version

1.102.0 - SC3

### Details

When placed in disk drive floppy shows as normally. However new floppy id is not saved on the item and on subsequent removal and replacement in disk drive floppy will get new id.
![obraz](https://user-images.githubusercontent.com/5893536/210107204-a658df6d-765f-468d-9215-074e6efea88a.png)
This is same floppy getting removed and replaced

![obraz](https://user-images.githubusercontent.com/5893536/210107183-716fc16c-5110-417e-ad33-c7b1a21ab3b6.png)
Here is nbt dump from that floppy after above test.

Tested both in SP and MP on SC3 modpack.

**Comment by SquidDev** [comment]
https://github.com/cc-tweaked/CC-Tweaked/blob/1259e29f213376bca7f11fd9644b71696a140676/projects/common/src/main/java/dan200/computercraft/shared/peripheral/diskdrive/DiskDriveBlockEntity.java#LL129C44-L129C48

Ahh, here's the culprit.

It occurs to me that we also need to be a little smarter here, and mark the owning tile as changed if we need to create a new mount. This will need some special handling for when creating a mount from the computer thread.
