### ISSUE TITLE
[Fabric] Sodium causes weird lighting with turtles

### ISSUE THREAD

**Issue by Merith-TK** [SquidDev-CC/CC-Tweaked#1286]
### Minecraft Version

1.19.x

### Version

1.102.0

### Details

it doesnt make the game unplayable but like... its weird lol

![image](https://user-images.githubusercontent.com/10422110/210184047-e97c2355-8626-4ea1-a5d2-471eafcca106.png)
![image](https://user-images.githubusercontent.com/10422110/210184049-38895748-7eed-485a-b3e8-2d6e52cd7538.png)
![image](https://user-images.githubusercontent.com/10422110/210184050-27dfb4f1-671c-4e7c-a94d-6ff59d423960.png)
![image](https://user-images.githubusercontent.com/10422110/210184051-275fd2d1-0bbf-4c53-abba-963c52cf261d.png)
![image](https://user-images.githubusercontent.com/10422110/210184052-0b95dfd6-b932-4c6d-80c2-e9f54b5b38d4.png)

**Comment by SquidDev** [comment]
Would you be able to post a side-by-side comparison? It's hard for me to tell the difference here, given they're all taken from different angles.

**Comment by Merith-TK** [comment]
Sure, give me a short bit 

I think the most notable one is of the turtle on the modem, moving just that much should not affect the lighting on the face of the turtle that much,

**Comment by SquidDev** [comment]
![A screenshot of a turtle from the side. All faces are brightish](https://user-images.githubusercontent.com/4346137/212997873-7a217387-8ac9-4ca7-9258-4f08092dbf34.png) ![A screenshot of a turtle from above. The top face is dark.](https://user-images.githubusercontent.com/4346137/212997949-5ad5d63e-1842-4520-905a-9cbb18500d75.png)

Here's an alternative view. Both images were taken at noon, so the top surface of the turtle should be bright, but isn't in the second image (when the player is looking down). Note the back face is still illuminated.

I guess there's something borked with normals. I'm going to chuck a "help wanted" on this, on the basis that I don't wish to dig into the guts of Sodium.

**Comment by Merith-TK** [comment]
Honestly fair enough on that front

**Comment by SquidDev** [comment]
Just tested on 1.20 and latest Sodium and this appears to no longer be an issue.
