### ISSUE TITLE
Speaker lags and stutters even with the max buffer size on high CC load

### ISSUE THREAD

**Issue by EmmaKnijn** [SquidDev-CC/CC-Tweaked#1293]
### Minecraft Version

1.19.x

### Version

1.102.0

### Details

The speaker lags when trying to play a song with the max buffer size when there's a lot of load on the CC thread. This is very apparent on SC3 where there's a lot of computers on at the same time

## Steps to reproduce
1. Get a dfpwm file, this can be any dfpwm file
2. Play the dfpwm file with speaker play
3. Observe bug

https://user-images.githubusercontent.com/64010592/211075507-e94a0661-1bc0-49b6-a7a6-d65ed215654c.mp4

**Comment by Lemmmy** [comment]
As a knee-jerk I don't think CC:T is directly at fault here, SC3's computer thread is completely maxed out on task time. There's probably room for optimization in speaker code but I wouldn't really consider this a bug?

From tomorrow we are raising the computer thread count to 4 and will share results

![image](https://user-images.githubusercontent.com/858456/211079959-4e1820cf-a284-45e3-b60e-f1f7147f0d28.png)
