### ISSUE TITLE
Name tags of crouching players makes monitors see through

### ISSUE THREAD

**Issue by raymondvansomeren** [SquidDev-CC/CC-Tweaked#1294]
### Minecraft Version

1.19.x

### Version

1.102.0

### Details

When a player crouches in front of a monitor, the place of the name tag becomes see through on the monitor.

https://files.satangaming.nl/images/1673044923_LawngreenGartersnake.png

**Comment by SquidDev** [comment]
This appears to be a vanilla bug, so unfortunately I don't think there's anything we can do about it

![A screenshot of Minecraft showing a player crouching in front of the nether portal. Like in the original report, the nametag makes the nether portal become see-through.](https://user-images.githubusercontent.com/4346137/211146866-a5a2ed17-64c4-4405-babc-ed9ae009e32d.png)

**Comment by SquidDev** [comment]
![Like the above, a player crouching in front of a chest and shulker box. The nametag makes the chest and shulkerbox transparent, showing the world behind it.](https://user-images.githubusercontent.com/4346137/211146970-74b276ae-7dc7-47e1-b778-0eb8cdc00126.png)

Oh, this happens even with solid blocks. Yeah, afraid I'm going to mark this as won't fix.
