### ISSUE TITLE
[Fabric] Altering server config file gets reverted on server start

### ISSUE THREAD

**Issue by Merith-TK** [SquidDev-CC/CC-Tweaked#1296]
### Minecraft Version

1.19.x

### Version

1.102.0 

### Details

I altered `[turtle] need_fuel = true` to `false` in `config/computercraft-server.toml` and it just gets reset on server start

**Comment by Lupus590** [comment]
I'm pretty sure that this happens with the forge version too.

The setting doesn't get read until a restart anyways so it's probably best to just turn the server off before editing any configs.
