### ISSUE TITLE
[Low Priority Suggestion] Rename the modem block

### ISSUE THREAD

**Issue by BTCTaras** [SquidDev-CC/CC-Tweaked#13]
The wired modem block and the wired modem both seem to have the exact same name. I suggest renaming the modem in block form to the "Modem Block" to prevent confusion/ambiguity.

**Comment by SquidDev** [comment]
Hrmr, I'm rather conflicted on this. I know AE2 calls calls their full-block and multipart versions the same thing. I guess "Wired modem (full block)" might work?
