### ISSUE TITLE
Monitor text scale to small

### ISSUE THREAD

**Issue by elyesghazel** [SquidDev-CC/CC-Tweaked#1301]
### Minecraft Version

1.19.x

### Version

1.101.1

### Details

The Text on the monitor is not the default size.
The text scale is on 1.
![2023-01-15_01 22 42](https://user-images.githubusercontent.com/92398042/212502931-9909bb78-ea5d-4813-9379-d3f07e63f418.png)

**Comment by SquidDev** [comment]
Sorry, I'm a little confused. What size would you expect it to be? Is it different compared with previous versions of the mod?

**Comment by elyesghazel** [comment]
The size of the text was perfect, but then the server crashed and suddenly just this monitor was no longer correct. And I've already tried to set the font size to 0.5 but the text was too small, and a friend also said it is a bug.
I also tried restarting the server but that didn`t help.
