### ISSUE TITLE
Optifine turtle crash

### ISSUE THREAD

**Issue by ghost** [SquidDev-CC/CC-Tweaked#1302]
### Minecraft Version

1.19.x

### Version

1.101.1

### Details

When placing a turtle that isn't the default advanced or normal turtle the game crashes. It occurs only with optifine (selected mods) and happens regardles of shaders and is reproducible.

The version of Optifine is preview_OptiFine_1.19.2_HD_U_I1_pre4

[debug-5.log](https://github.com/cc-tweaked/CC-Tweaked/files/10420758/debug-5.log)

**Comment by SquidDev** [comment]
See #1239. This is an Optifine bug: they don't support the latest version of Forge. You can probably downgrade to Forge 43.1.1, though really I'd recommend [switching to Occulus](https://modrinth.com/mod/oculus) instead.
