### ISSUE TITLE
Rednet `send` sends wrapper instead of actual message when the receiver is the same computer

### ISSUE THREAD

**Issue by jorolf** [SquidDev-CC/CC-Tweaked#1308]
### Minecraft Version

1.18.x

### Version

1.100.10

### Details

There is currently a bug introduced by https://github.com/cc-tweaked/CC-Tweaked/commit/e16f66e1286d03aeeffefac6586ad7e1b24061cb where `rednet.receive` receives the message wrapper for modem packets when the receiver is the local computer and the short circuit is triggered: https://github.com/cc-tweaked/CC-Tweaked/blob/da7a50368d17fc82f0a9315e7005190b1fb9117c/projects/core/src/main/resources/data/computercraft/lua/rom/apis/rednet.lua#L194-L197

Instead of `message_wrapper` `message` should be passed instead (like it used to).

**Comment by SquidDev** [comment]
Thank you for the detailed report, good spot!
