### ISSUE TITLE
Turtles drop every Items they get when they are mining

### ISSUE THREAD

**Issue by schrlu** [SquidDev-CC/CC-Tweaked#1319]
### Minecraft Version

1.19.x

### Version

1.19.3

### Details

Hi, in the current version of this Mod, there is a Problem with the turtles. They are constantly dropping all Items of their inventory while mining.

Greetings,

Luca

**Comment by SquidDev** [comment]
Can you upload your logs and double check you're using the latest version (1.102.2). There were some related fixes in more recent versions.

**Comment by annabelsandford** [comment]
I can confirm 1.102.2 fixes this issue
