### ISSUE TITLE
Accidentally dyeing Turtles when attempting to open the GUI

### ISSUE THREAD

**Issue by emmachase** [SquidDev-CC/CC-Tweaked#1321]
When a player is holding a dye in their hand and tries to open the Turtle GUI, the turtle will accidentally get re-colored with the dye, which is mildly frustrating as it will consume the dye (in addition to getting rid of your favorite color!). This is a common problem among players; having been reported multiple times on SwitchCraft (and it's happened to me many times as well).

## Proposed Solutions
Here are a few solutions that I can think of to resolve this issue:

1. **_A mechanic to lock the turtle's color_**: Some way to "coat" or "protect" the turtle's color, so that it can't be dyed. This could possibly be done using beeswax, or some other item, similar to how you can protect Copper blocks from rusting with beeswax (And then to remove the protection you would shift-right click with an axe or something). This is my favorite solution, as it would be the most consistent with vanilla Minecraft IMO.

1. **_Change the interaction mechanic_**: Instead of right-clicking to dye the Turtle, another interaction mechanic could be used, such as sneaking and right-clicking. This would eliminate the risk of accidentally dyeing the turtle. However, this is a breaking change, and also is inconsistent with how dyeing works in vanilla Minecraft. Alternatively, the dyeing process could be changed to happen in a crafting table (i.e. remove the right-click behavior), which would also eliminate the risk of accidentally dyeing the turtle. This is how Minecraft's dyeing mechanic works for everything except for sheep.

1. **_Don't consume the dye_**: If the turtle is dyed, the dye should not be consumed. This would be the easiest solution, but it would be inconsistent with how Minecraft's dyeing mechanic works, as every other dyeable item consumes the dye. It also doesn't solve the problem entirely, as the player would still have to re-dye the turtle if they want the old color back.

1. **_Give the old dye back_**: If the turtle is dyed, the old dye color could be given back to the player. This would include using a water bucket to remove the dye. This doesn't really make a whole lot of sense, as IRL when you paint something, you don't get the old paint back. However, it would be easy to implement.

1. **_Implement a confirmation prompt_**: Before the turtle is dyed, a prompt could appear asking the player if they really want to change the turtle's color. This would give players the opportunity to change their minds before the dye is applied. This one is not really in-line with how the Minecraft usually works.

I would be happy to help implement any of these, or to discuss other solutions.

**Comment by SquidDev** [comment]
I remember hitting this a lot on 1.12 (so many bonemealed turtles!), but had been less of a problem since 1.13 added separate dye items. I guess I clearly carry dyes about less often than some players :P.

I think the only option which really works here is just removing the right click behaviour. CC original didn't support the crafting recipe (see https://github.com/dan200/ComputerCraft/pull/230/).

> I wonder if a wet sponge would make more sense [for removing the dye off a pocket computer]

Damn, I had some great ideas.
