### ISSUE TITLE
Keys that coincide with CC shortcuts cannot be detected by computers while Ctrl is held

### ISSUE THREAD

**Issue by Kan18** [SquidDev-CC/CC-Tweaked#1326]
### Minecraft Version

1.19.x

### Version

1.102.2 (SC modpack)

### Details

On 1.12, computers were able to detect when Ctrl+S, Ctrl+R, Ctrl+T, or any other key with Ctrl was held via the `key` event.

https://user-images.githubusercontent.com/24967425/217605202-0412d2c1-4e3c-4597-a63b-89cf80de0d7e.mp4

On 1.19, this no longer seems to be the case; computers can detect other keys when Ctrl is held, but not S, R, or T.

https://user-images.githubusercontent.com/24967425/217605169-f35f81e8-87b0-4a5b-bc99-89fba22c16a8.mp4

Is this intentional? It seems to be caused by [this](https://github.com/cc-tweaked/CC-Tweaked/blob/77f62dac94ff0c2095e01993c4b5a6766401079c/projects/common/src/client/java/dan200/computercraft/client/gui/widgets/TerminalWidget.java#L82) which was put in at f9e13ca67a6b963635c4ef97fd6b065f7d0ce396 (1.13). Some old 1.12 programs used Ctrl+S as a keybinding (to save something to disk, or to dispense one stack of an item). If this is intentional, it probably should be documented somewhere.

**Comment by SquidDev** [comment]
Yeah, it's not really clear to me _what_ the intended behaviour is here.

Back in CC 1.2 (when these keyboard shortcuts were added), `key` events would be queued for the first 0.5s after one of those shortcuts were pressed.


```java
public void keyTyped(char ch, int key)
  super.keyTyped(ch, key);
  if (m_terminateTimer < 0.5F && m_rebootTimer < 0.5F) m_computer.keyTyped(c, k); 
}
```

However, in CC 1.76 the time [<kbd>Ctrl+S</kbd> needed to be held for](https://github.com/cc-tweaked/CC-Tweaked/blob/mc-1.19.x/projects/core/src/main/resources/data/computercraft/lua/rom/help/changelog.md#new-features-in-computercraft-176) was reduced to 0.5s, and similarly the delay before `key` events aren't queued was reduced to [0s](https://github.com/dan200/ComputerCraft/blob/e85cdacbc58dedacb7fcbb119efd2b44db4bcdd6/src/main/java/dan200/computercraft/client/gui/widgets/WidgetTerminal.java#L140).

However, the timer for the various shortcuts is started in the `update` method, which is (IIRC) called after `keyTyped` - hence the event being queued once.

---

Kinda moot - I think we can just increase the delay to 0.2s or something - just love an excuse to go through old versions.

**Comment by Lupus590** [comment]
With the buttons on the GUI, I would be tempted to remove the shortcuts altogether. Or at least have them implemented in Lua so that people have the option to customise them (even if via custom bios or shell)
