### ISSUE TITLE
Certain embedded functions in .settings can cause computers to get "bricked" upon startup

### ISSUE THREAD

**Issue by Kan18** [SquidDev-CC/CC-Tweaked#1337]
### Minecraft Version

1.19.x

### Version

1.102.2

### Details

Embedded functions in `.settings` which put an entry that `textutils.serialize` cannot serialize may result in computers not being able to boot. For example, this `.settings` file:
```lua
(function() a = {} return { a = {a, a} } end)()
```
<img width="712" alt="image" src="https://user-images.githubusercontent.com/24967425/219228247-b3aa20fa-94c1-4d82-b726-7bcccedafc81.png">
The error may confuse users who are unsure how this can happen, especially if there is no startup file. The only way to fix this computer would be to put it into a disk drive and remove `.settings`. The error might be caused by the `reserialize` function in settings.lua.

**Comment by SquidDev** [comment]
I assume you created this settings file manually? It shouldn't be possible to get a function in there normally.
