### ISSUE TITLE
Pastebin get failed

### ISSUE THREAD

**Issue by blooddrunkreaper** [SquidDev-CC/CC-Tweaked#134]
I've recently started playing Enigmatica 2 expert mode running the latest version with cc-tweaked-180pr1.14 and managed to make myself a mining turtle pretty early to get some early game automated mining.

Sadly I've been unable to download the quarry script that I've always used for computercraft because the connection to pastebin keeps failing even though I have the API enabled and pastebin is whitelisted.

![2019-03-03](https://user-images.githubusercontent.com/10961771/53697945-5f1ffd00-3dce-11e9-8896-e8b8f74beaed.png)

**Comment by Lemmmy** [comment]
@blooddrunkreaper Try this: `pastebin get rpXRAzs4 Quarry` - you're supposed to just put the ID in, not the whole URL.

**Comment by SquidDev** [comment]
As Lem says, you only need to put the ID in. However, it would be good if we handled putting in the whole URL.

**Comment by blooddrunkreaper** [comment]
Thanks for the fast reply, Been far too long since I used computercraft so I forgot that I only need the code lol

**Comment by blooddrunkreaper** [comment]
It's still not working
![2019-03-03 1](https://user-images.githubusercontent.com/10961771/53698028-6a275d00-3dcf-11e9-8042-1fefa5c2e72f.png)

**Comment by Lemmmy** [comment]
Try this:

```wget http://pastebin.com/raw/rpXRAzs4
mv rpXRAzs4 Quarry```

**Comment by blooddrunkreaper** [comment]
Wget returns domain not permitted even though I've got pastebin whitelisted

**Comment by Lemmmy** [comment]
Can you show us your whole config file?

**Comment by blooddrunkreaper** [comment]
Let me add it to pastebin and grab you a link

**Comment by blooddrunkreaper** [comment]
https://pastebin.com/7XfNHXyq

**Comment by Lemmmy** [comment]
You screwed up the whitelist. You shouldn'tve added `http` to it, and also, if you would've needed to, you missed the colon. (`http://`). Set it to either this:

```
    S:whitelist <
        *
     >
```

Or this:

```
    S:whitelist <
        pastebin.com
     >
```

**Comment by blooddrunkreaper** [comment]
That worked :) thanks for all the help

**Comment by SquidDev** [comment]
Glad you've got it working :). I'm just gonna keep this open for a wee bit - there's definitely some things we could make more obvious (config validation, better functionality in `pastebin`).

**Comment by Lemmmy** [comment]
Config validation (ideas are not mutually exclusive):
- Log an error into the console
- Show an error on player join in the chat
- Return an error in HTTP calls (like current whitelist failures do), e.g. `Config whitelist invalid`
- Prevent booting the BIOS and show an error

Pastebin:
- Fetch the ID using a pattern (e.g. `^https?://pastebin%.com/(%1+)$`) and handle raw URLs too
- Detect malformed IDs

**Comment by SquidDev** [comment]
I've made the changes I want to as far as this issue goes. 

I think we could do more work on notifying the user when there's a malformed config, but I think that's a separate issue, and I want to think about the flow of that first.
