### ISSUE TITLE
Optifine cc-tweaked compatibility issue - causes crash

### ISSUE THREAD

**Issue by NathanCPlaster** [SquidDev-CC/CC-Tweaked#1342]
### Minecraft Version

1.19.x

### Version

1.19.2-1.101.2

### Details

Using Optifine and cc-tweaked causes the game to crash as the game is unable to render the mining turtles.  Upon request I can offer a crash log.
For recreation have Optifine installed and cc-tweaked,  attempt to run the game and check the items in creative or add a mining turtle to your inventory.

Forge Version  43.2.3 for 1.19.2
Optifine_1.19.2_HD_U_H9
cc-tweaked-1.19.2-1.101.2

**Comment by SquidDev** [comment]
It looks like you're running an incompatible version of Forge and Optifine together. When [downloading Optifine](https://optifine.net/downloads), make sure you're running the _exact_ version of Forge recommended there.

That said, I'd really recommend [replacing Optifine with Occulus](https://modrinth.com/mod/oculus).

**Comment by NathanCPlaster** [comment]
Thank you for the recommendation!  Also would using the correct optifine version fix the crash issue with this mod?

**Comment by SquidDev** [comment]
Yes. Note there's no Optifine version compatible with your current version of Forge. You will need to upgrade Optifine to U I1 _and_ downgrade Forge to 43.1.52.

**Comment by NathanCPlaster** [comment]
Ill be sure to change that, thank you very much!
