### ISSUE TITLE
An idea.

### ISSUE THREAD

**Issue by awesomebossdj7** [SquidDev-CC/CC-Tweaked#1350]
So this mod has recently been ported to fabric, and also plethora has been updated to fabric 1.19.3...

I was wondering if you could add some features from plethora to vanilla CC:T

**Comment by SquidDev** [comment]
Do you have any features in particular you're thinking of? Right now it's quite hard to know what to do with this issue.

**Comment by awesomebossdj7** [comment]
I would mainly want the interface (i dont remember the full name, its just the thing you put on your head)

**Comment by SquidDev** [comment]
Nah, that really doesn't fit in the base mod.
