### ISSUE TITLE
[1.13.2] Can't join server, "Mismatched mod channel list"

### ISSUE THREAD

**Issue by goopsie** [SquidDev-CC/CC-Tweaked#136]
Minecraft 1.13.2
Computercraft tweaked version, 1.81.1
Forge version. 25.0.76

Download CC: Tweaked 1.81.1
Download forge 1.13 25.0.76
Start server and client with same version of forge, and CC: Tweaked
Try to join the server

I Can't connect to the server i'm hosting. Same version of computercraft, same forge version, but i get an error while connecting. "Connection closed - Mismatched mod channel list" Every time i connect after that, i get "Internal Exception: java.lang.NullPointerException"
I can connect to the server with other mods, like the simple harvest mod, but not computercraft. 

Logs of both the server, and the client.

[latestSERVER.log](https://github.com/SquidDev-CC/CC-Tweaked/files/2949778/latestSERVER.log)
[latestCLIENT.log](https://github.com/SquidDev-CC/CC-Tweaked/files/2949779/latestCLIENT.log)

Please tell me if you need anything more, this is my first github issue.

**Comment by TomKell** [comment]
Hey!

I have the same problem..
Singleplayer works fine but it doesn´t work at my server...
Is there already a soloution?

**Comment by SquidDev** [comment]
Thanks for the report! Sorry it took a while to get to this - I wanted to do a little bit more work on some 1.12 features, and then had an awful lot of fun getting the 1.13 version up-to-date with those changes.

Anyway, the latest commit should fix the `Mismatched mod channel list` error. I'm still getting `NullPointerException`, occasionally, though haven't really prodded into it much, so not sure if this is a Forge or CC:T issue.

**Comment by SquidDev** [comment]
The NPE is definitely happening within Forge's code, so there's little I can do about that. Sorry.
