### ISSUE TITLE
Add dashes in the place of spaces on drag and drop of a file

### ISSUE THREAD

**Issue by EmmaKnijn** [SquidDev-CC/CC-Tweaked#1362]
## Useful information to include:
 When you drag and drop a file the spaces would be replaced with dashes or some other character to allow for easier management of the file inside of the CraftOS shell. Right now you need to use "" around the file name to make programs like edit and rename manage it properly. I should be able to make a PR for this as its in CraftOS

**Comment by SquidDev** [comment]
I don't think it makes sense to change the filename of uploaded files, that sounds counter-intuitive.

There's an open issue for improving how we handle files with spaces (#1256), which is probably worth fixing instead.
