### ISSUE TITLE
Make turtle.forward() and turtle.back() atomically teleport and consume fuel

### ISSUE THREAD

**Issue by umnikos** [SquidDev-CC/CC-Tweaked#1364]
As an effort to circumvent issue #535 (which will probably never be fixed) I have been developing a reboot-resistant programming language for making programs that resume from where they left off when the chunk unloaded. The main inspiration for this is [LAMA](https://github.com/fnuecke/lama), and like LAMA the built-in movement functions check the fuel level to determine if a move operation was executed or not. The problem is, this currently doesn't actually work 100% of the time, as [the following code](https://github.com/cc-tweaked/CC-Tweaked/blob/87c6d3aef694917923436c026362acf14136c7be/projects/common/src/main/java/dan200/computercraft/shared/turtle/core/TurtleMoveCommand.java#L78) is not atomic and if the chunk unloads between the two lines the turtle moves twice instead of once:
```java
        // Move
        if (!turtle.teleportTo(oldWorld, newPosition)) return TurtleCommandResult.failure("Movement failed");

        // Consume fuel
        turtle.consumeFuel(1);
```

**Comment by SquidDev** [comment]
The above code runs on the main thread, so the chunk will never be unloaded between those two function calls - that only happens on tick end (Or possibly tick start. But definitely never in the middle of a tick!).

What exactly do you mean by the turtle moves twice instead of once here?

**Comment by umnikos** [comment]
Good to know, I guess I'll have to track down the bug in my own code.
