### ISSUE TITLE
Creative Mode Turtle / Pocket Computer

### ISSUE THREAD

**Issue by awesomebossdj7** [SquidDev-CC/CC-Tweaked#1365]
so my idea is make a turtle version and a pocket computer version of the command block computer

alternatives:
if command block peripheral is turned on in the config, be able to equip it onto the back of a pocket computer and/or a turtle

**Comment by awesomebossdj7** [comment]
OFF TOPIC:
if i also may suggest, i feel like a redstone integrator (plethora or advanced peripherals / peripherals plus plus) should be a vanilla CC feature, it just feels too vanilla to NOT be in the base mod

**Comment by SquidDev** [comment]
Duplicate of #1312 I think?

**Comment by awesomebossdj7** [comment]
> Duplicate of #1312 I think?

oh wow i do not remember making that lol, my bad
