### ISSUE TITLE
Change modem channels to accept strings rather than just numbers

### ISSUE THREAD

**Issue by scmcgowen** [SquidDev-CC/CC-Tweaked#1370]
This change will make modem channels not be capped to 65536 channels.

For legacy compatibility, any numbers passed into modem.open() would be converted into a string (example: `64 -> "64"`)

This would prevent modem sniffers and also be fairly useful to prevent interference, especially when using wireless and ender modems.

**Comment by SquidDev** [comment]
I'm happy with the current system. It relatively simple, and provides a good base on which more powerful or secure primitives can be built (rednet protocols for arbitrary channels, the various modem encryption libraries, etc...)
