### ISSUE TITLE
bad argument should say line that caused crash.

### ISSUE THREAD

**Issue by Ai-Kiwi** [SquidDev-CC/CC-Tweaked#1377]
When your program runs into an error and crashes and gives bad argument error it should give you the line number that crashed as well. for example 'bad argument #2 (expected number, got nil)' should return the line number in it to, This would be helpful for when you get this crash message and have no idea what caused it.

**Comment by SquidDev** [comment]
This should happen already. Would you be able to provide some code where it doesn't - that sounds like a bug.
