### ISSUE TITLE
Space character resets cursor or buffer in stitch

### ISSUE THREAD

**Issue by Sellular** [SquidDev-CC/CC-Tweaked#1380]
### Minecraft Version

1.19.x

### Version

1.101.2

### Details

Figured I'd report this since I know stitch is relatively popular in the community.

When displaying any text with a space, instead of displaying the space and proceeding text, the space is not displayed and the cursor is reset to the initial position. It then overwrites any previously written characters with the text that proceeded the space.

Reproduction code; Results in monitor_0 outputting "world!":
```
os.loadAPI( "stitch" )
stitch.setMonitors( {
    {"monitor_0", "monitor_1"},
    {"monitor_2", "monitor_3"},
} )
term.redirect( stitch )
stitch.setTextScale( 5 )
print( "Hello, world!" )
```

If `Hello, world!` is replaced with something akin to `FFFF DD` it would display `DDFF`

logs, however nothing CC related: https://gist.github.com/Sellular/7d50718ec004693ba38dfb3c25b234d0

**Comment by piprett** [comment]
This does not look like a issue with CC:T, the mod. This repo is only for CC:T, not for community creations.
