### ISSUE TITLE
When placing a Mining Turtle the game crashes and bricks the world

### ISSUE THREAD

**Issue by crackscout123** [SquidDev-CC/CC-Tweaked#1397]
### Minecraft Version

1.19.x

### Version

1.101.2

### Details

So when I try to place any item (from CC) nothing happens it works just as it should. But when placing a Turtle with an ability such as a mining or wirless turtle the game crashes instantly, it corrupts also the savefile (same if I try it on my server.) 

Here my latest.log
https://gist.github.com/crackscout123/04c0480181b1d3a3f7caed233b26a4a9

**Comment by SquidDev** [comment]
It looks like you're running an incompatible version of Forge and Optifine together. When [downloading Optifine](https://optifine.net/downloads), make sure you're running the _exact_ version of Forge recommended there.

That said, I'd really recommend [replacing Optifine with Occulus](https://modrinth.com/mod/oculus).

**Comment by crackscout123** [comment]
Thanks (:
