### ISSUE TITLE
[Feature Request] Individual Pixel Writing in Terminals and on Monitors

### ISSUE THREAD

**Issue by MCBEModder2020** [SquidDev-CC/CC-Tweaked#1398]
kind of a dupe of #423
maybe only on advanced computers and monitors and advanced pocket and advanced turtle
each charecter is made of pixels, right. why not be able to directly write pixels without having to use characters
ik, this would be harder to do networking, since sending monitors would have to be lossless compression
# example
<img width="200" alt="Screenshot 2023-04-03 at 5 02 21 PM" src="https://user-images.githubusercontent.com/78447517/229628365-b92a3b3c-60f6-4a68-b96b-b26c4992491a.png">

if implemented pls 1.18.2
isnt that version lts for modding since its somewhat recent and lots of mods for it

**Comment by MCBEModder2020** [comment]
pls explain why it is a wontfix

**Comment by piprett** [comment]
Because it won't be fixed.

**Comment by Lupus590** [comment]
The way that monitors work is one part design choice and one part limitation with how they interact with Minecraft's networking stack.

Implementing the requested change would break the design and affect the player experience when playing on a multiplayer server.

**Comment by fatboychummy** [comment]
Yeah, running 1080p monitors would mean you need to transfer 1080p data to each and every player connected (for every monitor nearby). If you truly need access to higher resolution, you can use CC's "drawing characters" which give you an effective resolution that is 2x3 times larger than just using a space as a pixel. The same "2 color per character" limit applies, though. I believe @9551-Dev has a good library to work with these "pixels," but I can't remember what it's calles atm.

**Comment by 9551-Dev** [comment]
> Yeah, running 1080p monitors would mean you need to transfer 1080p data to each and every player connected (for every monitor nearby). If you truly need access to higher resolution, you can use CC's "drawing characters" which give you an effective resolution that is 2x3 times larger than just using a space as a pixel. The same "2 color per character" limit applies, though. I believe @9551-Dev has a good library to work with these "pixels," but I can't remember what it's calles atm.

M- me? Indeed.
https://github.com/9551-Dev/apis/blob/main/pixelbox_lite.lua

local box = require("pixelbox_lite").new(term.current())

for i=5,20 do
    box.CANVAS[20][i] = colors.red
end

box:render()

**Comment by SquidDev** [comment]
> Yeah, running 1080p monitors would mean you need to transfer 1080p data to each and every player connected (for every monitor nearby). 

We could be smarter about this. For instance, [OC2 comes with a whole H.264 encoder](https://github.com/fnuecke/oc2/tree/1.18-forge/src/main/java/li/cil/oc2/jcodec/codecs/h264) for its video mode, which is incredibly cool. Rendering this efficiently is much harder, but maybe not impossible.

I can definitely see the merit of this feature, but I'm afraid it's not a feature I'm really interested in implementing.
