### ISSUE TITLE
[Question] Just few questions

### ISSUE THREAD

**Issue by JoeSGT** [SquidDev-CC/CC-Tweaked#14]
Hello i just saw your fork and i have a few question with it if you don't mind answering them
1) i am using original version of computercraft if i switch over to your fork how will it effect my world from switching too ComputerCraft to CC-Tweaked?

2) Is this fork aim to fix ComputCraft bugs?

3) How is this better performance then the original computercraft?

Thanks

**Comment by SquidDev** [comment]
Not a problem at all, always happy to answer queries:

 1. You should be able to switch between ComputerCraft and CC:Tweaked with no issue. Aside from adding one new block (and corresponding item), there aren't any changes to the save format.

 2. The aim of this fork is to provide more regular releases of CC, with [many of the latest PRs](https://github.com/dan200/ComputerCraft/pulls) merged. I'm definitely committed to squashing CC bugs, but I generally fix the original mod and then copy changes across to here.

 3. Just a couple of things off the top of my head:

     - Reduce network traffic of computers by only sending changes when needed.
     - Remove multiple block lookups in monitor code
     - Minor improvements to the Lua VM to reduce instruction overhead.

    I can't say this results in any tangible TPS/FPS gains, but it definitely doesn't do any harm.

Hope that helps!

**Comment by JoeSGT** [comment]
Thanks you, going definitely going to switch over to this one Thanks you for taking the time out of you day to fix up this mod <3

**Comment by JoeSGT** [comment]
Oh and something i forgot,
one more thing 
how do you trust mining turtles ? using GriefPrevention(Spongepowered)
because on the original mod you cannot

**Comment by SquidDev** [comment]
Turtles should now act as whoever placed them, so they should "just work" in claims. However [due to some Sponge/GP oddities](https://github.com/MinecraftPortCentral/GriefPrevention/issues/602) it's not quite working as expected.

**Comment by JoeSGT** [comment]
Ah! i hope it get fixed soon! thanks you very much !
