### ISSUE TITLE
[1.14-19w11b] Crash on startup

### ISSUE THREAD

**Issue by The-Fireplace** [SquidDev-CC/CC-Tweaked#140]
https://paste.ubuntu.com/p/pcm76xMD57/

fabric-loader-0.3.7.109-19w11b.2
cc-tweaked-1.80pr1.11

**Comment by SquidDev** [comment]
The current 1.14 version is several snapshots behind right now, and so will not work on the latest Fabric version. I'd like to get working again at some point, but it's very much not a priority - the Fabric port was always meant to be an experiment.

Sorry for the inconvenience.
