### ISSUE TITLE
Ticking block entity crash when turtle placed next to Alchemistry machine

### ISSUE THREAD

**Issue by singofwalls** [SquidDev-CC/CC-Tweaked#1401]
### Minecraft Version

1.19.x

### Version

1.101.2, forge

### Details

When placing a turtle such that it faces an Alchemistry machine (such as the dissolver), the server crashes with the following crash log:

[crash-2023-04-05_20.57.35-server.txt](https://github.com/cc-tweaked/CC-Tweaked/files/11165616/crash-2023-04-05_20.57.35-server.txt)

This occurs on single player and multiplayer (crashing the server itself in this case). I was able to reproduce the bug with only the following mods installed in single player (these are Alchemistry and its dependencies and CC: Tweaked):

- alchemistry-1.19.2-2.2.4
- alchemylib-1.19.2-1.0.20
- chemlib-1.19.2-2.0.17
- Patchouli-1.19.2-77
- cc-tweaked-1.19.2-1.101.2

Here is the latest.log and debug.log for the client during a crash on a new world with only these mods:

[latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/11165663/latest.log)
[debug.log](https://github.com/cc-tweaked/CC-Tweaked/files/11165671/debug.log)

And here is a log and debug.log from the server which experienced this crash (but with many other mods installed as well):

[2023-04-05-2.log](https://github.com/cc-tweaked/CC-Tweaked/files/11165720/2023-04-05-2.log)
[debug-2.log](https://github.com/cc-tweaked/CC-Tweaked/files/11165725/debug-2.log)

Many times, it'll crash as soon as a turtle is placed facing an Alchemistry machine. But on one test, I had to start up the turtle, pick up the Dissolver, and then place it back in front of the turtle again before the crash occurred.

It looks like this issue is already being tracked at the Alchemistry repo [here](https://github.com/SmashingMods/Alchemistry/issues/305). So perhaps this is better resolved from their end -- I don't have much practice reading Minecraft crash logs so I thought I'd post here in case this is a CC: Tweaked issue.

Please let me know if there's anything else I can do to help! Appreciate you folk, thanks!

**Comment by SquidDev** [comment]
Thank you for the report. This appears to be an issue on Alchemistry's end - I've left a little more detail on the issue on their repo.
