### ISSUE TITLE
Incompatibility with Rubidium / Oculus

### ISSUE THREAD

**Issue by Abelatox** [SquidDev-CC/CC-Tweaked#1405]
### Minecraft Version

1.19.x

### Version

1.104.0

### Details

I can't get CC:Tweaked to load alongside Rubidium 0.6.4 and oculus 1.5.2 (Using Forge 45.0.40 for 1.19.4)
I know the crash seems to point more towards Rubidium / Oculus

[crash-2023-04-08_14.04.34-client.txt](https://github.com/cc-tweaked/CC-Tweaked/files/11183202/crash-2023-04-08_14.04.34-client.txt)

The second crash is if I remove Oculus and I try with Rubidium and CC:Tweaked

[crash-2023-04-08_14.05.53-client.txt](https://github.com/cc-tweaked/CC-Tweaked/files/11183208/crash-2023-04-08_14.05.53-client.txt)

I report it here because if I take CC:Tweaked out Minecraft loads without a problem.

**Comment by SquidDev** [comment]
Thank you for the report!

For the Oculus crash, there's a similar looking crash at https://github.com/Asek3/Oculus/issues/336, so may be worth keeping an eye on that too.

The Rubidium one is very odd. We don't do anything which should cause that. I will try to reproduce and work out what's going on, but it may be worth reporting to them too.

**Comment by Abelatox** [comment]
Alright thanks! I guess it's important to note that it doesn't happen on the 1.19.2 versions of the mods.

**Comment by SquidDev** [comment]
Are you sure you were using 1.104.0 and Forge 45.0.40? That version of CC: Tweaked should require 45.0.42 or later.

I'm unable to reproduce on latest Forge (45.0.64), so might be worth updating and seeing if that helps.

**Comment by Abelatox** [comment]
Okay updating forge version to latest (.64) seems to allow me to load it again.
Same version of CC, same version of Rubidium and oculus.
Thank you! :D
