### ISSUE TITLE
 Computer power button is inverted

### ISSUE THREAD

**Issue by qrmcat** [SquidDev-CC/CC-Tweaked#1413]
### Minecraft Version

1.19.x

### Version

1.104.0

## The problem:
When a computer is on, the power button shows as if it is off, and the tooltip on it is "Turn this computer on", but when a computer is off, it shows as if it is on (with the tooltip for a computer that is on).
Here are two screenshots below about it:
![kép](https://user-images.githubusercontent.com/49914603/232228540-2233cf0d-179c-4592-b714-241363ae7673.png)
![kép](https://user-images.githubusercontent.com/49914603/232228545-54a9e255-0410-4cea-8036-6d1d97ebe161.png)
## To reproduce:
Simply go into a computer on the server. You will see that the power button is inverted.
## Expected behavior:
When the computer is off, the power buttons shows that it is off, instead of showing like it is on, and vica versa.

**Comment by piprett** [comment]
Source: https://github.com/cc-tweaked/CC-Tweaked/blob/3920ff08ab4b540a9cac0bb7c8569c56439e02a4/projects/common/src/client/java/dan200/computercraft/client/gui/widgets/ComputerSidebar.java#L48-L52

PR planted soon™
