### ISSUE TITLE
A build for (one of) 1.20 snapshots

### ISSUE THREAD

**Issue by vico93** [SquidDev-CC/CC-Tweaked#1415]
Yeah, i know, maintaining CC:T (on Fabric) for each snapshot released would be a unfeasible work, i know, but given 1.20 is a pretty huge update, why not release at least a version for one of the snapshots?

Not only as a test to prepare for the full 1.20 release (not only code-wise but also interaction with new features in-game) but also due to how huge the additions to that version will be.

**Comment by SquidDev** [comment]
You're more than welcome to do this yourself, but I have no interest in doing this myself.
