### ISSUE TITLE
[Feature Request] Wireless peripheral upgrade tool and/or wireless cable access point

### ISSUE THREAD

**Issue by zyxkad** [SquidDev-CC/CC-Tweaked#1416]
Wireless peripheral upgrade tool: A tool that can connect peripheral to wireless modem, allow computer to control peripheral wirelessly.

Wireless cable access point: a block like wired modem block, but needn't cable to connect it. It's different from wireless modem since it can connect to the cable and peripheral, but wireless modem not.

**Comment by Lupus590** [comment]
You can mostly mimic this by having a computer connected to the peripheral acting as a wireless proxy for the peripheral and the host machine.

**Comment by SquidDev** [comment]
I've experimented with similar ideas in the past (i.e. [CCTweaks's wireless bridge](https://github.com/SquidDev-CC/CCTweaks/wiki/Wireless-Bridge)), and I'm honestly not thrilled about how this works in practice. I think it ends up trivialising some of the interesting logistical problems that occur when working with long-distance/wireless peripherals.
