### ISSUE TITLE
New feature: 'wrun'

### ISSUE THREAD

**Issue by XDuskAshes** [SquidDev-CC/CC-Tweaked#1418]
# wrun
A solution to a very real problem.

Similar to `pastebin run`, the idea of `wrun` is to enable running things straight from the links, rather than having to put stuff everywhere and have your code live in one general spot.

**Comment by Lemmmy** [comment]
You can pass `run` to `wget`, e.g. `wget run https://p.sc3.io/WCHDD38naq`

**Comment by SquidDev** [comment]
Yep, as Lem says this exists already!
