### ISSUE TITLE
[Incompatibility] Iris v1.6.1 causes monitors to appear darker

### ISSUE THREAD

**Issue by hugeblank** [SquidDev-CC/CC-Tweaked#1419]
### Minecraft Version

1.19.x

### Version

1.104.0

### Details

The newest version of Iris causes monitors to appear darker than they are without Iris. This issue occurs even with shaders are disabled, like seen here on SC3:
![image](https://user-images.githubusercontent.com/16393543/233742464-f5c19699-a0db-462d-8b13-3769c25f4df1.png)
Log: https://mclo.gs/f8VNoPP

**Comment by SquidDev** [comment]
I would recommend posting this on the Iris issue tracker, or at least their Discord. They're probably in a better place to track down this regression and offer solutions - I know IMS was very helpful last time Iris broke monitors.

**Comment by SquidDev** [comment]
This was an Iris bug, closing.
