### ISSUE TITLE
Common (without API) is not present in maven repository

### ISSUE THREAD

**Issue by SirEdvin** [SquidDev-CC/CC-Tweaked#1424]
So, currently common-api is published in maven repository, 

Can we also have common in maven repository please? There is a lot of code, especially from `util` package, that can be reused (for example InventoryUtil, etc). I understand the consiquences of using not-api packages.

**Comment by SquidDev** [comment]
Please, please, please don't use internal classes. It just ends up being a nightmare every time. If you just need to use the `util` package, you can just copy and paste the code into your own project (well, where allowed under the license). That's the joy of open source!

**Comment by SirEdvin** [comment]
Okey, then how I can, for example, extract turtle access from block entity in common code? 
Also, I guess, `turtlesNeedFuel` is not exposed :( 

Okey, I will just make another issues with request for some extract API expose
