### ISSUE TITLE
The way synthetic recipes are placed affects the texture of the turtles [1.18.2]

### ISSUE THREAD

**Issue by PTALTS-LK** [SquidDev-CC/CC-Tweaked#1427]
### Minecraft Version

1.18.x

### Version

1.101.2

### Details

![image](https://user-images.githubusercontent.com/62936489/235356783-d54e98df-0a65-4c3a-af33-7e92d648fa16.png)
![image](https://user-images.githubusercontent.com/62936489/235356790-900f38b8-04d4-4574-9adc-78d91e7ac562.png)

**Comment by SquidDev** [comment]
Thank you for the report! Looks like I'd messed up the path of one of the model names.

Fixed in c0f982dc97a59ff98e892c98bca69417f0bced7f (I typoed the issue number :/).
