### ISSUE TITLE
Testing framework exposed as an artifact

### ISSUE THREAD

**Issue by SirEdvin** [SquidDev-CC/CC-Tweaked#1429]
So, testing framework, that was developed by CC:Tweaked team is really awesome to use, and I am glad that I can use it time to time in my project. But for now, this testing framework wasn't exposed as public artifact, so to use it I need to rip off some peace of code and put into into other repository and create artifact from it. 

This become more complicated now, because testing framework for vanilla minecraft exists, but it depends on vanilla minecraft project, which is not exposed as public artifact, so amount of code that should be ripped off is increased significantly. 

Can I ask to expose testing framework in some sort of maven artifact? I am pretty fine with it to be unstable/unfinished/etc

**Comment by SquidDev** [comment]
[Artifcat?](https://user-images.githubusercontent.com/4346137/236059721-973ab3f8-6f4e-486e-8797-3232d6f42f30.png "A statue of an Egyptian cat. An artifact of a cat. An artifcat!")

When you say the testing framework, what exactly do you mean here? CC:T has three different test suites (mcfly, JUnit, gametests), each with their own support library. Aside from the core project (whose test fixtures jar should be published already), I'm not sure which of those is very interesting!

**Comment by SirEdvin** [comment]
I am talking mostly about gametes :)

**Comment by SquidDev** [comment]
Right, makes sense.

I think the main trouble here is that you basically need to create a new multi-loader mod to make this work, which means this ends up spiralling into quite a lot of work. I'm afraid I just don't have the capacity for this right now, so going to leave this up to someone to PR.
