### ISSUE TITLE
[1.13.2] Piston extension crashes the game

### ISSUE THREAD

**Issue by BigBang1112** [SquidDev-CC/CC-Tweaked#143]
Forge version: 25.0.84
CC Tweaked version: 1.81.1

Any kind of redstone power provided to pistons will crash the game. Tested with Forge only and with Forge and CC Tweaked only, giving a reproducible result.

Log here:
[latest.log](https://github.com/SquidDev-CC/CC-Tweaked/files/2973309/latest.log)

**Comment by SquidDev** [comment]
This appears to be a Forge issue, and not directly caused by CC:Tweaked. I recommend filing a bug with them instead.

**Comment by BigBang1112** [comment]
Ok. It really needs to be solved.
Sorry for the random actions, pure mistakes.
