### ISSUE TITLE
Increase the wired modem range

### ISSUE THREAD

**Issue by myrddraall** [SquidDev-CC/CC-Tweaked#1434]
The maximum range for wired modems is currently 256 blocks, which isn't even enough to go from the top of the world to the bottom any more. It would be mice to increase this to at least 512 and/or make it configurable

**Comment by DevWolf31** [comment]
Good idea 👍👌👍👌.

**Comment by SquidDev** [comment]
We could probably just remove the range limit on wired modems. Given that peripherals are accessible over the whole network, it doesn't really make sense that modem messages have a limit.
