### ISSUE TITLE
[BUG]  Generic APIs not exists when the target block have other API implemented

### ISSUE THREAD

**Issue by zyxkad** [SquidDev-CC/CC-Tweaked#1435]
## Useful information to include:
 - Explanation of how the feature/change should work.
   - Many mod add it's own tanks to operate, (create, mekanism, AE2), it's useful if we can transform fluids through the wired modem because then we can autocraft fluids.
 - Some rationale/use case for a feature. My general approach to designing new features is to ask yourself "what issue are we trying to solve" and _then_ "is this the best way to solve this issue?".
   - For example, create mod can craft potions, if we have fluid transfer, we can easier to make potions from a basin to another one that contains gunpowder or dragon breath to upgrade them.

---

It's because some mods affect the tanks, not CC:T issue

**Comment by piprett** [comment]
I am a bit confused, doesn't this already exist?
https://tweaked.cc/generic_peripheral/fluid_storage.html

**Comment by SirEdvin** [comment]
It is probably request for fabric, I guess.
You can use [UnlimitedPeripheralWorks](https://www.curseforge.com/minecraft/mc-mods/unlimitedperipheralworks) version for fabric to close this gap for now.

**Comment by zyxkad** [comment]
No I'm on forge 1.19.2

<img width="1168" alt="Screenshot 2023-05-09 at 12 51 11 PM" src="https://github.com/cc-tweaked/CC-Tweaked/assets/91082411/b3fb7a35-e164-4cb4-b49b-e338cb80062a">

**Comment by SirEdvin** [comment]
Do you have AdvancedPeripherals installed? Can you try without them?

**Comment by zyxkad** [comment]
Ah yeah, I installed AdvancedPeripherals, so it should be that mod's issue?

**Comment by SirEdvin** [comment]
AdvancedPeripherals has integration with Create for some blocks. If another mod provide any kind of peripheral to block, generic peripheral (like energy_storage, fluid_storage and inventory) will not work. 

From your screenshort I guess something is providing a peripheral integration for tank, because method `getInfo` not belong to CC:T

**Comment by zyxkad** [comment]
I disabled advanced peripherals, and I'm testing without it

**Comment by zyxkad** [comment]
Yes, create tanks works well without advancedPeripheral, but mekanism's not, should I report the issue to them?

**Comment by SirEdvin** [comment]
Mekanism has its own integration with CC:T, so probaby, yes.

**Comment by SirEndii** [comment]
Is there even a way to fix this as an addon developer?

**Comment by SirEdvin** [comment]
You can or disable peripheral for this block or re-implement (copy) part of code that is responsible for this. 

In UPW I introduced plugin system to solve this issue :)

**Comment by SirEdvin** [comment]
And linking [this](https://github.com/cc-tweaked/CC-Tweaked/discussions/1093) discussion here

**Comment by zyxkad** [comment]
Noticed that even cc: tweaked it's own [`printer`](https://tweaked.cc/peripheral/printer.html) and [`diskDriver`](https://tweaked.cc/peripheral/drive.html) didn't implemented the [generic inventory API](https://tweaked.cc/generic_peripheral/inventory.html).

I'm not sure if it's on purpose, but if not, you should fix that then other modders know what can they do

**Comment by SquidDev** [comment]
Inventory methods on CC peripherals is an intentional choice right now - currently tracked at #633.
