### ISSUE TITLE
Turtle (any kind) crashes modpack when using optifine.

### ISSUE THREAD

**Issue by RealmKebab** [SquidDev-CC/CC-Tweaked#1436]
### Minecraft Version

1.19.x

### Version

1.101.2 - Forge 1.19.2

### Details

Logs: https://mclo.gs/Gb5BdOr

Reproduction:
Install the latest version of OptiFine 1.19.2
Make a world of any kind,
Spawn in and place any kind of turtle (advanced or normal)
World crashes and you cannot access that world without removing/disabling OptiFine.
- End of reproduction

Tried with OptiFine 4x, crashes
Without OptiFine 1x, does not crash.

[The modpack I used](https://legacy.curseforge.com/minecraft/modpacks/the-infinite-pain-modpack)

**Comment by zenithteam** [comment]
can confirm . run into the same issue today
OptiFine_1.19.2_HD_U_I1
cc-tweaked-1.19.2-1.101.1

**Comment by SquidDev** [comment]
It looks like you're running an incompatible version of Forge and Optifine together. When [downloading Optifine](https://optifine.net/downloads), make sure you're running the _exact_ version of Forge recommended there.

That said, I'd really recommend [replacing Optifine with Occulus](https://modrinth.com/mod/oculus).
