### ISSUE TITLE
Bow turtle

### ISSUE THREAD

**Issue by SirEdvin** [SquidDev-CC/CC-Tweaked#1454]
My suggestion is basically to add turtle ability to use bows for shooting arrows and regular items. [Here](https://www.youtube.com/watch?v=jDZlT2mr3yA) is video with feature demonstration.

Having this turtle is a nice way for short-range item transfer without cables, that requires some challenge to be used properly.

I can port feature myself, but I am not sure, will this feature fit CC:T correctly.

**Comment by SquidDev** [comment]
Oh, I love this. I'm not sure it's _practical_, but this is such a fun idea - systems where you can actually see the items moving about are always so satisfying.

As to whether this fits in CC:T itself, I don't genuinely know. I'm pretty conservative with what gets added to it, as it's much harder to remove a feature than to add it. This does kinda end up with it being the No Fun Allowed mod though, which is a bit of a shame.

**Comment by SquidDev** [comment]
I'm afraid CC is going to stay as the "No Fun Allowed" mod :D:.
