### ISSUE TITLE
Optifine making monitor not appear in periphials

### ISSUE THREAD

**Issue by SimulatorSia** [SquidDev-CC/CC-Tweaked#1458]
### Minecraft Version

1.19.x

### Version

1.104.0

### Details

OptiFine HD U I4 makes monitors not appear in the peripheral list. No program can interact with monitors either. Not looking to get it fixed just thought I would let you guys know about the interactions.

**Comment by SquidDev** [comment]
Someone hit something similar a few weeks back too in IRC, where CC's peripherals just weren't registered when Optifine was installed (possibly also related to #1452). I see you've opened #https://github.com/sp614x/optifine/issues/7395, so going to close this.

That said, I'd really recommend [replacing Optifine with Occulus](https://modrinth.com/mod/oculus).

**Comment by SimulatorSia** [comment]
Unfortunately Occulus doesn't have the feature to reduce shader render quality like Optifine does leaving me with incredibly poor TPS & FPS when I attempted Occulus. I've been searching through Optifine to see if a setting may change it. I've tried nearly a hundred combinations of quality and performance settings so far.

**Comment by SimulatorSia** [comment]
@SquidDev Please do not close this issue. Optifine is unlikely to resolve a conflict with another mod. Is there perhaps a small fix that could be added by connecting peripherals another way?

**Comment by SquidDev** [comment]
I did a quick bit of debugging here, and this is entirely on Optifine's side, so I'm afraid you'll have to wait for them to fix it. They've broken part of Forge's capability system, which will affect many other mods, though perhaps in more subtle ways.

**Comment by SimulatorSia** [comment]
I appreciate the debugging attempt I really do.
