### ISSUE TITLE
MC client crashes after placing down a mining turtle

### ISSUE THREAD

**Issue by EdisPL** [SquidDev-CC/CC-Tweaked#1463]
### Minecraft Version

1.19.x

### Version

1.101.2

### Details

I am playing on a forge(43.2.13) minecraft server with a couple of mods.
The minecraft client crashes when I place a Mining turtle on the ground (The server doesn't crash, but the client does).
(The same thing happens on a single-player world)

### Details
**The forge server has these mods:**

cc-tweaked-1.19.2-1.101.2
create-1.19.2-0.5.1.b
enderchests-forge-1.19.0-1.10.1.01
flywheel-forge-1.19.2-0.6.8.a
jei-1.19.2-forge-11.6.0.1015
shetiphiancore-forge-1.19.0-3.11.3.01

**The client has these mods:**

appleskin-forge-mc1.19-2.4.2
cc-tweaked-1.19.2-1.101.2
configured-2.1.1-1.19.2
create-1.19.2-0.5.1.b
enderchests-forge-1.19.0-1.10.1.01
jei-1.19.2-forge-11.6.0.1015
OptiFine_1.19.2_HD_U_I1
shetiphiancore-forge-1.19.0-3.11.3.01
Xaeros_Minimap_23.4.4_Forge_1.19.1
XaerosWorldMap_1.30.3_Forge_1.19.1

### Logs
(I recreated it on a single-player world)

**These are the logs:**
https://gist.github.com/EdisPL/260fe51013efbc0cae1d03942e9af900

**And these are the crash logs:**
https://gist.github.com/EdisPL/a933ee1d23b349a7fa4d6c3f16d8d09e

### Reproduction steps

1. Start the server
2. Join the server with the mc client
3. Place down a Mining turtle

**Comment by SquidDev** [comment]
It looks like you're running an incompatible version of Forge and Optifine together. When [downloading Optifine](https://optifine.net/downloads), make sure you're running the _exact_ version of Forge recommended there.

That said, I'd really recommend [replacing Optifine with Occulus](https://modrinth.com/mod/oculus).
