### ISSUE TITLE
Saving machines states

### ISSUE THREAD

**Issue by Fromant** [SquidDev-CC/CC-Tweaked#1468]
## Feature request

So, the thing i offer is simple. Whenever player leaves the world or server closes, the states of all machines voids.
If you open some things on computer, then leave and then join back, you'll see just blank default craftOS screen.
Mod doesn't saves and loads states of machines, programms it running and history of shell (just for example)

In my honest opinion it would be cool to save machines states and load it so i can build difficult systems and do not worry about reloads of the server or MC crashes.

Actually i can put my script into the startup but if it's a long and difficult program, it's kinda hard to handle myself all the states every time (maybe create some new API in crastOS?) 

For example, when tasking turtle to do a lot of stuff and leave, turtle completely stops and forgets what it was doing

😮

**Comment by Lupus590** [comment]
See:
#917 
#535

**Comment by SquidDev** [comment]
As Lupus has mentioned, this is planned. It's just a lot of work, and so and so hard to prioritise.
