### ISSUE TITLE
Fuel memory 

### ISSUE THREAD

**Issue by midu1863** [SquidDev-CC/CC-Tweaked#147]
## Don't waste fuel:
 - The mining turtle set fuel to 0 after picking in inventory.
   It will be nice if the mining turtle can memory fuel, if it's in inventory. Then i don't put later fuel again in 
   be cause there is the rest fuel in it

**Comment by Lemmmy** [comment]
You can already do this by labelling the turtle. It will keep its fuel, ID, and programs. `label set "My Turtle"`

**Comment by midu1863** [comment]
Thanks 
im sorry. i read over the information.
