### ISSUE TITLE
(Game Breaking) turles Crash the Game When Placed, And the Model looks broken and breaks world

### ISSUE THREAD

**Issue by classy-dragon** [SquidDev-CC/CC-Tweaked#1479]
### Minecraft Version

1.16.x

### Version

cc-tweaked-1.19.2-1.101.2.jar

### Details

Cannot Use Any Turles with out Game Crashing is 5 secs

**Comment by SquidDev** [comment]
Would you be able to attach a crash log? It's hard to know exactly what's going on without any further information.

I suspect you're running an incompatible version of Forge and Optifine together. When [downloading Optifine](https://optifine.net/downloads), make sure you're running the _exact_ version of Forge recommended there.

That said, I'd really recommend [replacing Optifine with Occulus](https://modrinth.com/mod/oculus).
