### ISSUE TITLE
Advanced Turtle Recipe

### ISSUE THREAD

**Issue by TomKell** [SquidDev-CC/CC-Tweaked#148]
Hello again!

I know that i use a pre version of the CC Tweaked 1.13.2, but I want to let you know the bugs that i find..
And the first Bug I found is the Recipe of the Advanced Mining Turtle..
It doesn´t work.. You just get a normal mining turtle..
![screenshot](https://user-images.githubusercontent.com/7360469/54523834-b5fe0880-4970-11e9-9ed6-bf049e92366f.png)

Just for you to know!
Have a great Day!

**Comment by SquidDev** [comment]
Should be fixed in the above commit. Thanks for the report :).
