### ISSUE TITLE
Optifine+CC

### ISSUE THREAD

**Issue by ChickenSquiggles** [SquidDev-CC/CC-Tweaked#1486]
### Minecraft Version

1.19.x

### Version

1.101.2

### Details

When using Optifine with CC:Tweaked the modpack does not start/gets an error when it opens. Would love for this to be fixed, and I'm probably not the only one. Thanks :)

**Comment by SquidDev** [comment]
Would you be able to attach a crash log? It's hard to know exactly what's going on without any further information.

I suspect you're running an incompatible version of Forge and Optifine together. When [downloading Optifine](https://optifine.net/downloads), make sure you're running the _exact_ version of Forge recommended there.

That said, I'd really recommend [replacing Optifine with Occulus](https://modrinth.com/mod/oculus).

**Comment by ChickenSquiggles** [comment]
The game crashes with the message 
`The game crashed whilst rendering overlay
Error: java.lang.NoSuchMethodError: 'void net.minecraft.client.renderer.block.model.BakedQuad.<init>(int[], int, net.minecraft.core.Direction, net.minecraft.client.renderer.texture.TextureAtlasSprite, boolean, boolean)'`

Here is the crash report:
[https://pastebin.com/BtW1hwrN](url)

Using oculus would not help in my situation, because I am looking for the performance/other features of optifine, not the shaders. I have ensured I am using the correct version, and as well when I remove CC it runs fine with optifine.

**Comment by SquidDev** [comment]
Yes, this is another instance of https://github.com/sp614x/optifine/issues/7127. You'll need to downgrade Forge to  43.1.52 - I don't think a fix was ever released for 1.19.2.

If you just need the performance, https://modrinth.com/mod/rubidium is a Forge fork of Sodium, which generally brings the same performance boost with far fewer mod compatibility issues.
