### ISSUE TITLE
[Java API] Methode to retrieve real file path for given computer path

### ISSUE THREAD

**Issue by MadddinTribleD** [SquidDev-CC/CC-Tweaked#149]
There should be a simple way to retrieve the real `file path` (in world folder) for a given `computer path` via the `IFileSystem`-api.

Currently the `IFileSystem` only allows checking if a file or directory exists.
   
This results in a addon developer, that need the real `file path`, to use reflection on members of `FileSystemWrapperMount` and other private classes only to to get the path.
  
  
A other way i currently use is to create a temporary file, open it for read and use reflection on the returned `FileChannelImpl`. Here is an example:
```
String path = "/test/sub/"
fileSystem.openChannelForWrite(path + "helpfile").close();
ReadableByteChannel channel = fileSystem.openChannelForRead(path + "helpfile");
String realPath = ReflectionHelper.getPrivateValue(FileChannelImpl.class, (FileChannelImpl)channel, "path");
```

**Comment by SquidDev** [comment]
Can you explain why you need access to the underlying file path? We intentionally hide that sort of information, as it means we can control how the mount is used (and so ensure that the computer's storage capacity is not overreached).

**Comment by MadddinTribleD** [comment]
I currently write a addon that lets you use `git` in lua.  
To execute commands on a `git`-repository that lays in a computer-directory i convert the computer-directory to the real path and use `JGit` to interact with the repository.

**Comment by SquidDev** [comment]
JGit is something [we discussed](https://github.com/dan200/ComputerCraft/issues/346) when implementing this functionality. It should be possible to implement a `Repository` which sits over CC's filesystem abstraction (see, for instance [`InMemoryRepository`](https://github.com/eclipse/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/internal/storage/dfs/InMemoryRepository.java)). That said, I don't think anyone has tried, so I'd be curious as to how feasible it'd actually be.

**Comment by MadddinTribleD** [comment]
Ok i think i came up with a good solution.  

I could instead of using a directory in the computer, make a own `IWritableMount` that uses my own directory.  
In the computer it would show up in the location the user specified.  
So if the user writes to it, it will check if there is enought space for writing and fail if there is not.
If the user clones/checks out a repo, i would after the operation is complete check the size and either mount it `Readonly` or undmount it completely.  

So i would not really need to interact with the filesystem of CC and dont need the path.
