### ISSUE TITLE
string.pack array index out of bounds

### ISSUE THREAD

**Issue by ghost** [SquidDev-CC/CC-Tweaked#1496]
### Minecraft Version

1.20.x

### Version

1.105.0

### Details

https://gist.github.com/notvirtio/003aa0774b63b6b3ddf7c14e742adf05
To reproduce just run `string.pack("z", ("a"):rep(32))` in the lua prompt.
For some reason it won't work if the output doesn't get used

**Comment by SquidDev** [comment]
Thanks for the report!
