### ISSUE TITLE
Able to pickup fluids multiple blocks away while looking at a running fluid.

### ISSUE THREAD

**Issue by Colby-Perry** [SquidDev-CC/CC-Tweaked#1497]
### Minecraft Version

1.19.x

### Version

1.101.2

### Details

Here is a clip of the issue, it may be fastest to watch to understand the bug.
https://youtu.be/cfBG0UVL-1c

Here is the program I ran; I have tested it a few different ways and the interaction was consistent.
https://pastebin.com/jZuN8v5w

Bug Description:
The turtle is able to pick up fluids with a bucket several blocks away.
The turtle can ONLY do this when looking through a flowing fluid block, but not a source block.
The turtle is unable to pick up a fluid source at the same distance when not looking through a flowing fluid block.

Using Prism Launcher V7.1

Forge Version 43.2.14

Mod List:
Advanced Peripherals v0.7.28r
AE2
bad packets
Create
JEI
Mouse Tweaks
WTHIT

**Comment by SquidDev** [comment]
Thank you for the report! This is a very odd one - it appears something about the sign causes the turtle to be able to place much further away than it should be.

Here's a minimal setup - the turtle can place/remove that water and up to two blocks below that.

![A screenshot of Minecraft. There is a block of water at the bottom, a sign above that, and then a turtle two blocks above that.](https://github.com/cc-tweaked/CC-Tweaked/assets/4346137/7e581b9c-d20d-4d92-904c-c90e20513779)

**Comment by Colby-Perry** [comment]
It also worked without the sign. I had the turtle pick up lava source through flowing lava. This was hard to showcase visually.
