### ISSUE TITLE
Add Command Turtle and Command Pocket Computer

### ISSUE THREAD

**Issue by Wilma456** [SquidDev-CC/CC-Tweaked#150]
It would be nice, if we have a Command Turtle and a Command Pocket Computer.

**Comment by SquidDev** [comment]
This was suggested [a while back](http://www.computercraft.info/forums2/index.php?/topic/22023-command-turtle-command-pocket-pc-command-everything/) on the forums, and I'm still not sure how useful they'd be. Command computers are very much intended as a creative adminy thing, so don't have much utility as turtles/pocket computers.

**Comment by Lemmmy** [comment]
Considering that you'd have to be opped and in creative mode to use them, they would hardly be much more useful than placed command computers
