### ISSUE TITLE
Turtle pickaxe durability server config

### ISSUE THREAD

**Issue by SammyForReal** [SquidDev-CC/CC-Tweaked#1501]
## The idea
I was thinking that it would be a nice addition **if there was a server config that allowed the durability of a turtle's pickaxe to be toggled on or off** _(where turned off is the default, making it not have a durability as it currently is)_.

It would also make it then possible to give a turtle a pickaxe with less durability, letting it draining that pickaxe until it breaks.

The idea behind this would be to give some modpacks more freedom in terms of configuring a difficulty. Because right now, once a turtle gets a pickaxe, it's basically usable forever.

It also feels more natural that the same tool that breaks in your hands can be broken when a turtle uses it too.
And since this is a big factor in terms of convenience _(and some would argue annoyance too)_, it would be recommended to turn this off by default.

## Problems
I got told that turtles can't store NBT data for Peripherals, which of course makes it kinda impossible for this. Maybe we can go around this by giving the turtle a variable counting to zero with each usage for the current holding tool?

**Comment by Lupus590** [comment]
Turtle upgrade NBT is in the pipeline I think.

#1465

**Comment by SirEdvin** [comment]
Another issue, that can be related, in such cases turtle should also be able to use mending, I suppose.

**Comment by SquidDev** [comment]
> in such cases turtle should also be able to use mending

Yeah, I need to think about whether I want that or not. I guess it could be another option on the tool.
