### ISSUE TITLE
Monitor Dark Text /w Oculus/Rubidium

### ISSUE THREAD

**Issue by quikenb** [SquidDev-CC/CC-Tweaked#1502]
### Minecraft Version

1.20.x

### Version

1.105

### Details

Using the monitor to show text, the text is presented as dark.
Enabling shaders does bring the text to the original brightness.
Having no shaders but Oculus/Rubidium causes the text to be dark.
Disabling Oculus/Rubidium fixes the issue.
/w shaders ( Complimentary Reimagined )
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/18548078/987ffcda-77c0-4e46-880a-2ac5d03893ba)
No Oculus/Rubidium Installed
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/18548078/30670bd4-e890-4921-a51f-d1c7acd4fc6a)
Oculus/Rubidium Installed but no shaders
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/18548078/8da4b115-8ae8-4379-947a-c513ef97a6f2)
[2023-06-26-5.log.gz](https://github.com/cc-tweaked/CC-Tweaked/files/11874004/2023-06-26-5.log.gz)
[2023-06-26-6.log.gz](https://github.com/cc-tweaked/CC-Tweaked/files/11874005/2023-06-26-6.log.gz)

**Comment by SquidDev** [comment]
I would recommend posting this on the Iris issue tracker, or at least their Discord. This is most likely a regression on the Iris side - there was a similar bug reported a few weeks back: https://github.com/cc-tweaked/CC-Tweaked/issues/1419

**Comment by quikenb** [comment]
Will do. Thank you.
