### ISSUE TITLE
Restitched Textures support

### ISSUE THREAD

**Issue by SammyForReal** [SquidDev-CC/CC-Tweaked#1505]
### Request
_I love the CC: Restitched textures. I prefer those over the ascent default CC textures._

And I figured it would be a nice option to have the same textures in CC: Tweaked too.

### Problem solving
I know that there are also people who don't like those textures, or that it would be weird to suddenly have the _"new"_ textures after updating this mod.
Which is why I would suggest to include them as an optional Resource Pack _(like the Programmers Art Pack in MC)_ that then would be off by default, but can be enabled if the player prefers those.

**Comment by SquidDev** [comment]
I'm afraid I don't want to distribute any additional resource packs with CC:T.
