### ISSUE TITLE
Get Bundled Input might not work correctly

### ISSUE THREAD

**Issue by Lilygabe** [SquidDev-CC/CC-Tweaked#1507]
### Minecraft Version

1.18.x

### Version

1.101.2

### Details

log file: [latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/11923900/latest.log)

As you might now, Project Red Transmission has updated to 1.18.2. While it could also be related to a change made in the mod, I wanted to report this to be sure. The mod's version is 1.18.2-4.16.0-beta-6.

The problem is that, while computers can transmit bundle messages, they may not be able to receive them.
Note that there is a possibility that I am doing something wrong, but I have tried searching for any solution with no results.

### Steps to reproduce:

1. Place down two computers, one or two blocks apart from each other;
2. Place a bundled cable between them, including on the face of the computer block. ( microblocks makes so it's necessary to both place the cable on the ground and on the block );
3. Using the lua prompt, on the computer on the left, run the command `rs.setBundledOutput("right",colors.black)`;
4. On the computer on the right, run the command `rs.getBundledInput("left")`;

The seemingly unintended behaviour is an output of 0.

**Comment by SquidDev** [comment]
The sides in the API appear to be flipped for me (as in I had to do `rs.setBundledOutput("left", colours.white)` for a cable placed on the right of a computer. I'm not sure if this is a CC or PR bug here.

**Comment by SquidDev** [comment]
I've done some debugging here, and this appears to be a ProjectRed bug. I've filed https://github.com/MrTJP/ProjectRed/issues/1785 on their side with some notes of my debugging, so probably best to keep an eye on that.
