### ISSUE TITLE
/.settings do not save upon restart

### ISSUE THREAD

**Issue by Yabastar** [SquidDev-CC/CC-Tweaked#1512]
### Minecraft Version

1.19.x

### Version

newest

### Details

if you change a setting, restart the computer, it resets.

**Comment by SquidDev** [comment]
How are you changing settings? Is this with the `set` program or with calls to `settings.set`? If you're using `settings.set`, you need to call [`settings.save`](https://tweaked.cc/module/settings.html#v:save) afterwards.
