### ISSUE TITLE
Allow a printed book to be stored in a chiseled bookshelf

### ISSUE THREAD

**Issue by umnikos** [SquidDev-CC/CC-Tweaked#1515]
It's just a thing you'd expect to work.

**Comment by SquidDev** [comment]
I'd also expect this to work given this functionality was added three weeks ago - https://github.com/cc-tweaked/CC-Tweaked/commit/fd1f6dda322c967f05c72e312526c1d2fddd2086! What version are you using?

**Comment by umnikos** [comment]
I guess it was that long ago when I last checked if it worked because it sure does work now :sweat_smile: 

Bundled pages do not work, though. Do those make less sense?

**Comment by SquidDev** [comment]
Yep. They're not books!

**Comment by SquidDev** [comment]
Ahh, this was only added in 1.106.0. Thought it was in 1.105 as well.
