### ISSUE TITLE
Add computercraft-tweaked topic

### ISSUE THREAD

**Issue by Commandcracker** [SquidDev-CC/CC-Tweaked#1518]
Add the [computercraft-tweaked](https://github.com/topics/computercraft-tweaked) topic to the [CC-Tweaked](https://github.com/cc-tweaked/CC-Tweaked) GitHub repository.

_(The [computercraft-tweaked](https://github.com/topics/computercraft-tweaked) topic was added in my [Minecraft computer mods topics PR](https://github.com/github/explore/pull/3769).)_

**Comment by piprett** [comment]
Could also remove forge / forge-minecraft, alternatively add fabric / fabricmc / similar

**Comment by Commandcracker** [comment]
Why should forge be removed, CC: T has booth fabric and forge builds ?

**fabricmc** _aliases: fabric, fabric-mod, fabricmc-mod, minecraft-fabric-mod, minecraft-fabric_

**minecraft-forge** _aliases: forge, minecraftforge, minecraft-forge-mod, minecraft-forge-mods, minecraft-forge-modpack, minecraft-forge-modpacks, minecraft-forge-modification_

**Comment by piprett** [comment]
I meant to either add fabricmc, or remove minecraft-forge, while your  already at it. It wouldn't make sense to have only forge topic.

**Comment by Commandcracker** [comment]
Now I understand, it would make sense to have booth fabricmc and minecraft-forge :D

**Comment by SquidDev** [comment]
What's ComputerCraft Tweaked? That's a name I've never heard of.
