### ISSUE TITLE
Quilt support

### ISSUE THREAD

**Issue by Commandcracker** [SquidDev-CC/CC-Tweaked#1519]
Are there any plans for [Quilt](https://quiltmc.org/en/) builds ?
Quilt might become the new main mod loader when it comes out of beta :D

https://modder.wiki.quiltmc.org/versions/1.19/getting_started/setup/migrating_from_fabric/

**Comment by SirEdvin** [comment]
Fabric builds works for Quilt just fine, I suppose, or not?

**Comment by Commandcracker** [comment]
Yes, but Quilt may offer some [features](https://github.com/QuiltMC/quilt-standard-libraries/tree/1.20#features) that make it worth of having a separate build. I don't really know if there are any, that's why I made this issue, to ask :squid:.

**Comment by SirEdvin** [comment]
So, this is only my opinion, but usually with multi-loader mod introducing extra logic for something that already working is fine is usually strange idea ...

**Comment by SquidDev** [comment]
Sorry, realise I never ended up commenting on this. I'd definitely be interested in having explicit Quilt support in the future, but right now it's just not practical.

The main problem is that the QSL is missing a lot of functionality that CC:T heavily relies on. Some of this we could reimplement CC:T side (screen handlers, fake players) or could PR upstream (custom audio streams), but some things would require a lot of time to design and implement (for instance a block lookup/capability system).

We'd also have to make sure all of this is compatible with Fabric mods trying to run on top of Quit, which seems like a nightmare.
