### ISSUE TITLE
CraftyTurtle crashes world

### ISSUE THREAD

**Issue by PCThrow** [SquidDev-CC/CC-Tweaked#1522]
### Minecraft Version

1.19.x

### Version

1.101.3

### Details

Crafts it fine, but the instant you put the crafty turtle down, the world crashes.  Sometimes it renders the turtle first, sometimes not.
[2023-07-16-3.log.gz](https://github.com/cc-tweaked/CC-Tweaked/files/12065091/2023-07-16-3.log.gz)

**Comment by SquidDev** [comment]
It appears you're running an incompatible version of Forge and Optifine together. When [downloading Optifine](https://optifine.net/downloads), make sure you're running the _exact_ version of Forge recommended there.

That said, I'd really recommend [replacing Optifine with Occulus](https://modrinth.com/mod/oculus).
