### ISSUE TITLE
rednet.recieve bug

### ISSUE THREAD

**Issue by HappyYoyo09** [SquidDev-CC/CC-Tweaked#1528]
### Minecraft Version

1.20.x

### Version

1.106.1

### Details

when using the code from the official wiki, it gives an error. the code in question is the rednet.recieve code with no timeout. it just says that there is an unexpected = sign, and suggests using ==, which does nothing.
here's a link to the log
https://mclo.gs/XQbYde0

**Comment by SquidDev** [comment]
Can you post the code you're trying to run? I've just tested [all three examples from the docs](https://tweaked.cc/module/rednet.html#v:receive), and they appear to work.
