### ISSUE TITLE
Support for different types of Spanish

### ISSUE THREAD

**Issue by piguman3** [SquidDev-CC/CC-Tweaked#1535]
In Minecraft there are many types of Spanish dialects, 
![imagen](https://github.com/cc-tweaked/CC-Tweaked/assets/113848275/3c75565d-3fba-4bdf-ad50-539358d6cc51)
and only the Spain Spanish translation is supported.

### The 2 solutions I think could work are:
- To apply the Spain Spanish translation to all of the other translations, which would be slightly inaccurate but would work fine in most situations.
- To create different translations for each dialect, which would be hard and demand a lot of work, but would give the most accurate results.

**Comment by SquidDev** [comment]
I think the best thing to do is probably rename the current `es_es.json` to just `es.json`, and that will be used as a fallback for all Spanish languages, and then other translations can override that if needed.

Unfortunately, it doesn't look like there's great support for this in Weblate - you can set up [secondary languages](https://docs.weblate.org/en/latest/user/profile.html#secondary-languages), but that's it.

I'm afraid I'm going to leave this to someone who understands the differences between the various dialects. The Spanish translation is pretty unloved in general right now, so any help with that would be appreciated.
