### ISSUE TITLE
[1.13.2 Forge] Crash on Client Load

### ISSUE THREAD

**Issue by Morpheus1101** [SquidDev-CC/CC-Tweaked#154]
https://pastebin.com/cV2uCnCs 

using Forge *.90
CC-Tweaks 1.81.1

**Comment by SquidDev** [comment]
Can you try with [this jar](https://www.dropbox.com/s/ho7gqx7xs16hu6o/cc-tweaked-1.13.2-1.81.1-network-fix.jar?dl=1) and see if it resolves this issue. It's most curious, as this code definitely worked when I tested it.

**Comment by Morpheus1101** [comment]
Yes, this works quite fine

**Comment by SquidDev** [comment]
Great :). I'm hoping to get another build out soonish, but this'll do for now :).
