### ISSUE TITLE
Farming Turtles can't till dirt below them

### ISSUE THREAD

**Issue by HumorousHooke** [SquidDev-CC/CC-Tweaked#1540]
### Minecraft Version

1.20.x

### Version

1.106.1

### Details

As of version 1.106.1 farming turtles can not till dirt below them. This effects fabric and forge version. 
**To replicate:**
-Install 1.106.1
-Place farming turtle 1 block above dirt
-Try to till land below
-Observe it can still till dirt in front of it

Version 1.105 is unaffected 

![image](https://github.com/cc-tweaked/CC-Tweaked/assets/13653568/08ba04ab-3b26-49d7-84f6-10f076d11c67)

**Comment by Lupus590** [comment]
I seem to remember that turtles will only till dirt if the resulting farmland would be able to become hydrated. Have you tried with a water source nearby?

**Comment by SquidDev** [comment]
There were a couple of issues introduced with tools in the latest version. These are now fixed (see #1527), but not yet released.
