### ISSUE TITLE
Transparent Monitors

### ISSUE THREAD

**Issue by G4PLS** [SquidDev-CC/CC-Tweaked#1541]
A block that behaves like a monitor but thats transparent.
Use something like glass blocks or glass panes and display monitor content on them.

It would be really nice for cool looking HUDs. When you create builds you wouldnt have a monitor wall instead you have a monitor wall where you can look through. 

For example When you build something like an airport and have a tower where you basically only have glass a normal monitor wall would be really annoying, having something to just look through would be a loot neater

Thats basically it with my feature request. I dont know how hard it would be to even implement because im not into modding.

**Comment by SquidDev** [comment]
Thank you for the suggestion! While I do think this would look cool, I'm afraid I don't think it really fits in with the aesthetic that CC has.
