### ISSUE TITLE
[1.20.1] Peripherals are not Recognized

### ISSUE THREAD

**Issue by Flexico** [SquidDev-CC/CC-Tweaked#1543]
### Minecraft Version

1.20.x

### Version

1.106.1

### Details

No computers or turtles, with the exception of pocket computers, recognize any connected peripherals!

**Comment by Wojbie** [comment]
Any chance you have Optifine installed and this is another instance of #1458 ?

**Comment by SquidDev** [comment]
Please, please, please include your logs when reporting bugs. They contain lots of useful information (other mods installed, whether you're using Forge/Fabric, errors/warnings) that are vital for reproducing bugs.

**Comment by Flexico** [comment]
I've tested it and it does seem to be an Optifine problem! Here's my log in case it can still be useful.
https://pastebin.com/buniZpdC
