### ISSUE TITLE
Minecraft Crashes with Exit Code 1

### ISSUE THREAD

**Issue by abcvacuum** [SquidDev-CC/CC-Tweaked#1555]
### Minecraft Version

1.20.x

### Version

cc-tweaked-120.1-forge-1.106.1

### Details

I am playing ATM9 with CurseForge. We have setup a server and it is using cc-tweaked-120.1-forge-1.106.1.   I upgraded to that version in CurseForge. At that point, it crashes the Minecraft client. None of the other users are having this issue. When I disable cc-tweaked-120.1-forge-1.106.1 or go to the previous version, the client works just fine. I'm technical (IT, not Dev), if you want me to try something to debug, let me know. 

[latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/12308530/latest.log)

**Comment by SquidDev** [comment]
You'll need to update Forge to the latest version - anything after 47.1.0 should work. It looks like you're currently running 47.0.14.
