### ISSUE TITLE
Diamond Hoe not tilling soil

### ISSUE THREAD

**Issue by Inksaver** [SquidDev-CC/CC-Tweaked#1557]
### Minecraft Version

1.20.x

### Version

1.106.1Forge Jul 8 2023

### Details

I am unable to use the hoe to till soil in a downwards direction. Previous versions: turtle 1 block above soil and use turtle.digDown(). Have tried turtle.digDown("left") and "right": 'Nothing to dig here'
Tried in direct contact with dirt: 'Cannot break block with this tool'
Tried turtle.dig([side]) as well. This works if placed immediately in front, as does turtle.digUp([side]) with block above.
If this is not a bug, then some serious recoding required to harvest and plant crops by removing and replacing dirt, then placing a crop from the side.
turtle.placeDown() works if the hoe is in the inventory, but is then damaged.
Have tried attack() and variations as well

**Comment by SquidDev** [comment]
There were a couple of issues introduced with tools in the latest version. These are now fixed (see #1527), but not yet released.
