### ISSUE TITLE
Crash when active computer is next to Tech Reborn storage

### ISSUE THREAD

**Issue by ali1234** [SquidDev-CC/CC-Tweaked#1563]
### Minecraft Version

1.20.x

### Version

1.107.0

### Details

Mods:

CC: Tweaked: 1.107.0
Fabric API: 0.87.0+1.20.1
Reborn Core: 5.8.6
Tech Reborn: 5.8.6

Steps to reproduce:

1. Make a new creative world.
2. /give self computercraft:computer_normal
3. /give self techreborn:crude_storage_unit
4. Place the computer.
5. Right click the computer to activate CraftOS.
6. Place the storage unit next to it.

Result:

The game crashes. Attempting to restart and reload the world also crashes.

The crash appears to be caused by the computer attempting to use the storage unit as a peripheral. 

Log:
[crash-2023-08-17_03.37.25-server.txt](https://github.com/cc-tweaked/cc-restitched/files/12364905/crash-2023-08-17_03.37.25-server.txt)

**Comment by SquidDev** [comment]
This appears to be an issue on the TechReborn side. I've opened an issue on their end with more details: TechReborn/TechReborn#3175.
