### ISSUE TITLE
turtle.craft()

### ISSUE THREAD

**Issue by gogedo** [SquidDev-CC/CC-Tweaked#1567]
### Minecraft Version

1.20.x

### Version

cc-tweaked-1.20.1-forge-1.107.0

### Details

Turtle don't craft

**Comment by SirEdvin** [comment]
Do you equip crafting table?

**Comment by SquidDev** [comment]
I'm afraid I cannot reproduce this. Could you post a screenshot of your turtle's GUI, with the recipe and error message you get visible?

**Comment by SquidDev** [comment]
Afraid I'm going to close this as the original report doesn't give me much to go on here. Happen to reopen if someone can reply with further information.
