### ISSUE TITLE
Recipe mod (JEI/REI) recipe/usage keys conflict with typing

### ISSUE THREAD

**Issue by vico93** [SquidDev-CC/CC-Tweaked#1571]
### Minecraft Version

1.20.x

### Version

1.107.0

### Details

Seemingly minor annoyance, but if using a mod that register letter keys as hotkeys (in my case, [REI](https://github.com/shedaniel/RoughlyEnoughItems)), when opening a turtle console (didn't tested on normal/advanced/pocket computers) if i try to type anything with the cursor over an item of either my or turtle's inventory, whatever letter key that is assigned to a hotkey will be activated instead of typing in the console.

Here's a video demonstration of the issue (notice that letters R and U only get "registered" by the console if the cursor is out of any of the inventory slots):

https://github.com/cc-tweaked/CC-Tweaked/assets/3485505/c493c849-019e-4fe2-970f-5522d4812291

**Comment by SquidDev** [comment]
I definitely agree that this is a pain, but I don't think there's really a good way to fix this. Sometimes one wants to find the recipe/usage of an item, and sometimes one wants to type the letter "r" - there's not really any way to know which!

**Comment by vico93** [comment]
> I definitely agree that this is a pain, but I don't think there's really a good way to fix this. Sometimes one wants to find the recipe/usage of an item, and sometimes one wants to type the letter "r" - there's not really any way to know which!

I see. Cancelling the hotkey when the turtle UI is open would have negative effects for other usages. I will try to assign another key for those actions that don't interfere much with CC:T typing.

**Comment by Lupus590** [comment]
Or you can just make sure that your mouse is not over the inventory or any other items when you type.
