### ISSUE TITLE
"Cannot mount Rom" when runin with running with IntelliJ

### ISSUE THREAD

**Issue by Wilma456** [SquidDev-CC/CC-Tweaked#158]
If I run CC-Tweaked with IntelliJ, I always get this Error:
![2019-03-26_19 34 00](https://user-images.githubusercontent.com/15185051/55026660-c0b93d00-5003-11e9-9aab-c66d789f2833.png)
I setup the Mod with this Commands:
```
./gradlew --stacktrace setupDecompWorkspace --refresh-dependencies
./gradlew --stacktrace cleanIdea idea
```

**Comment by SquidDev** [comment]
Can you upload your run configuration and see if there's anything in the logs? I've never come across this issue, so I suspect it's an issue with your setup.

**Comment by Wilma456** [comment]
[Here is the log](https://hastebin.com/cixopaqepe.md)

btw:
The Error message is a liitle bit broken on Pocket Computers:
![2019-03-26_20 27 42](https://user-images.githubusercontent.com/15185051/55027791-640b5180-5006-11e9-9d6a-16e5dd7e9d21.png)

**Comment by SquidDev** [comment]
```
[20:24:24] [main/ERROR] [FML]: Unable to read a class file correctly
java.lang.IllegalArgumentException: null
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185) ~[asm-debug-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168) ~[asm-debug-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:439) ~[asm-debug-all-5.2.jar:5.2]
[20:24:25] [main/WARN] [FML]: Zip file junit-platform-commons-1.1.0.jar failed to read properly, it will be ignored
net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException

	at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:63) ~[ASMModParser.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.findClassesASM(JarDiscoverer.java:102) ~[JarDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:77) [JarDiscoverer.class:?]
```

Well, these are somewhat concerning. A couple of things to try:
 - Does it work if you use `./gradlew runClient`?
 - Can you take a screenshot of your run configuration?

**Comment by Wilma456** [comment]
./gradlew runClient works!

Here's the run configuration:
![Screenshot at 2019-03-27 15:04:21](https://user-images.githubusercontent.com/15185051/55082292-b51c5380-50a1-11e9-88be-602e15d3cacf.png)

**Comment by Wilma456** [comment]
If I load a World that I created in a  IntelliJ Instance with a gradlew runClient, I get this Error:
![Screenshot at 2019-03-27 15:34:10](https://user-images.githubusercontent.com/15185051/55084928-121a0880-50a6-11e9-95ed-5b5c11de3baf.png)

**Comment by SquidDev** [comment]
> Here's the run configuration:

On the "Use classpath of module" section, see if you can select `cc-tweaked-1.12.2-main` instead. If that doesn't work, then I'm at a loss.

> If I load a World that I created in a IntelliJ Instance with a gradlew runClient, I get this Error:

Yeah, ForgeGradle/IntelliJ integration is a little broken so MCMultipart + Charset get injected into the wrong scope. It's OK to hit yes.

**Comment by Wilma456** [comment]
There is no cc-tweaked-1.12.2-main. There is only cc-tweaked-1.12.2.

**Comment by SquidDev** [comment]
Ahh, probably because you ran the `idea` task instead of importing directly. Really not sure what's going on then.

**Comment by Wilma456** [comment]
This two commands works perfect with the old CC. What commands do you suggest instead to make the code ready for IntelliJ?

**Comment by SquidDev** [comment]
Curious - nothing should have changed which'd cause file mounts to suddenly stop working. I Just use IntelliJ's built-in Gradle importing instead.

**Comment by Wilma456** [comment]
How do I run the mod, if I use the Gradle importer? "Minecraft Client" is not in the list.

**Comment by SquidDev** [comment]
You can use `./gradlew genIntellijRuns`, or just create a new task like your screenshot above. See also [the MinecraftForge docs](https://mcforge.readthedocs.io/en/latest/gettingstarted/#terminal-free-intellij-idea-configuration).

**Comment by Wilma456** [comment]
That worked for me! Thanks!
