### ISSUE TITLE
Forge server crash with NoClasDefFoundError

### ISSUE THREAD

**Issue by kyokeen** [SquidDev-CC/CC-Tweaked#1583]
### Minecraft Version

1.20.x

### Version

1.20.1-forge-1.106.0

### Details

Hello,

While playing, I found a computer situated in a village and tried interacting with it (first time doing this on a server that's 4 days old). Upon interacting with it, the server threw NoClassDefFoundError. Looking around cc-tweaked code, found that [PeripheralMethod class](https://github.com/cc-tweaked/CC-Tweaked/blob/mc-1.20.x/projects/core/src/main/java/dan200/computercraft/core/methods/PeripheralMethod.java) is in core package `methods` not `asm`... I would assume this was the cause of the error. 
[Here is the stack trace](https://github.com/cc-tweaked/CC-Tweaked/files/12528291/crash-report.txt)

I cannot reconnect to the server anymore. Even though the server starts as expected, when I reconnect it crashes with the same error.

I tried updating mod to 1.108 but the issue was not fixed.

Environment:
- FTB forge server 1.20.x, modpack 1.5.0

Repro steps:
1. Find computer (player X)
2. Right click on it to interact

Behavior: 
- server crashed
- server can be restarted, but when player X tries to reconnect server crashes with the same exception
- player Y was able to connect and join the server, but caused the same server crash when loading the chunk where player X/the computer was

Expected:
- no server crash i guess

Thanks a lot.

**Comment by Lupus590** [comment]
Do you have any add-on mods? I believe that one of them adds world generated computers and CC doesn't do that itself.

**Comment by SquidDev** [comment]
This is caused by Advanced Peripherals - you will need to update to the latest version of that too.

**Comment by kyokeen** [comment]
@SquidDev thanks a lot, however I could not update Advanced Peripherals. Other mods seem to depend on a specific AP version; all I tried was copy-paste the jar into the mods file, is there a better/correct way to do this?

**Comment by SquidDev** [comment]
Can you post the errors you get when trying to update?

CC @SirEndii here - you might have a better idea of what's going wrong?

**Comment by SirEndii** [comment]
Could you tell me which mods rely on AP? AP isn't made to be used as an API, so I am not sure if these mods should do that.

So yeah, only updating AP to 0.7.32b would fix your issue

I would like to know the mods which use AP as a mandatory Dependency so I could reach out to them.

0.7.32b is also already a month old, so these mods are quite out of date

**Comment by kyokeen** [comment]
@SirEndii thank you for your reply. I tried to use 0.7.32b again (copy-paste into the mods folder) and server did not start. The only difference between logs of the previous (working) server and the one using 0.7.32b is this line:
`[18Sep2023 20:58:48.694] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Unsupported installed optional dependencies:
	Mod ID: 'ae2', Requested by: 'advancedperipherals', Expected range: '[15.0.5-beta,)', Actual version: '15.0.4-beta'`
So I went in and got 15.0.5-beta version from [curseforge](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2/files/4647844)

But the server would not open, this time with another error: [pastebin](https://pastebin.com/ig0eJZzK)
`[18Sep2023 21:16:50.963] [main/FATAL] [mixin/]: Mixin apply failed AEInfinityBooster.mixins.json:MixinWirelessTerminalMenuHost -> appeng.helpers.WirelessTerminalMenuHost: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on testWap could not find any targets matching 'testWap' in appeng.helpers.WirelessTerminalMenuHost. Using refmap AEInfinityBooster.refmap.json [PREINJECT Applicator Phase -> AEInfinityBooster.mixins.json:MixinWirelessTerminalMenuHost -> Prepare Injections ->  -> handler$zee000$testWap(Lappeng/api/implementations/blockentities/IWirelessAccessPoint;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
`
Here is the [debug log](https://pastebin.com/HmgBzARe)

Thanks a lot

**Comment by SirEndii** [comment]
You either remove the AEInfinityBooster mod or wait until it gets an update
The thing with AP and CC got fixed with the latest version, that is now an AE2 and a AE2 addon(AEInfinityBooster) Issue

**Comment by kyokeen** [comment]
Confirm it works when I removed AEInfinityBooster. Thanks a lot, guys, for the speedy and helpful responses.
