### ISSUE TITLE
API for `peripheral_hub` chaining

### ISSUE THREAD

**Issue by SirEdvin** [SquidDev-CC/CC-Tweaked#1584]
So, I am trying to make this work.

![2023-09-11_20 56 39](https://github.com/cc-tweaked/CC-Tweaked/assets/3713151/594a3922-b1ca-4c09-bb86-67bb25f99eee)

I can create chaning from one peripheral proxy to another, but it is complicated things to do with wired modems. I don't want to artificially reuse wired networks here, because it probably would create some (a lot, actually) confusion. 

Can I suggest to have some interface that `peripheral_hub` Peripherals should implement to became _chain-able_ into another `peripheral_hub`'s?

**Comment by SquidDev** [comment]
While I think the concept is fine, I think the implementation of this is going to be incredibly nasty and/or error-prone, which ever way you slice it. I can elucidate, but it will require an essay, so hoping you can trust me on this and spare me from that :D.

I've made a change in b1248e4901aa70c73edabb23d0ffe87f201f6dbb which allows you to prevent the peripheral proxy being wrappable by a modem (if you so wish), similar to your current `peripheral_proxy_forbidden` tag. 

This is _exactly_ what the wired network API is here for. Use it!

**Comment by SquidDev** [comment]
> I've made a change in b1248e4 which allows you to prevent the peripheral proxy being wrappable by a modem (if you so wish), similar to your current `peripheral_proxy_forbidden` tag.

There's an argument that peripheral hubs should ignore any other peripheral tagged as `peripheral_hub`. I think making that change now is unhelpful, but is tempting in the future.

**Comment by SirEdvin** [comment]
> This is exactly what the wired network API is here for. Use it!

Well, I can understand, but for this I would need to make peripheral proxy part of wired network and (!) part of my own wireless network to make it work. Which is possible, but 
> I think the implementation of this is going to be incredibly nasty and/or error-prone, which ever way you slice it.

However, I am pretty sure that implementing API for this would be a little hell by itself, so I am perfectly fine with tag solution! I hope, in my planned future mod related to network I will make something crazy enough to work.

**Comment by SquidDev** [comment]
Hrmr, what do you mean by "wireless network" here - that seems a little suspicious.

**Comment by SirEdvin** [comment]
Something that I did with Enderwire networks :) 

![зображення](https://github.com/cc-tweaked/CC-Tweaked/assets/3713151/29e6f912-a522-4db7-8810-dd3c2914c502)

But I would need to handle something like this
![зображення](https://github.com/cc-tweaked/CC-Tweaked/assets/3713151/16df945e-4326-4599-bfc2-e4fd80536012)

So I would need a nice wireless network implementation, that could be handle cycles, sharing peripherals with all peripheral proxies in one direction or in two-way directions.
