### ISSUE TITLE
Access denied 

### ISSUE THREAD

**Issue by Jesse-Lucas1996** [SquidDev-CC/CC-Tweaked#1586]
### Minecraft Version

1.16.x

### Version

1.89.2

### Details

In Feed the beast revelation I get access denied creating any type of file 
places told me to restart server which I've done many times

**Comment by SquidDev** [comment]
I'm afraid 1.12 versions of the mod are no longer supported.

**Comment by fatboychummy** [comment]
This is likely a server config issue, make sure whatever user account is running the server has access to edit files in the `<worldfolder>/computercraft` folder.

**Comment by Jesse-Lucas1996** [comment]
Confirmed
Computer was a locked folder for some reason
sudo chmod a+rw ./computer did the trick
