### ISSUE TITLE
HTTP API broken on 1.4.7

### ISSUE THREAD

**Issue by ThePixelbrain** [SquidDev-CC/CC-Tweaked#1587]
The HTTP API appears to be broken when adding the CC-Tweaked coremod on MC 1.4.7.

It's not possible to get or post anything, it always just returns "nil". An easy way to test this is by using the pastebin program, which doesn't work because of this.
This bug is pretty game breaking, as downloading code from or to Computers is impossible right now.

Tested in the Rewind Upsilon modpack (v. 0.5.2) and CC-Tweaked 1.4.7-1.105.1.

PS: The issue template for reporting bugs doesn't allow the selection of 1.4.7, which is why I had to use the empty one.

**Comment by SquidDev** [comment]
Thanks for the report!

> PS: The issue template for reporting bugs doesn't allow the selection of 1.4.7, which is why I had to use the empty one.

Yeah, 1.4.7 isn't really an officially supported version, hence it not being there.

**Comment by walksanatora** [comment]
what else are you even playing with on 1.4.7

**Comment by SquidDev** [comment]
[Rewind Upsilon](https://www.rewindmc.com/#upsilon) - it's a really neat pack, I'd recommend checking it out for the loading screen alone.
