### ISSUE TITLE
Cannot serliaze table with recursive entities

### ISSUE THREAD

**Issue by SirEdvin** [SquidDev-CC/CC-Tweaked#1588]
### Minecraft Version

1.20.x

### Version

1.108

### Details

It seems, it is impossible to serialize table, that contains several instances of another table.

For example, like here:

```lua
local empty_table = {}
local big_table = {empty_table, empty_table}
print(textutils.serializeJSON(big_table))
```

But itself it probably fine, but with combination different minecraft addons, that usually use `Collections.emptyList` or something like this to return empty values, this leads to strange issues, when table, that are purely serializable at first glance, turns out to be not serializable. 

![зображення](https://github.com/cc-tweaked/CC-Tweaked/assets/3713151/fcf9f7ba-0ff1-4de2-9081-f9c01781ebd1)

I believe, or empty tables should be excluded from this rule, or Java -> Lua transformation should always create new table for empty table.

**Comment by SquidDev** [comment]
I'm not really sure there's a sensible and disciplined way to "fix" this. As I've mentioned elsewhere (i.e. #1368), I really want `textutils.unserialise(textutils.serialise(x))` to return an equivalent table, and so excluding empty tables from this check is a bit silly. Similarly, special-casing any empty collection on the Java side is wrong.

We _could_ special-case some of the known empty collections (`List.of()`, `Collections.emptyList()`, and their set and map equivalents), but this feels ugly.

As an aside, one can pass [`{ allow_repetitions = true }` to the serialise function](https://tweaked.cc/module/textutils.html#v:serialise) to prevent this error.

**Comment by SirEdvin** [comment]
To serialize function, but not to serializeJSON, I believe?

**Comment by SquidDev** [comment]
Oh, so it doesn't. We should definitely add that then.
