### ISSUE TITLE
Configurable speaker range

### ISSUE THREAD

**Issue by mjarduk** [SquidDev-CC/CC-Tweaked#1592]
While playing a modpack which included CC: Tweaked I stumbled upon an annoying issue: the speakers range was sometimes a tidbit too small. 

What I wish and pray for is to have one more line in the configuration file that would set the range of all speakers in the world.

**Comment by woooferz** [comment]
This would be so useful!

**Comment by SquidDev** [comment]
Not sure if you're aware already, but all the [`speaker` methods](https://tweaked.cc/peripheral/speaker.html) take a `volume` argument, which can be up to 3 (audible up to 48 blocks away).

I don't want to increase that limit any further - as mentioned in #1223, I don't really want to add any more config options which change how computers or peripherals behave. In those sorts of cases, it should be possible to have multiple speakers and network them together.
