### ISSUE TITLE
java.lang.NoClassDefFoundError: dan200/computercraft/shared/peripheral/monitor/ClientMonitor

### ISSUE THREAD

**Issue by ModernGamingWorld** [SquidDev-CC/CC-Tweaked#1596]
### Minecraft Version

1.19.x

### Version

cc-tweaked-1.19.2-1.101.3

### Details

[crash-2023-09-28_11.28.48-client.txt](https://github.com/cc-tweaked/CC-Tweaked/files/12751876/crash-2023-09-28_11.28.48-client.txt)

[latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/12751880/latest.log)

**Comment by SquidDev** [comment]
Thank you for the report. This looks to be a duplicate of https://github.com/cc-tweaked/CC-Tweaked/issues/979, which I believe is caused by a nasty interaction with Forge's class loading and CC. This is fixed on later versions of Minecraft.
