### ISSUE TITLE
Monitor getTextScale() returns value double of expected.

### ISSUE THREAD

**Issue by Wojbie** [SquidDev-CC/CC-Tweaked#16]
When you getTextScale() it returns value that is double of current textScale.

Per example getTextScale() returns 5 with scale 2.5 and 8 with scale 4.

**Comment by Wojbie** [comment]
I believe [line ](https://github.com/SquidDev-CC/CC-Tweaked/blob/662fb96beb971578f67bbb0aa4e06839af2bf724/src/main/java/dan200/computercraft/shared/peripheral/monitor/MonitorPeripheral.java#L246) should divide by 2.

Cause [line](https://github.com/SquidDev-CC/CC-Tweaked/blob/662fb96beb971578f67bbb0aa4e06839af2bf724/src/main/java/dan200/computercraft/shared/peripheral/monitor/MonitorPeripheral.java#L150) multiplies by 2 in other direction.

**Comment by SquidDev** [comment]
Thanks for the report: I noticed this a couple of days ago and then promptly forgot.
