### ISSUE TITLE
Camera block

### ISSUE THREAD

**Issue by BigBang1112** [SquidDev-CC/CC-Tweaked#160]
I know it's not an easy one, but I have a need to share it.

Camera block could be something like a very low-quality viewport that can be rendered on the computer in a similar way as Paint program does.

- This rendered image would be possible to render straight in a nearby computer or sent through modems by data in some sort.
- You would be able to set FOV, render settings etc by using an API.
- Stone camera block would receive a black and white image, Gold camera block would receive a colorful image.

Negative is the complexity of the raycasting (or any similar technology used for this, I don't really know) and the performance drop it could bring. But the positive side is the low-resolution ComputerCraft is intentionally limited to.

I'm unable to contribute into this myself as of my lacking Java nor Forge experience. But this would be something I would find beautiful seeing.

**Comment by SquidDev** [comment]
It would definitely be cool to have, but sadly there's several technical limitations which make this effectively impossible to do. The server (where ComputerCraft does most of its work) doesn't have any idea how to do rendering (no block models, textures, etc...) so you'd effectively only be able to render based on if there's a block there or not.

It'd probably be possible to do something with [Plethora's block scanner](https://squiddev-cc.github.io/plethora/items/module-scanner.html). Honestly though, I feel this is something better suited for an external mod - it's a really cool feature, but I'm not sure how useful something would actually end up being for most users.
