### ISSUE TITLE
Problems using CC:Tweaked and Optifine

### ISSUE THREAD

**Issue by THeExUduS** [SquidDev-CC/CC-Tweaked#1602]
### Minecraft Version

1.20.x

### Version

1.108.1

### Problem:
Using CC:Tweaked and Optifine causes multiple bugs. Not sure on whose side, but just in case :

- Computers cannot see any modems as peripherals (although turtles can use them)
- Network Cables don't connect to any other than one side

No config files of any mod were changed.

### Versions:
Minecraft version: 1.20.1
Forge version: 47.1.41
CC: Tweaked versions: 1.20.1-forge-1.108.1, 1.20.1-forge-1.108.0 or 1.20.1-forge-1.107.0
Optifine versions: 1.20.1_HD_U_I6_pre6 or 1.20.1_HD_U_I6_pre5
(any other Optifine version crashes immediately)

### JVM Arguments in Profile:
-Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Dorg.lwjgl.opengl.Window.undecorated=true

**Comment by SquidDev** [comment]
This is a bug with Optifine - see also https://github.com/sp614x/optifine/issues/7395 and #1458. This has been open for multiple months on their end, so I'm not holding out much hope of it being fixed.

I'd recommend [switching to Occulus](https://modrinth.com/mod/oculus) instead, which is much better behaved with other mods.
