### ISSUE TITLE
WGet run adds wierd characters to unicode

### ISSUE THREAD

**Issue by mirkokral** [SquidDev-CC/CC-Tweaked#1605]
### Minecraft Version

1.19.x

### Version

1.101.3

### Details

When running code directly with WGet run, wierd characters appear near unicode characters. Note: They do not appear if the file is downloaded by wget and then ran from the shell.

![2023-10-07_08 31 20](https://github.com/cc-tweaked/CC-Tweaked/assets/75212488/5e60ab17-53b7-4531-941b-c32eef8435fa)
Notice the chat.

**Comment by SquidDev** [comment]
I suspect this is another instance of #1246 - `wget` downloads the file in binary mode, but the  shell runs it in text mode, which will interpret the unicode characters differently.

I'm not quite sure what you mean by "Notice the chat".
