### ISSUE TITLE
1.20.2 support?

### ISSUE THREAD

**Issue by ArsiTheFox** [SquidDev-CC/CC-Tweaked#1606]
Just asking when 1.20.2 support will be available <3

**Comment by ArsiTheFox** [comment]
Keep up the AMAZING work <3

**Comment by SquidDev** [comment]
No clue I'm afraid. I'm currently wainting for NeoForge to be updated, but there's a good chance I'll just skip 1.20.2 and wait for 1.20.3.

**Comment by ArsiTheFox** [comment]
> No clue I'm afraid. I'm currently wainting for NeoForge to be updated, but there's a good chance I'll just skip 1.20.2 and wait for 1.20.3.

Hecciez
`*~Sad foxxor noises~*`

No problem man, thx for the update

**Comment by vico93** [comment]
> No clue I'm afraid. I'm currently wainting for NeoForge to be updated, but there's a good chance I'll just skip 1.20.2 and wait for 1.20.3.

tbh i'm going to do the same thing on my end. While 20.3 isnt ready i'm trying other indie games to kill the time, but i think i will reassemble my modpack in 1.20.1 for the while just because CC:T.

Anyway, keep the good work with this amazing mod!
