### ISSUE TITLE
Monitor bug introduced with commit in 1.108.2

### ISSUE THREAD

**Issue by Selim042** [SquidDev-CC/CC-Tweaked#1608]
### Minecraft Version

1.20.x

### Version

Fabric 1.108.3

### Details

When a monitor block that is directly attached to a computer is broken, if it is any column of the structure other than the first, the monitor will no longer be usable until the world is reloaded (and possibly chunk reload).  See below screenshots for examples.

![image](https://github.com/cc-tweaked/CC-Tweaked/assets/8419844/84fe6f02-e9e2-4814-9042-a1260e9e63ba)
This layout works after replacing the connecting monitor:
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/8419844/b9fa5b7b-6c7a-4fba-9020-626cb7b1e4f7)
This one doesn't:
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/8419844/92802b40-4870-4dec-a424-fe79db00b680)

Credit to @PatriikPlays for testing this out.  They went to the commit before this one: https://github.com/cc-tweaked/CC-Tweaked/commit/ab785a090698e6972caac95691393428c6f8370b
and found that monitors worked as expected, but including the changes made in that commit then re-introduces the issue.

**Comment by SquidDev** [comment]
Thank you for the detailed report, that was very helpful!
