### ISSUE TITLE
Chunk Loading turtle

### ISSUE THREAD

**Issue by EnderShadow** [SquidDev-CC/CC-Tweaked#161]
This is similar to #117 but still a separate suggestion. My suggestion is that a config option is added that makes turtles load the chunk they're in (and the the 4 chunks around them if they can't move to unloaded chunks) or a chunk loading turtle is added which allows the turtle to chunkload a configurable number of chunks around them.

**Comment by SquidDev** [comment]
This has always been something I've felt better suited to an external mod. There's a lot of technicalities which arise from this (what chunk loading strategy do you use, how do you impose limits, etc...) and that's a whole rabbit hole I really don't want to go down as part of CC:Tweaked.

I'm personally also not really a fan of chunkloaders except when you really need them. They rather break the fourth wall and expose Minecraft internal mechanics, which is something CC:T generally tries to avoid.

**Comment by EnderShadow** [comment]
Ah ok.

**Comment by NicTanghe** [comment]
kindof lame reply this should md should have the chunk loader module

**Comment by m00nlygreat** [comment]
If you didn't know about chunk loading, you might have thought that turtles could work in the world by themselves. In my opinion it's the opposite. Turtles that do not work when there are no players around reveal the secrets of chunk and chunk loading in minecraft

**Comment by SPOOKEXE** [comment]
Definitely think this should be an option. Could be a separate module (like how apotheosis does it for its features) for it so its fully toggleable, or have a configuration option that can enable/disable it (disabled by default) as letting my turtles keep chunks loaded they're working in is a must without having to reserve a equipment slot for a chunk loader item in advanced peripherals
