### ISSUE TITLE
placing signs with turtle.place("text") does not show the text

### ISSUE THREAD

**Issue by DragonCraft5** [SquidDev-CC/CC-Tweaked#1611]
### Minecraft Version

1.20.x

### Version

1.08.3

### Details

[latest - Copy.log](https://github.com/cc-tweaked/CC-Tweaked/files/13053278/latest.-.Copy.log)

this is a video to my problem:
https://youtu.be/9wsXJsFN1x0

**Comment by SquidDev** [comment]
Thanks for the report, looks like that crept in during the 1.20 update.
