### ISSUE TITLE
"Incorrect server given" on server tick

### ISSUE THREAD

**Issue by blackcatwithpurpleeyes** [SquidDev-CC/CC-Tweaked#1612]
### Minecraft Version

1.18.2

### Version

1.101.3

### Details

I have gotten this issue with my modpack and i don't know what to do. can i have some help? i have included the log file and crash report it kept saying something about computer craft so that why im here.
[crash-2023-10-22_19.07.58-server.txt](https://github.com/cc-tweaked/CC-Tweaked/files/13065539/crash-2023-10-22_19.07.58-server.txt)
[latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/13065537/latest.log)

also how do i add labels?

**Comment by blackcatwithpurpleeyes** [comment]
also how do i add labels?

**Comment by SquidDev** [comment]
Thank you for the report! That's very odd - it suggests the server startup event didn't get delivered properly. Will have a look to see what's going on.

> also how do i add labels?

Normally when you create an issue you should be given a screen [like this](https://github.com/cc-tweaked/CC-Tweaked/issues/new?assignees=&labels=bug&projects=&template=bug_report.yaml) which prompts you for some extra fields and fills in the labels. What buttons did you press to report the bug, not quite sure why you didn't get shown this form!

**Comment by SquidDev** [comment]
Just to clarify, I don't _believe_ this is a CC:T issue. This should never happen under normal situations - my suspicion is that another mod is causing issues, and CC:T is the first mod to be affected.

Going through the log, I can't see anything obvious. My main suggestion here would be to remove a bunch of mods at a time until you can narrow it down to a minimal set of mods. Essentials is spitting out a lot of errors <sub><sup>(and frankly is a pretty dubious mod)</sup></sub>, so I'd probably try without that first - it'll at least make your log less of a mess :).

**Comment by blackcatwithpurpleeyes** [comment]
thanks, and what i pushed was new issue and then other because i don't know what category to put it in.

**Comment by blackcatwithpurpleeyes** [comment]
tried doing that and it dint help still the same thing.

**Comment by SquidDev** [comment]
When you say "tried doing that", what do you mean? Did you find a minimal set of mods which cause this issue?

**Comment by blackcatwithpurpleeyes** [comment]
no tried deactivating mods that probably caused the issue like essentials and the origins mod and it just kept spitting out the error. would it help if i sent you the modpack?

**Comment by SquidDev** [comment]
That would be useful, yes please!

**Comment by blackcatwithpurpleeyes** [comment]
how i got the error was logging into a world a 2ed time and the 3rd the game will crash
[magic vs metel.zip](https://github.com/cc-tweaked/CC-Tweaked/files/13079715/magic.vs.metel.zip) <-- modpack

**Comment by SquidDev** [comment]
I'm spent far too long trying to debug this yesterday, and afraid I made very little progress. There's too many mods here throwing errors to debug this effectively.

My recommendation here is to remove CC:T and AdvancedPeripherals for now, debug the other issues, and then add them back when things are a little more stable.
