### ISSUE TITLE
is craftos 2.0 going to be implemented?

### ISSUE THREAD

**Issue by Nukley** [SquidDev-CC/CC-Tweaked#162]
Craftos 2.0 custom os concepts never fail to amaze me as to what could be possible. 

So my question is, since we already do have sort of a craftos 2.0 standard, is implementation of it on the current roadmap? I would love to see these os concepts become a reality.

**Comment by SquidDev** [comment]
CraftOS 2.0 was always meant to be something which ran outside of Minecraft. It was a bit of a stand alone application, merely being inspired by ComputerCraft.

As of right now, I don't really have any plans to integrate any features from it - there's a lot of decisions about how the underlying system works (say, the terminal, etc...) which make it hard to get working in a backwards compatible manner.

If you're interested in the more "fantasy console" aspect, things like [TIC-80](https://tic.computer/), [PICO-8](https://www.lexaloffle.com/pico-8.php) and [Riko4](https://github.com/incinirate/riko4) are worth an investigation.
