### ISSUE TITLE
CC: Tweaked for 1.12.2 doesn't appeared to be remapped and causes crashes.

### ISSUE THREAD

**Issue by ProjectHSI** [SquidDev-CC/CC-Tweaked#1622]
### Minecraft Version

1.12.x

### Version

1.89.2

### Details

[debug.log](https://github.com/cc-tweaked/CC-Tweaked/files/13255271/debug.log)
[latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/13255272/latest.log)

**Comment by SquidDev** [comment]
I'm not sure this is an issue with CC: Tweaked. Your crash message reports this is an issue with a mixin from Phosphor.

**Comment by ProjectHSI** [comment]
i'm actually looking into that now.
it doesn't seem to be a cc: tweaked issue. it was working fine before it was all updated.

**Comment by ProjectHSI** [comment]
thanks for providing me another lead and thanks for the quick response.

**Comment by ProjectHSI** [comment]
can confirm it's phosphor. disabling it resolves this issue.
modpack still didn't start the first time i verified this but it's an issue with this modpack. computronics hasn't been updated in ages and it's dependent on an old version of RailCraft. i wish there was a way to do proper dependency version enforcement in prism launcher.
