### ISSUE TITLE
Add a separate redstone peripheral

### ISSUE THREAD

**Issue by accrrsd** [SquidDev-CC/CC-Tweaked#1624]
- Let the wired modem be able to recognize redstone signals in the same way as the computer recognizes them.

By default, the computer has the ability to identify the redstone signal from each side, there are 6 outputs in total. Due to the features of minecraft redstone, the circuits turn out to be quite large and it is very inconvenient to connect them into one computer, and even if you connect them, it is only 6 signals, which may seem insufficient. Because of this, it is necessary to build complex systems with several computers that exchange data, instead it would be great to be able to connect a wired modem and use it as a "splitter" of redstone signals.

Ultimately, this will simplify interaction with redstone, and will avoid unnecessary use of additional computers, because in fact they are used only to identify redstone signals.

Example of use: Let's say we are building schemes on several floors of a building, whether it is a multi-storey farm or an architectural idea. Now we can get 4 signals for the current floor and only 1 signal for the upper and lower floors, which is definitely not enough. However, with this update, we will be able to conduct a wired modem for each desired floor and get additional redstone slots.

**Comment by Lupus590** [comment]
There are a few add-on mods that do this via a redstone peripheral.

**Comment by SquidDev** [comment]
I do think this is one of those things which probably does make sense to have in the main mod (though probably via a peripheral rather than methods on the modem itself). I did a ComputerCraft-only playthrough a couple of years ago, and it was the main feature I missed.


I did start some work on this last year (almost exactly!, the last commit was 29th Oct 2022). However, could not find a texture I was happy with. Maybe something to pick up again.

As a work around for now, if you've got [Wired Redstone](https://modrinth.com/mod/wiredredstone) or [MoreRed](https://modrinth.com/mod/more-red) installed, you can use their bundled cables instead, which allows transferring 16 signals in one cable.

**Comment by fatboychummy** [comment]
I also one-up the thought of having a redstone integrator in the main mod. Having remote redstone capability is really nice, rather than having to write little redstone controller computers.

~~Even though programming those is fun too~~

**Comment by TheStraying11** [comment]
![redstone_top_off](https://github.com/cc-tweaked/CC-Tweaked/assets/18197081/463afa82-aedb-4359-b9fd-d12ab6567986)
![redstone_top_on](https://github.com/cc-tweaked/CC-Tweaked/assets/18197081/1d17dfad-53b3-4c12-9fbe-84fe41ddaf0f)
![redstone_front_off](https://github.com/cc-tweaked/CC-Tweaked/assets/18197081/19a55631-3ff0-4c1a-aad1-8151df16fb2c)
![redstone_front_on](https://github.com/cc-tweaked/CC-Tweaked/assets/18197081/385d4d0f-ac01-4970-8279-e2b1522aa60e)
![redstone_side_off](https://github.com/cc-tweaked/CC-Tweaked/assets/18197081/2586222f-57f8-461d-8f6f-f56daf90fadf)
![redstone_side_on](https://github.com/cc-tweaked/CC-Tweaked/assets/18197081/a4d99c18-20d9-47fc-ba11-415e96e0fd9e)
my weak attempt at a texture based on the existing peripherals, and the vanilla observer

**Comment by TheStraying11** [comment]
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/18197081/3db2d0cc-d5dd-4eed-8a29-40e0ae38d00b)
here they are blown up

**Comment by SquidDev** [comment]
@TheStraying11 Sorry, somehow I'd missed your comments entirely! I had another go at making some textures a few weeks back, and well ... somehow my pixel art skills have got even worse over the years. Let's go with yours! :D

![A screenshot of my attempted textures for a redstone controller. I'd attempted to make it a face (like droppers or observers), but with a red mouth at the base of the block, where the redstone would connect. I cannot explain how terrible it looks. It's not even especially ugly, it just looks boring and naff.](https://github.com/user-attachments/assets/1aa70040-7fb1-4995-a67c-7a7bf4073faa)
