### ISSUE TITLE
Pastebin Server Changing

### ISSUE THREAD

**Issue by OttersMeep** [SquidDev-CC/CC-Tweaked#1625]
There should be a command, under `pastebin server` or similar allowing you to change what server the pastebin program actually uses.
With this command you could easily use package managers, etc. because they can just host a pastebin style server anyone can use without additional setup.

**Comment by SquidDev** [comment]
Thank you for the suggestion! I'm afraid I'm not going to implement this - I don't really think overriding the pastebin server is the best way for package managers to do their thing. They're much better off having their own program.
