### ISSUE TITLE
term.resetPaletteColors()

### ISSUE THREAD

**Issue by MarcoPolo0306** [SquidDev-CC/CC-Tweaked#163]
Simply resets all of the palette colors to their defaults.

**Comment by SquidDev** [comment]
We discussed this on the original repo (dan200/ComputerCraft#343), and instead settled on a `term.nativePaletteColour`, which just acts like `term.getPaletteColour` but returning the default.

This is more flexible than a `reset` method, and means such a thing can be implemented as follows:
```lua
for i = 0, 15 do term.setPaletteColour(2^i, term.nativePaletteColour(2^i)) end
```
