### ISSUE TITLE
Printer

### ISSUE THREAD

**Issue by PonCorp** [SquidDev-CC/CC-Tweaked#1631]
### Minecraft Version

1.20.x

### Version

1.20.1 For Forge 47.2.0

### Details

I can't put ink in the printer

**Comment by SquidDev** [comment]
Just to check, are you trying to put in an "Ink Sac"? Recent versions of CC:T use dyes instead, so you'll need to craft the sac into black dye.

**Comment by PonCorp** [comment]
> Just to check, are you trying to put in an "Ink Sac"? Recent versions of CC:T use dyes instead, so you'll need to craft the sac into black dye.
Oh, sorry, it's work
