### ISSUE TITLE
Mixin apply fail on launch

### ISSUE THREAD

**Issue by fatboychummy** [SquidDev-CC/CC-Tweaked#1632]
### Minecraft Version

1.20.x

### Version

1.109.0

### Details

On launch, a `MixinTransformerError` is generated.

Crash report: https://mclo.gs/OSdnHYj

Logs: https://mclo.gs/Yh6FXfn

Tried using both Forge version 47.2.6 and 47.2.0, same error.

**Comment by SquidDev** [comment]
Thank you for the report!

Oh this is really odd. It looks like one of our mixins didn't get remapped. This is really odd - comparing the 1.108.4 and 1.109 jar, we can see this is the only file which has unexpectedly changed:

![image](https://github.com/cc-tweaked/CC-Tweaked/assets/4346137/5f754941-37af-4c4b-85c4-f25977ebd206)

I've deleted the broken release and pushed a new version - if you re-download from Modrinth it should now work.

**Comment by SirEdvin** [comment]
Forge are well-known (at least, by me) for randomly dropping refmap file generation
