### ISSUE TITLE
__gc not functional

### ISSUE THREAD

**Issue by DaPiMasta131** [SquidDev-CC/CC-Tweaked#1641]
### Minecraft Version

1.20.x

### Version

1.108.3

### Details

the __gc metamethod does not seem to work

**Comment by SquidDev** [comment]
I'm afraid this is expected behaviour. Due to how CC's Lua VM is implemented, it's not possible/practical to implement the `__gc` metamethod.

**Comment by zyxkad** [comment]
@SquidDev Sorry for brought this back again. Currently I'm developing a thread managing library and needs `__gc` for user friendly clean up.

I think we can use [`Cleaner`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/ref/Cleaner.html) to implement this.
Meanwhile, to prevent object resurrection, we can implement a modified `__gc`, which means we don't pass the object's reference to the function.

I can try working on this if you accept the idea above.

**Comment by SquidDev** [comment]
Sadly `Cleaner` isn't as useful as it first appears:

 - As you say, there's no way to obtain the original object and/or resuscitate it, and so we cannot provide a standards-compliant `__gc`. I'd like to avoid this really — Cobalt has enough quirks as-is!
 - It has a lot of the same issues as `finalize` (https://github.com/cc-tweaked/Cobalt/pull/64#issuecomment-1415209364). You don't want to run the `__gc` metamethod within `Cleaner`'s callback, as that won't be thread-safe. Instead you need to schedule the function to run on the computer, uh ... somehow.

Personally, I don't think `__gc` is especially desirable. I understand why it's needed for PUC Lua, but it's a really awkward feature, especially within the realms of CC. For instance:
 - `__gc` methods can execute at any point, not just within the "scope" of a program. This means if you `print()` within a `__gc` callback, the text could be printed to any multishell tab.
 - `__gc` functions can't yield, but do need to be interruptible if they run for too long.
 - `__gc` functions silently consume errors. This gets a bit odd with "Too long without yielding", as those could get swallowed, and the computer will abort instead.

`__close` fixes a lot of the problems with `__gc`, but unfortunately its interactions with tail-calls are incredibly janky, so I'm unlikely to support it in Cobalt.

I'm not quite sure why you need `__gc` for a concurrency library. Can you elaborate? — I feel there must be a cleaner way.

**Comment by zyxkad** [comment]
So I'm point [this part](https://github.com/zyxkad/cc/blob/master/coroutinex.lua#L651) of the script. That I registered [a background coroutine](https://github.com/zyxkad/cc/blob/master/coroutinex.lua#L556) to poll if any thread in the thread pool is done, and if is, run the thread in the queue.

However, if users create thread pools in a loop or such, the background manager don't get stopped automatically. They have to invoke the `destroy` method to make the background thread exit.

**Comment by zyxkad** [comment]
O

> Personally, I don't think `__gc` is especially desirable. I understand why it's needed for PUC Lua, but it's a really awkward feature, especially within the realms of CC. For instance:
> 
> * `__gc` methods can execute at any point, not just within the "scope" of a program. This means if you `print()` within a `__gc` callback, the text could be printed to any multishell tab.
> * `__gc` functions can't yield, but do need to be interruptible if they run for too long.
> * `__gc` functions silently consume errors. This gets a bit odd with "Too long without yielding", as those could get swallowed, and the computer will abort instead.

Okay, I get your idea, but I think there is an alternate solution:
What if we queue a event instead when object get cleaned? I mean if a table in its metatable contains such thing like `__gc_mark`, we can queue that object in the event `gc`, and user can explicitly poll this and do the logics.

**Comment by SquidDev** [comment]
Thread pools are pretty-much a perfect use-case for try-with-resources/`with`/whatever you want to call it! In fact, that's kinda what the whole idea behind [structured concurrency](https://en.wikipedia.org/wiki/Structured_concurrency) is.

You can see an example of this in #1734 — the thread-pool stops running when the scope is exited.

**Comment by zyxkad** [comment]
Hmm? I think we are talking different thing here.
What I mean thread pool is "a pool that limit threads to run", because CC:T has such low queue capacity.
I don't know how to describe this well, but if you can check the code I send above you'll get that.

**Comment by SquidDev** [comment]
Oh, that was very much just an example of the concepts, not a complete implementation of what you're trying to do! Though fairly easy to extend to support a thread limit, e.g. this is lifted from one of my projects:

<details><summary><code>thread.lua</code></summary>

```lua
local expect = require "cc.expect".expect

local exception_mt = {
    __name = "exception",
    __tostring = function(self) return self.message end,
}

local function checked_resume(co, ...)
  local ok, result = coroutine.resume(co, ...)
  if ok then return result end

  if type(result) == "string" then
    -- Support CC:T's exception protocol - see cc.internal.exception
    result = setmetatable({ message = result, thread = co }, exception_mt)
  end
  error(result, 0)
end

local function create_runner(max_size, init)
  if type(max_size) == "function" and init == nil then max_size, init = nil, max_size end
  expect(1, max_size, "number", "nil")
  expect(2, init, "function")
  if not max_size then max_size = math.huge end

  local active, active_n = {}, 0
  local queue, queue_n = {}, 0

  local function spawn_impl(fn)
    local co = coroutine.create(fn)
    local result = checked_resume(co, fn)
    if coroutine.status(co) ~= "dead" then
      active_n = active_n + 1
      active[active_n] = { co = co, filter = result or false }
    end
  end

  --- Queue a new task to be executed.
  local function spawn(fn)
    expect(1, fn, "function")

    -- If we've exhausted our threads, add to the queue, otherwise queue it.,
    if active_n < max_size then return spawn_impl(fn) end
    queue_n = queue_n + 1
    queue[queue_n] = fn
  end

  -- Spawn the first function.
  spawn(function() return init(spawn) end)

  while active_n > 0 do
    local event = table.pack(os.pullEventRaw())
    local event_name = event[1]

    -- Run pending tasks
    for i = active_n, 1, -1 do
      local task = active[i]
      if not task.filter or task.filter == event_name or event_name == "terminate" then
        local filter = checked_resume(task.co, table.unpack(event, 1, event.n))
        if coroutine.status(task.co) == "dead" then
          table.remove(active, i)
          active_n = active_n - 1
        else
          task.filter = filter or false
        end
      end
    end

    -- Add items to the queue
    while queue_n > 0 and active_n < max_size do
      local task = table.remove(queue, 1)
      queue_n = queue_n - 1
      spawn_impl(task)
    end
  end

  assert(queue_n == 0)
end
```

</details>

**Comment by zyxkad** [comment]
I see your idea here, but we are using different styles to solve this. Your code is kinda scope based. However I'm writing a JavaScript like scheduler, where you have one and only have one big event loop.

Maybe it just harder to do with my style

**Comment by zyxkad** [comment]
I just realized another solution, I can simply maintain the pool in the main event loop using weaktable
