### ISSUE TITLE
You are not attached to this computer Error

### ISSUE THREAD

**Issue by MrReps** [SquidDev-CC/CC-Tweaked#1645]
### Minecraft Version

1.20.x

### Version

1.108.4

### Details

Hello folks,

I'm on forge 47.2.0 with CC 1.108.4 and i've some error with my program. (i'm on server also)

It was working fine one minecraft 1.19, same program without any change. This is my pastebin [link](https://pastebin.com/wdFbvKjv) to the code if needed. 

I've the following error line:195: : Java Exception Thrown: dan200, computercraft.api.periphera.NotAttachedException: You are
not attached to this computer

This doiesn't make any sens for me : i'm able to get all the item from the pedestall, but no to push into them, on the second pedestal only ! It work for the first (the first pedestall is correctly filled). I've tested to change the order of the pedestal by changing the name but nothing change.

I suspect a problem in the mod not in the code because it was workign fine. I've tested to put everythiong in the same chunk and i still have the error.

If needed i can details this more, or give any other informations.

Thanks

MrReps

![image](https://github.com/cc-tweaked/CC-Tweaked/assets/10788750/5b00646f-abc3-483c-8165-63c4056a90ce)

**Comment by MrReps** [comment]
Hi,
My friend just propose a temporary fix, which is working : Adding a sleep(1) after the line 197. I suppose that something is to quick for the java thread.

**Comment by MrReps** [comment]
After more investigation, it's look like there some random "peripheral_detach" event. It looks like the peripheral are randomly detached :/. I've during my code more than 5 peripheral_detach in less than 3 second, but nothing else (like peripheral_attach) !

So for me, if there is any interaction with a peripheral, you shouldn't do anything with another peripheral for the next second, and there is also this strange event spam.

Anyway thanks for the work

**Comment by SquidDev** [comment]
Thanks for the report! I suspect this is an issue specific to the arcane pedestals - by the sounds of it, changing an item causes the peripheral to be reattached (though to be clear, still a bug the CC end).

Would you do able to upload your logs? They'll include some additional information (full error message, mod info) which is useful when debugging.

**Comment by MrReps** [comment]
Hello,

I'm surprised that someone has been able to understand what I said !

Sure I will give you the log, as soon as possible. In half a day or so. Have you any preferences for the sharing service ? (Dropping the file is good for you?). 

When you are asking for the log, the latest log file is what you need. Isn't it ? 


Also, by the way your suggestion is smart. For the peripheral_detach, following your hint, it's maybe because there is a crafting process on the umber which is causing the same problem. I've saw that when I was waiting for the craft. 

Anyway, Thanks

**Comment by SquidDev** [comment]
Thank you! 

> When you are asking for the log, the latest log file is what you need.

Oh, just realised you're on a server. I'd ideally have the server logs, but if you're not able to get them, don't worry - can probably try to reproduce this myself.

**Comment by MrReps** [comment]
I believe I can get the log. And in the worst case, I'll be able to
reproduce it myself on a solo map. It's juste that I do not have access to
my computer until this evening.

**Comment by MrReps** [comment]
Hello, 
I've reproduce the bug on a solo map, because i wasn't able to contact the owner of the server. If needed I'll be able in the future.
But for now i've got the log from a solo map. If you need anything else, feel free to ask.

[error.log](https://github.com/cc-tweaked/CC-Tweaked/files/13504487/error.log):

```
dan200.computercraft.api.peripheral.NotAttachedException: You are not attached to this computer
	at dan200.computercraft.shared.peripheral.modem.wired.WiredModemPeripheral$RemotePeripheralWrapper.getAvailablePeripheral(WiredModemPeripheral.java:438) ~[cc-tweaked-1.20.1-forge-1.108.4.jar%23505!/:1.108.4] {re:classloading}
	at site.siredvin.peripheralium.extra.plugins.AbstractInventoryPlugin.pushItems(AbstractInventoryPlugin.kt:74) ~[peripheralium-forge-1.20.1-0.6.13.jar%23666!/:?] {re:classloading}
	at dan200.computercraft.core.asm.PeripheralMethodSupplier.lambda$static$0(PeripheralMethodSupplier.java:28) ~[cc-tweaked-1.20.1-forge-1.108.4.jar%23505!/:1.108.4] {re:classloading}
	at dan200.computercraft.core.asm.PeripheralMethodSupplier.lambda$static$2(PeripheralMethodSupplier.java:35) ~[cc-tweaked-1.20.1-forge-1.108.4.jar%23505!/:1.108.4] {re:classloading}
	at dan200.computercraft.api.lua.TaskCallback.execute(TaskCallback.java:30) ~[cc-tweaked-1.20.1-forge-1.108.4.jar%23505!/:1.108.4] {re:classloading}
	at dan200.computercraft.core.computer.LuaContext.lambda$issueMainThreadTask$0(LuaContext.java:29) ~[cc-tweaked-1.20.1-forge-1.108.4.jar%23505!/:1.108.4] {re:classloading}
```

**Comment by SquidDev** [comment]
This may be a Peripheralium issue (cc @SirEdvin). I've not been able to reproduce with CC:T and Peripheralium 0.6.14 - could you confirm what mod versions you're running?

**Comment by MrReps** [comment]
I didn't even think about cc add-on! My bad. 

This is the list of the possible addon that I have :

AdvancedPeripherals-1.20.1-0.7.32b.jar
MoreRed-CCT-Compat-1.20.1-1.0.0.jar
peripheralium-forge-1.20.1-0.6.13.jar
peripheralworks-forge-1.20.1-1.4.0.jar


I think I've put them all. It's a lot of mod. I didn't even know there were this much mod... I'll try tomorrow to test it myself with each addon to see if I can reproduce it with any of them. Sorry for the trouble. 

(And the closing was a mistake because big hand on small phone...)

**Comment by SquidDev** [comment]
Thank you, that's very helpful!

> Sorry for the trouble.

No, don't apologise - you've been super helpful with getting info. This is definitely one of the odder bugs :).

**Comment by SirEdvin** [comment]
![alt](https://media1.giphy.com/media/st8Wfzji7jm146Ru7p/giphy.gif)

Oh, I would take a look. Thanks for report

**Comment by MrReps** [comment]
Hi it's me again !
I tested different configuration of addon and i found out that : 
-CC itself works fine no crash of the prog, and no spam of peripheral_detach event
-CC + AdvancedPeripherals-1.20.1-0.7.32b.jar + MoreRed-CCT-Compat-1.20.1-1.0.0.jar same as before, no crash no spam event
-CC + peripheralium-forge-1.20.1-0.6.13.jar same as before, no crash no spam event
-CC + peripheralium-forge-1.20.1-0.6.13.jar + AdvancedPeripherals-1.20.1-0.7.32b.jar + MoreRed-CCT-Compat-1.20.1-1.0.0.jar same as before, no crash no spam event
-CC + peripheralium-forge-1.20.1-0.6.13.jar + peripheralworks-forge-1.20.1-1.4.0.jar : crashing and spam event
-CC + peripheralium-forge-1.20.1-0.6.14.jar + peripheralworks-forge-1.20.1-1.4.1.jar : spam event (wasn't able to make the prog crash, but i believe on a solo map it's harder to produce the bug)

So i believe there is a problem with peripheralworks-forge (UnlimitedPeripheralWorks)

If you wan't me to close this ticket and to go to the author ([SirEdvin](https://github.com/SirEdvin)) to report it i'll gladly do it !

Thanks

**Comment by SirEdvin** [comment]
You can close this ticket, I have created report about this issue and, well, I _hope_ I would be able to fix this and not lost my mind.

**Comment by MrReps** [comment]
Thanks :) Have a great time fixing computer, with a computer ^^
