### ISSUE TITLE
https://copy-cat.squiddev.cc/ Does not work anymore

### ISSUE THREAD

**Issue by MCBEModder2020** [SquidDev-CC/CC-Tweaked#1646]
### Minecraft Version

1.20.x

### Version

copy cat web emu

### Details

It doesn't work anymore
![IMG_1718](https://github.com/cc-tweaked/CC-Tweaked/assets/78447517/30138fd1-e2ca-490d-acc2-4d0055aa385a)

**Comment by SquidDev** [comment]
Ahh, this was fixed for CC:T's web emulator, but not copy-cat. Fixed in https://github.com/SquidDev-CC/copy-cat/commit/acc68168af66575bdf525f3ec5f201141d09f807.
