### ISSUE TITLE
Adv Comp Startup Script vs Disk Startup Script

### ISSUE THREAD

**Issue by RedAngel121** [SquidDev-CC/CC-Tweaked#1649]
### Minecraft Version

1.20.x

### Version

1.108.4

### Details

I am having issues with the startup scripts and peripherals. 

I have an Advanced Computer next to a disk drive, I have a `/startup.lua` file on the disk and on the adv computer.
When using the `/startup.lua` on the Adv Computer, everything goes along fine, but if I don't use the `/startup.lua` from the Adv Computer and I only use the `disk/startup.lua` from the disk drive it seems to not recognize that the `disk/startup.lua` script exists when starting the computer, and I have to manually load the `disk/startup.lua` script to access the peripherals and code I wrote. 

Based on my limited understanding of how this works, it seems like the computer checks for startup scripts before it checks for peripherals and does not look for startup scripts after it has found my peripheral disk. Currently, I am using the `/startup.lua` to execute the `disk/startup.lua` after a `sleep(0.1)` is invoked, allowing the Computer to check for peripherals and still use the `/startup.lua`

Both Scripts Exist and it works fine:
![Screenshot_20231206_164413](https://github.com/cc-tweaked/CC-Tweaked/assets/33588872/b42d0bb8-6e37-4161-90f1-5dd71200da2b)

But if i remove the Adv Computer Startup.lua it stops working:
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/33588872/8464929a-c974-43bd-8e2a-9636c692fef6)
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/33588872/761af561-45e2-4b14-9db1-699561626a5f)

**Comment by fatboychummy** [comment]
Related: SwitchCraftCC/issues/issues/31 and #1399
