### ISSUE TITLE
Backport of TURTLE_CAN_PLACE tag to 1.19.2

### ISSUE THREAD

**Issue by samuelWilliams99** [SquidDev-CC/CC-Tweaked#1654]
### Minecraft Version

1.19.x

### Version

1.19.2

### Details

[This commit](https://github.com/cc-tweaked/CC-Tweaked/commit/118d04f018923ccb850a005c082688e60959df27) fixed an issue with turtles putting liquids into cauldrons/beehives, and added the tag so it can also be fixed for ender-storage via a data-pack.
Would it be possible to have this backported to 1.19.2? I see its on the 1.19.x branch, but I assume that doesn't include 1.19.2 given releases for 1.19.2 are made from its own branch.

All notes about the bugs it fixes are listed in the commits description.

**Comment by SquidDev** [comment]
Thanks for the report! I'm afraid I'm only backporting major bugs (e.g. crashes) to the 1.19.2 branch, so won't be backporting this commit.

The 1.19.3/1.19.4 update had some major internal refactors, which make porting commits between those versions quite painful.

**Comment by samuelWilliams99** [comment]
If I did this myself and put up a PR, could it be merged?

**Comment by SquidDev** [comment]
Oh, if you're happy to, then probably yes!

**Comment by samuelWilliams99** [comment]
Great alright, i'll give it a go :)
