### ISSUE TITLE
mouse_drag event not emitted for right-click or middle-click dragging

### ISSUE THREAD

**Issue by tehbiga** [SquidDev-CC/CC-Tweaked#1655]
### Minecraft Version

1.20.x

### Version

1.109.0

### Details

I'm not sure if I've seen this before, but it seems that `mouse_drag` events are not being emitted when dragging the right or middle mouse button.

Here is the code I used to check, just through the interactive `lua` program:
```lua
while true do local e,b,x,y=os.pullEvent('mouse_drag') print(e,b,x,y) end
```

**Comment by SquidDev** [comment]
Thanks for the report! Looks like that crept in during one of the recent Minecraft updates, not sure how I'd not spotted that before :smiling_face_with_tear:.
