### ISSUE TITLE
Computer won't detect modems

### ISSUE THREAD

**Issue by Umar-Haqimi** [SquidDev-CC/CC-Tweaked#1657]
### Minecraft Version

1.20.x

### Version

1.108.4

### Details

I'm currently working on a secure storage system, and the system I was working on needs a modem, but **my computer didn't detect wireless nor wired modem**

To check if this is a bug, I tried on an another device(turtle, pocket computer) went to another minecraft version, tried another peripherals, it was working fine! I don't want to use turtles because they are small and weird for my storage system

if I didn't explain detailed enough, you can always ask me for more questions. And if you want the screenshot(s), [here](https://imgur.com/a/xNWqjU7)

**Comment by SquidDev** [comment]
Thanks for the report! Would you be able to upload your logs, that would be very helpful in debugging this. 

Do you have Optifine installed? There is a bug in Optifine that breaks some of the Forge functionality we depend on (see #1458). I'd recommend removing it and replacing it with Oculus.

**Comment by Umar-Haqimi** [comment]
> Thanks for the report! Would you be able to upload your logs, that would be very helpful in debugging this.
> 
> Do you have Optifine installed? There is a bug in Optifine that breaks some of the Forge functionality we depend on (see #1458). I'd recommend removing it and replacing it with Oculus.

Aye! The problem is fixed! I forgot that my Optifine is sitting on my mods folder. Thanks for the mod recommendation, too
(If you still need my [.log](https://github.com/cc-tweaked/CC-Tweaked/files/13715484/latest.log) file.)
