### ISSUE TITLE
[BUG] Holiday hat and texture are visible from certain distances

### ISSUE THREAD

**Issue by ArsiTheFox** [SquidDev-CC/CC-Tweaked#1660]
### Minecraft Version

1.20.1
ATM9 Modpack

### Version

cc-tweaked-1.20.1-forge-1.109.2.jar

### Details

Only able to see the Christmas textures of the turtles from a certain distance and angle
![2023-12-26_22 06 32](https://github.com/cc-tweaked/CC-Tweaked/assets/24835664/3495121d-1ed7-4945-957a-3f4233800155)
![2023-12-26_22 06 34](https://github.com/cc-tweaked/CC-Tweaked/assets/24835664/f8cc7a78-0dad-4832-b07b-8256d4942bf6)
![2023-12-26_22 06 39](https://github.com/cc-tweaked/CC-Tweaked/assets/24835664/db5c99f6-f43e-40f8-9c90-1c98a65fad27)
![2023-12-26_22 06 55](https://github.com/cc-tweaked/CC-Tweaked/assets/24835664/fbf09cc2-bb09-4993-a365-eb93515cf49c)

**Comment by ArsiTheFox** [comment]
Video: https://puu.sh/JXyhT.mp4

**Comment by SquidDev** [comment]
Thanks for the report! Oh, this is a very odd bug - I'm not quite sure why this would happen at all, and I'm afraid I'm unable to reproduce this with just CC:T.

Would you be able to try to reproduce this on a superflat world, with no other blocks around (you may need to set your computer date to the 25th). I'm wondering if there's some other nearby block which is interfering with turtle rendering.

**Comment by ArsiTheFox** [comment]
> Thanks for the report! Oh, this is a very odd bug - I'm not quite sure why this would happen at all, and I'm afraid I'm unable to reproduce this with just CC:T.
> 
> Would you be able to try to reproduce this on a superflat world, with no other blocks around (you may need to set your computer date to the 25th). I'm wondering if there's some other nearby block which is interfering with turtle rendering.

I am soooo sorry I didn't answer back. Life caught up and stuff.

**Comment by ArsiTheFox** [comment]
I am using the AllTheMods 9 modpack and have a couple of machines and stuff around that area for testing. I Will test the bug more soon and fully do a test and try to place the creations nearby and see if the entit
