### ISSUE TITLE
Holiday hats not visible on turtles with flags

### ISSUE THREAD

**Issue by Kan18** [SquidDev-CC/CC-Tweaked#1663]
### Minecraft Version

1.20.x

### Version

1.109.2 (SC modpack)

### Details

If you set your computer date such that turtles will normally have Christmas clothing, then you craft a turtle with a flag, then the turtle with a flag will not have any Christmas clothing.
<img width="1280" alt="image" src="https://github.com/cc-tweaked/CC-Tweaked/assets/24967425/285ee42d-1b1d-44cf-8dac-9352f86b7b92">
(P.S. could the turtle holiday dates be synchronized with the Minecraft chest holiday dates? I think that would be more consistent.)

**Comment by SquidDev** [comment]
Thanks for the report!

I also noticed this when trying to reproduce #1660 and then decided to ignore it :D:. The main problem is that both the Christmas model and turtle flag [are treated as "overlays"](https://github.com/cc-tweaked/CC-Tweaked/blob/ed3a17f9b94b6a73eabdf1fa9c2fd51e1d84814b/projects/common/src/client/java/dan200/computercraft/client/render/TurtleBlockEntityRenderer.java#L41C54-L45), and turtles can only have one overlay.

In the general case I think this is the correct choice. While this isn't the case for flags, some other overlays (e.g. those from from CCEdu) would intersect/z-fight with the Christmas overlay.

I'm not 100% sure what the correct solution here is. Maybe we should make overlays more data-driven, and then allow them to specify whether they're compatible with Christmas or not. Though special-casing does feel a little ugly.

> could the turtle holiday dates be synchronized with the Minecraft chest holiday dates? I think that would be more consistent

Oh, hah. I thought they were already. Will check that.
