### ISSUE TITLE
[Feature Request]: Command Computers should be in the operator tab

### ISSUE THREAD

**Issue by lexi-the-cute** [SquidDev-CC/CC-Tweaked#1666]
Mojang has a special operator tab in the creative menu which is only visible when the player is an operator. This contains all the other command blocks. The Command Computer should be placed in this tab

![2024-01-03_07 42 51](https://github.com/cc-tweaked/CC-Tweaked/assets/120563837/b386348f-f35d-4eeb-bf67-5f0bc2895080)

**Comment by SquidDev** [comment]
Thanks for the report! We show the command computer in CC's creative tab when the op tab is enabled but yep, it probably makes sense to do it here too.
