### ISSUE TITLE
Game crashed when rendering item

### ISSUE THREAD

**Issue by AlisonHuang777** [SquidDev-CC/CC-Tweaked#1667]
### Minecraft Version

1.20.x

### Version

1.108.1

### Details

Crash Reports & Log:
https://gist.github.com/AlisonHuang777/3b5a320c9635a2a14de2a421ab68e034
https://gist.github.com/AlisonHuang777/70ba1e2b4cb43ebf0281618f107744b4 (crash report only)
Playing Prominence II Classic modpack.
Sorry but I can *not consistently* reproduce this in the most recent version of the modpack.
However, in older versions (of the modpack), I *can* consistently reproduce this bug: If I go to Creative Inventory Search Tab and search "tur" immediately after the world loads in, it will instantly crashes, with a similar Crash Report.

**Comment by SquidDev** [comment]
Thanks for the report! I believe this is the same issue as #1626, so am going to close in favour of that.

Odd that it no longer occurs, will take a look and see what has changed!

**Comment by AlisonHuang777** [comment]
I have edited the original post to clarify some miscomprehension, and add another crash report. Sorry for the late update.

**Comment by SquidDev** [comment]
When you say "older versions", which version(s) have you tested with?

**Comment by AlisonHuang777** [comment]
I forgot the exact version. I said "older versions" is just based on my memories of the crashes.
But I'm willing to provide all 6 crash reports I have (encountered): https://gist.github.com/AlisonHuang777/d557c089c282b1c184710dec161b3bbf
Maybe you can determine the versions by the date of the crash logs. I tend to update the modpack as soon as it has a new release. So you can assume that each of the crash report is on the newest version possible for the date on which the crash report is generated.
Also, I had modified the pack by adding and removing some mods, so remember to check the mod list at the end of each crash report if that piece of information is relevant.
