### ISSUE TITLE
Add Cyrillic alphabet to mod

### ISSUE THREAD

**Issue by Pr0st0Danya** [SquidDev-CC/CC-Tweaked#1669]
many people who use the CC:Tweaked mod speak different languages. It would be great if people who are used to writing in Cyrillic had the opportunity to use the Cyrillic alphabet that is convenient for them in fashion. at least print information in Cyrillic

**Comment by SquidDev** [comment]
Thanks for the report! This is definitely something I want to do, as it does make the mod harder to use for non-English users. However, finding a way to do this which doesn't break existing programs is quite hard, hence it not being done yet!

There's some existing discussion for this in #860, so going to close this issue in favour of that.
