### ISSUE TITLE
Game server crashes after placing Macaw’s Furniture block near computer

### ISSUE THREAD

**Issue by nordegraph** [SquidDev-CC/CC-Tweaked#1670]
### Minecraft Version

1.20.x

### Version

cc-tweaked-1.20.1-fabric-1.109.3

### Details

[crash-2024-01-06_06.02.39-server.txt](https://github.com/cc-tweaked/CC-Tweaked/files/13848842/crash-2024-01-06_06.02.39-server.txt)

If I try to place computer or monitor near Macaw’s furniture block (https://www.curseforge.com/minecraft/mc-mods/macaws-furniture), server crashes, probably either because this furniture have an inventory but it cannot be cast correctly by CC to one of the internal classes, or due to some other compatibility issue. As a result, I can't start the server again while this blocks combination is present inside the gameworld. Can I prevent CC from trying to interact with some of the modded unsupported blocks, or do something else to prevent this situation from happening again? Thanks for help in advance.

**Comment by SquidDev** [comment]
Thanks for the report!

This appears to be a bug with Macaw’s furniture, so I'm afraid you'll need to report it to them instead.

When breaking a block with a block entity (such as a bookshelf), it doesn't actually remove the block entity. This means it hangs around in the world. If you then place another block in that position (such as a monitor in this case), you then get this crash.

You can confirm this by placing a bookshelf in the world and then using the `/data get block` command:
![A screenshot of a Minecraft superflat world with a Macaw's Furniture bookshelf. The bottom left shows the output of the /data get block command, showing there is a block entity with the mcwfurnitures:box_block id.](https://github.com/cc-tweaked/CC-Tweaked/assets/4346137/187240b3-821b-4a0e-b44f-bc3a16e9d360)

After breaking the block, you can re-run the command to see the block entity is still present:

![A screenshot of the same scene as before, but with the bookshelf removed. The command has been run again, showing there is still a block entity present.](https://github.com/cc-tweaked/CC-Tweaked/assets/4346137/26ffac3d-f7e4-485a-a7c3-96970b6d4d23)

If you place another block in that position (such as a chest), you won't be able to interact with that chest.
