### ISSUE TITLE
Crash on Fabric Server 

### ISSUE THREAD

**Issue by ryanrossiter** [SquidDev-CC/CC-Tweaked#1671]
### Minecraft Version

1.20.x

### Version

1.109.3

### Details

# Logs
https://pastebin.com/eJqBWw5j

# Versions
Minecraft: v1.20.4
Fabric Loader: v0.15.3
Java: 21

# Mods
Fabric API: v0.92.1
LuckPerms: v5.4.116
vanilla-permissions: v0.2.2

**Comment by SquidDev** [comment]
It looks like you're trying to run CC:T with Minecraft 1.20.4. I'm afraid only 1.20.1 is supported right now - the work to update to 1.20.4 is [still ongoing](https://github.com/cc-tweaked/CC-Tweaked/pull/1618).

We should really be catching this earlier though, I'll update the mod metadata to prevent this.
