### ISSUE TITLE
Console Spammed with "Allocated a negative number of bytes"

### ISSUE THREAD

**Issue by kaboom-tastic** [SquidDev-CC/CC-Tweaked#1672]
### Minecraft Version

1.20.x

### Version

1.109.2

### Details

I have been using [this awesome program](https://github.com/MikaylaFischler/cc-mek-scada) to control mekanism reactors through CC. No problems operating normally, but the console gets spammed with 
![negative bytes](https://github.com/cc-tweaked/CC-Tweaked/assets/155666778/87a0c526-1467-4b34-a356-244d005d76ab)

I can ignore the warnings, and everything operates normally. The author of the above program has helped pinpoint when and where this issue may arise. 
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/155666778/c974afa8-2b80-4c38-be4f-112e75d250c6)
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/155666778/31576a51-f77e-49c8-a236-00dd1e9ca90f)

Could this stem from my Java settings possibly? Currently I have its max memory allocation as a percentage of the total RAM, not a hard limit. 

Thanks in advance, and thanks for keeping this awesome mod alive!

**Comment by SquidDev** [comment]
Thanks for the report! Hah, that was a silly oversight on my part.

**Comment by J2-Tech** [comment]
I've still got this problem on the latest version. 
I've also got Aikar's Flags as java options on my server, and many turtles running while true loops. Any workaround / tips on how to avoid this happening ?

**Comment by SquidDev** [comment]
Oh, that's very odd! Would you be able to file a new report and attach your logs?
