### ISSUE TITLE
game crash on startup version 1.13.2

### ISSUE THREAD

**Issue by daodragon** [SquidDev-CC/CC-Tweaked#168]
i would very much like if you guys told me what i did wrong or if there is a problem with the current version of the mod.

Also the crash report want me to well report : cc:tweaked the nullpointerexception error

Minecraft Version: 1.13.2
(modded) forge-25.0.107
cc-tweaked-1.13.2-1.82.0

[latest.log](https://github.com/SquidDev-CC/CC-Tweaked/files/3044495/latest.log)
[crash-2019-04-04_11.35.54-client.txt](https://github.com/SquidDev-CC/CC-Tweaked/files/3044496/crash-2019-04-04_11.35.54-client.txt)

**Comment by SquidDev** [comment]
Oh goodness. Why does this bug always come back to haunt me. Thanks for the report, I'll look into it.

**Comment by SquidDev** [comment]
Hrmr, I'm unable to reproduce with just CC: Tweaked. Given that there's other mods listening to this event, I suspect this is an issue with Forge or some other mod is causing issues in the mod-loading process. There's definitely several other mods throwing errors, so I'd try removing them one at a time and seeing what changes.

**Comment by SquidDev** [comment]
Done some further investigation into this - the above commit should fix this issue occurring, but the actual crash is caused by other mods crashing (and then Forge not handling it as expected).
