### ISSUE TITLE
[Fabric + Velocity] Incompatible with Velocity

### ISSUE THREAD

**Issue by ERroooooR** [SquidDev-CC/CC-Tweaked#1685]
### Minecraft Version

1.20.x

### Version

1.109.3

### Details

Velocity:https://mclo.gs/JtDkPZ8
server:https://mclo.gs/YmwsSyQ
Client:https://mclo.gs/akrLk9O

**Comment by SquidDev** [comment]
Thanks for the report! I'm fairly sure this should work - I know some other server are using CC behind Velocity.

Can you try again with the [CrossStitch](https://modrinth.com/mod/crossstitch) mod installed on the Fabric server? [The Velocity docs](https://docs.papermc.io/velocity/server-compatibility#fabric) suggest that it is required to be installed when using content-adding mods.

**Comment by ERroooooR** [comment]
Works fine after adding CrossStitch, thanks :P
