### ISSUE TITLE
Random Camera, Iron Noteblock, Radar rendering over result in JEI

### ISSUE THREAD

**Issue by NiallDoherty** [SquidDev-CC/CC-Tweaked#169]
## Useful information to include:
 - Minecraft version: 1.12.2
 - CC: Tweaked version: 1.182.0, didn't happen in 1.181.1
 - Detailed reproduction steps: Search turtle in JEI.

![cc](https://user-images.githubusercontent.com/1338161/55653514-b149a900-57e6-11e9-8c82-ad751a398e4b.PNG)

**Comment by SquidDev** [comment]
Ahh. I tried to enchance our JEI integration to show all mod-added turtles, but it looks like a couple have broken models. If you hover over those items, it should say which mod adds them.

**Comment by NiallDoherty** [comment]
They're from Computronics.

**Comment by SquidDev** [comment]
Fixed in Vexatos/Computronics#279
