### ISSUE TITLE
Max websocket lower limit is improperly capped or wrongly documented.

### ISSUE THREAD

**Issue by Wojbie** [SquidDev-CC/CC-Tweaked#1691]
### Minecraft Version

1.20.x

### Version

1.109.3

### Details

In CC:T config it states that if you set max websocket limit to 0 it will become unlimited but value itself has lower cap set to 1 so it never can be set to 0. Either 0 is unlimited is incorrectly documented or value is incorrectly limited.

https://github.com/cc-tweaked/CC-Tweaked/blob/f695f22d8a6ae5987ad59ac69489071a4ab6e47b/projects/common/src/main/java/dan200/computercraft/shared/config/ConfigSpec.java#L226-L228

**Comment by SquidDev** [comment]
Good spot, thanks!
