### ISSUE TITLE
Add more security

### ISSUE THREAD

**Issue by ghost** [SquidDev-CC/CC-Tweaked#1695]
Basically, add things to make it harder to hack into in-game systems without using external tools. For example, if you want to send something to another computer without any other computer listening, it's hard to do so, even if you encrypt it.

To solve this, I would add protectors to cables, and an in-game encryption system. I would also add a hash function for passwords, if people wanted to password protect their files.

**Comment by piprett** [comment]
>  For example, if you want to send something to another computer without any other computer listening, it's hard to do so, even if you encrypt it.

It's pretty easy, don't attach a wireless modem and wire it with cables. There are also cryptographic libraries in lua to reasonably protect from rednet spoofing and sniffing. See [ccryptolib](https://github.com/migeyel/ccryptolib).
