### ISSUE TITLE
Add a custom GUI editor

### ISSUE THREAD

**Issue by ghost** [SquidDev-CC/CC-Tweaked#1698]
How this would work is that any advanced computer/turtle can show these, and you have to make them as an object using code. There could be a new API for this, and people could use it to make custom operating systems.

**Comment by Lupus590** [comment]
Do you mean that you want an API for users to make custom MineCraft GUI elements inside of the computer?

**Comment by ghost** [comment]
Yes.

**Comment by walksanatora** [comment]
so you mean like LevelOS's ShapeScape?

**Comment by ghost** [comment]
I have no idea what that is.

**Comment by accrrsd** [comment]
I don't think this is necessary, the mod already provides all the tools for writing a graphical interface, and then everything depends on the hands of the one who is going to make it. But if you're looking for ready-made solutions, take a closer look at a thing called Basalt.

**Comment by SquidDev** [comment]
I do agree that this sort of project would be useful. However, I don't think I'm comfortable putting a UI library into CC:T itself, let alone a designer for that UI. Both are a *lot* of work, and I think the community is better placed to provide various implementations.
