### ISSUE TITLE
Integration with Sonic Screwdriver mod

### ISSUE THREAD

**Issue by stuin** [SquidDev-CC/CC-Tweaked#170]
This is not as much an issue as just formally asking for the go ahead to add some integration features. 

I am in development of a Sonic Screwdriver mod for fabric and would like to add the ability to shutdown or reboot computers with it. Just for the sake of accuracy, as well as setting a precedent for future fabric tech mods. 

Again nothing needs to be done here, I believe it can all be handled by the screwdriver.

**Comment by SquidDev** [comment]
Sure, feel free to do whatever! There's not much exposed by the API here, so you'll probably have to do some messing around with `TileComputerBase` and `createServerComputer`.
