### ISSUE TITLE
Crash on fabric 1.20.4

### ISSUE THREAD

**Issue by samos667** [SquidDev-CC/CC-Tweaked#1700]
### Minecraft Version

1.20.x

### Version

1.109.3

### Details

Tested with only fabric-api

https://mclo.gs/URguClY

**Comment by SquidDev** [comment]
It looks like you're trying to run CC:T with Minecraft 1.20.4. I'm afraid only 1.20.1 is supported right now - the work to update to 1.20.4 is [still ongoing](https://github.com/cc-tweaked/CC-Tweaked/pull/1618).

**Comment by samos667** [comment]
Ah yes mb. Thanks for your work (and shame to Mojang update method)
