### ISSUE TITLE
Graphics Mode

### ISSUE THREAD

**Issue by ExotisDev** [SquidDev-CC/CC-Tweaked#1704]
So currently, the maximum resolution of a CC computer is 51*19 pixels, which seems a bit restrictive to me. Adding a graphics mode than can increase the resolution of computers (and possibly other types too) would my bet on this problem. CraftOS-PC has a similar feature (if not the same) implemented already, and I believe many uses for this higher resolution can be found.
![Screenshot 2024-01-30 093733](https://github.com/cc-tweaked/CC-Tweaked/assets/107165956/56580915-45d0-4bf3-bf02-6e9abbcd5a2c)
An alternative approach could be to add the `monitor.setTextScale()` method to normal computers too, and also make the lower bound go below 0.5.

**Comment by Lupus590** [comment]
You can change the size of computer screens in the server/world config.

**Comment by ExotisDev** [comment]
Thanks for the hint, that was really useful!
