### ISSUE TITLE
Press any key to continue. 

### ISSUE THREAD

**Issue by VenerableTimeWanderer** [SquidDev-CC/CC-Tweaked#1705]
### Minecraft Version

1.20.x

### Version

1.109.4

### Details

Making a program in the computer, save, then run the program then Press any key to continue. which the key you pressed gets added to the
![2](https://github.com/cc-tweaked/CC-Tweaked/assets/57559691/c913be59-cdfe-4c22-ae64-b0fd224da4f8)
![3](https://github.com/cc-tweaked/CC-Tweaked/assets/57559691/cf8a3b27-21a5-4209-93c1-467eb906f8e0)
![4](https://github.com/cc-tweaked/CC-Tweaked/assets/57559691/dc01ab57-b16e-44be-8118-ee92e67cac22)
![5](https://github.com/cc-tweaked/CC-Tweaked/assets/57559691/9387723e-9313-4548-b77b-85e71b60e6c0)
 code.

**Comment by VenerableTimeWanderer** [comment]
Hard to show because the run screen is hard to capture because just pressing a button will remove it.

**Comment by SquidDev** [comment]
Thanks for the report! There's been several instances of similar issues, annoying that it keeps cropping up :/.
