### ISSUE TITLE
Not working with fabric server?

### ISSUE THREAD

**Issue by ded811** [SquidDev-CC/CC-Tweaked#1708]
### Minecraft Version

1.20.x

### Version

1.109.5

### Details

Internal Exception: java.lang.RunstimeException: Error while handling packet "computercraft:upgrades_loaded": Index 103 out of bounds for length 3
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/128560135/35611b23-3f5c-485f-ac8f-b34d1f713f32)
I can get into singleplay just fine, my friends can join me using hamachi, essentials, minetogether but when I host an actual fabric server everyone attempting to join receives this error. I have been trying to figure out if this is mod incompatibility or something wierd with my computer, but I keep getting this error and I do not have another machine to test it on, I have attempted to reinstall java and make a clean instance of minecraft and my server but I keep getting this error.
[latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/14119661/latest.log)
[server latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/14119682/server.latest.log)

**Comment by SquidDev** [comment]
Thanks for the report! I'm afraid I can't reproduce this with just CC: Tweaked at all (with Fabric loader 0.15.3 and fabric-api 0.91.0+1.20.1).

Looking at your logs, there's 29 turtle upgrades being loaded, so I'm assuming you've either got a datapack or another add-on mod adding them?  It might be worth removing that and trying again, to see if it helps.

**Comment by ded811** [comment]
I found the issue to be one of my create add-ons modified something in the server files that only became an issue when cc craft was installed on a server. I was struggling to debug what mod was at fault because it remained even after the removal of the mod.
