### ISSUE TITLE
Creating resource pack for programs

### ISSUE THREAD

**Issue by ozBillo** [SquidDev-CC/CC-Tweaked#171]
What is the correct folder for CC programs in a 1.13.2 resource pack?

I've tried...
data/computercraft/lua/rom/programs/
assets/computercraft/lua/rom/programs/

Neither work for me.

**Comment by SquidDev** [comment]
So we're now using [data packs](https://minecraft.gamepedia.com/Data_pack) for handling custom ROMs, which means they now need to be in the world folder. This makes out handling of custom ROMs a lot nicer (can be enabled/disabled in-game, reloaded, etc...), but is a little different to the previous behaviour.

Putting your code in `saves/(world)/datapacks/something/data/computercraft/lua/rom/programs` should work, but you may also need a `pack.mcmeta` file. I'll have a play later today and see I can put together a small example pack...

**Comment by ozBillo** [comment]
:(
Couldn't you cater for both data packs and resource packs?

Just like my favorite texture pack, my turtle programs are ones I use in all new worlds I create. They do farming, mining, and other repetitive tasks. They're not specific to any saves or worlds.

**Comment by SquidDev** [comment]
I had another look at this today... Using the client-side resource pack folder when available would be possible, though does make things a little more messy as you have multiple `IReloadableResourceManager`s.

Ideally it'd be possible to have a global `datapacks` folder which is shared across worlds. I know [this mod](https://minecraft.curseforge.com/projects/drp-global-datapack/) adds that, and we could set up our own, though ideally it'd be functionality built-in to Forge.

**Comment by ozBillo** [comment]
That mod suggestion worked and allowed my turtle programs to be used in all new worlds I create. 
But, you're right. Ideally this functionality would be built-in to Forge.
