### ISSUE TITLE
Terminate program hotkey not working

### ISSUE THREAD

**Issue by 64gamesteam** [SquidDev-CC/CC-Tweaked#1718]
### Minecraft Version

1.16.x

### Version

1.91.1

### Details

to recreate what i did:
edit test.lua (name doesnt matter)
inside it, type:
**function dothething()
  io.read()
  dothething()
 end
 dothething()**
 then save it and run it via run button or start menu thingy, i cant exit the program without breaking and re-placing my computer block.

**Comment by fatboychummy** [comment]
Version 1.91.1 is a nearly 3.5 year old 1.16.2-only alpha. I am unsure if there will be much that can be done to help you here.

Instead, I will ask how you are trying to terminate the program? Are you holding the hotkeys (ctrl+t)? If you're just pressing them once, it won't work, they need to be held.
