### ISSUE TITLE
Bundled Redstone cable not functioning on turtles or computers v1.82

### ISSUE THREAD

**Issue by rangerdude** [SquidDev-CC/CC-Tweaked#172]
- Minecraft version 1.12.2
 - CC: Tweaked version 1.82.0 

rs.setBundledOutput("anyside", colors.pink)

Also if redstone is there as an input it does not detect it.

I have gone back and tested on 1.81 and it works fine there.

**Comment by Wojbie** [comment]
Could you also add information what mod is adding the bundled cables you are using in this example?

**Comment by SquidDev** [comment]
This should have been fixed by 765c31315a460f70913d8e78a00de5094ad46b4c - hoping to get a release out in a few hours. Sorry for the bug!

**Comment by SquidDev** [comment]
[1.82.1](https://minecraft.curseforge.com/projects/cc-tweaked/files/2696466) should resolve this - can you confirm?
