### ISSUE TITLE
ArrayIndexOutOfBoundsException when setting entries on weak tables

### ISSUE THREAD

**Issue by migeyel** [SquidDev-CC/CC-Tweaked#1721]
### Minecraft Version

1.20.x

### Version

1.109.4, 1.109.5

### Details

The following code errors pretty reliably when it shouldn't:
```lua
local t = setmetatable({}, { __mode = "k" })
for _ = 1, 1e6 do t[{}] = {} end
```
This looks like a regression. I'm not able to reproduce it on 1.109.3.

**Comment by Lupus590** [comment]
I seem to remember that weak tables are not implemented, there are a few things with memory management/garbage collection that PUC Lua provides but Cobalt (and thus CC) doesn't due to how Cobalt is implemented on Java.

**Comment by SquidDev** [comment]
Weak tables are implemented, they just have somewhat broken semantics. No, this is a recent regression caused by https://github.com/cc-tweaked/Cobalt/commit/5aebd8899246d6e19508c6b651ea80db9a0dcf70.

**Comment by SquidDev** [comment]
Thanks for the report, that was an annoying one - I was so careful when porting to avoid this specific bug, and it still happened :facepalm:.
