### ISSUE TITLE
Adding term.setTextScale

### ISSUE THREAD

**Issue by vuyghu2020** [SquidDev-CC/CC-Tweaked#1724]
I think it would be good if you could change the text size for the computers like in the monitors. I want it because I'm making a program that can play an animated movie.

**Comment by fatboychummy** [comment]
If you aren't already, do note that you can use "drawing characters" to achieve a bit higher resolution.

You can use the characters from `\x80` to `\x9f` in the image below to get an effective increase in resolution by 2x3 pixels per character (with the restriction that each character is still limited to only two colors).

<details><summary>CC:Tweaked Character Sheet</summary>

![image](https://github.com/cc-tweaked/CC-Tweaked/assets/39929480/5575eb8d-f48a-4abd-b5ad-90c65fbe2ef4)

</details>

I believe @9551-Dev has a writeup on how they can be used, but I am struggling to find it.

**Comment by 9551-Dev** [comment]
> If you aren't already, do note that you can use "drawing characters" to achieve a bit higher resolution.
> 
> You can use the characters from `\x80` to `\x9f` in the image below to get an effective increase in resolution by 2x3 pixels per character (with the restriction that each character is still limited to only two colors).
> 
> <details><summary>CC:Tweaked Character Sheet</summary>
> 
> ![image](https://github.com/cc-tweaked/CC-Tweaked/assets/39929480/5575eb8d-f48a-4abd-b5ad-90c65fbe2ef4)
> 
> </details>
> 
> I believe @9551-Dev has a writeup on how they can be used, but I am struggling to find it.

The reason the writeup is hard to find is because its not officially released, there is still some stuff missing and there is a lot od grammatical errors (proofreading needed)

**Comment by SquidDev** [comment]
[This forum post](https://www.computercraft.info/forums2/index.php?/topic/25340-cc-176-easy-drawing-characters/) and [this longer explanation](https://www.computercraft.info/forums2/index.php?/topic/29566-teletext-and-character-tutorial/) cover some of the basics at least.

If it's helpful, you can configure the resolution of computers via a config file (though it's a little janky, see #825). 

However, this is currently not something I really want to expose in the Lua API right now. Any discussion about graphic capabilities always gets into tricky questions about what fits CC's Aesthetic (TM), and for now I think it's easier to stick with the status quo.
