### ISSUE TITLE
Programs crashing server after restart/crash on server

### ISSUE THREAD

**Issue by Dangrainage** [SquidDev-CC/CC-Tweaked#1728]
### Minecraft Version

1.19.x

### Version

1.101.4

### Details

We are running a server, one of our players has made multiple scripts (or programs I guess), that when running together are a kind of stock market. If the server restarts or crashes during the time that the computer is loaded reloading the computer back when the server starts back up will crash the server once again, resulting in an infinite loop of crashes and computer loading until one of the admins fills the place where the computer is with air - AE destroys It.

The player has relayed the following information for me to leave here in the issue.
1. We are using an addon called CC:C Bridge for bridging Create mod and ComputerCraft
2. The crash loop only happens when the server is restarted or crashes while the PC is actively running the code.
3. The player uses a VS code addon for easier code readability.
4. The code is provided in a file, In case that's the problem. 
[stock.zip](https://github.com/cc-tweaked/CC-Tweaked/files/14324353/stock.zip)

**Comment by NorphyOG** [comment]
[crash-2024-02-17_05.02.47-fml.txt](https://github.com/cc-tweaked/CC-Tweaked/files/14324796/crash-2024-02-17_05.02.47-fml.txt)
[crash-2024-02-17_08.42.11-server.txt](https://github.com/cc-tweaked/CC-Tweaked/files/14324797/crash-2024-02-17_08.42.11-server.txt)
[crash-2024-02-17_09.06.48-server.txt](https://github.com/cc-tweaked/CC-Tweaked/files/14324798/crash-2024-02-17_09.06.48-server.txt)
[crash-2024-02-17_09.10.52-server.txt](https://github.com/cc-tweaked/CC-Tweaked/files/14324799/crash-2024-02-17_09.10.52-server.txt)


These logs are from the crash. The admins have already removed the bug by deleting all CC PCs on the server every time the server crash

**Comment by SquidDev** [comment]
Can I just double check those are the right crash reports? None of those look especially related to CC (one is a launch error in Vinery, the others appear to be related to Botarium or Create New Age).

**Comment by NorphyOG** [comment]
> Can I just double check those are the right crash reports? None of those look especially related to CC (one is a launch error in Vinery, the others appear to be related to Botarium or Create New Age).

I'll get some more, I hope that the whole thing isn't total nonsense and that it's actually due to some server settings

**Comment by NorphyOG** [comment]
[crash-2024-02-18_12.17.27-server.txt](https://github.com/cc-tweaked/CC-Tweaked/files/14334027/crash-2024-02-18_12.17.27-server.txt)
[crash-2024-02-18_12.38.02-server.txt](https://github.com/cc-tweaked/CC-Tweaked/files/14334029/crash-2024-02-18_12.38.02-server.txt)
[crash-2024-02-18_16.55.33-server.txt](https://github.com/cc-tweaked/CC-Tweaked/files/14334030/crash-2024-02-18_16.55.33-server.txt)
[crash-2024-02-18_12.05.33-server.txt](https://github.com/cc-tweaked/CC-Tweaked/files/14334031/crash-2024-02-18_12.05.33-server.txt)
[crash-2024-02-18_12.08.30-server.txt](https://github.com/cc-tweaked/CC-Tweaked/files/14334032/crash-2024-02-18_12.08.30-server.txt)
[crash-2024-02-18_12.12.07-server.txt](https://github.com/cc-tweaked/CC-Tweaked/files/14334033/crash-2024-02-18_12.12.07-server.txt)

**Comment by SquidDev** [comment]
Those are all watchdog errors. This typically means that the server is too overloaded (it takes 60s for a whole tick!). 

While it's possible that this is caused by CC, none of the stack traces include it, so it's hard to know for sure. I'd recommend using a profiler like Spark (especially Spark's `--only-ticks-over` flag) to keep an eye on the lag spikes you're seeing, which might help track the issue down.
