### ISSUE TITLE
<stringVariable>:find() causing vm exception (java.lang.ArrayIndexOutOfBoundsException)

### ISSUE THREAD

**Issue by fatboychummy** [SquidDev-CC/CC-Tweaked#173]
# Error:
`vm error: java.lang.ArrayIndexOutOfBoundsException`

# Cause:
I am making a thing that reads through files to check if it's a FATFILE (aka a file that is made by me, and thus compatible with certain things).  The program in question reads each line, and does a very simple operation on each line.

That operation would be:

```lua
currentLine:find("--[[FATFILE")
```

This seems to cause an array index out of bounds exception.

# Information:
### MC version: 
1.12.2

### CC:Tweaked version: 
1.12.2-1.81.1

### Forge: 
14.23.5.2824

### The program in question: 
[Lonky Link to the Program](https://github.com/fatboychummy/CCmedia/blob/master/helpfulthings/FatFileSystem.lua)

The erroring line is on line 54.

### Maybe helpful screenshots:
![image](https://user-images.githubusercontent.com/39929480/55700780-d9bfd780-598d-11e9-94cd-701aae5c23b2.png)

**Comment by SquidDev** [comment]
Worth noting that you should probably be doing `:find("--[[FATFILE", 1, true)` instead.
