### ISSUE TITLE
Minecraft Crashing when Nearing some villages

### ISSUE THREAD

**Issue by einfachtorben** [SquidDev-CC/CC-Tweaked#1731]
### Minecraft Version

1.20.x

### Version

1.109.6

### Details

Ive happend to encounter this issue twice now, on a singleplayer world and on an multiplayer/server world.

What i think is happening is that the village is decorated with some CC items and causing this bug somehow, so when i load in that chunk it crashes. So Currently when i try to load the world or join the server, my client crashes after a few seconds of loading the world

this also appears to be related to Issue #1626

attached is my debug log.
[debug.log](https://github.com/cc-tweaked/CC-Tweaked/files/14374332/debug.log)

**Comment by einfachtorben** [comment]
I could narrow it down to the mod [CC Cosmetics](https://github.com/JheffersonMarques/TurtleCosmetics).
after removing it from my modpack the error didnt persist anymore, i didnt think about it before opening this issue.

**Comment by SquidDev** [comment]
Ahh yes, this looks like another instance of https://github.com/JheffersonMarques/TurtleCosmetics/issues/1.
