### ISSUE TITLE
GPS API broken in 1.4.7

### ISSUE THREAD

**Issue by spacekatia** [SquidDev-CC/CC-Tweaked#1733]
### Minecraft Version

1.16.x

### Version

1.108.1

### Details

When using the CC:Tweaked coremod on Minecraft 1.4.7 and trying to use the gps API, the program fails because it tries to call isWireless from inside rom/apis/gps.lua, which doesn't exist.

**Comment by SquidDev** [comment]
Thanks for the report!

**Comment by SquidDev** [comment]
Sorry for the delay in getting the release out. [Have just pushed this to Modrinth](https://modrinth.com/mod/cc-tweaked/version/X7MARvdR).
