### ISSUE TITLE
Item Disappears When Mining a Computer or a Turtle Instead of Dropping Item

### ISSUE THREAD

**Issue by jessiewestlake** [SquidDev-CC/CC-Tweaked#174]
## Useful information to include:
 - Minecraft version: `1.14 Pre-Release 1`
 - CC: Tweaked version: `cc-tweaked-1.14+Pre-Release+1-1.82.1`
 - Detailed reproduction steps: sometimes I can spot a bug pretty easily, but often it's much more obscure. The more information I have to help reproduce it, the quicker it'll get fixed.

The mod works fine except that when mining a turtle or computer to try and pick it up, it does not drop the item, it just disappears. This happens when using any pickaxe. The same thing happens with advanced computers and advanced turtles. Mining peripherals like Disk Drives and Monitors actually drops the item like it should.

The problem occured before the latest update as well. Using the previous CC:Tweaked release and 19w14b.
[latest.log](https://github.com/SquidDev-CC/CC-Tweaked/files/3071714/latest.log)

**Comment by SquidDev** [comment]
Thanks for the report! Should be fixed in the next release (targetting 1.14 pre-release 2).
