### ISSUE TITLE
Game doesn't load on version 1.19.2

### ISSUE THREAD

**Issue by Kurovt** [SquidDev-CC/CC-Tweaked#1740]
### Minecraft Version

1.19.x

### Version

1.19.2- 1.01.2., 1.19.2- 1.01.3., 1.19.2- 1.01.4. (other versions doesn't work either) 

### Details

<img width="518" alt="Screenshot 2024-03-09 214307" src="https://github.com/cc-tweaked/CC-Tweaked/assets/162838465/d5ebfd69-ce01-44e3-9c80-ceb18a093557">

<img width="652" alt="Screenshot 2024-03-09 214748" src="https://github.com/cc-tweaked/CC-Tweaked/assets/162838465/2b8aeddd-ce3d-4cf2-bd71-d4d44f9b3443">

<img width="587" alt="Screenshot 2024-03-09 215156" src="https://github.com/cc-tweaked/CC-Tweaked/assets/162838465/90569885-f140-4ca5-96dd-08cc66978131">

[crash-2024-03-09_21.51.33-client.txt](https://github.com/cc-tweaked/CC-Tweaked/files/14547784/crash-2024-03-09_21.51.33-client.txt)

<img width="1515" alt="Screenshot 2024-03-09 214416" src="https://github.com/cc-tweaked/CC-Tweaked/assets/162838465/0fa915e3-6a51-4d8d-b021-a2aefde903dc">

I play a modpack on the version 1.19.2. I tried to delete the other mods but its the same result. 

I tried everything, like adjust the RAM, install and uninstall the mod and other mods, installing a other version but only the versions 1.19.2- 1.01.2., 1.19.2- 1.01.3., 1.19.2- 1.01.4. let me start the game and then crash at the startup. 

You can see screenshots with a yellow dot and a red dot. I think you can understand the meaning. 

I use this mod with the "Stargate Journey" mod. Without CC: Tweaked the game works.

I linked a screenshots with all mods.

<img width="1382" alt="Screenshot 2024-03-09 221501" src="https://github.com/cc-tweaked/CC-Tweaked/assets/162838465/55dc73a5-b040-4080-86cd-5c2c09af3dfd">

(PC: 3070, ryzen 5 5600X, 32GB RAM 3600MHZ)

**Comment by SquidDev** [comment]
Oh, this is very odd - the crash points to Iris/Oculus, rather than anything CC:T specific. Would you be able to remove Oculus and see if that helps?

**Comment by SquidDev** [comment]
Looking at https://github.com/Asek3/Oculus/issues/407, it suggests that this may be caused by a different missing dependency. Would you be able to upload your full logs?

**Comment by Kurovt** [comment]
> Looking at [Asek3/Oculus#407](https://github.com/Asek3/Oculus/issues/407), it suggests that this may be caused by a different missing dependency. Would you be able to upload your full logs?

Thank you for the help!
### **After hours I was fortunately able to figure it out.** 

> Unfortunately, nothing could be found in the logs and error messages, but i think it is not uncommon that the exit codes are not necessarily correct, or help.

> But out of nowhere it suddenly works! Strangely enough, I only now noticed that it was due to certain mods, even though I thought I had removed them all.

**The solution was to remove mods that were supposed to "improve the performance". 
In this case it were the mods: “Entity Collision FPS Fix” and “FPS optimizer”. Without them, I was able to start Minecraft with CC Tweaked without any problems. Unfortunately, the versions with a red dot don't work, but the ones with the yellow one do.**
 

**All said, I think it could help some people that have problems running the game with this mod. If there are one or more performance mods in the modpack and they don't work with CC Tweaked, you should remove them because they don't seem to be compatible.**
