### ISSUE TITLE
Client Crash cc-tweaked-1.20.1-forge-1.109.7

### ISSUE THREAD

**Issue by BonaireDreams** [SquidDev-CC/CC-Tweaked#1742]
### Minecraft Version

1.20.x

### Version

1.109.7

### Details

Forge 47.2.19
Update cc-tweaked (along with a number of other updated mods) in my modpack to 1.109.7 from 1.109.6 on both server and client. Server launches fine. Client crashes. Reverted cc-tweaked back to 1.109.6 on both client and server, both now launch fine. Crash log attached.
[crash-2024-03-10_13.57.08-client.txt](https://github.com/cc-tweaked/CC-Tweaked/files/14551803/crash-2024-03-10_13.57.08-client.txt)

**Comment by SquidDev** [comment]
Thanks for the report! Gah, looks like the refmap failed to apply again (see also #1632). Will unpublish this version for now.
