### ISSUE TITLE
Monitors are transparent when viewed through the nametag of a sneaking player

### ISSUE THREAD

**Issue by powerboat9** [SquidDev-CC/CC-Tweaked#1746]
### Minecraft Version

1.20.x

### Version

1.109.7

### Details

Have one player sneak while in front of a monitor, and view the monitor through that sneaking player's name tag.

![2024-03-13_00 08 56](https://github.com/cc-tweaked/CC-Tweaked/assets/7397652/8990831e-7396-48dd-b997-f014afdd4d1c)

**Comment by SquidDev** [comment]
Thanks for the report! Unfortunately, this is a vanilla bug, and so there's not much that can be done to fix it - see #1294.
