### ISSUE TITLE
CompileException not found

### ISSUE THREAD

**Issue by LubieKakao1212** [SquidDev-CC/CC-Tweaked#1751]
I have a Development Environment set up with architectury, when I try to launch the forge version it works fine until I try joining a world then it crashes with:
```
java.lang.ClassNotFoundException: org.squiddev.cobalt.compiler.CompileException
```

the project files can be found here
https://github.com/LubieKakao1212/OpenCombatUtility/tree/dev1.19.4-arch

**Comment by SquidDev** [comment]
Does it work if you remove the dependency on Cobalt?
