### ISSUE TITLE
Static recipe materials are hardcoded.

### ISSUE THREAD

**Issue by Patbox** [SquidDev-CC/CC-Tweaked#1755]
Recipes for disks and printout contain hardcoded static items, that can't be replaced. In case of modpacks/servers wanting to tweak their recipes to be more inline with other mods it prevents from doing so (only having the impostor recipes, which changing is useless).

Solution:
- Unhardcode things such as  redstone/paper/string/leather from recipes and move them to custom serializer json.
- Use custom cc-specific tags with default values pointing to current requirements

**Comment by SquidDev** [comment]
I have changed printed pages in ad70e2ad906026e59c900c28fde5a1918cab90f4.

I want to have a bit more of a think about disks. Ideally we'd just be able to expose these as a shapeless recipe, but I'm not sure what to do about the impostor recipes. I don't want to design a system where the impostor recipes are out-of-sync with the "actual" crafting recipe, but the only options I can see are generating the impostor recipes at runtime (a lot of extra code for something quite niche), or just removing them (loathe to do, as they're important for recipe book support).

**Comment by SquidDev** [comment]
This should be done as of MC 1.21.3.
