### ISSUE TITLE
Networking Cable not going to correct model

### ISSUE THREAD

**Issue by wolfieboy09** [SquidDev-CC/CC-Tweaked#1759]
### Minecraft Version

1.20.x

### Version

1.110.0

### Details

![image](https://github.com/cc-tweaked/CC-Tweaked/assets/105564186/fa39ba32-c86f-48b9-b529-e400dd7d08b1)

**Comment by wolfieboy09** [comment]
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/105564186/8bd4daac-bd8c-4967-a1a4-b84986b03d06)

**Comment by wolfieboy09** [comment]
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/105564186/3d949d25-957c-4ecc-8e2e-d1773d6c4b1f)
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/105564186/167ee339-9076-42ee-8f67-11c4f2953d47)
I turned a resouce pack on, but it does not effect the shape at all

**Comment by SquidDev** [comment]
Thanks for the report, this will be fixed in the next version!

For future reference, please include your logs when reporting a bug! This was a Forge-specific issue, so having that extra information helps track this sort of stuff down.
