### ISSUE TITLE
Crash on Mulitplayer server

### ISSUE THREAD

**Issue by SacrificialFlame** [SquidDev-CC/CC-Tweaked#176]
## Useful information to include:
 - Minecraft version 1.12.2
 - CC: Tweaked version 1.12.2-1.82.1
 - Detailed reproduction steps: sometimes I can spot a bug pretty easily, but often it's much more obscure. The more information I have to help reproduce it, the quicker it'll get fixed.

Went to break Advance Monitors and it kicked me with the following
https://paste.dimdev.org/enopirajex.mccrash

**Comment by SquidDev** [comment]
Thanks for the report! Really sorry about this, looks like this is a weird interaction between MCMultipart, CC:T and Proportional Destruction Particles. I'll see what I can do :).

**Comment by SacrificialFlame** [comment]
Thanks and its not your fault as its a weird bug
