### ISSUE TITLE
Computers unusuable once unloaded then loaded

### ISSUE THREAD

**Issue by SpookyEna** [SquidDev-CC/CC-Tweaked#1760]
### Minecraft Version

1.20.x

### Version

1.110.0

### Details

When a computer goes unloaded in a chunk it turns off and will not turn back on again when loaded.
When it does this it becomes completely inoperable until you break or replace the computer.
You cannot hit the power button, you cannot type, and terminate does nothing.
This also applies to pocket computers, which can't be replaced so they are remaining off.
This is on a server wth a fairly large list of mods. Nothing is in the client logs or the server logs.

Repro Steps:
1. Put computer in a chunk, preferably with something running on startup
2. Leave the chunk unloaded for a short period of time
3. Come back to find the machine off entirely and unable to be turned on.

Similar steps can be taken for the pocket computer by putting it within a storage it doesn't remain on in.

Complete Mod List: https://gist.github.com/SpookyEna/18155a36cdcd571d829d8e5c163c8b12

**Comment by SquidDev** [comment]
Thanks for the report! This should be fixed in 1.110.1.
