### ISSUE TITLE
Network cables not connecting?

### ISSUE THREAD

**Issue by Morketh** [SquidDev-CC/CC-Tweaked#1772]
### Minecraft Version

1.20.x

### Version

1.109.6

### Details

![2024-04-02_15 33 57](https://github.com/cc-tweaked/CC-Tweaked/assets/6291631/17fed7e4-b158-4fe9-b6a9-c9397761bfc3)
Can provide more details when I get home from work. But from what I've been able to test they do not connect together I have not tested network functionality however I was able to pass between the cables as if they were not connected. 

Edit: will provide mod list and game logs let me know if you need any additional details. CC has been a favorite mod I'd like to help with this anyway I can.

**Comment by SquidDev** [comment]
Thanks for the report! Just to check, are you running Optifine?

**Comment by Wojbie** [comment]
This looks like common issue caused by Optifine. See [#1389](https://github.com/cc-tweaked/CC-Tweaked/discussions/1389)

Do you have it installed in your pack?

**Comment by Morketh** [comment]
Optifine is installe. Have not double checked with the server side as I was playing around in creative first.

**Comment by SquidDev** [comment]
This is a bug caused by Optifine (see #1458 and https://github.com/sp614x/optifine/issues/7395), so I'm afraid there's nothing I can do here.

I'd strongly recommend removing Optifine and replacing it with Embeddium (and Occulus if you need shaders). They tend to have much better mod compatibility.

**Comment by Morketh** [comment]
> This is a bug caused by Optifine.....

I appreciate the reply and the Information for shaders and things. For future reference is there an FAQ section I should be looking at?

**Comment by SquidDev** [comment]
I'm afraid not, no. "Don't use Optifine" is kinda general modding folklore/knowledge, but not sure there's a good centralised resource for any of this.
