### ISSUE TITLE
[1.19,2] Workbench inventory api needed

### ISSUE THREAD

**Issue by accrrsd** [SquidDev-CC/CC-Tweaked#1780]
Problem: I'm playing on version 1.19.2 and wanted to make an automatic crafting system using an inventory api and a workbench. I know that I could do this through a turtle, but I don't want to spam computers, clogging up the world and increasing the number of running programs, because in fact they will execute the same code.

Solution: It would be great to be able to connect a workbench via a wired modem and interact with its inventory directly from a computer.

Argumentation:
1. I do not know about 1.20+, but considering that an automatic workbench will soon appear in the vanilla game, this request is even more reasonable. 

2. In fact, this interaction is the most common inventory API, as with stoves or chests, it seems to me that the lack of such an opportunity for a workbench is just an oversight, not a technical difficulty. (it is also worth considering interaction with other vanilla block inventories, if any are missed)

3. Turtles that can craft still will not lose their relevance, because unlike a static workbench, they can do it on the go.

Usage example:
With this small feature, it will be possible to implement a full-fledged replacement for AE2 exclusively using computercraft programming and single computer.

**Comment by SquidDev** [comment]
Thank you for the suggestion! This is something I have thought about several times in the past, but I'm afraid this isn't possible. Crafting tables don't actually have an inventory — remember, once you close the UI, all the items will pop out! This means there's no way to store items, or transfer items to a crafting table.

Honestly, I wouldn't worry too much about having extra turtles running. Most of the time they're not going to be idle, waiting for the signal to craft. Unless you're placing dozens and dozens of them, it shouldn't have any noticeable impact on performance.

**Comment by accrrsd** [comment]
@SquidDev
I'm sorry for the second post, I thought I hadn't sent the first one. If it's not difficult for you, please delete it.
Regarding the problems with the workbench, it's a pity. But what about automatic workbenches in 1.21 snapshot? They seem to keep objects inside themselves.

**Comment by SquidDev** [comment]
Yep, those should be supported by default!
