### ISSUE TITLE
Workbench as peripheral with inventory api

### ISSUE THREAD

**Issue by accrrsd** [SquidDev-CC/CC-Tweaked#1781]
Problem: I'm playing on version 1.19.2 and wanted to make an automatic crafting system using an inventory api and a workbench. I know that I could do this through a turtle, but I don't want to spam computers, clogging up the world and increasing the number of running programs, because in fact they will execute the same code.

Solution: It would be great to be able to connect a workbench via a wired modem and interact with its inventory directly from a computer.

Argumentation:
1. I do not know about 1.20+, but considering that an automatic workbench will soon appear in the vanilla game, this request is even more reasonable.

2. In fact, this interaction is the most common inventory API, as with stoves or chests, it seems to me that the lack of such an opportunity for a workbench is just an oversight, not a technical difficulty. (it is also worth considering interaction with other vanilla block inventories, if any are missed)

3. Turtles that can craft still will not lose their relevance, because unlike a static workbench, they can do it on the go.

Expamle usage:
A local network with a large number of chests and workbenches connected, for mass crafting, remelting, etc. The implementation of mods for autocraft through computercraft alone.

Simplified interaction with a static workbench on a small scale, since there is no need to build an intermediary in the form of a turtle.

**Comment by SquidDev** [comment]
Oh, I think you accidentally opened the same issue twice? See #1780.
