### ISSUE TITLE
turtle not attack or attackUp, zombie farm brok :( sorry squid im not good at writing issues

### ISSUE THREAD

**Issue by MCBEModder2020** [SquidDev-CC/CC-Tweaked#1786]
### Minecraft Version

1.20.x

### Version

1.110.2 with polymer adapter on fabric server behind velocity

### Details

log has no errors or anything abt cc

turtle just dont attack

mods:
[19:19:58] [main/INFO]: Loading 151 mods:
	- autosmeltenchant 1.3.2
	- cc-tweaked-polymer-patch 1.109.6.0+1.20.4
	   |-- factorytools 0.1.8+1.20.4
	   |-- map-canvas-api 0.2.2+1.19.4
	   |-- player-data-api 0.4.0+1.20.3
	   \-- sgui 1.4.1+1.20.4
	- chosenenchantsmod 1.1-1.20.4
	- codenamegamer-paxels 1.0.0+1.20.1
	- computercraft 1.110.2
	   |-- cc_tweaked_cobalt 0.9.2
	   |-- com_electronwill_night-config_core 3.6.7
	   |-- com_electronwill_night-config_toml 3.6.7
	   |-- com_jcraft_jzlib 1.1.3
	   |-- io_netty_netty-codec-http 4.1.97.Final
	   |-- io_netty_netty-codec-socks 4.1.97.Final
	   \-- io_netty_netty-handler-proxy 4.1.97.Final
	- crafttweaker 17.0.13
	   |-- org_javassist_javassist 3.29.0-GA
	   \-- org_reflections_reflections 0.10.2
	- crossstitch 0.1.6
	- enchantedshulkers 1.2.4
	   |-- conditional-mixin 0.4.1
	   |-- io_hotmoka_toml4j 0.7.3
	   |-- mixinsquared 0.1.1
	   |-- mm 2.3
	   |-- server_translations_api 2.2.0+1.20.3-rc1
	   \-- sgui 1.4.1+1.20.4
	- enchantment 1.0.0
	- fabric-api 0.96.11+1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.49+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.16+78d798af4f
	   |-- fabric-block-api-v1 1.0.16+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.46+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.7+78d798af4f
	   |-- fabric-command-api-v1 1.2.41+f71b366f4f
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- fabric-commands-v0 0.2.58+df3654b34f
	   |-- fabric-containers-v0 0.1.86+df3654b34f
	   |-- fabric-content-registries-v0 5.0.15+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.10+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.23+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.4+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.4+5c0133444f
	   |-- fabric-dimensions-v1 2.1.61+78d798af4f
	   |-- fabric-entity-events-v1 1.6.1+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.1+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.74+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.46+78d798af4f
	   |-- fabric-item-api-v1 2.2.0+d6f2b0844f
	   |-- fabric-item-group-api-v1 4.0.26+58f8c0124f
	   |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
	   |-- fabric-keybindings-v0 0.2.39+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.0+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.9+78d798af4f
	   |-- fabric-message-api-v1 6.0.5+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.65+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.8+78d798af4f
	   |-- fabric-models-v0 0.4.7+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.7+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.0.14+080016e44f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.20+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.19+58f8c0124f
	   |-- fabric-renderer-api-v1 3.2.4+78d798af4f
	   |-- fabric-renderer-indigo 1.5.4+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.53+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.1+e761c6694f
	   |-- fabric-rendering-v0 1.1.56+df3654b34f
	   |-- fabric-rendering-v1 3.2.0+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.14+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.20+df798a894f
	   |-- fabric-screen-api-v1 2.0.17+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.55+78d798af4f
	   |-- fabric-sound-api-v1 1.0.17+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.11+eb30349a4f
	   \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.9
	   \-- mixinextras 0.3.5
	- fabricproxy-lite 2.7.0
	   \-- com_moandjiezana_toml_toml4j 0.7.2
	- faux-custom-entity-data 9.0.1
	- ferritecore 6.0.3
	- forgeconfigapiport 20.4.3
	- image2map 0.5.0+1.20.2
	   \-- map-canvas-api 0.2.2+1.19.4
	- java 17
	- krypton 0.2.6
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- lazydfu 0.1.3
	- lithium 0.12.1
	- minecraft 1.20.4
	- moretools 1.1.0+1.20.4
	- nochatreports 1.20.4-v2.5.0
	   |-- fabric-rendering-v1 3.0.11+9468a19d32
	   \-- fabric-screen-api-v1 2.0.15+f6e85ac232
	- polydecorations 0.2.2+1.20.4
	   |-- common-protection-api 1.0.0
	   |-- factorytools 0.1.8+1.20.4
	   |-- map-canvas-api 0.2.2+1.19.4
	   \-- sgui 1.4.1+1.20.4
	- polydex 1.0.1+1.20.4
	   |-- placeholder-api 2.3.0+1.20.3
	   |-- player-data-api 0.4.0+1.20.3
	   |-- predicate-api 0.3.0+1.20.2
	   |-- server_translations_api 2.2.0+1.20.3-rc1
	   |-- sgui 1.4.1+1.20.4
	   \-- sidebar-api 0.3.0+1.20.3
	- polyfactory 0.3.4+1.20.4
	   |-- common-protection-api 1.0.0
	   |-- graphlib 1.4.0+1.20.4
	   |    |-- kmodlib-overlay 0.2.13+1.20.3
	   |    \-- libnetworkstack 0.11.0-pre.1
	   |-- map-canvas-api 0.2.2+1.19.4
	   |-- sgui 1.4.1+1.20.4
	   \-- sidebar-api 0.3.0+1.20.3
	- polymc 5.6.1+1.20.4
	   \-- resource-locator-api 0.5.1+1.20.1
	- polymer-bundled 0.7.7+1.20.4
	   |-- polymer-autohost 0.7.7+1.20.4
	   |-- polymer-blocks 0.7.7+1.20.4
	   |-- polymer-common 0.7.7+1.20.4
	   |    \-- packet_tweaker 0.5.1+1.20.4
	   |-- polymer-core 0.7.7+1.20.4
	   |    |-- polymer-networking 0.7.7+1.20.4
	   |    |    \-- polymer-common 0.7.7+1.20.4
	   |    |         \-- packet_tweaker 0.5.1+1.20.4
	   |    \-- polymer-registry-sync-manipulator 0.7.7+1.20.4
	   |-- polymer-resource-pack 0.7.7+1.20.4
	   |    \-- polymer-common 0.7.7+1.20.4
	   |         \-- packet_tweaker 0.5.1+1.20.4
	   \-- polymer-virtual-entity 0.7.7+1.20.4
	        \-- polymer-common 0.7.7+1.20.4
	             \-- packet_tweaker 0.5.1+1.20.4
	- polysit 0.5.3+mc.1.20.1
	- signedvelocity 1.2.3
	- silk-all 1.10.3
	   |-- silk-commands 1.10.3
	   |-- silk-core 1.10.3
	   |-- silk-game 1.10.3
	   |-- silk-igui 1.10.3
	   |-- silk-nbt 1.10.3
	   |-- silk-network 1.10.3
	   \-- silk-persistence 1.10.3
	- silkfortune 1.0.0
	- stackdeobfuscator 1.4.2+bf1fc22
	   |-- dev_booky_common_ 1.4.2+bf1fc22
	   \-- net_fabricmc_mapping-io 0.3.0
	- starlight 1.1.3+fabric.f5dcd1a
	- telekinesis 2.4.0-1.20.4
	   |-- com_akuleshov7_ktoml-core-jvm 0.5.1
	   \-- mixinsquared 0.1.1
	- terralith 2.4.11
	- universal-graves 3.2.1+1.20.3
	   |-- common-protection-api 1.0.0
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   |-- placeholder-api 2.3.0+1.20.3
	   |-- predicate-api 0.3.0+1.20.2
	   |-- server_translations_api 2.2.0+1.20.3-rc1
	   \-- sgui 1.4.1+1.20.4
	- veinminer 2.0.2
	   |-- de_miraculixx_core_ 2.0.3
	   \-- fabric-permissions-api-v0 0.2-SNAPSHOT
	- veinmining 3.1.0+1.20.4
	   \-- spectrelib 0.15.2+1.20.4
	- voicechat 1.20.4-2.5.12
	   \-- fabric-key-binding-api-v1 1.0.39+f4b7e42432
	- wiretap 1.20.2-1.1.0
	- worldedit 7.3.0+6678-55745ad
	- yawp 0.0.2.9-beta3
	- yet_another_config_lib_v3 3.3.2+1.20.4
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1

**Comment by hugeblank** [comment]
If you could provide screenshots of the situation, reproduction steps, the mod pack name (if it's not a custom one), that would be helpful! Also I'd report this to [the polymer patch](https://github.com/PolymerPorts/cc-tweaked-patch) first!

Additional nitpick, everything after the comma in this title would be better off in the issue description field:
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/16393543/2cc97e19-f7e8-4b85-81d8-4380d403b3b6)

**Comment by SquidDev** [comment]
> Sorry squid, I'm not good at writing issues

That's fine, it takes practice! A useful pattern I like to follow is try to reproduce the bug from scratch, and write down each step. For instance, something like:

> 1. Create a new superflat world.
> 2. Place down a melee turtle, a zombie in front of the turtle, and a block over the zombie so it does not burn.

At this point, it may be worth including a screenshot or two, just to clarify the exact setup. Then, continue:

> 3. Open the Lua prompt in the the turtle, and run `turtle.attack()`.

Then explain what outcome you got. This might include any error messages you got, what happened to the zombie, etc... In your case, it sounds like your entire farm turned into [that dwarf from God of War](https://godofwar.fandom.com/wiki/Brok), so I'd love to have a screenshot :p!

It's also useful to try to reproduce this with as few mods as possible. Honestly, if an issue report requires a whole modpack to reproduce, I'm tend to ignore it.

**Comment by MCBEModder2020** [comment]
maybe its an interaction with [yawp](https://modrinth.com/mod/yawp)

**Comment by hugeblank** [comment]
> maybe its an interaction with [yawp](https://modrinth.com/mod/yawp)

Try removing the mod and testing in a test world to see if that fixes it. If it fixes it report the issue to them, and link this report. If not, then do the good ol' binary search, where you remove half of the mods, then test for the issue.

Also, again, **If you could provide screenshots of the situation, reproduction steps, the mod pack name (if it's not a custom one), that would be helpful!** For all we know you could be calling the function incorrectly making this wild goose chase a complete waste of time.

**Comment by fatboychummy** [comment]
In the shell, run the `lua` program so you get something that looks like this:
```
CraftOS 1.9
blabla the MOTD
> lua
Interactive Lua prompt.
Call exit() to exit.
lua> 
```

Then, type `turtle.attack()`, ensuring the turtle has a tool of *some kind* equipped and something attackable is in front. It should return some information about why it is failing to attack, something like so:
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/39929480/e627eeba-7b47-475f-ac9c-2385cc03987a)

Screenshots of your setup would also be helpful, as others have said!
