### ISSUE TITLE
Computer work range

### ISSUE THREAD

**Issue by FimastGDOld** [SquidDev-CC/CC-Tweaked#1788]
I have created a program that makes a pulsating redstone, but when I go away the redstone stops working, when I come back it works again

**Comment by FimastGDOld** [comment]
how can I increase the range of my computer?

**Comment by SirEdvin** [comment]
So, computer works until [chunk](https://minecraft.fandom.com/wiki/Chunk) is loaded.

You can increase load range of chunks, but more correct way of solving this is to [force load the chunk](https://minecraft.fandom.com/wiki/Commands/forceload) or use some mod, that provides chunk loading, like [this](https://www.curseforge.com/minecraft/mc-mods/chunk-loaders), but there is a plethora of them.
