### ISSUE TITLE
Mining turtle freezes the game then mining a block

### ISSUE THREAD

**Issue by MaxConz** [SquidDev-CC/CC-Tweaked#1789]
### Minecraft Version

1.20.x

### Version

1.110.2

### Details

Turtle try's mine Xpertrified ore block from Forbidden & Arcanus mod.

**Comment by Lupus590** [comment]
Some questions.
Does this still happen if the turtle mines another block?
Can you post the server's logs (or your singleplayer logs)?
Can you reproduce this with a minimum set of mods? E.g. just CC and Forbidden & Arcanus.

**Comment by MaxConz** [comment]
[2024-04-12-1.log](https://github.com/cc-tweaked/CC-Tweaked/files/14967101/2024-04-12-1.log)

I tested only with CC and Forbidden & Arcanus mods, I can't reproduce the same outcome.

**Comment by Lupus590** [comment]
Can you try to reproduce it with some other combination of mods? Do you have a mod that changes tools or block interactions, that might be a good mod to try checking first.

**Comment by MaxConz** [comment]
Updated Forbidden & Arcanus version 1.20.1-2.2.6, seems to be fixed maybe, still cannot reproduce .

**Comment by SquidDev** [comment]
Thanks for the additional info! Given that, I think I'll close this for now — if this happens again and/or anyone can reliably reproduce, I'm happy to reopen :).
