### ISSUE TITLE
[1.12.2] Mining turtle related crash

### ISSUE THREAD

**Issue by cheatscom** [SquidDev-CC/CC-Tweaked#179]
**Minecraft**: 1.12.2
**Forge**: 14.23.5.2836
**CC:** cc-tweaked-1.12.2-1.82.2
**Main mods of note**: PeripheralsPlusOne-1.12.2-1.1-build-T58 and possibly BetterFps, foamfix and Optifine.

Hello,

When trying to use a mining turtle with a program to plant trees and harvest them, I get a crash log that seems to be relating to CC-T trying to call on the collecting silk touch drop? The crash occurs after running the program on the turtle, where it will start to move but then crashes after mining one block. The blocks that are being mined are wood blocks and the program should allow it to place a sapling afterwards, but it never quite gets that far. Please see below for the crash log;

https://pastebin.com/PfTCgXBs

Hopefully this isn't a case of me missing some kind of dependencies or overlooking something silly. I can see there was an issue regarding the turtle's "turtle.place()" command back from 2018 but this seems to be different and was fixed back then. I can send the code from the turtle or the test world file if it would help replicate this issue.

Thank you in advance for your time.

**Comment by kreezxil** [comment]
I got this crash on the server twice today in build 1.12.2-1.82.2

http://paste.ubuntu.com/p/yhnb8P99qs/
http://paste.ubuntu.com/p/PKyRVFwbQc/

Been trying different programs for mining.

This last one is using the "supposedly" bedrock friendly mining program at https://pastebin.com/JbFMHaNg, it's supposed to mine vertical shafts thus avoiding the issue of getting trapped under bedrock when not using flat bedrock.
