### ISSUE TITLE
Kind of a reopen of #1786, with things i forgot to mention

### ISSUE THREAD

**Issue by MCBEModder2020** [SquidDev-CC/CC-Tweaked#1798]
### Minecraft Version

1.20.x

### Version

same as #1786

### Details

#1786
and the /computercraft command does not exist? is it my luckperms or smth
in regards to me not providing enough detail about it attacking, it does not say that the zombie is protected it just says there is nothing to attack
the diamond pickaxe does work though, since my nether tunnel bore program worked (im sooo used to meteor client tunnel bore but cc is a good replacement its just 30x slower)
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/78447517/17459396-593f-493b-975d-0899a0205aeb)
when i ran the code in the screenshot there was a skeleton in front of the turtle

**Comment by MCBEModder2020** [comment]
![Screenshot 2024-04-20 at 4 50 01 PM](https://github.com/cc-tweaked/CC-Tweaked/assets/78447517/0d15fb31-0bdb-4b39-a52e-39d934a9f9de)

**Comment by SquidDev** [comment]
> and the `/computercraft` command does not exist?

The CC polymer patch disables this command, as it cannot be used on vanilla clients.

**Comment by SquidDev** [comment]
I've had a go at reproducing this. This only appears to occur when the polymer patch is installed, so I'm afraid you'll need to report this [on their issue tracker](https://github.com/PolymerPorts/cc-tweaked-patch).

Once again, please please please, [follow something like the format I suggested in the previous issue](https://github.com/cc-tweaked/CC-Tweaked/issues/1786#issuecomment-2051196975). When reporting bugs, you're trying to make it as easy as possible for the mod developer to see what you've tried, and reproduce it themselves.
