### ISSUE TITLE
Minor documentation mispelling

### ISSUE THREAD

**Issue by C2Gamser** [SquidDev-CC/CC-Tweaked#1799]
While reading through the 'How to play speaker audio' page on tweaked.cc, I noticed a minor misspelling of the DFPWM file format.

[https://tweaked.cc/guide/speaker_audio.html](url)
![mispelling_audio_page](https://github.com/cc-tweaked/CC-Tweaked/assets/121264000/5d86cbba-e180-4731-bdb2-fa2b0219087c)

**Comment by Lupus590** [comment]
I belive that this should be easy to fix via a pull request on this file: https://github.com/cc-tweaked/CC-Tweaked/blob/mc-1.20.x/doc/guides/speaker_audio.md
