### ISSUE TITLE
Excavate program terminates when turtle dumps it's inventory

### ISSUE THREAD

**Issue by kreezxil** [SquidDev-CC/CC-Tweaked#180]
## Useful information to include:
 - Minecraft version 1.12.2.-14.23.5.2836
 - CC: Tweaked version 1.12.2-1.82.2
 - When using the excavate program, when the turtle returns to dump its contents into a chest, it turns around and stops. When you look at it, the output says it mined so many things in total. Which is what it says when it is done mining.

![image](https://user-images.githubusercontent.com/3880072/56458628-c417be00-634e-11e9-9eaa-405130322e4c.png)

![image](https://user-images.githubusercontent.com/3880072/56458647-f32e2f80-634e-11e9-8a47-02e07147aa0c.png)

As you can see I'm standing at y:52 and the turtle barely went down much, just enough to fill itself and return and empty and that's when it decided that it was done. It's not suppose to act like that until reaches bedrock or y:1 or similar.

**Comment by Wojbie** [comment]
Looking at your screenshot i see some other mods materials - Can you post what mods are you using? My fist guess would be that turtle detected something it could not break and that triggered the end of mining routine.

**Comment by kreezxil** [comment]
I'm using it my own pack  [(World of Dragons)](https://minecraft.curseforge.com/projects/world-of-dragons). Which has all about 200+ mods in it. Modlist here: http://paste.ubuntu.com/p/PnPPXYGtJj/

**Comment by Wojbie** [comment]
Just to check could you tell me if those blocks (or any other modded blocks that are on bottom level of the excavated area) are breakable with normal pick / test if turtle can break them? 
![obraz](https://user-images.githubusercontent.com/5893536/56460393-4e3d4200-63a2-11e9-9c37-2c6cd62c0820.png)

**Comment by kreezxil** [comment]
yeah those require diamond pick. however, the turtle is crafted with a
diamond pick. ...

**Comment by kreezxil** [comment]
Created this in single player, the turtle is unnaffected by the weird ore.

![weird_ore_test](https://user-images.githubusercontent.com/3880072/56472400-b122ed80-6423-11e9-9882-60305c04e9b0.gif)

**Comment by SquidDev** [comment]
Weird, I'm entirely unable to reproduce. My robot has dumped its items twice now, and not seen any issues:

![image](https://user-images.githubusercontent.com/4346137/56498085-2829b600-64f8-11e9-971a-402eca834323.png)

The only reason a turtle should stop digging without printing anything else is if it is blocked from moving forward but can't dig/attack it - so pretty much just when encountering bedrock or some unbreakable ore. I'd suggest just running the program again and seeing if it stops at the same point - then you can do some diagnosis to see what `turtle.detect()`, `turtle.dig()`, `turtle.attack()` return.

**Comment by kreezxil** [comment]
Would it also behave this way if a lag spike hits the server?

**Comment by SquidDev** [comment]
It shouldn't no - it'd just cause a turtle (like any other tile entity) to run slightly slower, but not actually break functionality.

**Comment by kreezxil** [comment]
not sure if this is related, but in FTB utilities if FAKE PLAYER is not
enabled as a member or ally with editing powers this behavior starts. I'll
test again, maybe that was an issue.

**Comment by kreezxil** [comment]
ok, that seems to be the issue, I'm using FTB UTILITIES claiming system and prior to today I had not told it what a fake player can do in the claims. I set it to member and now the turtle is excavating without dumping and terminating.

If this issue comes up again it's because the FAKE PLAYER is not added to the claim. Minecolonies has a protection system to and the fake player can be added to it as well.
