### ISSUE TITLE
Version for the April 1st Potato Update?

### ISSUE THREAD

**Issue by Flexico** [SquidDev-CC/CC-Tweaked#1802]
I know it's a snapshot/not serious, but it has enough unique content that I'll probably be playing it for a while, and it would be awesome to have some of my favorite mods along! Fabric and Fabric API are updated already, along with REI and a few others~

**Comment by SquidDev** [comment]
There is a WIP update to 1.20.5 in #1793, which it might be possible to base a 24w14potato build off. I'm afraid you'll have to do this yourself though, as I have no interest in attempting this.

**Comment by Flexico** [comment]
Ok, I guessed you might say that! Thanks for the info, though I already tried that one, and Fabric didn't like it. ><
