### ISSUE TITLE
Create depot reported to have a size of 9 slots

### ISSUE THREAD

**Issue by ascpial** [SquidDev-CC/CC-Tweaked#1804]
### Minecraft Version

1.19.x

### Version

1.101.4 (forge)

### Details

CC: Tweaked reports that Create mod's depot bloc has a size of 9 slots, even though it only has one available.

When adding items to the second slot for example, the items are put in the first slot. It is not possible to push more than a stack of items.

**Comment by SquidDev** [comment]
I'm afraid there's not any way to fix this. While they may not display in game, depots do actually have 9 slots - one input slot, and 8 output slots:

https://github.com/Creators-of-Create/Create/blob/d66170c8fed5d02ad46f44fd0e66685be88a3170/src/main/java/com/simibubi/create/content/logistics/depot/DepotItemHandler.java#L17-L20

**Comment by ascpial** [comment]
I wasn't aware of this, thanks!
