### ISSUE TITLE
Allay cannot triggered by computer using noteblock

### ISSUE THREAD

**Issue by tmvkrpxl0** [SquidDev-CC/CC-Tweaked#1812]
### Minecraft Version

1.20.x

### Version

1.110.2

### Details

I tried to automatically call allays using computer, but neither using noteblock as peripheral nor sending redstone signal to it calls allays back. I don't even see light blue thing that normally gets sent to them.

**Comment by SquidDev** [comment]
I'm afraid I cannot reproduce this (using MC 1.20.1, CC:T 1.110.3, Fabric 0.86.1). I did the following in a creative world:

 - Spawn in a new allay.
 - Gave the allay a sandstone.
 - Placed a note block and activated it once.
 - Placed a computer next to the allay, and ran the `while true do rs.setOutput("right", true) sleep() rs.setOutput("right", false) sleep() end`.
 - Threw a piece of sandstone on the floor.

The allay picked up the sandstone and returned to the noteblock. I can also confirm I saw the particle effects:

![A CC computer with a noteblock to the right of it. An allay is in the distance, and there is a blue wave coming from the note block to the allay.](https://github.com/cc-tweaked/CC-Tweaked/assets/4346137/d774e79b-7eda-438c-b275-eb283691c801)

**Comment by tmvkrpxl0** [comment]
I tried your test code and it worked on my side, that was strange.
However I still can't make work as peripheral.

**Comment by SquidDev** [comment]
Hrrm, CC doesn't include a noteblock peripheral by default. Do you have any other peripheral mods installed?

**Comment by tmvkrpxl0** [comment]
Yes, I didn't know it wasn't supported by default. It's actually from Advanced Peripherals. I should report there instead.
