### ISSUE TITLE
The redstone link on CC- Tweaked's computer is activated incorrectly

### ISSUE THREAD

**Issue by AhmedAtheek** [SquidDev-CC/CC-Tweaked#1829]
### Minecraft Version

1.18.x

### Version

1.101.2

### Details

https://github.com/cc-tweaked/CC-Tweaked/assets/114966571/7d3507f6-5555-4193-9edb-fcb78aabd559

only occurs when the bottom is powered

**Comment by SquidDev** [comment]
Thanks for the report! I'm afraid I think this might be an issue on the Create end. I can't replicate this behaviour with using any other redstone component (such as repeaters or wire) in place of the redstone link.
