### ISSUE TITLE
What's wrong with the cable?

### ISSUE THREAD

**Issue by YideBN** [SquidDev-CC/CC-Tweaked#1845]
### Minecraft Version

1.20.x

### Version

1.110.3

### Details

![2024-05-28_22 30 36](https://github.com/cc-tweaked/CC-Tweaked/assets/113898536/7736e119-0eb4-479b-aa72-01182506849a)
I don't know what it is, but when I play without Optifine, this error doesn't exist. On older versions of the game (1.19) everything is fine both with and without Optifine.

**Comment by SquidDev** [comment]
See #1458. Optifine breaks several Forge features, which in turn causes issues with CC:T. I'd recommend removing Optifine, and replacing it with more stable/reliable mod like Occulus.

**Comment by YideBN** [comment]
thx
