### ISSUE TITLE
Turtles can`t equip tools

### ISSUE THREAD

**Issue by Aranyalma2** [SquidDev-CC/CC-Tweaked#1848]
### Minecraft Version

1.20.x

### Version

110.3

### Details

[[1.20.5] 1.110.3](https://github.com/cc-tweaked/CC-Tweaked/releases/tag/v1.20.5-1.110.3)

Turtles can`t equip pickaxe, axe, hoe, etc,,,, (Modems and crafting table works)
On the other hand, the ones already on it work, they can be removed, but they cannot be put back on

- On the UI, the slot does not accept them.
- The equip command and the lua function also throw an error. 
- Crafting recipe doesn't work either (but it shows).

No errors are logged during startup or running.

**NeoForge, Fabric version affected (Forge untested)**

Side note: This is the only version (yet) that is compatible with the polymer (run CC-Tweaked only server-sided) patch under 1.20.5 and 1.20.6

**Comment by Zirunis** [comment]
I've encountered the same bug a couple days ago but didn't think anything of it because I never equip/unequip peripherals so I didn't know whether the behavior was intended or not. Same version on NeoForge.
I think you accidentally closed this issue, maybe reopen it if you can?

**Comment by Aranyalma2** [comment]
Isssue is dupliacated (my bad) [#1810](https://github.com/cc-tweaked/CC-Tweaked/issues/1810) and already patched in [Ignore enchantments/attributes on the original item](https://github.com/cc-tweaked/CC-Tweaked/commit/94c864759d8ad98abaadc6c053edbc12e420af3d) commit (released under 1.110). On 1.20.5 the easiest way get the patch, compile your own .jar after the [#1810](https://github.com/cc-tweaked/CC-Tweaked/issues/1810).

~~But after the [Ignore enchantments/attributes on the original item](https://github.com/cc-tweaked/CC-Tweaked/commit/94c864759d8ad98abaadc6c053edbc12e420af3d) the [polymer patch`s](https://github.com/PolymerPorts/cc-tweaked-patch) mixins (TurtleToolAccessor) are incompatible with CC:T~~
