### ISSUE TITLE
Rendering dan200 skull causes crash in build 1.12.2-1.82.2

### ISSUE THREAD

**Issue by kreezxil** [SquidDev-CC/CC-Tweaked#185]
## Useful information to include:
 - Minecraft version: 1.12.2-14.23.5.2836
 - CC: Tweaked version: 1.12.2-1.82.2
 - Detailed reproduction steps: 
1. have JEI installed
1. open jei and browse to silverfish
1. press 'u' while hovering over silverfish

A player on my World of Dragons modpack reported they did this. I posted the report to JEI first as it appears in the top of the stack trace. However, I noticed the Mezz will tell players that another mod is responsible for the rendering crashes. So looking deeper into the crash report it shows not a silverfish but the dan200 skull being rendered as to what is causing the crash

https://pastebin.com/rswhFiPY

**Comment by SquidDev** [comment]
I'm unable to reproduce with just CC:T and JEI (Forge 14.23.4.2749, JEI 4.15.0.269).

I'm fairly sure this is due to a core mod interfering - there's nothing in `renderItemAndEffectIntoGUI` (`func_184391_a`) which should ever throw an NPE.

**Comment by SquidDev** [comment]
As mezz has said on the other issue, this is most likely not a JEI or CC:T issue. Try to remove some mods, reproduce the issue, and repeat until you can work out who/what is causing it.

**Comment by kreezxil** [comment]
well it's not happened again, probably one off, please close.
