### ISSUE TITLE
Audio guide's examples have issues

### ISSUE THREAD

**Issue by Zirunis** [SquidDev-CC/CC-Tweaked#1851]
Super low priority because the guide is great and the examples are good and work in Minecraft, but...
at least for me they don't quite work in the browser.

- Example 2 throws "Too long without yielding"
- Example 3 throws "Too long without yielding"
- Example 4 works, but hangs (loading the buffer takes longer than playing the audio)

This may be an issue just for me (using ungoogled chromium), in that case simply close this issue.

Otherwise I'm assuming that these may be hard to fix or simply limited by the processing power the browser is allowed to use?
Like I said, not important. I just noticed it so I thought I'd document it.

**Comment by SquidDev** [comment]
Thanks for the report! 

Unfortunately the browser Lua VM is not especially efficient, and these examples are really pushing the limits of what we can achieve in the browser, especially the fourth one. *However*, I'm surprised that it's this bad — I can run examples 2 and 3 on my phone, so a normal desktop/laptop shouldn't have any issues!

Would you be able to try with a different browser (e.g. Firefox) and see if it's any better there?

**Comment by Zirunis** [comment]
Yup, installed firefox and it runs flawlessly! Also doesn't eat nearly as much CPU as it does on Chromium. So it's probably an issue with my browser. Probably won't dig deeper though as I've not encountered the issue before
