### ISSUE TITLE
Site: Dead link

### ISSUE THREAD

**Issue by za3k** [SquidDev-CC/CC-Tweaked#1855]
In getting started, http://www.computercraft.info/forums2/index.php?/topic/15033-computer-basics-i/ is now a dead link.

**Comment by fatboychummy** [comment]
From what I hear, Dan is working on getting a read-only version of the forums back up and running again, but that may take a bit of time.

In the meantime, it may be worthwhile to use an archive link, something like:

https://web.archive.org/web/20230210010158/http://www.computercraft.info/forums2/index.php?/topic/15033-computer-basics-i/

Edit: The Wayback Machine unfortunately didn't properly save the image links on the page.
