### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by swinzy** [SquidDev-CC/CC-Tweaked#1859]
Hi team, I've been trying to load https://tweaked.cc website and it seems like it's not accessible anymore?

It was still fine a couple of days ago.

Can anyone load it?

**Comment by fatboychummy** [comment]
Checked myself, also can't access it. Looked in discord and it looks like quite a few people are also unable to access. It's not just you.

Left ping running while I went to grab some stuff, seems twelve99 is responding that it's unreachable.
```
PING tweaked.cc (173.249.23.137) 56(84) bytes of data.
From anonymous-ic-359969.ip.twelve99-cust.net (62.115.33.119): icmp_seq=18 Destination Host Unreachable
From anonymous-ic-359969.ip.twelve99-cust.net (62.115.33.119): icmp_seq=25 Destination Host Unreachable
From anonymous-ic-359969.ip.twelve99-cust.net (62.115.33.119): icmp_seq=75 Destination Host Unreachable
From anonymous-ic-359969.ip.twelve99-cust.net (62.115.33.119): icmp_seq=94 Destination Host Unreachable
From anonymous-ic-359969.ip.twelve99-cust.net (62.115.33.119): icmp_seq=118 Destination Host Unreachable
From anonymous-ic-359969.ip.twelve99-cust.net (62.115.33.119): icmp_seq=148 Destination Host Unreachable
From anonymous-ic-359969.ip.twelve99-cust.net (62.115.33.119): icmp_seq=155 Destination Host Unreachable
From anonymous-ic-359969.ip.twelve99-cust.net (62.115.33.119): icmp_seq=188 Destination Host Unreachable
^C
--- tweaked.cc ping statistics ---
207 packets transmitted, 0 received, +8 errors, 100% packet loss, time 210979ms
```

**Comment by SquidDev** [comment]
It appears my VPS provider is having issues, so the server is down entirely. I've contacted support, but have no estimate when this will be resolved.

**Comment by Kxuan** [comment]
@SquidDev The website has been down for about 24 hours.

If you don't mind, I can upload a backup of the site to GitHub Pages to keep the documentation accessible to others and delete it when tweaked.cc is back to work.

The backup is downloaded via `wget -m` on June 10th. So the content should be good.

**Comment by DaleFoley** [comment]
Reminder that wayback machine could be useful here if you really need to access the docs.

**Comment by SquidDev** [comment]
All CC-related services should now be migrated to my new VPSs. Please let me know if there are any further issues.
