### ISSUE TITLE
wiki issue

### ISSUE THREAD

**Issue by EntityinArray** [SquidDev-CC/CC-Tweaked#1870]
what's the measure for time here? ms, s, ticks?
https://github.com/cc-tweaked/CC-Tweaked/blob/819a4f7231a2d661d854e59b180498d61c14c914/projects/core/src/main/java/dan200/computercraft/core/apis/OSAPI.java#L189

**Comment by Wojbie** [comment]
Alarms use ingame time of day. Ingame time of day is a number in the range [0.0, 24.0) that does not have a unit. 

EDIT: Tho if one really wanted they could consider it ingame hour?

**Comment by SquidDev** [comment]
As @Wojbie mentions, this uses in-game time, which is effectively hours. I've added a link to `os.time` in e188f1d3fa2eabf3c3d78eb50e780e2c616e24f7, which explains this a little better.
