### ISSUE TITLE
(Resolved) Chats Randomly Just Stop Working + Computers Restarting on Server Restart.

### ISSUE THREAD

**Issue by EyemSoReel** [SquidDev-CC/CC-Tweaked#1877]
### Minecraft Version

1.21.x

### Version

1.111.0

### Details

So on my server, we only use simple voice chat and the pocket computer chat to communicate, but we're having issues with the chats on the computer randomly stopping

So I already increased the size of my radius for the wireless modems, I have a cell tower in my town that I built at a medium height with a Advanced Computer with a wireless monitor and an advanced Monitor on the right side, I do Monitor Right Chat Host (Name) and I can usually connect to the chat from the pocket computers across the whole town but out of no where all my pocket computers reset and when we try to join back to the chat it says "Looking up (Hostname).... Failed"    

this is very frustrating as we need the chat to stay active until the server resets... speaking of that, is there not a way to make it where the computers don't reset when you leave a singleplayer world or when a multiplayer server restarts, we have a lot of computers we use to display information across a base and they're frustrating to have to all reset every restart.

**Comment by Lupus590** [comment]
> speaking of that, is there not a way to make it where the computers don't reset when you leave a singleplayer world or when a multiplayer server restarts, we have a lot of computers we use to display information across a base and they're frustrating to have to all reset every restart.

A file called `startup` in the root of the drive will be automatically run when the computer starts.

I'm not sure about the chat program just randomly stop working. There is a bug report for computers timing out when ticks pause, do you have a mod that makes backups in your modpack? See #1876

**Comment by fatboychummy** [comment]
Building on Lupus' response, you can use `shell.run` to run another program from your `startup.lua` file:

```lua
shell.run("monitor right chat host epic_chat")
```

As for it randomly stopping: My assumption is either the chunk is being unloaded (*everything* in an unloaded chunk stops, including CC computers), or the issue linked above.

Also, do note that wireless modems have a maximum range. If you leave that range, you will not be able to connect to the chat room. Upgrade to ender modems when you can! They have infinite range.

**Comment by EyemSoReel** [comment]
so if I do startup shell.run("monitor right chat host epic_chat") ? or how do I get that to auto start everytime cause seems dope

also I found some chunk loading mods that should let me keep the chunk even after server restart!

**Comment by EyemSoReel** [comment]
So I was using a regular wireless modem and I just crafted the ender modem and I downloaded a chunk loader mod to the server, but now I need to get the computer startup working so when we restart the server all the computers reboot to the proper program.

Some are just paint files we designed that are saved to floppy disks and some tell time, some connect to the chat, one hosts chat... 

simple stuff really, just dont know lua and Chat GPT isnt good at working with computer craft lua yet

**Comment by EyemSoReel** [comment]
Okay I had Chat GPT help me get the startup working

It was "edit startup"

then the command you gave me with an edited group name

then for the chunks I ended up using a Chunk Loader Mod on the server.
