### ISSUE TITLE
Turtle Chunk Loader

### ISSUE THREAD

**Issue by SteveMan67** [SquidDev-CC/CC-Tweaked#1883]
I am suggesting this because whenever you set a turtle to work, it has to be within simulation distance otherwise it stops working. What I am suggesting is making the turtles automatically load the chunks around them, making you able to just leave them running. This could be an option to turn on or off.

**Comment by Lupus590** [comment]
Possible duplicate of:
* #161 
* #850 
* #1483

**Comment by SteveMan67** [comment]
For some reason they didn't show up when I searched
