### ISSUE TITLE
Server crash when using a mining turtle.   (All the mods 10 pack)

### ISSUE THREAD

**Issue by IBuildVans** [SquidDev-CC/CC-Tweaked#1891]
### Minecraft Version

1.21.x

### Version

cc-tweaked-1.21-forge-1.111.0.jar

### Details

[crash-2024-07-03_21.59.52-server.txt](https://github.com/user-attachments/files/16092977/crash-2024-07-03_21.59.52-server.txt)

When trying to use the 'tunnel' command with a standard turtle, the server crashes as soon as the turtle moves.  Repeated several times.   This in in the All the Mods 10 pack version 0.7.   It also happened with version 0.6 of the modpack.

**Comment by SquidDev** [comment]
Thanks for the report! This appears to be the same issue as #1881, which is fixed in dev, but not released yet.

**Comment by IBuildVans** [comment]
You are welcome!   I will watch for a released update.  Thank you for the
info.
