### ISSUE TITLE
Game Crash after Start a Turtle

### ISSUE THREAD

**Issue by Schaury** [SquidDev-CC/CC-Tweaked#1892]
### Minecraft Version

1.21.x

### Version

1.111.0

### Details

Hello there, I seem to have found a mistake. I am currently playing MC version 1.21.1 with the modloader NeoForge version 21.0.52. 
Every time I load a program into a turtle or write one myself, Minecraft crashes. This also happens with the standard routines of the mod itself. 
Minecraft delivers the following: 
The game crashed whilst ticking block entity
Error: java.lang.NoClassDefFoundError: net/neoforged/neoforge/common/ToolActions

Exit code -1

Crash report attached for analysis

Greetings and keep up the good work!

[crash-2024-07-04_19.54.17-server.txt](https://github.com/user-attachments/files/16101887/crash-2024-07-04_19.54.17-server.txt)

**Comment by SquidDev** [comment]
Thanks for the report! This appears to be the same issue as #1881, which is fixed in dev, but not released yet.

**Comment by Schaury** [comment]
Thanks 😊😊

Jonathan Coates ***@***.***> schrieb am Do., 4. Juli 2024,
20:03:
