### ISSUE TITLE
What happend to the IRC channel

### ISSUE THREAD

**Issue by wolfieboy09** [SquidDev-CC/CC-Tweaked#1899]
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/105564186/dc1d3be9-bcad-4140-a96f-bc0595e74fe5)

I went to the IRC channel to ask a question, and I get taken here FROM THE HOME PAGE OF tweaked.cc
![image](https://github.com/cc-tweaked/CC-Tweaked/assets/105564186/e71a066e-de76-4589-b7f8-5e218e3b2d97)

**Comment by piprett** [comment]
It looks like EsperNet's webclient is not working. The IRC channel however, works as expected. Find yourself an IRC client, such as The Lounge or hexchat, and join #computercraft.

**Comment by SquidDev** [comment]
Asked about this in the `#help` channel on EsperNet, and it sounds like they've decommissioned the web client. I've updated the docs in 1d45935a257cee7aee4347cc24153c86cc7cc052 to mention using desktop clients, and suggest KiwiIRC as an alternative web client, though it's not a perfect replacement.
