### ISSUE TITLE
[Fabric 1.14 | 1.82.3] Startup Crash

### ISSUE THREAD

**Issue by Diamondman121314** [SquidDev-CC/CC-Tweaked#190]
I'm currently using the latest Fabric version of CC: Tweaked and after the recent update, it seems to crash the game during the loading process before the client starts. I do have a [crash log](https://gist.github.com/Diamondman121314/a2021e338a172ada7f5c0e21e828bf22).

**Comment by SquidDev** [comment]
Looks like it didn't upload an obfuscated build. That's a little worrying.

**Comment by SquidDev** [comment]
Hopefully fixed in [1.82.4](https://minecraft.curseforge.com/projects/cc-tweaked/files/2703457). Looks like Loom was acting up a little bit.
