### ISSUE TITLE
Version 1.111.1 is not published to Maven

### ISSUE THREAD

**Issue by Rover656** [SquidDev-CC/CC-Tweaked#1901]
Hi, just a quick report to let you know that version 1.111.1 is not published on your maven at the moment, and as such it is not possible to depend against CC: Tweaked at runtime.

No rush or pressure, just making this issue so that you are aware :)

Thank you!

**Comment by SquidDev** [comment]
I recently moved the maven server to [a new domain](https://github.com/cc-tweaked/CC-Tweaked?tab=readme-ov-file#using). Just to check, are you using the new one?

**Comment by Rover656** [comment]
Aha I missed the change from squiddev.cc/maven to maven.squiddev.cc - my apologies, and thank you!
