### ISSUE TITLE
Crash on opening to friends with World Host mod (Fabric 1.21 Loader 0.16.0)

### ISSUE THREAD

**Issue by Knito58** [SquidDev-CC/CC-Tweaked#1902]
### Minecraft Version

1.21.x

### Version

1.111.1

### Details

I added the "World Host" mod and upgraded the Loader Version to 0.16.0. The world runs nicely and all turtles work well.
The crash happens after hitting the button "open to friends" and in the following menu then "open" it.

https://pastebin.com/nzCbXyag
[crash-2024-07-14_08.52.26-server.txt](https://github.com/user-attachments/files/16215898/crash-2024-07-14_08.52.26-server.txt)

The Fake Player Network Handler seems to hate me for doing this.

**Comment by SquidDev** [comment]
Thanks for the report! This appears to be caused by World Host not handling Fabric's fake player API. Could you [report this on their issue tracker](https://github.com/Gaming32/world-host/issues) instead?
