### ISSUE TITLE
[1.21] Neoforge Game does not start with latest Mod Version

### ISSUE THREAD

**Issue by Periam** [SquidDev-CC/CC-Tweaked#1903]
### Minecraft Version

1.20.1

### Version

cc-tweaked-1.21-forge-1.111.1.jar

### Details

when launching the game the same does not start/

![image](https://github.com/user-attachments/assets/92449197-8125-452a-979f-708951a65880)

[crash-2024-07-15_10.45.06-fml.txt](https://github.com/user-attachments/files/16235459/crash-2024-07-15_10.45.06-fml.txt)

[debug.log](https://github.com/user-attachments/files/16235466/debug.log)
[latest.log](https://github.com/user-attachments/files/16235467/latest.log)

**Comment by MuteTiefling** [comment]
Same issue here. Glad to upload more logs, but it seems that's already quite well covered

**Comment by SquidDev** [comment]
I'd recommend switching to Fabric for now. NeoForge has yet to release a stable build for 1.21, so will see frequent API breakages (see also #1881). I'm on holiday right now, so this is unlikely to be fixed any time soon.

**Comment by MuteTiefling** [comment]
Thanks for the response. Enjoy the holiday!

**Comment by whatthedrunk** [comment]
Thanks for the update while you are away. We will just remove it from atm10 till you get back.
