### ISSUE TITLE
Crafting Duplication Issue with Crafty Turtles

### ISSUE THREAD

**Issue by axhar005** [SquidDev-CC/CC-Tweaked#1918]
### Minecraft Version

1.21.x

### Version

1.111.1

### Details

Crafting Duplication Issue with ComputerCraft Turtles

I have encountered an issue with crafting using turtles, where the items used in the crafting process are duplicated. Here is a detailed explanation of the problem:

When I attempt to craft an item using a turtle, such as a stone sword, the materials required for the recipe are not consumed properly. Instead, the turtle produces the crafted item without using up the materials.

For example, if I place a stick and two cobblestones in the turtle's inventory and use the turtle.craft() function, the turtle successfully crafts a stone sword. However, the cobblestones are not consumed in the process. As a result, I still have the original cobblestones in the turtle's inventory along with the newly crafted stone sword.

In this specific example:

    The selected slot is 1.
    Cobblestone is placed in slot 8 and slot 12.
    The stick is placed in slot 16.

**Comment by SquidDev** [comment]
Thanks for the report! Hah, this was a silly one.
