### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by Devilswarchild** [SquidDev-CC/CC-Tweaked#1921]
### Minecraft Version

1.20.1

### Version

1.112.0

### Details

[Crash report ](https://mclo.gs/dSySXNN)

[Latest Log](https://mclo.gs/7jNJ8fx)

[Debug Log](https://mclo.gs/jS15kmj)

[My Modpack](https://www.curseforge.com/minecraft/modpacks/minecolonies-dimensional-adventure)

steps:

update cc tweaked to latest in and launch the game

expected behavior: Not to crash.

**Comment by Devilswarchild** [comment]
rolling back to 1.111 resolved the issue for now

**Comment by SquidDev** [comment]
Thanks for the report. This appears to be an issue with colony4cc — they're mixing in to some code that has changed in the latest version, so that will need updating.

```
[31Jul2024 19:02:39.037] [Render thread/FATAL] [mixin/]: Mixin apply failed colony4cc.mixins.json:MixinPocketServerComputer -> dan200.computercraft.shared.pocket.core.PocketServerComputer: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field upgrade was not located in the target class dan200.computercraft.shared.pocket.core.PocketServerComputer. Using refmap colony4cc.refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field upgrade was not located in the target class dan200.computercraft.shared.pocket.core.PocketServerComputer.
```

**Comment by SquidDev** [comment]
I'm pretty confused by their mixin. The source on GitHub appears to be a few years old, but it's very much not clear what [this function](https://github.com/uecasm/colony4cc/blob/8838524390487b8a6d2ab6fb2828a7022c8bb284/src/main/java/nz/co/mirality/colony4cc/mixin/MixinPocketServerComputer.java#L28) is meant to do.

**Edit:** Oh, it adds a *new* peripheral on the bottom. Oh, that's hella cursed.

**Comment by Devilswarchild** [comment]
Im going to reference this git issue in their issue tracker
