### ISSUE TITLE
disk no longer shows in auto fill with new disk

### ISSUE THREAD

**Issue by MinecraftedGaming** [SquidDev-CC/CC-Tweaked#1922]
### Minecraft Version

1.20.1

### Version

1.112.0

### Details

_(right now there is no way for me to upload a log here due to issues with current setup)_
I was using cc:tweaked and when I updated it from 1.111 to 1.112 disk drives stopped working. when I did the `peripherals` command it shown the disk drive but when trying to use the `edit` command the auto fill only would show `edit rom/` and never shown `edit disk/`  upon downgrading back to previous version it still wouldn't show till I ran `edit disk/test` then `edit disk/` finally was in autofill. even after deleting all files it would show. when gabbing a new disk from 1.111 it shows disk in auto fill.
sorry I couldn't get a log file but I tried explaining as best as I could. I don't think its caused by upgrading but could be.

1. run instance with cc:t 1.111 (might not be related)
2. make world (don't grab computer or disk yet) _(or anything)_
3. update cc:t to 1.112
4. grab computer, disk, and disk drive
5. attempt to have autofill show disk (it wont show it)

**Comment by SquidDev** [comment]
Hi! Thanks for the report. I'm afraid I'm unable to reproduce this at all — the disk appears to be mounted correctly, and shows up in auto-complete.

Would you be able to try to reproduce this in a fresh Minecraft installation with just CC:T installed?

If you can get find a way to get hold of your logs from your current setup, that would be incredibly useful.
