### ISSUE TITLE
HTTP/0.9 support

### ISSUE THREAD

**Issue by WindClan** [SquidDev-CC/CC-Tweaked#1927]
Currently, CC:Tweaked is lacking HTTP/0.9 support. If it were added it would allow access to more web servers.

A use case for this would be allowing people to write their own HTTP socket servers easily to server code that is generated on the fly without setting up PHP or Node.js.

**Comment by zyxkad** [comment]
HTTP/1.x protocol are still simple and human readable. And a lot languages include http server as their standard library, so there should have no difficulty to use it. Meanwhile HTTP/1 also support tls encrypt for safty.

**Comment by SquidDev** [comment]
This is probably going to be quite a bit of work (Netty doesn't support HTTP 0.9), for next to no benefit. HTTP 1.x is a very simple protocol to implement, most languages have an existing library for adding support for it, and failing that one can always put it behind a reverse proxy like Nginx.
