### ISSUE TITLE
1.14 fabric server crash on startup

### ISSUE THREAD

**Issue by spyguy26** [SquidDev-CC/CC-Tweaked#193]
- Minecraft version: 1.14
 - CC: cc-tweaked-1.14-1.82.4
 - fabric version: fabric-0.2.7+build.127

to reproduce simply put cc tweaked on a fabric dedicated server and launch the server 

here is the log https://gist.github.com/spyguy26/d0502bc9dae644f02ca0d509a61481fc

thank you for your time!

**Comment by chukleberryfinn** [comment]
Same issue. Easy to produce. Commenting and following thread for fix.
