### ISSUE TITLE
ReadHandle.readAll behaviour differs from documentaiton

### ISSUE THREAD

**Issue by sashafiesta** [SquidDev-CC/CC-Tweaked#1931]
### Minecraft Version

1.20.1

### Version

1.109.6

### Details

The documentation says that the [ReadHandle.readAll (docs)](https://tweaked.cc/module/fs.html#ty:ReadHandle:readAll) returns nil when the cursor is at the end of the file.
In fact, in this case, the method returns an empty string.
So
```lua
handler.readAll()
print(type(handler.readAll()))
```
Prints `string`, when it should print `nil`

So there's probably a mistake in the documentation or a bug.

**Comment by sashafiesta** [comment]
ReadWriteHandle.readAll seems to be affected too

**Comment by SquidDev** [comment]
Thanks for the report! I have corrected the docs in 34a2fd039f419cc53efc99968190e193eb263628.

Binary handles (`rb`) used to return `nil` if they reached the end of the file, while text handles (`r`) returned an empty string. As of the unification of file handles in CC:T 1.109, both will always return an empty string. This matches the behaviour of PUC Lua, and I think generally is less confusing.
