### ISSUE TITLE
Vector Dot Returns Number Product Documentation

### ISSUE THREAD

**Issue by Zelaux** [SquidDev-CC/CC-Tweaked#1932]
### Minecraft Version

1.20.1

### Version

1.122.0

### Details

https://github.com/cc-tweaked/CC-Tweaked/blob/mc-1.20.x/projects/core/src/main/resources/data/computercraft/lua/rom/apis/vector.lua#L119
![изображение](https://github.com/user-attachments/assets/c032cc76-7867-4d83-bb86-ce3e69cbab84)

https://tweaked.cc/module/vector.html#ty:Vector:dot
![изображение](https://github.com/user-attachments/assets/f8edc682-6a06-4e61-94cd-fecb4af40e78)

**Comment by Wojbie** [comment]
Hey could you explain a bit what issue are you reporting here?

I am guessing use of "self" here might be a bit unclear to some users. Is that the issue?

**Comment by Zelaux** [comment]
This function returns number, not a Vector

**Comment by Zelaux** [comment]
Dot product is number
