### ISSUE TITLE
Allow bucket as tool

### ISSUE THREAD

**Issue by auroraanna** [SquidDev-CC/CC-Tweaked#1939]
Turtles can empty filled buckets they carry with (`turtle.place()`) but they can't pick up fluids into empty buckets in their inventory.

If we look at the fluid_storage peripheral, they can only transfer fluids from one container to another, never actually having the fluid in their inventory.

Sometimes the you want to move fluids from a container too far away. The turtle can't have both of them be adjacent and therefore not transfer fluid. Mods allow for moving fluid with pipes but these don't work across dimensions for example and can't always be programmed.

I propose making turtles able to have a bucket as a tool. This way they should be able to put fluids from adjacent blocks or fluid containers into the bucket and empty it out the other way too.

**Comment by zyxkad** [comment]
I believe turtle already can fill bucket with water, just do `turtle.place()` with an empty bucket

**Comment by SquidDev** [comment]
They definitely should be able to ([we even have a test for it](https://github.com/cc-tweaked/CC-Tweaked/blob/aa8078ddebf8c6b54fc33b090eefd43b34bc3fe7/projects/common/src/testMod/kotlin/dan200/computercraft/gametest/Turtle_Test.kt#L152)). If it's not working, would you be able to upload a log auroraanna, just so I can see if there's any other mods doing odd things.

**Comment by auroraanna** [comment]
oh, i did not read the documentation for place() and therefore thought i could only place things. i did not try executing place() with an empty bucket on an adjacent fluid. excuse me
