### ISSUE TITLE
Chat command duplicating message glitch

### ISSUE THREAD

**Issue by 07Productions** [SquidDev-CC/CC-Tweaked#1941]
### Minecraft Version

1.20.1

### Version

I am using 1.18.2 for minecraft (it doesn't let me select it) V 1.101.2

### Details

This happens when I host to chatroom servers and join both of them, my messages start duplicating

![image](https://github.com/user-attachments/assets/33dcd8b4-ca67-4558-b189-2e311b56d407)

**Comment by 07Productions** [comment]
In addition to this I found out messaging from two different chatrooms still show up regardless of chatroom name

**Comment by SquidDev** [comment]
> This happens when I host two chatroom servers 

Sorry, just to clarify here, are you hosting these servers on the same computer or different ones?

**Comment by 07Productions** [comment]
> > This happens when I host two chatroom servers
> 
> Sorry, just to clarify here, are you hosting these servers on the same computer or different ones?

Different computers, two computers which are servers and two which are connected to separate servers

**Comment by Wojbie** [comment]
Could you provide more information about your setup? A screenshot how it's cabled or is it wireless? What commands you run on which computers and in which order.

**Comment by 07Productions** [comment]
> Could you provide more information about your setup? A screenshot how it's cabled or is it wireless? What commands you run on which computers and in which order.

It is all wireless, the two servers are put away not too far, one uses the command "chat host name1" and the other server does "chat host name2", then the two chat computers join, one joins name1 using "chat join name1" and the other uses "chat join name2", however, after the second computer joins separate chatroom the text starts to duplicate and is displayed in the other chatroom.

**Comment by SquidDev** [comment]
Thank you for the extra information, that's very helpful.

This definitely shouldn't be *normally* possible. The only way I think this can happen is if the two computers have the same id (which might happen if they've been duplicated in creative). Can you run the `id` program on each computer (or `os.getComputerID()` in the `lua` REPL), and check whether this is/isn't the case?

**Comment by 07Productions** [comment]
> Thank you for the extra information, that's very helpful.
> 
> This definitely shouldn't be _normally_ possible. The only way I think this can happen is if the two computers have the same id (which might happen if they've been duplicated in creative). Can you run the `id` program on each computer (or `os.getComputerID()` in the `lua` REPL), and check whether this is/isn't the case?

Yes! That was definitely the problem, I must have tried to replace both servers in an attempt to fix the issue but used the same block since both servers had an id of "15". 

My apologies for making this mistake.
