### ISSUE TITLE
Pocket computer not updating in left hand

### ISSUE THREAD

**Issue by TotoShampoin** [SquidDev-CC/CC-Tweaked#1945]
### Minecraft Version

1.21.x

### Version

1.112.0

### Details

I will let the title and the video speak for itself first

https://github.com/user-attachments/assets/1496b720-f11d-4ebb-8fd4-bba8b2e4b1d4

My steps here:
1. Open the game
2. Start the advanced pocket computer (no wireless, no ender, no speakers)
3. Type `help` and press enter
4. Leave the ui
5. Swap hands (with F)
6. Right click to go in computer mode
7. Type `programs` and press enter
  1. Exepected: The monitor should display things
8. Swap back, go back in the UI, notice that it did in fact print the programs list, internally
9. Put something in the left hand, and play around with the computer. Notice the updates work in the right hand.
10. Play worm, leave the UI
11. Swap hands
  1. Expected: The monitor should update regardless of the hand
  2. Instead, it only updates in the right hand

It is worth mentioning that:
 - I use arch linux
 - I have other mods (but I tried removing those, it still bugs)
 - I have another advanced computer and a turtle powered on (but I tried turning them off, it still bugs)
 - I did not update to 1.21.1

[latest.log](https://github.com/user-attachments/files/16661685/latest.log)

**Comment by TotoShampoin** [comment]
Duplicate: #1944

**Comment by SquidDev** [comment]
Thanks for the report! Hah, that's an ... interesting quirk of Minecraft's implementation!
