### ISSUE TITLE
excavate not working. 

### ISSUE THREAD

**Issue by jheugh** [SquidDev-CC/CC-Tweaked#1948]
### Minecraft Version

1.21.x

### Version

cc-tweaked-1.21-forge-1.112.0.jar

### Details

using default excavate command  "excavate 10" and the mining turtle will spin 360 degrees.  Output says Excavating...Returning to surface...Unloading items... Mined 0 items total.    The turtle does not break any blocks.  I have tried standard mining turtle or Advanced turtle with same results.  I have tried with Diamond pick on top slot or Bottom slot with same results.   if coal is in first slot then it will deposit the coal in the chest.  the turtle is setup with chest behind it and stone in front of it. 
Please help, love this mod.  It has always worked for me before.

**Comment by jheugh** [comment]
Minecraft version is 1.21.1 using neoforge-21.1.15  in Published Modpack All the Mods 10  version 10-0.34

**Comment by SquidDev** [comment]
Thanks for the report! I'm afraid I cannot reproduce this in a fresh singleplayer world (tested on ATM 10-0.35, but there shouldn't be any relevant changes from 10-0.34).

Just a couple of things it might be worth checking:
 - If you're on a server, are you within the spawn protection radius?
 - Is the current chunk claimed in any other way? Not sure what (if any) claim mods ATM 10 has.

Can you place the turtle on the ground, start the `lua` program, and then run `turtle.digDown()` and `turtle.forward()`, and then post whether they worked, and if not what message they printed?

**Comment by jheugh** [comment]
Ok, lua turtle.dig(down) says nothing to do here.   
using the default  FTB Chunks claim manager i had the chunk claimed and loaded. 
I went outside the claimed area and the turtle works now  with excavate.

**Comment by jheugh** [comment]
BTW, I created a Party with me as the only member, so the chunk claim says "my party". 
is there a setting to change to allow using the turtle in a claimed/loaded chunk?   
I have never had an issue with doing it this way until now.  
I would love to have my turtle work for me while I am away.

**Comment by Wojbie** [comment]
Looks like this may be symptom of issue detected in #1949 and will most likely be fixed when that issue is fixed.

**Comment by jheugh** [comment]
thank you for looking into it promptly.   
I will wait for the fix.
