### ISSUE TITLE
Turtle FakePlayer reporting Default UUID instead of owning player

### ISSUE THREAD

**Issue by dimaguy** [SquidDev-CC/CC-Tweaked#1949]
### Minecraft Version

1.21.x

### Version

1.113.0

### Details

I am unable to use a turtle's FakePlayer UUID for permission checks, because every time I place one, be it in any gamemode and online/offline mode, it reports itself as the Default UUID given to turtles (0d0c4ca0-4ff1-11e4-916c-0800200c9a66) to my spawn protection mixin for Flan.
[debug.log](https://github.com/user-attachments/files/16674393/debug.log)
[latest.log](https://github.com/user-attachments/files/16674395/latest.log)

**Comment by SirEdvin** [comment]
Hm ... you should use yourself as a source of permission check, turtle should mimic a permission of player that placed them.

**Comment by dimaguy** [comment]
> Hm ... you should use yourself as a source of permission check, turtle should mimic a permission of player that placed them.

that is what I'm doing, the turtle's actions should work under the placing player's uuid, therefore when I'm doing permission checks, it's the player uuid that counts, the turtle should not have a different one

**Comment by SquidDev** [comment]
Thanks for the report! Looks like the update to 1.20.5 (01407544c9903acb12079e9a1600da74857352ad) removed the code that sets the owner on place, should be an easy fix!
