### ISSUE TITLE
Excavate not working with FTB chunk manager claimed chunks. (From ticket#1948)

### ISSUE THREAD

**Issue by jheugh** [SquidDev-CC/CC-Tweaked#1952]
### Minecraft Version

1.21.x

### Version

cc-tweaked-1.21-forge-1.113.0.jar

### Details

Mining turtle cannot mine items if the FTB chunk manager has claimed the chunk. 
creating the turtle as player
placing the turtle as player.
claimed chunk owned by player and loaded
turtle does not mine. 
unclaim  chunk
turtle mines fine.
Moded Minecraft ATM10  V0.36 (w/cc-tweaked-1.21-forge-1.113.0.jar)

**Comment by SquidDev** [comment]
Sorry, just a little confused here. Is this not just the same issue as #1948? Why have you opened it again?

**Comment by jheugh** [comment]
The #1948 was closed and thought to be fixed int the next version.   I am on the next version 113 and it does not apear to be fixed.

**Comment by SquidDev** [comment]
Ahh, I see! CC:T 1.113 was released on the 19th August, so before the fix was made. The fix will be available in the next version.

**Comment by jheugh** [comment]
Ok so 114 is what I am looking for then.
