### ISSUE TITLE
Error running task on computer LuaTable.rawset

### ISSUE THREAD

**Issue by schindlershadow** [SquidDev-CC/CC-Tweaked#1955]
### Minecraft Version

1.21.1

### Version

1.113.0

### Details

ATM10 modpack

Server Log1: https://pastebin.com/raw/DQCNnAJC
Server Log2: https://pastebin.com/raw/t5XAGjUB
Not sure why there are 2 different errors in the logs but they are too large to put in one pastebin

Code running: storageServer.lua https://github.com/schindlershadow/ComputerCraft-Item-Storage-System

Code is very large and complicated, the error seems to come up after certificate exchange maybe when encrypted messages are sent. 
Code uses cryptoNet for handling certs and encryption https://github.com/SiliconSloth/CryptoNet

**Comment by schindlershadow** [comment]
confirmed same error comes up when running the example server and client code in the cryptoNet readme

**Comment by SquidDev** [comment]
Thanks for the report! Oh, that was a very silly mistake.
