### ISSUE TITLE
1.14 client crash

### ISSUE THREAD

**Issue by hugeblank** [SquidDev-CC/CC-Tweaked#196]
This looks similar to #193, but I'm having this issue on a client.
Running CC 1.82.4

https://pastebin.com/MSDcJpgm

**Comment by muizzsiddique** [comment]
Did you download the Fabric API? You might need that.

**Comment by hugeblank** [comment]
🤔 I didn't. I don't have time to test it tonight, but I sure as hell will tomorrow. Thanks @muizzsiddique!
