### ISSUE TITLE
`atan2` works incorrectly

### ISSUE THREAD

**Issue by Renegatto** [SquidDev-CC/CC-Tweaked#1962]
### Minecraft Version

1.20.1

### Version

1.113.0

### Details

`atan2` returns incorrect results, different from a results of a standalone lua (and from online calculators).

## Expected behavior
Checked with my local `lua` v5.3.6 and in online caluclators, all agree with this:
```lua
atan2(0.72999052539834, -0.68345726481518) -- returns 2.3232845658174
```
## Actual behavior
While in CC: Tweaked I get this:
```lua
atan2(0.72999052539834, -0.68345726481518) -- returns 0.63057157635225
```

**Comment by SquidDev** [comment]
Thanks for the report. I'm afraid I'm not able to reproduce this at all — I get the same result as expected.

![image](https://github.com/user-attachments/assets/70222ec0-bc57-4f61-8347-bbbc9de0d265)

This is very odd, as CC's Lua VM [just uses Java's built-in `atan2`](https://github.com/cc-tweaked/Cobalt/blob/1b4ade20d3f229f4365b173458641d98122f1e74/src/main/java/org/squiddev/cobalt/lib/MathLib.java#L76) implementation, so you'd expect this to be correct! Would you be able to upload your logs? Just in case you're running an odd JVM version or something.

**Comment by Hex4dec** [comment]
You called atan, not atan2: (from qalc)

```
> atan(0.72999052539834, -0.68345726481518)

  warning: Additional arguments for function arctan() were ignored. Function can only use 1 argument.
  arctan(0.72999052539834) ≈ 0.6305715764
```

Lua ignores excessive arguments.

**Comment by Renegatto** [comment]
@Hex4dec that's not the case, I ran literally the same file in both cases.

@SquidDev 
Here is my java version:
```
openjdk 11.0.14.1 2022-02-08
OpenJDK Runtime Environment (build 11.0.14.1+1-Ubuntu-0ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.14.1+1-Ubuntu-0ubuntu1, mixed mode, sharing)
```

Will try to upload logs.

**Comment by Renegatto** [comment]
> You called atan, not atan2: (from qalc)
> 
> ```
> > atan(0.72999052539834, -0.68345726481518)
> 
>   warning: Additional arguments for function arctan() were ignored. Function can only use 1 argument.
>   arctan(0.72999052539834) ≈ 0.6305715764
> ```
> 
> Lua ignores excessive arguments.

You are right, that was `atan` in both cases, not `atan2`.
I've missed the fact that Lua 5.3 transition
> math.atan2 -> math.atan

is not supported in CC:Tweaked.

Anyway, there is no bug, thanks! :+1:
