### ISSUE TITLE
issues with shaders 

### ISSUE THREAD

**Issue by C00P2009** [SquidDev-CC/CC-Tweaked#1967]
### Minecraft Version

1.21.x

### Version

1.113.0

### Details

hi there i spoke with the guys on the iris discord as having an issue when shaders enabled the advanced screens in a multiple config  glitches out real bad they suggested to log with you guys to see if it can be fixed
![Screenshot 2024-09-05 175019](https://github.com/user-attachments/assets/4c67ff76-1757-4445-8a36-49b5c50a675d)

**Comment by SquidDev** [comment]
Thanks for the report! I suspect this is an issue with our detection of Iris — we currently look for Oculus, but this will need updating now that Iris natively supports NeoForge.

**Comment by C00P2009** [comment]
OK cool thanks for fast response having to not use shaders right now lol
