### ISSUE TITLE
Speaker incorrect item ID and missing fields

### ISSUE THREAD

**Issue by TachyonicSpeed** [SquidDev-CC/CC-Tweaked#1977]
### Minecraft Version

1.21.x

### Version

1.109.6

### Details

I am not sure if this report is appropriate as it is a compatibility issue relevant only to minecraft version 1.4.7. 

 When installed along with Immibis's Peripherals version 52.1.2 and computercraft 1.5 the speaker gets Immibis's Peripherals' peripheral id and is missing all its functions.

![2024-09-16_06 48 42](https://github.com/user-attachments/assets/6af89ef8-800c-4a88-a1b4-d93335a1d59b)
![2024-09-16_06 48 46](https://github.com/user-attachments/assets/6fe59a97-893c-4a41-827a-a45657b9843f)
![2024-09-16_06 48 54](https://github.com/user-attachments/assets/492d6faf-764b-4c00-9cc8-bbca3641e2ce)
![2024-09-16_06 49 12](https://github.com/user-attachments/assets/903171e7-917c-4b70-a2b6-c277d68ba155)
![2024-09-16_06 49 18](https://github.com/user-attachments/assets/5d200056-5dd7-4af3-9f98-83d1f72bcbf4)

**Comment by SquidDev** [comment]
Thanks for the report. I'm afraid this is expected — the 1.4.7 only backports some functionality of the main mod (mostly around the Lua environment). This means a lot of other functionality (such as CC:T's speakers) won't be present.
