### ISSUE TITLE
I found a typo: keys contains both scrollLock and scollLock

### ISSUE THREAD

**Issue by Codenade** [SquidDev-CC/CC-Tweaked#1980]
### Minecraft Version

1.20.1

### Version

1.113.1

### Details

* Open any advanced computer's shell.
* Type `lua`
* Type `keys.sc` and find `scollLock` followed immediately by `scrollLock` in completions (navigate with up / down arrow keys)

**Comment by SquidDev** [comment]
Thanks for the report! Unfortunately this is intended behaviour — we fixed the spelling of `scollLock` a while back, but still need to maintain the incorrect spelling(s) for backwards compatibility with older programs.

https://github.com/cc-tweaked/CC-Tweaked/blob/e9aceca1de0283ff7830d82d8f14875c881007fe/projects/core/src/main/resources/data/computercraft/lua/rom/apis/keys.lua#L142-L145
