### ISSUE TITLE
Font atlas is messed up in a slightly annoying way

### ISSUE THREAD

**Issue by hatkidchan** [SquidDev-CC/CC-Tweaked#1987]
### Minecraft Version

1.20.1

### Version

1.113.1 (present in previous ones)

### Details

A picture is worth 1000 words
![image](https://github.com/user-attachments/assets/aaa8d021-181d-4f86-8d20-c340c83824cc)

**Comment by hatkidchan** [comment]
While we're at it, can we also extend character 0x80 to fill entire cell like so? 
![image](https://github.com/user-attachments/assets/62945ed6-0566-453d-b0cf-c8948bbcfd10)

**Comment by hatkidchan** [comment]
Nevermind I just realized that CC actually uses 6x9 font and space between characters is unused :/

**Comment by SquidDev** [comment]
Yep. Each character has a 1px border around it to prevent rendering artifacts (see https://github.com/dan200/ComputerCraft/issues/300 and https://github.com/dan200/ComputerCraft/pull/367). It's not clear whether this is actually needed on recent versions of the game (the rendering code has changed a lot), but loathe to change the font texture again :).
