### ISSUE TITLE
[Suggestion] Increase default space limits for computers and floppy disks

### ISSUE THREAD

**Issue by sashafiesta** [SquidDev-CC/CC-Tweaked#1990]
This suggestion might be controversial, but I think it worth try proposing.
I propose increasing Floppy Disk space limit to 320K (Like in 5¼-inch double sided floppy, 40 tracks, 8 sectors)
And also increasing Computer space limit to 10M (Like in IBM PC/XT stock Seagate ST-412 hard disk)
(or probably to 5M like in IBM 5440 for PDP-11s)

This would help CC:Tweaked enjoyers develop their project on servers with default CC:Tweaked settings (the majority of servers)
Also, It'd provide some compatability with existing capacity standards (125K disk drives never made sense for me. It's not enough even for copy-ing rom into!)

Disk drives were introduced in ComputerCraft 1.2 for Minecraft 1.0 (Minecraft 1.0 was released Nov 8, 2011, more than a decade ago)
Server owners were mostly using 160-500GB hard drives back then. Today, hard drives are dirt cheap, SSD disks got much cheaper, so I don't think storing computer data would be a large problem. To consume 20GB of server disk capacity, one would need to craft and fill 2048 computers!(more than a double chest of computers!).
I think increasing default space limits would help players while not hurting server owners.

**Comment by SquidDev** [comment]
Afraid I'm going to mark this as won't fix for now. I might revisit this if/when #1580 is implemented (it doesn't make sense for computers to have more memory than hard drive space), but for now I'm happy with the current limits.
