### ISSUE TITLE
[Question] Changing quantity of fuel u get per burnable!

### ISSUE THREAD

**Issue by ArsiTheFox** [SquidDev-CC/CC-Tweaked#1993]
Want to know if there is a setting u can change to change the amount of fuel u can get from a burnable resource to fine tune the cost of running a turtle.

**Comment by SquidDev** [comment]
No, afraid not. CC's fuel levels are given by the burn time of the item, so currently the only way to change the fuel given would be to change the burn time of the item.

**Comment by ArsiTheFox** [comment]
> No, afraid not. CC's fuel levels are given by the burn time of the item, so currently the only way to change the fuel given would be to change the burn time of the item.

Can't you add a system to set the percentage that the burn value returns?

**Comment by ArsiTheFox** [comment]
Like adding a config called "Efficiency" and u input a percentage float??

Like for Coat will give 80 blocks or 1600 ticks of burn
So you input Efficiency 50 it will make coal only give 40 blocks??
So half efficiency

**Comment by Lupus590** [comment]
Why do you want this feature?

**Comment by ArsiTheFox** [comment]
> Why do you want this feature?

Just giving ideas for servers to tune costs for use of the turtles. not demanding for it or anything xP
