### ISSUE TITLE
Strongly recommend add turtle.detectLeft() and turtle.detectRight() 

### ISSUE THREAD

**Issue by wuyoui** [SquidDev-CC/CC-Tweaked#1994]
Strongly recommend add `turtle.detectLeft()` and `turtle.detectRight() `
It‘s reasonable and useful

**Comment by Lupus590** [comment]
```lua
function turtle.detectLeft()
  turtle.turnLeft()
  local detected = turtle.detect()
  turtle.turnRight()
  return detected
end
```

**Comment by SquidDev** [comment]
Afraid I'm not going to add this. I want to keep the turtle commands consistent (for instance, if there's a `detectLeft` we should also have an `inspectLeft`, `suckLeft`, `digLeft`, etc...), and definitely don't want to go down that route.

**Comment by Lupus590** [comment]
Also, it's really easy to implement in user code.

**Comment by wuyoui** [comment]
Thanks for your reply,Also I know it's easy to implement in user code,but if I want to know what's on both sides,turtle need to turn&turn even if there is nothing,It wasted a lot of time.
Unfortunately,it did not planned,I have implemented it using javassist for myself,just detect and inspect,As for suck and dig,it's illogical,and doesn't fit the player's logic.
