### ISSUE TITLE
NullPointerException; Crashed after I threw Pocket Computer on the ground, now world is softlocked

### ISSUE THREAD

**Issue by EndDragon438** [SquidDev-CC/CC-Tweaked#1997]
### Minecraft Version

1.20.1

### Version

1.113.1

### Details

CRASH REPORT:
https://bytebin.lucko.me/zmsi7RAgId

Important Bit: 
`java.lang.NullPointerException: Cannot invoke "dan200.computercraft.shared.pocket.core.PocketServerComputer.getLevel()" because "computer" is null`

I had a basic GPS network setup with Ender Modems, and a Pocket Computer looped into that network. I dropped the Pocket on the ground and my game crashed. Now the world won't load with the same NullPointerException.

Using a custom modpack, who's modlist I can provided if needed.
I believe https://github.com/cc-tweaked/CC-Tweaked/commit/cbe075b001c46cee95e00b8151f59f86203a03ac may be related, it was mentioned in #1912

**Comment by SquidDev** [comment]
Thanks for the report! This appears to be an issue with the VS Addition mod. The code in question has been deleted on their end (https://github.com/xiewuzhiying/VS-Addition/commit/01f0bedd4161098cd5a0794477b44aba0a5f4e7c), so I guess this should be fixed in the next version.
