### ISSUE TITLE
Bug when using the mining turtle and it mines a certain ore

### ISSUE THREAD

**Issue by RedBullSlurpie** [SquidDev-CC/CC-Tweaked#2]
When using the mining turtle, it works great, however when it mines a certain ore, "Dye Ore" from a mod called "PattysMoreStuff", it doesn't drop dye like it should, it drops the ore, but the ore, has a no texture icon. When you, (yourself) mine the ore, it drops dye like it should, only seems to be when the turtle mines the ore, it doesn't mine correctly. If i place the no textured Dye Ore the turtle mines, and I break it myself, it drops dye like normal. Not a game breaking bug, just letting you know.

**Comment by SquidDev** [comment]
This is technically an issue with PattysMoreStuff (see StuffTheChickenMC/PattysMoreStuff#4). However, it should be possible to work around it on my end.
