### ISSUE TITLE
Pocket Computer Dimension Transit - Blank Screen

### ISSUE THREAD

**Issue by RacerDelux** [SquidDev-CC/CC-Tweaked#2004]
### Minecraft Version

1.21.x

### Version

1.113.1

### Details

Using a Pocket Computer, if you have a program running that displays anything, and you change dimensions, the screen will go blank and will not display anything until the Pocket Computer is restarted.

In my tests, my Pocket Computer is always in the hotbar, though not focused. I am using the framework "Basalt" to show the UI which runs on a loop to refresh the UI. I don't think this is related, but just in case I am including that.

This is 100% repeatable, though not game breaking. I can still right click the Pocket Computer and see the screen again. This just affects the screen that you see when just holding it in your hand passively.

**Comment by SquidDev** [comment]
Thanks for the report!

> the screen will go blank and will not display anything until the Pocket Computer is restarted.

From my testing, any change to the terminal's contents should cause it to appear again (for instance, typing or terminating a program). Can you confirm that's the case, otherwise there might another bug hiding here!

**Comment by RacerDelux** [comment]
> From my testing, any change to the terminal's contents should cause it to appear again (for instance, typing or terminating a program). Can you confirm that's the case, otherwise there might another bug hiding here!

You are absolutely right, interacting with the terminal in any way (even just right clicking anywhere) will cause it to work again. So it looks like right now it just needs user interaction after a dim hop to get around the issue. Seems like it would be a small bug hopefully!
