### ISSUE TITLE
1.19.2 Fabric support?

### ISSUE THREAD

**Issue by scottycool64** [SquidDev-CC/CC-Tweaked#2006]
I'm running this mod with my friends, and I'm hoping we could get one of the versions to work on 1.19.2 on fabric?
Thanks!

**Comment by SquidDev** [comment]
For older versions of the game, [CC: Restitched](https://modrinth.com/mod/cc-restitched) should work.

**Comment by scottycool64** [comment]
yeah, was just about to say that
