### ISSUE TITLE
crafting turtles with ingredients that aren't supposed to be used up get used.

### ISSUE THREAD

**Issue by JJSax** [SquidDev-CC/CC-Tweaked#2007]
### Minecraft Version

1.21.x

### Version

1.113.1

### Details

If you have a recipe that has an ingredient that should not leave the crafting grid after the craft, often this is buckets that should use up the fluid, but leave the bucket, and you craft with turtle.craft() or as a crafting peripheral, the bucket gets eaten by the crafting operation.

**Comment by SquidDev** [comment]
Thanks for the report! That was a silly bug :facepalm:
