### ISSUE TITLE
math.atan(x, y) or (y, x)?

### ISSUE THREAD

**Issue by zyxkad** [SquidDev-CC/CC-Tweaked#2009]
[The release](https://github.com/cc-tweaked/CC-Tweaked/releases/tag/v1.20.1-1.114.0) messages seems not match what [the commit](https://github.com/cc-tweaked/CC-Tweaked/commit/304295050728b977366c39f7e4c07c957d8aacac) is saying.

**Comment by SquidDev** [comment]
Fixed in f776b1715055cc825d463a17ec0b9f3264b98ca2.
