### ISSUE TITLE
`monitor_touch` Event Misbehaving with 1x4 Multi-Block Advanced Monitors in 1.114.0

### ISSUE THREAD

**Issue by RainerZufall187** [SquidDev-CC/CC-Tweaked#2010]
### Minecraft Version

1.20.1

### Version

cc-tweaked-1.20.1-forge-1.114.0.jar

### Details

The `monitor_touch` event does not behave as expected when using a 1x4 advanced multi-block monitor in version `cc-tweaked-1.20.1-forge-1.114.0.jar`. This issue is not present in version 1.113.1.

# Steps to Reproduce
1. Set up a 1x4 advanced multi-block monitor (4 blocks in a row horizontally) and connect it to the left side of an advanced computer.
2. Use the example code provided at https://tweaked.cc/event/monitor_touch.html on the advanced computer.
3. Interact with the monitor:
   - Click on the outermost monitor block (furthest from the computer).
   - Click on the monitor block directly adjacent to the computer.

# Observed Behavior
1. Clicking the outermost block results in no output – the `monitor_touch` event does not trigger.
2. Clicking the monitor block directly adjacent to the computer triggers the `monitor_touch` event four times. The coordinates (x, y) reflect the position only within the individual monitor block that was clicked, rather than the full 1x4 multi-block monitor.

# Expected Behavior
- The `monitor_touch` event should trigger correctly for any block within the multi-block monitor.
- The coordinates (`x, y`) should reflect the position within the entire monitor (1x4).
- The event should be triggered only once per click.

# This issue does not occur in `cc-tweaked-1.20.1-forge-1.113.1.jar`, where the same setup behaves as expected.

**Comment by SquidDev** [comment]
Thanks for the report!

**Comment by kevinunger** [comment]
Same with 1x2 monior or 2x2 or any other setup. Only the "monitor_touch" events of the closest monitor next to the turtle / advanced computer are pulled. No other events are fired as well (Checked with os.pullEven())

**Comment by kevinunger** [comment]
@SquidDev  You probably already fixed it here https://github.com/cc-tweaked/CC-Tweaked/commit/63bdc2537cbe5d7b731e43e1fe40951b7d1e0950, right? We just need to wait for the relase don't we? :)

**Comment by SquidDev** [comment]
Yep. I'm hoping to get some other bugs fixed first (i.e. #2013), but should be a release soonish.
