### ISSUE TITLE
API to get facing (or direction) for turtle

### ISSUE THREAD

**Issue by IceCola97** [SquidDev-CC/CC-Tweaked#2018]
May add a function called 'turtle.getFacing()', return the current facing direction of turtle.

I checked the source code, and my implement code like this:
```java
// projects/common/.../turtle/apis/TurtleAPI.java
@LuaFunction
public final String getFacing() throws LuaException {
    return turtle.getDirection().toString();
}
```

**Comment by Wojbie** [comment]
Duplicate of #788

**Comment by IceCola97** [comment]
> Duplicate of #788

ok, I'll close the issue
