### ISSUE TITLE
Redstone Relay not recognized by wired modems

### ISSUE THREAD

**Issue by Shadowfire86** [SquidDev-CC/CC-Tweaked#2020]
### Minecraft Version

1.21.x

### Version

1.114

### Details

I'm on the Direwolf20 1.21 pack, and maybe I misunderstood the usage of these, but I assumed they were a peripheral, but neither the wired modems nor computers recognize it via cable. (yes, I had a modem on the computer AND the redstone relay when I attempted to activate it)

**Comment by Lupus590** [comment]
Did you right click the modem and get a chat message with the peripheral name?
Did you wrap it with that peripheral name?

**Comment by SquidDev** [comment]
Thanks for the report! Looks like some code got lost when merging the changes between 1.20 and 1.21, should be an easy fix.

**Comment by Shadowfire86** [comment]
You're Welcome, and glad to hear that I was helpful and that a fix shouldn't be difficult.
