### ISSUE TITLE
Allow turtles to do "fake player" actions

### ISSUE THREAD

**Issue by chuman72486** [SquidDev-CC/CC-Tweaked#2025]
## Useful information to include:
 - Explanation of how the feature/change should work.
 - Some rationale/use case for a feature. My general approach to designing new features is to ask yourself "what issue are we trying to solve" and _then_ "is this the best way to solve this issue?".

It could be useful for a turtle to be able to automate certain actions, such as being able to open a door or push a button.  Some blocks need to be clicked on with an item to do their intended function.  If the turtle could do player click actions, including right-click and sneak-right-click while "holding" an item, it could open up a ton of new possibilities for turtles.

Something simple like turtle.click(), turtle.clickUp(), turtle.clickDown(), with arguments to specify if the selected inventory item should be "used" on the target, and if it should be done while "sneaking".
For server admins, a config option to enable/disable "fake player" actions by computers and turtles should be included.

**Comment by Wojbie** [comment]
Related: https://github.com/cc-tweaked/CC-Tweaked/issues/125
