### ISSUE TITLE
Add more "Advanced" versions of blocks, or even something better than Advanced.

### ISSUE THREAD

**Issue by chuman72486** [SquidDev-CC/CC-Tweaked#2026]
## Useful information to include:
 - Explanation of how the feature/change should work.
 - Some rationale/use case for a feature. My general approach to designing new features is to ask yourself "what issue are we trying to solve" and _then_ "is this the best way to solve this issue?".

As the title suggests, more versions of existing items and peripherals.

Advanced Printer - Has slots to carry up to 4 ink colors, allowing it to print in multiple colors. (API updated to include setTextColor() and will print in the selected color if ink is available)

Ultimate Printer - Has slots to carry 16 ink colors or an Ink Cartridge (see below), allowing it to print in all 16 available colors, if ink is available in the selected color.

Ink Cartridge - An item crafted from Black, Cyan, Yellow, and Magenta dye, along with a material for the case. to be placed into the Ultimate Printer, allowing it to print in any color.  Ink Cartridge will drain as it is used and will need to be replaced periodically.

XL Ink Cartridge - Same as Ink Cartridge, but needs 2 of each of the four dyes and the resulting cartridge can last twice as long.

Advanced Drive - Able to hold multiple disks and mount them all the same as if you had multiple separate Drives.  This can include being able to hold multiple music disks and use playAudio on a specific disk.  Adds an Event for when a music disk finishes playing.

Ultimate Monitor - Able to use setTextScale(0.25) for an even sharper image.  Able to implement fonts, such as bold, italics, underline, etc.  Sprite drawing function, maybe? If so, also the ability to write text at as an overlay at any TextScale, without having to change the monitor's overall TextScale (draw a text of different sizes anywhere on the screen, independent of the monitor's cursor position and TextScale setting)

Flat-Panel Monitor - Same as a regular Monitor, but behaves like a Sign. When placed on top of a block, it will appear as a flat panel with a post behind it and a stand at the bottom. Due to the shape, it has a couple fewer vertical lines available to allow space for the stand. It'll merge with other Flat-Panel Monitors the same way a regular Monitor does, with the stand automatically adjusting to be at the center of the overall Monitor and multiple stands if the Monitor is 4 blocks wide or wider. They can also be mounted on the side of a block, the same as a Sign, then taking up the full block height and width, but only as thick as a regular Sign. If placed on the bottom of a block, it'll behave like the first version, but the mount will hang from the block above. If a floor mounted Monitor and ceiling mounted Monitor connect, the stands will also connect, forming a stand extending the full height and mounting at both the top and bottom. As a peripheral, it can connect through its stand or it's back side when wall mounted, kinda like how wireless modems connect.

Flat-Panel Monitor will also have Advanced and Ultimate versions. 

Wireless Terminal - Basically the Monitor equivalent of a Pocket Computer.  It's able to be redirected to from a regular computer or turtle's `term.redirect()` function.  This way you can put a computer somewhere, connect all your peripherals, networks, etc.  Add a wireless/ender modem to the computer and sneak-right-click the Wireless Terminal to the modem to bind it.  The computer will now see the terminal as if it were a monitor and can redirect its terminal to it, or just write/print to it as it would a regular monitor.  The Wireless Terminal is crafted with a Wireless Modem, but can be upgraded with an Ender Modem for unlimited range and cross-dimension use.

Advanced Wireless Terminal - Same as above, but color screen.

Ultimate Wireless Terminal - Same as above, with the features of Ultimate Monitor.

Ultimate Computer - Able to use term.setTextScale().  Able to implement the features of the Ultimate Monitor.  Has an inventory slot that can hold a peripheral block or disk, accessible from peripheral.wrap('inside') or something similar.

Ultimate Pocket Computer - Basically the same as Ultimate Computer + Advanced Pocket Computer, but the added ability to carry more than one upgrade, so it can have a modem, but also other modded upgrades like from Advanced Peripherals, accessible from peripheral.wrap('back') and now "up" and "down" slots.

Ultimate Turtle - Same as Ultimate Computer, but with four upgrade slots to carry multiple tools and peripherals.  Able to use forward(), back(), up(), and down(), to move two steps in one command (effectively moving a double speed), with additional fuel cost.  Added turnAround, to make the turtle turn full 180 degrees, instead of turnLeft/turnRight, uses more fuel than two turnLeft or turnRight commands.

Turtle Fuel Station - Able to hold an inventory of Turtle fuel items and if a Turtle stands on or next to the charger/fuel station, the Turtle will be automatically refueled.  The refuel process is slower than if the Turtle refuels itself from its own inventory, adding 20 blocks of fuel range per tick and gradually consuming the stored fuel items (like how a furnace consumes Coal), but only requires that the Turtle be touching the Fuel Station, meaning the Turtle does not need to carry its own fuel in inventory.  The Turtle Fuel Station can operate on its own, or be connected as a peripheral to a computer/turtle.  While connected, it will have the `inventory` API, so the Computer can push fuel items into it from a nearby chest, etc or the Turtle can pull out fuel items to carry in its inventory.  It can also be interacted with as a regular inventory block, so pipe mods can also insert or remove items and players can right click it to manually insert or remove items.  Optionally, the Fuel Station can set a limit to how much to fuel the Turtle, stopping once the Turtle has a certain about of fuel stored.

Advanced Turtle Fuel Station - Same as above, but can refuel Turtles faster, at 80 per tick.  Can also store twice as much fuel items in its inventory.

Ultimate Turtle Fuel Station - Same as above, but can refuel Turtles even faster, at 320 per tick. Can also store four times as much fuel items in its inventory compared to the basic version.

Also add Cable Facade, an item that can cover network cables with the texture of another block, to help hide network cables in compact builds.  Might also be useful to have colored network cables so you can run multiple wired networks without the cables crossing.  For example a red network cable can only connect to other red cables, peripherals, modems, and plain network cables, they won't connect to other colors. (You can use a plain cable to bridge two colored cable networks)

Also the ability to color the computer and monitor cases.  I'd love to have a blue or maybe a black computer.

**Comment by SquidDev** [comment]
Thanks for the suggestions! I'm afraid I'm not going to add these. I think one of the joys of CC is that it offers simple building blocks that can be combined in complex ways.

For instance, printers already support multiple colours. It requires you to write some code to shuffle items around, but I think that's a good thing — it provides an interesting challenge. Pocket computers are my favourite example of this — they can act as an external keyboard for another computer, they can be converted into an external display for another computer — you just need to write the code for it!

I guess a couple of other issues of note:
 - Dying computers: #1327 and #1348
 - Pocket computer upgrades: #1406 
 - Cable facades: #451 and to a lesser extent #1511. I'd like to add multipart support to cables, but it's quite a tricky thing to get right.
