### ISSUE TITLE
peripheral.call taking a string as a number?

### ISSUE THREAD

**Issue by SethGamer1223** [SquidDev-CC/CC-Tweaked#2036]
### Minecraft Version

1.20.1

### Version

1.114.2

### Details

create a table with a value that is the string name of a peripheral. use peripheral.call to call a action from that peripheral name inside of the table. the code i used:
msg = {
  type = "move",
  to = "sc-goodies:diamond_barrel_0",
  from = "sc-goodies:diamond_barrel_1",
  slotfrom = 1,
  slotto = 5,
  count = 5
}

if msg.type == "move" then
    peripheral.wrap(msg.from)
    peripheral.call(msg.from,"pushItems",msg.slotfrom,msg.count,msg.slotto)
end
errors: argument #1 expected string got number

logs: https://mclo.gs/lwmMh0T

**Comment by zyxkad** [comment]
actually the `#1` argument here reference to what you passed to `pushItems`, which is `msg.slotfrom`

**Comment by SethGamer1223** [comment]
ah crap mb...
