### ISSUE TITLE
Read Only

### ISSUE THREAD

**Issue by BlightPanda** [SquidDev-CC/CC-Tweaked#2038]
Hello im playing on a server and i can import files into the computer but only to / if i try to move them to rom/ or edit anything in rom/ it says its read only, i cant find anything on this through google and the staff on the server have no idea as well, is it a permissions issue on the server itself, does a directory on the server need to be changed from read only or is this something i can fix in the mod myself?

**Comment by piprett** [comment]
The `rom` directory is **R**ead **O**nly **M**emory. You can't write to it.

**Comment by BlightPanda** [comment]
Ahh okay that makes sense, thanks.
