### ISSUE TITLE
Other HTTP request methods

### ISSUE THREAD

**Issue by osmarks** [SquidDev-CC/CC-Tweaked#21]
Functions similar to http.post, but for PUT, DELETE and others, in order to access REST APIs more easily.

**Comment by JasonTheKitten** [comment]
Mine still only supports like 7 methods...

**Comment by SquidDev** [comment]
For reference, that's `GET`, `POST`, `HEAD`, `OPTIONS`, `PUT`, `DELETE`, `TRACE`. The only other REST method I've seen in common usage is `PATCH`, but one can always use `X-HTTP-Method-Override` for that.
