### ISSUE TITLE
Turning on a pocket computer makes it yellow (looks like an advanced computer)

### ISSUE THREAD

**Issue by SzDavidHUN** [SquidDev-CC/CC-Tweaked#211]
Minecraft 1.14.1
CC: cc-tweaked-1.14.1-1.82.4.jar
Fabric-loader: 0.4.7+build.147-1.14.1+build.4

Steps to reproduce:
1. Get a not andvanced pocket computer. 
2. Right click it to turn on.
Now the computer turned yellow, looks like an advanced computer.
Shut it down to turn it back to gray.
The UI is correctly the gray UI for regular pocket computers.

**Comment by SquidDev** [comment]
Fixed in bb138326dfeac74253ff5d91046f220e4dfa87b8.
