### ISSUE TITLE
[1.12.2-1.83] rednet.lookup() is requiring two strings instead of only one

### ISSUE THREAD

**Issue by HydrantHunter** [SquidDev-CC/CC-Tweaked#224]
MC 1.12.2 / CC:T 1.83

What's happening:
When doing a rednet host lookup with rednet.lookup("someName") the lookup crashes out with the error "Bad argument #2 to 'lookup' (expected string, got nil) instead of returning one or more host IDs.

What's expected:
In prior versions of CC:T and CC the second string was optional for lookups, and the lookup would return the IDs of any computers hosting "someName", regardless of the second value on the host.

Thanks for all the effort put into CC:T - it's not unnoticed.

**Comment by SquidDev** [comment]
Thanks for picking this up - terribly sorry about this! Tried to make sure all the tests were correct, but evidently missed one.
