### ISSUE TITLE
Prevent defining environment-level globals in programs

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaked#233]
@lupus590 recently added a [strict mode](http://lua-users.org/wiki/DetectingUndefinedVariables) to mbs's shell (SquidDev-CC/mbs@031d3c766354415e4b6bb647691c88af187e7aaa), which raises an error when a program tries to define a global within its environment table.

It'd be nice to integrate something similar into the CraftOS shell. Most of the time defining globals is a bug in the program's code (due to someone missing a `local`). That said, in the interest of backwards compatibility, it's probably worth leaving off for the time being.

I'm also not 100% happy with the error message in the attached PR (sorry Lupus :p), so suggestions are welcome!

**Comment by JasonTheKitten** [comment]
settings: general.enable_globals

**Comment by Wojbie** [comment]
Considering this would be just a option (that most sane people would turn on in instant) i would say having just `"Attempt to create global " .. tostring(name)` as error would make it simple to scour the file to find it. No need for that extra info about _G in my opinion. Also to comment of preceding comment erroring with this optional setting on would make more sense then just writing a warning afterwards.

**Comment by lupus590** [comment]
The error blames the caller so you should be getting the line number from that.

As for the message of the error, I agree that it's not the best message. I'll make suggestions if I come up with any.
