### ISSUE TITLE
Improved pretty-printing within the REPL

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaked#234]
The current pretty-printer within the REPL is a little naive: it tries to use `textutils.serialise`, and if that errors just uses `tostring`. While that's sufficient for basic things, it rather stinks when you're trying to dump an object with methods, or recursive table.

It might be worth writing a custom pretty-printer for the Lua REPL, which handles functions, recursive tables, and coroutines (most likely just by `tostring`ing them).

A couple of neat things we could try out:
 - [Colours](https://raw.githubusercontent.com/SquidDev-CC/mbs/master/img/00-lua-serialise.png) <sub>Oh no, more mbs</sub>!
 - Some level of "layout awareness". So short tables (such as `{ 1, 2, 3 }` are displayed on one line, rather than 5.
 - Length limits - if we've got a massive table or string, there's no point trying to print the whole thing, as it'll just take a long time and not fit on the screen! It would be nice if we could restrict how much we print in one go.
    That said, this is kinda complex to do well - mbs tries to be smart, and still leaves a lot to be desired. A naive implementation (only do the first 20 keys, 1000 characters, etc...) may be sufficient.

**Comment by JasonTheKitten** [comment]
I do like MBS, but I do not want it built in. As far as too many entries go, perhaps if we had a textutils.pagedPrint-type approach but with a cancel button or timeout.

**Comment by SquidDev** [comment]
@JasonTheKitten While I'm not proposing copying the entire mbs pretty-printer, I'm curious as to which bits you object to?

**Comment by JasonTheKitten** [comment]
Nothing really. I really like the alternate autosuggest highlighting. I don't exactly like how it's REPL adds out[x] in front of every line if I remember correctly - You could just have 1 line to indicate this is return values

**Comment by JasonTheKitten** [comment]
I am thinking for REPL with my pagedPrint idea, we would probably print as we go, instead of pre-serializing everything.

**Comment by hugeblank** [comment]
don't mind me, for the sake of keeping track, #195 is relevant in this issue as well
