### ISSUE TITLE
Configuration missing in Fabric?

### ISSUE THREAD

**Issue by cooper-anderson** [SquidDev-CC/CC-Tweaked#243]
I started messing around with Fabric and the new version of CC:Tweaked recently and noticed that I could not find where to customize the configurations. Back with Force, it was in the `config/computercraft.cfg` file but I see that it does not exist in this case. I thought that maybe it still works with it but just does not create the file if it does not have to, so I tried copying over the old one and nothing happened. Does Fabric not support features like this yet? I noticed that there is the ClothConfig API that might circumvent this issue. Is there a temporary way to modify the configs before this feature is readded? Thanks!

**Comment by SquidDev** [comment]
I was rather waiting until a standardised system made its way into Fabric API, but that's looking increasingly unlikely.

I'm afraid I'm no longer maintaining the Fabric version due to limited time and motivation, so I'm not going to look at this.
