### ISSUE TITLE
Mining Turtle just destroys blocks - does not mine

### ISSUE THREAD

**Issue by Knito58** [SquidDev-CC/CC-Tweaked#244]
- Minecraft version 1.14.2
 - CC: Tweaked version  1.83.1
 - Fabric API v0.3.0 build 180 <<== Probably causing the bug

Take a mining program from pastebin and mine with it. 
Example: pastebin get cWwJ0FYW Mine
The turtle just destroys the blocks and does not harvest anything. The same program did work nicely for me when the fabric api was lower.

Advantage: The turtle's internal storage gets never filled up.

I believe that bug was already in fabric api build 179.

**Comment by SquidDev** [comment]
I'm afraid I'm no longer maintaining the Fabric version due to limited time and motivation, so this will not be fixed. I'm unable to reproduce on the Forge 1.14.2 version, so I suspect this is a Fabric-specific bug.

**Comment by Knito58** [comment]
Am on Forge for 1.14.3 now. There's no mining Problem as you assumed with 1.14.3-1.83.1. Close confirmed.
