### ISSUE TITLE
Crash "Could not execute entrypoint stage 'main'"

### ISSUE THREAD

**Issue by FireHead996** [SquidDev-CC/CC-Tweaked#250]
- Minecraft version: 1.14.1
 - CC: Tweaked version: 1.82.4
 - Fabric version: 0.4.8+build.155
 - Fabric API version: 0.3.0+build.184
 - Detailed reproduction steps: Clean setup with installed Fabric and Fabric API. MC without CC:T runs ok. After adding CC:T to mods folder, I got this crash report:
[crash-2019-06-14_10.59.59-client.txt](https://github.com/SquidDev-CC/CC-Tweaked/files/3289991/crash-2019-06-14_10.59.59-client.txt)

This issue might be related to the #269 issue on Fabric bug tracker, but I'm using vanilla MC launcher instead.

**Comment by el0c** [comment]
Not sure if you've figured this one out already, but another few mods I play with had the same crash on startup.

Epicurean Gastronomy's patch notes said: 

> fix a crash from Fabric registry sync due to how mixins handled re-registering items

Maybe that points you in the right direction if you haven't taken a look yet.

**Comment by SquidDev** [comment]
I'm afraid I'm no longer maintaining the Fabric version due to limited time and motivation, so this will not be fixed.
