### ISSUE TITLE
tab key doesn't work

### ISSUE THREAD

**Issue by absolument** [SquidDev-CC/CC-Tweaked#256]
- Minecraft version 1.14.2
 - CC: Tweaked version 1.83.1
 - Forge version 26.0.32

Tab key work fine for MC (I can assign it to controls and work fine), but not when focused on computers. So I cant use autocomplete (I verify autocomplete is set to true), and cant write tabulation.

Also, I test with this program : 
`repeat
a = {os.pullEvent("key")}
print(unpack(a))
until false`

It confirm that an event is fired when any key from my keyboard is pressed, excepted Tab (and Escape, as espected)

(I have a dell keyboard sk 8115 French AZERTY)
![dell-sk-8115-0j4629-j4629-keyboard-azerty-french-usb-navy-blue-wired- 2 -43358-p](https://user-images.githubusercontent.com/17803584/59567058-acb43300-9068-11e9-9ec5-686e729577ac.jpg)

**Comment by Mishqutin** [comment]
Same here. I think it may be something with Minecraft adding accessibility settings and navigating with Tab key.
