### ISSUE TITLE
Fails to use any CC item

### ISSUE THREAD

**Issue by UmutAlihan** [SquidDev-CC/CC-Tweaked#261]
- Minecraft version -> forge-1.14.2-26.0.32.jar   
 - CC: Tweaked version -> cc-tweaked-1.14.2-1.83.1.jar

 - Detailed reproduction steps: 
Client and Server sides have the same mod version.
When server starts, logs show these problematic lines. (Everything esle just fine)

<details>
<summary>related log outputs:</summary>

- [29Jun2019 10:55:58.588] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Starting minecraft server ver$
- [29Jun2019 10:55:59.341] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:comput$
- [29Jun2019 10:55:59.342] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:comput$
- [29Jun2019 10:55:59.347] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:comman$
- [29Jun2019 10:55:59.354] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:turtle$
- [29Jun2019 10:55:59.355] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:turtle$
- [29Jun2019 10:55:59.361] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:speaker
- [29Jun2019 10:55:59.381] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:disk_d$
- [29Jun2019 10:55:59.406] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:monito$
- [29Jun2019 10:55:59.420] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:monito$
- [29Jun2019 10:55:59.444] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:printer
- [29Jun2019 10:55:59.450] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:wirele$
- [29Jun2019 10:55:59.451] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:wirele$
- [29Jun2019 10:55:59.460] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:wired_$
- [29Jun2019 10:55:59.482] [Server thread/WARN] [computercraft/]: No data fixer registered for block entity computercraft:cable
- [29Jun2019 10:56:00.928] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Starting version check a$
- [29Jun2019 10:56:01.003] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Loading properties
- [29Jun2019 10:56:01.005] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Default game type: SURVIVAL
- [29Jun2019 10:56:01.006] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Generating keypair
- [29Jun2019 10:56:01.141] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Starting Minecraft server on $
- [29Jun2019 10:56:01.226] [Server thread/INFO] [net.minecraft.network.NetworkSystem/]: Using epoll channel type

</details>

In the game any CC item placed shown as below:
(and when I click, server crashes)
![2019-06-29_11 35 38](https://user-images.githubusercontent.com/16688836/60381827-66e16c80-9a63-11e9-9ef2-4de3e0f678fc.png)

**Comment by SquidDev** [comment]
The crashing on a server is a known bug - it should be fixed on the 1.14.3 version. 

Textures not showing up is very curious though - it might be worth trying to see if it persists on the 1.14.3 version. If so could you attach your full (client side) logs - there should be some other useful debugging information further down.

**Comment by UmutAlihan** [comment]
Upgrading to 1.14.3 solved all problems. Currently it works fine. 
Thank you very much. You are really the best, because of contributions to community <3
