### ISSUE TITLE
Server crash - ExceptionInInitializerError: null 	at dan200.computercraft.shared.turtle.core.

### ISSUE THREAD

**Issue by ProsperCraft** [SquidDev-CC/CC-Tweaked#265]
#85  Useful information to include:
 - Forge- forge-1.14.3-27.0.23
 - CC: cc-tweaked-1.14.3-1.83.1
 - Detailed reproduction steps: make a world, make a turtle, name the turtle, delete the world, copy your playerfiles over to the new world, and place your old turtle in the world, label it, and tell it to tunnel. crash.

Crash report- 
https://gist.github.com/ProsperCraft/1bda7c11f4792f454c09a2a5453f7016

Debug log-
[debug.log](https://github.com/SquidDev-CC/CC-Tweaked/files/3360147/debug.log)

**Comment by SquidDev** [comment]
> copy your playerfiles over to the new world

Oh gosh, why?

Thankfully, I don't think this is actually the issue - looks like Lycanites mobs doesn't like some of the questionable decisions I made. Hopefully should be quite simple for me to fix.

**Comment by ProsperCraft** [comment]
We copied the playerfiles over because we are playing Mine and Slash and player leveling is a huge deal, and the equipment you loot.

Reset the world because we added quite a few new and newly working mods and needed the worldgen.

As an update- removing lycanites stops cc from crashing.  He is happily mining now.
