### ISSUE TITLE
[1.14.3] Turtle consumes the entire stack of coal even if it only needs 4

### ISSUE THREAD

**Issue by ProsperCraft** [SquidDev-CC/CC-Tweaked#266]
- Minecraft version 1.14.3
 - CC: Tweaked version cc-tweaked-1.14.3-1.83.1
 - Detailed reproduction steps:  Put a stack of coal in a turtle that only needs 2-3 coal then refuel all, it consumes the entire stack.

Expected behavior- eat what it can use and leave the rest.

![2019-07-05_14 11 34](https://user-images.githubusercontent.com/4427684/60743444-dd341200-9f2e-11e9-8830-3824f267a54d.png)

**Comment by SquidDev** [comment]
Hrmr, this appears to be an issue in the original ComputerCraft too, so at least it's not a regression as part of the update.

I guess the best thing to do here would be to refuel one item, and use that as a guess for how many more we need.

**Comment by powerboat9** [comment]
This fixes it #274
