### ISSUE TITLE
Pocket computer disappears when placed in offhand

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [SquidDev-CC/CC-Tweaked#268]
- Minecraft 1.12.2
 - CC: Tweaked 1.83.1

Steps to reproduce:
1. obtain a pocket computer
2. open your inventory
3. place it in your offhand slot
4. close your inventory
5. right click

After around half a second, the pocket computer will disappear without a trace

**Comment by SquidDev** [comment]
I'm unable to reproduce with Forge 14.23.5.2806 and no other mods installed.

I can't think of what would cause this within CC:T's codebase, so I _suspect_ something else is interfering. Some things worth trying:

 - Does it happen with any item in your off-hand, or just pocket computers?
 - Does it happen in a fresh world?

If so, it might be worth removing several mods until you can work out what is causing it.

**Comment by ThizThizzyDizzy** [comment]
Figured it out;
It was a different mod clearing my offhand slot
