### ISSUE TITLE
Backport to 1.7.10?

### ISSUE THREAD

**Issue by Nukley** [SquidDev-CC/CC-Tweaked#269]
Would it be possible to backport this to 1.7.10? Me and my friends are running a minecraft server, and I like this tweaked version more than cc 1.75.

**Comment by SquidDev** [comment]
![](https://squiddev.cc/r/let-it-1.7.10.png "Let it go!")

1.7.10 is 5 years old at this point, and there's been far too many architectural changes since then for this to be feasible. Sorry.
