### ISSUE TITLE
View for Pocket Computers/Printed Pages renders twice

### ISSUE THREAD

**Issue by Inkemann** [SquidDev-CC/CC-Tweaked#271]
When holding a Pocket Computer or a Printed Page it is rendered twice, once large, held in both hands (like the vanilla map) and once smaller, held just in the main hand (which is added to the two "regular" hands, rendering three hands).

Steps to reproduce:
1. Get a Pocket Computer or Printed Page.
2. Put it in your currently selected quickbar slot.
3. Observe.

Minecraft Version: 1.14.3
Forge Version: 27.0.13
CCTweaked Version: 1.83.1

**Comment by Inkemann** [comment]
When a shield is in the offhand slot and a Pocket Computer or Printed Page is selected in the main slot, it is rendered twice, too. Both views are the small version, once in the main hand, once in the offhand.

**Comment by SquidDev** [comment]
Looks like this is a Forge bug - I clearly failed to fix things correctly the last time. Woops!

**Comment by SquidDev** [comment]
Should be fixed by MinecraftForge/MinecraftForge#5927.
