### ISSUE TITLE
Turtles can duplicate wired modems and cables

### ISSUE THREAD

**Issue by lupus590** [SquidDev-CC/CC-Tweaked#273]
## Useful information to include:
 - Minecraft version: 1.12.2
 - CC: Tweaked version: 1.81.1
 - Detailed reproduction steps:
get a turtle to place a wired modem (the small one not the full block one)
get the turtle to place a modem cable into the same block space
get the turtle to dig
note that the turtle gets two cables and a modem and that there is still a modem in the world
the turtle can dig again to get a second modem

**Comment by powerboat9** [comment]
#276 
This fixes it

**Comment by SquidDev** [comment]
Curses, should have said "Fixes x" instead.
