### ISSUE TITLE
Turtles cannot be placed

### ISSUE THREAD

**Issue by bruce** [SquidDev-CC/CC-Tweaked#275]
- Minecraft version 1.14.3-forge-27.0.51
- CC: Tweaked version: 1.83.1 (`cc-tweaked-1.14.3-1.83.1.jar`)

Turtles that are placed immediately disappear.

![turtle-disappear](https://user-images.githubusercontent.com/72/61267326-506a2f00-a74c-11e9-8af9-547a196f006a.gif)

Possibly related: if you give yourself a computer in creative and switch to survival mode, it will disappear from your inventory when the crafting table is opened.

**Comment by rangerdude** [comment]
Are you on a server?  If so do you have rights to place there?    Just a thought.

**Comment by bruce** [comment]
@rangerdude Locally running server, connected as an op

**Comment by bruce** [comment]
Also worth noting that I’m not running any other other mods (eg, that might modify permissions)

**Comment by rangerdude** [comment]
@bruce  Is this in more than one block?  
If yes 
Can you break the block and place the turtle above or below it?

Have your tried other areas?  or a different map?   One more thing, can can check to see if there is a block where you placed the turtle and it disappears? Can you walk over it , or does it act like there is a block there?    
Can you place another block there?   in Creative and  Survival?

could you also during your test look at your logs from the server and client.
That might show you something that will help out.
What OS are you running on?   if Linux what user? root?   test under root to see maybe if permission problems.


To many questions :> . I am sure you have done some of these,, but checking on what else there could be.

**Comment by bruce** [comment]
@rangerdude Thank you for helping out! Answers to your questions below.

> Does this happen in more than one block?

Yes; placing on any block seems to exhibit the same behavior.

> Can you break the block and place the turtle above or below it?

I can break the block, but I can't place the a turtle above or below it.

> Have your tried other areas?

Yes, still a problem.

> ... or a different map?

Yes, still a problem.

> One more thing, can can check to see if there is a block where you placed the turtle and it disappears? Can you walk over it , or does it act like there is a block there?

There doesn't appear to be a block there. I can walk right over it.

>  Can you place another block there? in Creative and Survival?

Yes and yes. Notably, in survival the turtle block _does_ disappear from my inventory.

> Could you also during your test look at your logs from the server and client. That might show you something that will help out.

No suspicious output to logs; just seeing normal "Set own game mode to Survival/Creative Mode" lines as I switch game modes.

> What OS are you running on? if Linux what user? root? test under root to see maybe if permission problems.

macOS Mojave 10.14.5. I've run the server with `sudo` with the same results.

**Comment by Auios** [comment]
Also having this issue - except I cannot place _any_ computercraft blocks.
No other mods are installed.
I did all the same tests at @bruce and got the same results.
My OS is Windows 10 as an admin

**Comment by Auios** [comment]
> Also having this issue - except I cannot place _any_ computercraft blocks.
> No other mods are installed.
> I did all the same tests at @bruce and got the same results.
> My OS is Windows 10 as an admin

I was running the mod on both the client and a server. However I switched to just running the world on the client and not connecting to my server. The blocks place just fine now. Something about being on a server it doesn't like.

**Comment by Auios** [comment]
Upon further testing I noticed that other mods were doing the same thing. This must have been a forge issue I concluded. I quickly looked into this. 
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/mods-discussion/2456477-my-modded-servers-modded-block-placing-isnt

A used named `doggstar` at the very bottom said:

> I now got my modded forge minecraft server working. i wasn't calling the universal server, but was calling the vanilla server that is distributed with forge. seems simplisticly stupid, but i was beating my head against a wall for a few hours.
> Note to anyone else having this problem, you need to have the vanilla minecraft server in the same folder as the universal server that you are executing via the java command

Discussing this with my friend @Eagle517 he found:
![Screenshot_5](https://user-images.githubusercontent.com/7435026/61583563-f2509980-ab07-11e9-8436-4097c83a10af.jpg)

The mystery has been solved. @bruce - You need to run the `forge.jar` file, not the `minecraft_server.jar` file

**Comment by SquidDev** [comment]
I'm unable to reproduce. As others have touched on, worth double checking you're running the same Forge and CC:T version on client and server.

If you're still having issues, can you attach your logs for _client and server_?

**Comment by bruce** [comment]
Thank you @Auios (super helpful digging), @SquidDev — I'll give this a shot today and report back.

**Comment by bruce** [comment]
To circle back, it was just me running the wrong server (that is, `minecraft_server` vs `forge`). Thanks again for your help.
