### ISSUE TITLE
Crafty Felling Turtle destroyed by tree growing into same space

### ISSUE THREAD

**Issue by TheDarkPreacher** [SquidDev-CC/CC-Tweaked#278]
## Useful information to include:
 - Minecraft version
 - CC: Tweaked version
 - Detailed reproduction steps: sometimes I can spot a bug pretty easily, but often it's much more obscure. The more information I have to help reproduce it, the quicker it'll get fixed.

Minecraft Version: 1.14.3
CCT Version: 1.83.1
Steps to reproduce: Create crafty felling turtle, place in world, run pastebin get JgRgRK5q aTreeFarm, then run aTreeFarm and follow directions. Turtle will build the base of the tree farm, and then start farming trees. Wait long enough and eventually, a tree will grow that grows into the same space as the turtle, destroying it. 
Currently being used on the All The Creators server, issue reported there as well (https://github.com/AllTheMods/ATC2/issues/19)

**Comment by SquidDev** [comment]
I'm unable to reproduce this on latest Forge.

This is a very odd issue - saplings shouldn't even grow into an area where a turtle already exists. You're not using modded trees at all?

**Comment by TheDarkPreacher** [comment]
can confirm, only using vanilla oak trees, as the server is only using vanilla terrain gen and vanilla trees.

**Comment by SquidDev** [comment]
Bumping up the random tick rate seemed to help reproducing this issue.
