### ISSUE TITLE
[1.14.4] Update please :)

### ISSUE THREAD

**Issue by ProsperCraft** [SquidDev-CC/CC-Tweaked#279]
![49555cf89fe0619b9a1018a2800f8129](https://user-images.githubusercontent.com/4427684/61600276-133eea80-abed-11e9-8629-d88e3f613314.png)

Need 1.14.4 :)

Quite a few mod authors are just posting it to 1.14.3 until Curse adds the 1.14.4 label, and that is working well for me, I just update my old pack and move the files over.

**Comment by ProsperCraft** [comment]
P.S. I can't edit the label.

**Comment by SquidDev** [comment]
Fixed in ccd85eb0556f6aaa134f14871f96ae233567ee17.

**Comment by ProsperCraft** [comment]
Looking forward to a new build :)

**Comment by ProsperCraft** [comment]
The 1.14.4 label  is on curseforge now, if that is what you were waiting for.
