### ISSUE TITLE
Clear all monitors when running /computercraft shutdown

### ISSUE THREAD

**Issue by Lemmmy** [SquidDev-CC/CC-Tweaked#28]
So it doesn't appear shops are running and stuff

**Comment by SquidDev** [comment]
I'm a little iffy on this - I can definitely see the uses of resetting peripherals upon a forcible shutdown, but I've a couple of problems with it:

 - I don't necessarily think that a shutdown should result in a reset. After all, `os.shutdown` and <kbd>C-s</kbd> don't do this. Whilst one is "server" initiated and one is "user" initiated, it does seem a little inconsistent.
 - Determining what peripherals are associated with what computers is hard. Especially when you take into account wired modems (worth noting that the `Computer` class doesn't have any concept of remote peripherals, merely the ones on the 6 cardinal directions). One could just reset every modem on the server, but obviously that's not ideal

**Comment by Lemmmy** [comment]
perfectly valid. we can find workarounds for the shop problem, this just seemed like it may be the nicest way

**Comment by hugeblank** [comment]
Inconsistency aside, one is the literal shutting down of computercraft (AFAIK. I can't seem to find much documentation on it so I could be totally wrong), and one is a single computer shutting down, so maybe it is worth clearing them. Additionally I see the ability for a little fun feature to be put here, where on all terminal displays some sort of "[I am dead](https://i.kinja-img.com/gawker-media/image/upload/s--4UnmYHfu--/c_scale,fl_progressive,q_80,w_800/rowkmwebfngibxpb244h.jpg)" image is shown to make the users aware that computercraft is shutdown. But of course this is all hinging on my assumption of the `/computercraft shutdown` command. :P

**Comment by SquidDev** [comment]
I'm closing this for now, for a couple of reasons:

 - It's not apparent that there's a nice way to solve the aforementioned issues.
 - I don't think there's sufficient demand/need for this feature that it's worth implementing it - especially as any implementation will most likely be quite complex.
