### ISSUE TITLE
[WIP] [Fabric] Porting to 1.14.4

### ISSUE THREAD

**Issue by parly** [SquidDev-CC/CC-Tweaked#282]
I'm currently working on porting the `mc-1.14-fabric` branch to 1.14.4.
When this work is finished, would you accept the pull request for this?
Or is Fabric version no longer supported?
Thank you!

**Comment by lupus590** [comment]
I remember SquidDev saying that fabric was only a temporary thing until forge caught up.

**Comment by SquidDev** [comment]
I'm afraid I'm no longer maintaining the Fabric branch as I just haven't got time and energy to work on it. For the same reason, I don't really want to release other people's work using it - I can't commit to being bug-free and keeping it updated, and so it doesn't seem fair to promise that to users.

That said, I'm more than happy for you to release your work as a separate project <sub>(as long as ComputerCraft's wacky license is followed)</sub> and I can point people towards it.

**Comment by parly** [comment]
I understand. I'll release it later as a separate project.
Thank you for your reply!
