### ISSUE TITLE
[1.14.4] Error loading with for .45 with forges breaking changes.

### ISSUE THREAD

**Issue by ProsperCraft** [SquidDev-CC/CC-Tweaked#283]
Encountered an exception during parallel processing
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError

## Useful information to include:
 - Minecraft version 1.14.4
 - CC: Tweaked version 	cc-tweaked-1.14.4-1.84.0.jar
 - Forge 28.0.45

When this breaks on loading, other mods show up as crashing.

When loaded by itself it makes it to the main menu oddly enough.

[debug.log](https://github.com/SquidDev-CC/CC-Tweaked/files/3485124/debug.log)
[latest.log](https://github.com/SquidDev-CC/CC-Tweaked/files/3485125/latest.log)

**Comment by SquidDev** [comment]
Fixed in a0e72d02c8ceee5fe04de667b9fea96a016e844b / 1.84.1
