### ISSUE TITLE
Inconsistent error message with getfenv()

### ISSUE THREAD

**Issue by Kan18** [SquidDev-CC/CC-Tweaked#284]
## Useful information to include:
 - Minecraft 1.12.2
 - CC: Tweaked 1.84.0
 - using CodersNet modpack
 - Detailed reproduction steps: 
Open a new computer and open /rom/programs/lua. Doing `getfenv(false)` or `getfenv(true)` (or with a table) will show the error message of: 'bad argument: integer expected, got (type)'. `getfenv("test")` (or any other string) will show the error message of: `bad argument: number expected, got string`. 
![image](https://user-images.githubusercontent.com/24967425/62973782-ccf03c00-bde4-11e9-9644-b42241b2bb9e.png) Normal behavior of Lua looks like this: 
![image](https://user-images.githubusercontent.com/24967425/62973824-e42f2980-bde4-11e9-9e62-f00c07c3be5e.png)

**Comment by SquidDev** [comment]
While this is a Cobalt bug, please stop using `getfenv`. If we ever move to Lua 5.3+, it's going to break.

**Comment by Kan18** [comment]
I wasn't depending on `getfenv` but for my sandboxing system I was sandboxing getfenv and setfenv so that malicious programs couldn't escape the sandbox, and I noticed this while looking at error messages.
