### ISSUE TITLE
Missing textures for noisy and crafty turtles [1.14.4]

### ISSUE THREAD

**Issue by ScrambledGamer** [SquidDev-CC/CC-Tweaked#285]
## Useful information to include:
 - Minecraft version : 1.14.4
 - CC: Tweaked version: cc-tweaked-1.14.4-1.84.1.jar
 - Detailed reproduction steps: No steps needed the noisy and crafty turtle (both advanced and normal) are missing some of the textures (for the tools they're suppose to be holding)

**Comment by SquidDev** [comment]
Thanks for the report! This'll be fixed in the next version.
