### ISSUE TITLE
server not launching due to many mod class exceptions(fabric 1.14.4)

### ISSUE THREAD

**Issue by SDUBZ** [SquidDev-CC/CC-Tweaked#286]
this the issue gist i made with log and mod list etc due to many class conflicts https://gist.github.com/SDUBZ/8a121bddf045e26d7234afb321140f29

**Comment by SquidDev** [comment]
I do not maintain the Fabric port - you'll probably want to file this at https://github.com/mystiacraft/cc-tweaked-fabric/issues instead.

**Comment by SquidDev** [comment]
It also appears that the gist is missing the actual log - you may have copied the wrong thing :)
