### ISSUE TITLE
BetterWithMods mod interaction

### ISSUE THREAD

**Issue by za3k** [SquidDev-CC/CC-Tweaked#288]
-Minecraft Version: 1.12.2
-Forge Version: 14.23.5.2838
-Better With Mods Version: 2.30.2-10-27
-ComputerCraft version: CCTweaked 1.81.3

Mining sand with a computercraft turtle using a shovel, it correctly gets one sand block. **But while using an axe or pickaxe, a computercraft turtle gets both 1 sand block (incorrect), and pile of sand items.** The correct behavior is to return 3 "pile of sand" items but no sand block.

Mining wood with an axe correctly gives 1 wood block. Mining wood with a pick correctly gives planks, sawdust, and bark. (A shovel fails, which is ok I guess). I hope that helps narrow things down a bit.

I'm not sure whether CC or BwM needs to make a change, but I suspect CC. I've crossposted to the Better With Mods bugtracker here: https://gitlab.com/BetterWithMods/1.12/BetterWithMods/issues/1336

**Comment by SquidDev** [comment]
Can you try on the latest CC:T version (1.84.0)? It includes a fix for a similar sounding issue (#273), so worth double checking before going any further :).

**Comment by za3k** [comment]
Will do. Had to double check that you're releasing for 1.12, I really appreciate that you are.

Psst also the github releases page and curseforge page don't have jars for any of those versions.

**Comment by za3k** [comment]
Reproduced in CC:T 1.12-1.84.0

**Comment by SquidDev** [comment]
Yeah, sorry - Curse's interface isn't the most intuitive. The panel on the right-hand-side of the main mod page is probably the best way to see the latest files - the actual file page is ... confusing.

Thank you for double checking on 1.84.0 - fix should be released in the next few days.
