### ISSUE TITLE
[1.14.4] Server crash with breaking a lucky block with a turtle.

### ISSUE THREAD

**Issue by ProsperCraft** [SquidDev-CC/CC-Tweaked#294]
- Minecraft version 1.14.4
 - CC: Tweaked version cc-tweaked-1.14.4-1.84.1.jar
 - Detailed reproduction steps: sometimes I can spot a bug pretty easily, but often it's much more obscure. The more information I have to help reproduce it, the quicker it'll get fixed.

https://www.curseforge.com/minecraft/mc-mods/lucky-ores?comment=19 (https://gist.github.com/ProsperCraft/9d629ec47c2f7cd03a27a6feaed5886a)

Guessing this is on luckyores side because they are trying to assign effects to the breaker which isn't a player.

**Comment by SquidDev** [comment]
Yeah, this probably counts as a Forge bug - probably similar to dan200/ComputerCraft#539. Forge needs to stub out some additional methods within the fake player. I'll see if I can get a PR out this afternoon.

**Comment by SquidDev** [comment]
Finally submitted a PR to Forge today, so going to close this.

**Comment by ProsperCraft** [comment]
Not sure what the status of this is, but we had another crash, server fully updated.

https://www.curseforge.com/minecraft/mc-mods/lucky-ores/issues/1

**Comment by lupus590** [comment]
Based on squid Devs previous replies, this is a bug with forge not lucky blocks or CC.

This looks like it's the pull request that he made https://github.com/MinecraftForge/MinecraftForge/pull/6097
