### ISSUE TITLE
turtle.dig() not digging 

### ISSUE THREAD

**Issue by galyfray** [SquidDev-CC/CC-Tweaked#295]
minecraft version:1.12.2
CC:tweaked version :1.84.0

i give me a turtle using JEI in creative test world and try to dig with turtle.dig(), the turtle has  a diamond pickaxe of course.
it always return to me "false Unbreakable block detected" even far from spawn and with the turtle ignore block protection set to true and after a restart.

as there is other mods in my instance a listed them here :

other mods:

- AE2
- avaritia 
- avaritia tweak
- baubles
- better questing 
- better questing book
- Bookshelf
- CC:tweaked
- code chicken lib 
- COFH core/world
- construct's armory
- CT2
- cumcumber library
- extented crafting
- Foam Fix
- gamestage
- iron chest
- item stage
- JAOPCA argiculture/custum/cingularities
- JEI
- mantle mod tweaker
- MTlib
- Mystical agraddition/argriculture
- packaged auto/crafting
- plus TIC
- recipes stages
- redstine flux
- ressource loader
- standar expantion
- thaumcraft
- thaucraft JEI
- thermal cultivation/dynamics / expansion / foundation / innovation
- tikerStages
- tinkers' tool leveling
- tinkers construct
- together forever
- wrapUp
- Zenstages

**Comment by galyfray** [comment]
i've tried with only :

- bookshelf
- CC:wteaked
- CT2
- gamestage
- itemstage
- JEI
- mod Tweaker
- MTlib
- recipeStage
- Ressource loader
- Together Forever
- Wrapup
- zenstages

**Comment by galyfray** [comment]
alright i found were it comes from it seems that the part wich allow turtle to dig over the blocks protection doesn't overrides gamesStage stages then it's kind of fixed sorry for the Issue 
i just a question to ask what is the name of the fake player used in turtle ? after this i will close this issue and again sorry the annoying :)

**Comment by SquidDev** [comment]
So the fake player's name is `[ComputerCraft]` (UUID `0d0c4ca0-4ff1-11e4-916c-0800200c9a66`). 

However, most of the time, turtles will inherit the game profile of the player who placed them, and so will be called `gayfray` instead of `[ComputerCraft]`. Normally, this means progression information will be inherited, but this does not appear to be the case with Game Stages - it looks like this was discussed in Darkhax-Minecraft/Game-Stages#14, but never actually implemented.

**Comment by galyfray** [comment]
fake player can be given stage it has been implemented this is why i was needing the fake player name of the turtle 
it's wrote just here : https://github.com/Darkhax-Minecraft/Game-Stages you need to scroll a bit ^^
Thanks a lot for this info <3
