### ISSUE TITLE
Unable to Collect Lava with Turtle.PlacedDown()

### ISSUE THREAD

**Issue by Riewest** [SquidDev-CC/CC-Tweaked#297]
Currently Playing a custom 1.14.4 pack, and when I call "turtle.placeDown()" with an empty bucket and a lava source block below it does not collect the lava.  I made a pack with only JEI and CCTweaked with the following versions and it still persisted their as well. Happens with both Water and Lava

Forge Version: 28.1.10
CCTweaked Version: 1.84.1
JEI Version: 6.0.0.13

![CCTweakedBug](https://user-images.githubusercontent.com/16376061/65392730-71975f00-dd3d-11e9-8bd3-e1d3c0481131.png)

**Comment by SquidDev** [comment]
It appears that fluid placing/breaking is somewhat broken - it often goes on the wrong side (and in the case of water, goes inside the turtle). I suspect this is due to the 1.14 fluid changes, but I'll look into it.

**Comment by SquidDev** [comment]
This will be fixed in the next release, sorry for the slow fix.
