### ISSUE TITLE
Turtle inventory destroys items while moving

### ISSUE THREAD

**Issue by sewbacca** [SquidDev-CC/CC-Tweaked#298]
## Useful information to include:
 - Minecraft version: 1.14.4
 - CC: Tweaked version: 1.84.1
 - Forge version: 28.1.10
 - Detailed reproduction steps: 
1. Place turtle and refuel
2. type lua and then: "while true do turtle.turnLeft(); turtle.forward() end"
3. take any stack and try to evenly distrubute the stack in turtles inventory with holding the left mouse button.
4. Reaccess the inventory -> Items vanished

**Comment by sewbacca** [comment]
I think it also happens if you place a singel item or stack of items into the inventory. However, the other way arround it might duplicates the item. I didn't tested much.

**Comment by wieselkatze** [comment]
> 
> 
> I think it also happens if you place a single item or stack of items into the inventory. However, the other way arround it might duplicates the item. I didn't tested much.

Can reproduce. If placing new items in the turtle, they seem to stay, but after closing the GUI and opening it again, the item vanished.

**Comment by SquidDev** [comment]
This is most likely a 1.12 issue too, introduced by 75e2845c01532987026ed028e97bab74e274a9dd.
