### ISSUE TITLE
1.12.2 CC:Tweaked Turtles don't respect FTB utils claims

### ISSUE THREAD

**Issue by roger109z** [SquidDev-CC/CC-Tweaked#3]
CC: Tweaked Version: 1.80pr1.3
FTBU version: 4.2.4
This is on the Project </Beta> V2 server
Turtles don't respect claims at all
Steps to replicate:
1. have a turtle try and break a claimed block and he has no issue

**Comment by SquidDev** [comment]
This is a configuration issue with FTBUtilities: fake players are considered an "ally" by default.
