### ISSUE TITLE
CC addon Plethora Peripherals demands ComputerCraft 1.80pr1

### ISSUE THREAD

**Issue by shelbykauth** [SquidDev-CC/CC-Tweaked#30]
With ComputerCraft 1.80pr1, I can use Plethora Peripherals and Peripherals Plus One.  When I disable ComputerCraft and enable CC:Tweaked (1.80pr1.5), making sure that Plethora and PlusOne are still enabled (I'm using Twitch Launcher, Forge 2655, plus several dozen other mods), one of two things happen.  Either 1: ComputerCraft gets reenabled.  Or 2: Plethora gets disabled.  (1: get an error at the end of launch telling me about duplicate mods or 2: get a warning when I try to go into my world with Plethora stuff in it)

I don't know if this is a problem with pr1.5 or with Plethora.  I would really like to use Plethora along with pr1.5, for obvious reasons.

The only other thing I can think of to do what I want to do (connect to chests via wired modem) is to use the "Slightly larger chest" from Extra Utilities (or another solid-block inventory), unless I'm missing something here...

**Comment by SquidDev** [comment]
Right, this is an issue with the Twitch launcher/Curse not having a way to show multiple mods can satisfy a dependency. I've updated the Curse metadata - can you confirm enabling CC:T and Plethora works?

**Comment by shelbykauth** [comment]
Yeah, it is a problem with Twitch.  It was showing Plethora as enabled when the jar was marked disabled.  Had to go to the mod folder to change it to make it work.  But yes, CC:T and Plethora are both enabled, and I don't have to delete the ComputerCraft jar like I thought I would have to.  Thank you kindly for helping me fix this.
