### ISSUE TITLE
Crash with Villager

### ISSUE THREAD

**Issue by Darkere** [SquidDev-CC/CC-Tweaked#304]
This seems to happen when calling placeDown() with a Villager in the same tile. Although I am kind of abusing the fact that placeDown soft harvests plants with Harvest installed so that might be related.

Crash Report: https://hatebin.com/zaacjaynjb

- Minecraft version 1.14
- CC: Tweaked version 1.84.1
Modpack: ATM4 0.1.3

**Comment by SquidDev** [comment]
I'm afraid this is caused by the same underlying problem as #294. There's nothing I can do on CC's end, it's waiting on a fix on Forge.

I've got a PR open, but haven't looked at it for a while.
