### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by yanrenbin** [SquidDev-CC/CC-Tweaked#307]
Building on MacOS Mojave 10.14.6, with Java SE 8u231, failed with the following error. 
I ran "./gradlew build". 

----------------------------------------------------------------
> Configure project :
New Dep: net.minecraftforge:forge:1.14.4-28.1.26_mapped_snapshot_20190912-1.14.3_at_43e649be4ebe4501aed19ce82818d65414ce55a7

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/renbin/Desktop/atlauncher/CC-Tweaked-1.14.4-1.85.0/build.gradle' line: 448

* What went wrong:
A problem occurred configuring root project 'cc-tweaked-1.14.4'.
> java.io.FileNotFoundException: /Users/renbin/Desktop/atlauncher/CC-Tweaked-1.14.4-1.85.0/config (Is a directory)

-------------------------------------------------------------
config is indeed a directory and it seems it has been this way for the past few releases. What am I missing?

**Comment by SquidDev** [comment]
Hrmr, that's very odd. Can you run with `-i` (`./gradlew build -i`, and post the full log in a gist? Would you also be able to post which commit you're on `(git rev-parse HEAD`), just so I can check the build script - currently line 448 really doesn't line up with anything that would _obviously_ cause this issue.

**Comment by yanrenbin** [comment]
I was running it from the folder of the release 1.14.4-1.85.0 downloaded using the tar ball. 
Here is the gist for the log. <script src="https://gist.github.com/yanrenbin/a673cc6ddf6369718924fe7409e1ffba.js"></script>

Building a cloned version of the master or the branch mc-1.14.x worked without a problem. Though,  the branch mc-1.14.x failed once. It seems I had to build the minecraftforge. Although I could not get minecraftforge built successfully, somehow the second time I build mc-1.14.x for CC-Tweaked, it worked without a problem. Not sure exactly why.

**Comment by SquidDev** [comment]
Ahh, I see - it appears the build-script requires that the CC:T source code is in a git repo. I guess most people building it have cloned it, hence this not showing up before.
