### ISSUE TITLE
startup auto-run script runs on all turtles

### ISSUE THREAD

**Issue by McSharidan** [SquidDev-CC/CC-Tweaked#309]
- Minecraft: v1.12.2
 - CC: Tweaked: 1.85.0

Placing a file called "startup" in the root of a turtle, causes it to automatically run that script when the turtle is turned on. With multiple turtles in the same world, just having one /startup script causes the same script to be run on every turtle. It should only be executed on the turtle where the script resides, not across every turtle.
This bug is easily reproducable.

**Comment by SquidDev** [comment]
I'm afraid I'm unable to reproduce on Forge 14.23.4.2749 with just JEI and CC:T installed. 

Just a couple of quick questions:
 - If you run the `id` program on each of the turtles, do the turtles have the same IDs or different ones?
 - Did you place the turtles in creative or survival mode?

If you've got time, it would be great if you could reproduce in a fresh world with just CC:T installed, and zip the save up - just so I can have a look everything locally.

**Comment by johnneijzen** [comment]
it sound like you did not label turtle so all have same id

**Comment by SquidDev** [comment]
@johnneijzen That shouldn't be the case. Turtles should always have unique IDs (unless you copy them in creative mode), irrespective of whether any have been labelled or not.
