### ISSUE TITLE
Add a "horizontal_scroll"

### ISSUE THREAD

**Issue by LDDestroier** [SquidDev-CC/CC-Tweaked#310]
Trackpads are capable of scrolling both vertically and horizontally, and sometimes I wish I could take advantage of that in CC. Adding a separate "horizontal_scroll" event would not interfere with existing programs, and would be useful for programs with scrolling canvases.

**Comment by znepb** [comment]
If this were added, it should definitively be implemented into Paint.

**Comment by SquidDev** [comment]
Sadly I'm not sure this is really possible to implement.

 - On Minecraft 1.12, LWJGL 2 doesn't appear to expose the horizontal scroll at all.
 - On 1.13 and later, LWJGL 3/GLFW *does* expose this information, but Minecraft discards it, meaning we can't listen to it without doing some really horrible hacks.
