### ISSUE TITLE
Is there a wiki for CC: Tweaked in 1.14?

### ISSUE THREAD

**Issue by GrimmDZ** [SquidDev-CC/CC-Tweaked#312]
I would like to see a way to figure out the mod without old videos, that aren't from 1.14. And that don't need testing.

**Comment by lupus590** [comment]
https://wiki.computercraft.cc/CC:Tweaked
Third on Google

**Comment by SquidDev** [comment]
As Lupus says, both [the CC][http://www.computercraft.info/wiki/Main_Page] and [CC:T](https://wiki.computercraft.cc/Main_Page) wiki should be pretty accurate here - there's been a couple of _minor_ changes, but most things should work the same.

I'll try to add some comments on the wiki to show when things are substantially different between versions.

**Comment by SquidDev** [comment]
There is now a page [summarising the major differences](https://github.com/SquidDev-CC/CC-Tweaked/wiki/Incompatibilities-between-versions).
