### ISSUE TITLE
Monitors placed underwater render incorrectly

### ISSUE THREAD

**Issue by WenXin20** [SquidDev-CC/CC-Tweaked#314]
## Useful information to include:
 - Minecraft v1.14.4
 - CC: Tweaked v1.85.0
 - Detailed reproduction steps: 
1. Place a Monitor or Advanced Monitor underwater.
2. Observe water flowing down their sides.

**Comment by lupus590** [comment]
Screenshots help when posting about render issues.

**Comment by WenXin20** [comment]
Here ya go:
![2019-11-20_09 50 38](https://user-images.githubusercontent.com/12000593/69254076-46818e00-0b7b-11ea-886b-8071655a589d.png)

**Comment by lupus590** [comment]
are those flowing water blocks or source blocks?

**Comment by lupus590** [comment]
are those flowing water blocks or source blocks?

**Comment by WenXin20** [comment]
Source blocks

**Comment by SquidDev** [comment]
Thanks for the report, this should be fixed in the next release, which I'm hoping to get out early next week.
