### ISSUE TITLE
Click on Advanced Computer results in "bios.lua:528: attempt to compare number with nil"

### ISSUE THREAD

**Issue by LeMoonStar** [SquidDev-CC/CC-Tweaked#318]
Minecraft version: 1.12.2
CC: Tweaked version: 1.85.1
Forge version: 1.12.2-14.23.5.2768

Whenever I click anywhere within the GUI of an Advanced Computer or Advanced Pocket Computer I get the error `bios.lua:528: attempt to compare number with nil`

![2019-11-29_19 43 06](https://user-images.githubusercontent.com/24989169/69887188-11490e80-12e6-11ea-8d02-7c927b2b6251.png)

I've searched the issues and found nothing like this. It seems like only I have this problem?

**Comment by NullvaIue** [comment]
Also occurs on forge 1.14.4 - 28.1.96 and latest CC release.

**Comment by SquidDev** [comment]
Terribly sorry about this, thank you for reporting! This should be fixed in 0ae70fed13a7be95ff6ca29b8117987bfbb6fe82. I'm currently deploying a release, so this should show up in the next 10 minutes.
