### ISSUE TITLE
Releases JAR files

### ISSUE THREAD

**Issue by redfast00** [SquidDev-CC/CC-Tweaked#32]
It would be pretty cool if there were JARs of the prereleases. Thanks!

**Comment by redfast00** [comment]
Well, oops, didn't google enough: https://minecraft.curseforge.com/projects/cc-tweaked/files

**Comment by SquidDev** [comment]
Yep, beat me to it. The CurseForge downloads are updated relatively often - normally when there's been sufficient changes from the last release.
