### ISSUE TITLE
Open command computer in survival

### ISSUE THREAD

**Issue by RetroAsgardian** [SquidDev-CC/CC-Tweaked#325]
On my server, where I have full op permissions, I can't access Command Computers in Survival mode - I get a message that states `You must be an opped player in creative mode.` But I don't want to have to switch to Creative Mode every time I want to use a command computer.

I think there should be an option in the config file that lets you disable the creative mode restrictions on command computers.

**Comment by SquidDev** [comment]
It's worth noting that command computers just obey the same restrictions as command blocks. Not saying it's not inconvenient at times, but it's also not unprecedented :).

**Comment by lupus590** [comment]
You could use the cloned computer trick to have two computers with the same id, one is your command computer and the other is any other computer type. The two then share a filesystem and can securely message each other that way, you can then have the non-command computer send commands via the file system which the command computer then reads, executes, and then replies via the file system.

You can clone any computer by using the give command setting the new computer's id to that of an existing computer.

**Comment by RetroAsgardian** [comment]
Hm. So I'm assuming there's no way to just check if the `EntityPlayer` is opped?

Also, thanks for that trick! I'll try it when I get the chance.

**Comment by SquidDev** [comment]
@RetroAsgardian Sorry, entirely forgot to respond to the above message. It is possible to do check directly, but I'd rather not. For the time being, I want to keep things consistent with command blocks.
