### ISSUE TITLE
Player / Motion Sensor

### ISSUE THREAD

**Issue by Nisutec** [SquidDev-CC/CC-Tweaked#326]
Please add a Player / Motion Sensor peripheral to the Mod to allow the computer to track nearby players and or Mobs.

**Comment by SquidDev** [comment]
Plethora's entity sensor should provide this functionality already! It's not something I currently want to replicate in CC:T as I'm not sure it thematically fits.

**Comment by Nisutec** [comment]
Works Plethora with the 1.14 ?

**Comment by SquidDev** [comment]
Not yet, no. It's in the pipeline, but also a rather big update and I'm somewhat limited in time & energy right now.
