### ISSUE TITLE
Limiting HTTP

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaked#33]
ComputerCraft added very rudimentary limiting system to the filesystem (a fixed number of handles per computer), but no similar system was added to the HTTP API. It would be nice to add some more fine grained control to the `http` API, to prevent abuse by malicious/badly implemented programs.

One nice thing about HTTP is that, as it is asynchronous, we can delay requests instead of outright rejecting them. I suspect this will be required as many installers/updaters will download multiple files in parallel.

Configuration options could be server wide and per-computer. While the latter is more important (normally it will be a few computers playing up), it may be useful to enforce some global constraints too. If so, we will have to establish some level of scheduling, prioritising requests from computers which don't access the network very often, etc...

## Request limits
These limits are designed to control individual requests. They are not going to prevent abuse of the HTTP API, but should stop people doing insanely stupid things with it.

### HTTP Requests
 - **Max requests:** The maximum number of requests a computer can be making at one time. Additional requests can be pushed to a queue.
 - **Max download size:** The maximum size an incoming response can be before the connection is terminated.
 - **Max upload size:** The maximum size an outgoing request can be.

### Websockets
 - **Max websockets:** The maximum number of open websockets a computer can have. Unlike HTTP requests, it is probably save to error if this limit is reached.
 - **Max packet size:** The maximum size a websocket message can be (incoming and outgoing).

It's also worth noting that many of these options could be configured on a per-domain/per-IP-range level. For instance, you could allow downloading larger files from GitHub, or limit the upload size to Pastebin.

## Rate limiting
While the above has some utility, it doesn't prevent people making lots of requests in a short period of time. Instead, we should also investigate ways of limiting the amount of bandwidth a computer may consume.

--- 

If people have ideas, suggestions or if there's anything else we could look into limiting, do comment!

**Comment by hugeblank** [comment]
An obvious first question: 
What would each of those limits be by default, and would the limits be enabled at all by default?

**Comment by LemADEC** [comment]
We need to limit the request rate and bandwidth usage, at least globally. When a global limit is reached, I would advise to prioritize the 'good' computers. For example, the computer doing the most request/bandwidth throws a LUA exception, and a console log reports it. That way the player and server owners are aware of the issue.

**Comment by nevercast** [comment]
I think its better to rate limit rather than size limit, at least for Websockets but also for HTTP, since large files can just be spread across multiple requests without too much effort. Presumably what you're trying to limit is max concurrent connections, and throughput/rate, from this you can work out how much bandwidth at max a user can occupy per day, for example.

**Comment by SquidDev** [comment]
![image](https://user-images.githubusercontent.com/4346137/125687814-cce3fb8b-ca20-46e0-9cf1-2fceca059038.png)

Some people have pointed out that you can pump some _serious_ numbers using HTTP and a decent host. This would be good to fix next release.

**Comment by ImALolNoob** [comment]
stopping this fully from being abused is like impossible. don't forget about the older version of computercraft on 1.7 etc that have no updates anymore regardless of what the limits are, even if the limits seem abit high limiting it down to under 100mpbs/50mpbs per server is 10x/20x better than having no limit and being able to push a 1 Gbps out of each server hosting provider or many providers :D

**Comment by SquidDev** [comment]
> don't forget about the older version of computercraft on 1.7

Well sure, but that's an issue with _every_ bug. I can only make sure the latest release is as bug-free as possible :p.

**Comment by WarLordN1k** [comment]
> 
> 
> stopping this fully from being abused is like impossible. don't forget about the older version of computercraft on 1.7 etc that have no updates anymore regardless of what the limits are, even if the limits seem abit high limiting it down to under 100mpbs/50mpbs per server is 10x/20x better than having no limit and being able to push a 1 Gbps out of each server hosting provider or many providers :D

That issue with out of DEV builds of CC would have to be fixed in other server side ways ie plugins, mods or network filtering.

**Comment by EntityinArray** [comment]
limiting download and upload size is a dumb idea, that makes streaming audio, playing web radios impossible
size is not the problem, your problem is the bandwitch you allocate to each in-world computer

ratelimiting download and upload speed to ~10 mbit/s per computer (for example) would be enough to elegantly solve abuse, while not limiting legit usecases.
