### ISSUE TITLE
Use a string buffer within textutils.serialize

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaked#336]
`textutils.serialize` (or rather [`serializeImpl`][impl]) currently builds up its result via immediate string concatenation. This means its complexity is quadratic, which isn't fantastic.

While textutils.serialize's performance is not a serious concern, it would still be nice to improve it. The best way to do that would be replacing our concatenation with a classic string buffer and a final concatenation:

```lua
local function serializeImpl( t, tTracking, sIndent, buffer )
    if sType == "string" then
        buffer[#buffer + 1] = string.format( "%q", t )
    elseif -- etc...
end

function serialize( t )
    local tTracking, buffer = {}, {}
    serializeImpl( t, tTracking, "", buffer )
    return table.concat(buffer)
end
```

One other thing to note is that getting the length of a table is O(lg(n)), so it may be worth keeping that around too. However it's probably worth profiling doing so and seeing if it is worthwhile or not.

[impl]: https://github.com/SquidDev-CC/CC-Tweaked/blob/0bcd28e58c8cffc92af75e7bc58da2de681222bb/src/main/resources/assets/computercraft/lua/rom/apis/textutils.lua#L194

**Comment by SquidDev** [comment]
Just had a stab at this, and was unable to find a solution which consistently ended up faster than the naive implementation. Which leaves me slightly worried, as it does question everything I know about Lua performance. Welp.

**Comment by SquidDev** [comment]
If people want to have a look at this themselves, happy to share my benchmarking scripts and various attempts.

**Comment by exerro** [comment]
I had a little go with this and got a pretty good result.
![benchmark-results](https://user-images.githubusercontent.com/2530315/77551758-9f0ac400-6eaa-11ea-87d9-7843b3f53d02.png)
As shown, the new approach is better in every benchmark.

The benchmark script and impl are available [here](https://pastebin.com/Kr9BdBWJ) (`pastebin get Kr9BdBWJ`). See line 174 for changing the benchmarks run, and the tables the benchmarks are run on.
