### ISSUE TITLE
[1.14.4] Server freezing "server detected that a single server tick took"

### ISSUE THREAD

**Issue by Gbergz** [SquidDev-CC/CC-Tweaked#343]
Useful information to include:
 - Minecraft version: **1.14.4**
 - CC: Tweaked version: **1.86.0**
- Forge Version: **28.1.107**
 - Detailed reproduction steps: It's totally random I think or not.. it happens alot or it happens once in awhile i don't know how to exactly re-produce it. But looking at the crash report and then the stacktraces i've finally found a mod there. The only one in my roughly 14 Crash reports, they all have "computercraft" in them. Do CTRL + F and search for "computer" and you'll find the message below in all the crash reports i've listed. Any ideas?

Message in crash report:
[https://gist.github.com/Gbergz/e005c6e47d36d0e66f870c6ab93bbd94](https://gist.github.com/Gbergz/e005c6e47d36d0e66f870c6ab93bbd94)

1 of the crash-report: [https://gist.github.com/Gbergz/5c744dbf59b79410ad2aac91ff00c0fc](https://gist.github.com/Gbergz/5c744dbf59b79410ad2aac91ff00c0fc)
2nd crash: [https://gist.github.com/Gbergz/9bbf8d34c53f0bf67be49e7a79964277](https://gist.github.com/Gbergz/9bbf8d34c53f0bf67be49e7a79964277)
3rd crash: [https://gist.github.com/Gbergz/be28671897ebde18f4664315695632b4](https://gist.github.com/Gbergz/be28671897ebde18f4664315695632b4)
4th crash: [https://gist.github.com/Gbergz/5f835ae7ee1bc75346084d3c3b0dbcd0](https://gist.github.com/Gbergz/5f835ae7ee1bc75346084d3c3b0dbcd0)
5h crash: [https://gist.github.com/Gbergz/c19c277606d4558ca74a3c90b69e5db3](https://gist.github.com/Gbergz/c19c277606d4558ca74a3c90b69e5db3)

**Comment by SquidDev** [comment]
This crash occurs when the server has lagged so much, Minecraft gives up and just kills it. It's most likely unrelated to ComputerCraft - we generally have very little impact on tick time.

**Comment by SquidDev** [comment]
Just a couple of other notes:

 - You can set `max-tick-time=-1` in your `server.properties` to disable this error. You probably don't want to though, as it means you have a 1m lag spike.

 - You might want to install something like [spark](https://github.com/lucko/spark) or Lag Goggles in order to track down what's actually causing this lag.
