### ISSUE TITLE
[1.12.2] Calling certain external component functions works on OpenComputer through the 'component' variable, but the same functions return "nil" if called through a relay with a ComputerCraft computer

### ISSUE THREAD

**Issue by Yarillo4** [SquidDev-CC/CC-Tweaked#344]
(Duplicate from [here](https://github.com/MightyPirates/OpenComputers/issues/3212) ; I'm making an issue in both repos as I am not sure if the bug is coming from OpenComputers or CC:Tweaked)

- CC-Tweaked 1.85.2
- OpenComputers 1.7.5.192
- AppliedEnergistics2 rv6-stable-7

I am trying to retrieve the contents of a ME System. Since they don't have Plethora on the server I play on, I had to get creative and I tried to retrieve that information through OpenComputer's adapter, with the help of the "relay" component which exposes the component to my CC Computer.

Unfortunately, while it correctly exposes all the functions of the component, some of them only return 'nil', but only on CC:Tweaked computers

Could it be a problem on CC:Tweaked's part ?

Here's a ME Controller with a single item in its drives being read from OC

![OC](https://i.imgur.com/JLkDKZI.png)

But here's on ComputerCraft

![CC](https://i.imgur.com/IcITeJ4.png)

* canExtract():bool => works
* canReceive():bool => works
* getAvgPowerInjection():float => works
* getAvgPowerInjection():float => works
* getCpus():table => always nil
* getCraftables():table => always nil
* getEnergyStored():float => works
* getItemsInNetwork():table => always nil

It seems like tables do not make it through the relay. 

For what it's worth, the relay is fully upgraded with a tier 3 disk, tier 3 CPU and a tier 3.5 ram stick so the serialized data should have room ?

![Relay](https://i.imgur.com/ckEfWya.png)

The whole setup is like so (yes it's powered)

![Setup](https://i.imgur.com/VQzqvbc.png)

**Comment by SquidDev** [comment]
I suspect this is entirely on OC's end. We don't add any explicit integration with OpenComputers, so this should be entirely occurring within OC code.
