### ISSUE TITLE
Can't wrap peripherals in version 1.86.1

### ISSUE THREAD

**Issue by Cra7y** [SquidDev-CC/CC-Tweaked#346]
I used all day trying to figure out why I could not use a modem through the modem API, after some experimentation I figured out that the peripheral.call() function worked, but if I tried to wrap a peripheral before using it it just failed with an error (something about the function was nil).
I tried this with a printer too and it was the same story, peripheral.call() is fine but wrapping is not.
I know this isn't the most detailed description, but hope it helps anyway...

Edit:
It also appears that the distance always returns nil when using the peripheral.call() and peripheral.getMethods() also always returns an empty table.

**Comment by SquidDev** [comment]
Thanks for the report! Really sorry you spent so long on this, this is a pretty embarrassing bug on my part.

Fixed in 8b1773dd6019eb9ec5e7dfff44f1568518c2c930 - will upload a new release.

**Comment by Cra7y** [comment]
No problem, I downgraded one version and the everything was fine, I'm just so happy that there are still active development on this mod👌😉
