### ISSUE TITLE
Advanced Monitor won't connect between each other

### ISSUE THREAD

**Issue by HonzaVinCZ** [SquidDev-CC/CC-Tweaked#347]
Minecraft 1.12.2
CC: Tweaked 1.84.0

If I place more Advanced Monitors, they won't connect between each others. Basic monitor is connecting without problems.

Link to modpack: [here](https://www.technicpack.net/modpack/mc-titan-tekkt.1144196)

![image](https://user-images.githubusercontent.com/29098779/72447906-6c5f9380-37b6-11ea-858b-02969bdd1e18.png)

**Comment by SquidDev** [comment]
I can't reproduce this with just CC: Tweaked and Forge. I suspect you have another mod interfering with this.

Was this screenshot taken on a server? If so, does it also occur in single player - there's a bit of me which wonders if some server software (Sponge, etc...) is doing something odd.

**Comment by HonzaVinCZ** [comment]
Yes, the screenshot was taken on Sponge server. Honestly, I didn't try it in SP yet, will try and reply soon.

**Comment by HonzaVinCZ** [comment]
Tested it in SP and cannot reproduce it. Problem must be on the server then.

**Comment by SquidDev** [comment]
Yeah, I'm inclined to blame Sponge here. Though it's definitely rather odd - I help with managing a Sponge server, and we've not seen similar issues there.
