### ISSUE TITLE
Wired network visualiser

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaked#35]
![](https://i.imgur.com/4dVSbqn.png)

I'm not entirely sure how we should expose this, as I'm somewhat reluctant to add an item specifically for it. Could add a sub-command, but it's a little clunky to use.

**Comment by SquidDev** [comment]
The main blocker here is working out how to expose this functionality to the end user. Ideas are welcome.

**Comment by Jummit** [comment]
Here is a proposal/Idea: Make a item/command that targets a block and displays little lines that go into/out of the computer. The lines could also be replaced by "Computer <ID>", which would be extra useful. If the message is short, like "received" or "start" then it could display that as well.

**Comment by JoeJoeTV** [comment]
Maybe it could work like that tool for applied energistics from ae2stuff. I think it's called the Network Visaulizer.

**Comment by Earthtomars-GA** [comment]
> Maybe it could work like that tool for applied energistics from ae2stuff. I think it's called the Network Visualizer.

Yes but that would mean the AE2Stuff and by extension AE2 would be needed for computercraft

**Comment by JoeJoeTV** [comment]
> > Maybe it could work like that tool for applied energistics from ae2stuff. I think it's called the Network Visualizer.
> 
> Yes but that would mean the AE2Stuff and by extension AE2 would be needed for computercraft

No, my idea was to make a computercraft network visualizer simmilar to the one from ae2stuff, not use that one.

**Comment by SquidDev** [comment]
I'm kinda reluctant to add an item for something that was effectively designed as just a debugging tool, hence this issue being open for so long at all.

**Comment by hugeblank** [comment]
Consider adding it to plethora? I know it's not exactly a 'peripheral', but I don't think it's something that really fits into CC:T.

**Comment by SquidDev** [comment]
@hugeblank It rather has to be in CC:T, as most of the data it needs isn't exposed in the API (and I'm rather reluctant to expose it right now). Given that this has always been a creative-only item, I'm _less_ worried about fitting in thematically, though it's definitely a valid concern.

**Comment by SquidDev** [comment]
I'm going to close this for now. While it was a fun feature in CCTweaks, it was something which started off as a tool for debugging cables, and rather spiralled into a complex behemoth.

I don't seen an immediate need for it, and so it's one rather complicated feature I'm happy to let go of.
