### ISSUE TITLE
Turtles and computers sometimes not showing text on screen

### ISSUE THREAD

**Issue by kromkrot** [SquidDev-CC/CC-Tweaked#352]
Opening a turtle interface just showed a blank black screen:

![](https://i.imgur.com/6J3PNWS.jpg)

After shutting down game and coming back after a few hours the terminal now shows normally, so I'm not sure how to reproduce it.

### F3 screen: 
![](https://i.imgur.com/qZxNpG1.jpg)

### Logs:
[debug and lastest.log](https://gist.github.com/SquidDev/8d01d1c14d6cb26b8260606610d2c94a)

I really have no idea what i'm doing here so hopefully this has the info you may need, thanks 

### Further info
 - Minecraft version: 1.15.2-forge-31.0.1
 - CC: Tweaked version: 1.15.2-1.86.2
 - Display: 1920x1080 (NVIDEA Corporation)
 - GeForce GTX 970/PCIe/SSE2
 - 4.6.0 NVIDIA 432.00

### Mod list:
- cc-tweaked-1.15.2-1.86.2.jar
- jei-1.15.2-6.0.0.2.jar
- NaturesCompass-1.15.1-1.8.3.jar
- obfuscate-0.3.4-1.15.2.jar
- vehicle-mod-0.42.4-1.15.2.jar

**Comment by SquidDev** [comment]
That's perfect, thank you very much!

It's just useful to have as much information as possible, as it generally makes it easier to reproduce a bug.

**Comment by SquidDev** [comment]
I was unable to reproduce using this mod list, which makes me wonder if it's a graphics driver issue. I'm trying to get other people with the same graphics hard to see if anyone else is able to reproduce.

**Comment by kromkrot** [comment]
yeah it most likely is, this computer is old and has suffered a lot of
power surges. After a few hours without a restart the game gets quite slow.
either that or ram problems

thanks anyway dude, especially for maintaining this beautiful mod
