### ISSUE TITLE
Map rendering for pocket computers and printouts

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaked#357]
This was originally just a note on [the 1.15 project](https://github.com/SquidDev-CC/CC-Tweaked/projects/1), but I'm moving it into an issue to create the false illusion of progress.

---

Our custom rendering for pocket computers and printouts was removed as part of the 1.15 update.  Now that MinecraftForge/MinecraftForge#6444 is merged, it should be possible to add them back in. However, it appears there are a lot of rendering issues when doing so. I'm _reasonably_ sure our code is correct (though we should double check), so it'd be worth verifying that the correct values are passed to the event.

**Comment by Sammydoodlew** [comment]
I noticed this on the 1.14.4 version, and I was able to use it just fine last night, (the night I downloaded it), and this morning. Later, however, the rendering issue was present in all worlds. I hope this helps!

**Comment by SquidDev** [comment]
Hey @Sammydoodlew, thanks for the report!

If the problem crops up again, would you be able to take a couple of screenshots showing the problem and create a new issue with them and your `latest.log` file? If you're on 1.14.4, this'll most likely be a different issue to the 1.15 one - that you'll definitely notice every time!

**Comment by Sammydoodlew** [comment]
Sounds good! I'll try to get a screenshot, and in case it helps, the other mods I have installed are:
Just Enough Items (JEI)
Crayfish's Furniture Mod
Quark
and AutoRegLib (For Quark)
