### ISSUE TITLE
Moving pistons with Quark does not update monitor dimensions

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaked#36]
I suspect we'll need to hook into `.invalidate` and `.validate` and update monitor dimensions in those cases.

[Image, which GH doesn't seem to want to embed](https://dl.scoopta.ninja/Scoobooru/image?id=1527401589843)

**Comment by StefanJanssen95** [comment]
@SquidDev Is this bug still relevant? It's a year old now and the image link is dead. I'm not a Java developer so I doubt I can fix the issue, though I have no clue what the issue is exactly.

**Comment by SquidDev** [comment]
I suspect it is - I'll try to reproduce it and get a new screenshot.

I haven't really looked at this recently - Quark in a core mod, and so doesn't run in a deobfuscated environment, making it a pain to test changes.

**Comment by SquidDev** [comment]
It's also possible to create similar funky issues with Carry On, by picking up and placing down monitors.

I think a good fix here is to verify that a monitor is well-formed (i.e. there is a matching monitor at the origin) when placed/validated, and reset to a single monitor if not.
