### ISSUE TITLE
Include additional function information in pretty printer

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaked#361]
#334 introduced a new pretty printer which brings in many of the features from mbs (see #234). However, one feature which I and other people find rather useful is pretty-printing of function arguments:

![image](https://user-images.githubusercontent.com/4346137/73891071-4d12ce00-486b-11ea-87d8-39f4c8d78cf3.png)

It'd be nice to bring this back, [and the implementation is pretty simple][code]. However, not everyone is a fan of this functionality, so I think for now we should gate it behind a config option (which can be enabled by default at a future date).

[code]: https://github.com/SquidDev-CC/mbs/blob/master/bin/lua.lua#L86-L109

**Comment by exerro** [comment]
Is there any reason to include the line number it's defined on (and the file too?). Parameters are incredibly useful though, I'd very much like to see this in-game.

On a side note, did you really `good first issue` your own issue? 😛

**Comment by lupus590** [comment]
Off topic: `good first issue` indicates that an issue is easy to fix for anyone new to the repo, marking things as such means that SquidDev doesn't have to make simple changes to the mod and thus can focus on bigger or deeper changes to the mod. It also allows Squid to get some spare time back as maintaining a mod can eat a lot of time.

**Comment by Lemmmy** [comment]
I definitely find the line numbers useful (I find myself looking at the CC:T source dozens of times per day), though perhaps they should be hidden for functions in the ROM to reduce visual clutter.

**Comment by SquidDev** [comment]
@exerro "good first issue" serves multiple purposes:

 - This is issue #1, and it's a good one.
 - This is your first issue.
 - This is a horrifically hard issue and I'm just a psychopath.
 - This is quite simple, and is good introduction to contributing to CC.

In this case the, the last one was the most applicable. Sadly, [all those people who could have helped](https://github.com/SquidDev-CC/CC-Tweaked/commits?author=exerro) didn't (:p), so there we go...

**Comment by exerro** [comment]
Welp, I had always thought `good first issue` was like a reward to newcomers for putting a well-written issue up. I learnt the hard way.
