### ISSUE TITLE
Update Cobalt to 0.5.1

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaked#363]
With the help of Abigail, I've been making some updates to Cobalt to bring it more in line with PUC Lua, and incorporate some versions of Lua 5.2/5.3.

Obviously it'd be nice to update CC:T to use these features. However, there's a couple of things which will need testing to ensure they do not break existing programs too badly.

[You can see the list of changes since the last CC:T update](https://github.com/SquidDev/Cobalt/compare/v0.5.0...master), but a brief summary of things which may make a noticeable difference:

 - The `__len` metamethod may now be used by tables.

 - Strings now accept hexadecimal, unicode and the zap (`\z`) escape code. Please make sure you're only using valid escape codes - this can be done by chucking your code into [illuaminate](https://squiddev.cc/illuaminate/), or running it through Lua 5.3.

 - Java functions are no longer tail called. This means that `return error("bad argument")` will no longer lay blame at the calling function. This should be replaced with `error("bad argument", 2)`, or use the [`cc.expect`](https://tweaked.cc/module/cc.expect.html) library.

#### Some other niceties which won't break anything, but worth pointing out.
 - Add Lua 5.3's `utf8` library.
 - `math.log` also accepts a "base" argument (e.g. `math.log(123, 2)` is log<sub>2</sub>(123)).
 - Parser error messages now include the token where the error occurred.
 - `table.unpack` now uses `__len` and `__index` metamethods.

**Comment by Lemmmy** [comment]
Slight issue with the errors in tail calls, the one I noticed was in the peripheral API. Example:

```lua
local mon = peripheral.find("monitor")
mon.setTextColour(nil)
```

![](https://i.lemmmy.pw/9lmn.png)

Claims the error is in `peripheral.lua`.
