### ISSUE TITLE
Monitors are still broken with shaders

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaked#37]
![](https://i.imgur.com/oAzYhfF.png)

Using the [Wisdom Shaders pack (v3.2)](https://qionouu.cn/wisdom.html).

**Comment by Scoopta** [comment]
Monitors do really weird crap when it's raining. They reflect text [image](https://imgur.com/a/4czrQ8Q)

**Comment by ChlorideCull** [comment]
After spending a couple of hours looking at the code of the Wisdom Shaders and reproducing it, I'm really not much closer to figuring out *why* it happens.

Here's a newer screenshot from 1.14.4 which also show that the light glows through the arm partially.
![](https://u.teknik.io/lYC6d.png)

Try playing with the normals :)

**Comment by Theemok** [comment]
![image](https://user-images.githubusercontent.com/33252531/68995198-31f77a00-088b-11ea-939c-641aaf13f973.png)

using:
cc-tweaked-1.14.4-1.85.0.jar
OptiFine_1.14.4_HD_U_F4

shaders:
Sildurs Vibrant Shaders v1.25
I have tested on light, high and extreme and they are all have the same problem.

**Comment by SquidDev** [comment]
As with #95, I'm going to flag this as "Cannot reproduce" for now. My laptop cannot run most shader packs, and so I'm unable to test/fix this problem.

If anyone else has this issue, and/or is able to help out, comment and I'll reopen.
