### ISSUE TITLE
Not a bug report - question about resource packs

### ISSUE THREAD

**Issue by Sabster** [SquidDev-CC/CC-Tweaked#374]
This might be a bug report - I haven't used CC in a while; and what used to work isn't working...

I have a cc-progs.zip file in my resourcepacks folder.   It used to be that you would have a file structure in the zip file as such:  assets\computercraft\lua\rom\programs\turtle - and all the programs go there.  But it doesn't seem to be working anymore.

Did this change, or is there a bug with 1.15?

**Comment by Sabster** [comment]
Oh and this is on a single player world (I use a resource pack because I used to have a custom API in the resource pack...)

**Comment by JakobDev** [comment]
You have to use a datapack now

**Comment by Sabster** [comment]
Sorry about late delay - I'll google it, but is there any info on the datapack?  (I can't remove the bug tag)  :(

**Comment by lupus590** [comment]
This might be useful https://github.com/SquidDev-CC/CC-Tweaked/issues?utf8=%E2%9C%93&q=datapack

**Comment by Sabster** [comment]
Didn't realize this was still open - I figured it out.  Thanks!
