### ISSUE TITLE
64k Message size too low?

### ISSUE THREAD

**Issue by fionera** [SquidDev-CC/CC-Tweaked#376]
Currently every message sent over a Websocket Connection has to be smaller than 64k. Based on the RFC this should be bigger and I myself just ran against this limit. 

https://tools.ietf.org/html/rfc6455#section-5.2
https://github.com/SquidDev-CC/CC-Tweaked/blob/93a9ebc4f6b8c7c59151feffa1b5ab3996c016f5/src/main/java/dan200/computercraft/core/apis/http/websocket/Websocket.java#L43

**Comment by SquidDev** [comment]
There was some reason I added this, and I cannot for the life of me remember what it was now. Ughr.

**Comment by Lemmmy** [comment]
Netty?
