### ISSUE TITLE
API request 1.14.4+

### ISSUE THREAD

**Issue by Edivad99** [SquidDev-CC/CC-Tweaked#377]
Hi, I wanted to ask you for information. My mod used OpenCumputers APIs to manage my block through computers. Now since the OC is not updating it anymore I wanted to use your mod. But from what I see you don't provide APIs, if there are you could tell me?

**Comment by Jummit** [comment]
Aren't these the CC apis?
https://github.com/SquidDev-CC/CC-Tweaked/tree/master/src/main/java/dan200/computercraft/api

**Comment by Edivad99** [comment]
For MC 1.14.4?

**Comment by Jummit** [comment]
Yep.

**Comment by Edivad99** [comment]
And what is the Maven repository?

**Comment by lupus590** [comment]
https://squiddev.cc/maven/

**Comment by Edivad99** [comment]
But I don't understand one thing, for example TOP has the full version and the API version. I use the API version because I don't want to force the player to have to install the TOP. Now CC-Tweaked only has the full version, if I use this and I only rely on the API, if the player doesn't want to install the CC can he do it?

**Comment by SquidDev** [comment]
While we don't ship two separate jar files, using CC:T's API should be exactly the same as any other mod API. As long as you're guarding the integration code correctly, it shouldn't introduce a runtime dependency.

You can exclude CC:T from your (runtime) development environment by making it a compile-only dependency - replace `implementation`/`compile` with `compileOnly` in your `dependency` block.
