### ISSUE TITLE
Better script editor

### ISSUE THREAD

**Issue by ViniDalvino** [SquidDev-CC/CC-Tweaked#380]
- Add better syntax highlighting
- Add an better intelisense. As exemple I would like to be able to see all the possibility for api. And also, I would like to have the hability to press control+space to open the intelisensse.
- The hability to select and drag, use control/shift + arrow key to select and block select
- hability to cut, paste and copy
- add user added variable and function to the intelisense

**Comment by plt-abigail** [comment]
Pull requests welcome.

**Comment by SquidDev** [comment]
While I agree that the built-in editor is far from perfect, I'm afraid none of these points are likely to be fixed soon. The limits of computers' screen sizes, mean that editing in game is always going to be sub-optimal - hence most people just edit using their normal text editor, or using a like [cloud-catcher](https://cloud-catcher.squiddev.cc/),
