### ISSUE TITLE
Where did setTextScale() go?

### ISSUE THREAD

**Issue by josh-65** [SquidDev-CC/CC-Tweaked#384]
I saw this being a thing in other peoples post and the wiki but just gives this.
![2020-03-27_20 15 31](https://user-images.githubusercontent.com/26977075/77796762-c9ee4700-7067-11ea-9d98-fcb21e78ef13.png)

**Comment by Lemmmy** [comment]
Can you share your code, Minecraft version, and CC:Tweaked version? It looks like you're trying to run `setTextScale` globally instead of on a `term` or `mon`.

**Comment by josh-65** [comment]
Minecraft - 1.12.2
CC: Tweaked - 1.86.2

[SS_tp-b.txt](https://github.com/SquidDev-CC/CC-Tweaked/files/4395780/SS_tp-b.txt)

**Comment by plt-hokusai** [comment]
You `term.redirect` into an empty table - and obviously, the empty table doesn't support `setTextScale`.

**Comment by josh-65** [comment]
Oh ok thanks.

**Comment by Lemmmy** [comment]
Did you get it working?

**Comment by josh-65** [comment]
Hydraz said 
> You term.redirect into an empty table - and obviously, the empty table doesn't support setTextScale

But don't know where the comment went

**Comment by josh-65** [comment]
I have now just put multiTerm before it.
