### ISSUE TITLE
Render printed pages in world

### ISSUE THREAD

**Issue by Lemmmy** [SquidDev-CC/CC-Tweaked#39]
In item frames definitely
In hand maybe would be cool

**Comment by SquidDev** [comment]
Talking through this in slack + some other notes:

 - Render in-hand. We could use something like `shift+scroll` to go to the next page.
 - Use `RenderItemInFrameEvent` to allow fancy rendering on item frames.

**Comment by Lemmmy** [comment]
![](https://you.wouldnot.download/a-freedom.png)
![](https://you.wouldnot.download/an-applewood.png)
![](https://you.wouldnot.download/a-civilisation.png)

**Comment by SquidDev** [comment]
Added in fd10ed6. There's probably more to come as the PR is updated, but let's get it here first.

**Comment by vpontin** [comment]
VERY interesting. Thanks for deploy this @SquidDev .

I imagine using this for make like newspapers glued on walls, or wanted posters.
