### ISSUE TITLE
Provide some option like "disable-turtle-backpack-sucked-by-hopper" 

### ISSUE THREAD

**Issue by luochen1990** [SquidDev-CC/CC-Tweaked#390]
Hello, I find that my turtle will lost items when it move through a hopper's upper face,  and it seems there is no easy way to avoid this problem.

I have considered following solutions:

1. Detect if there is a hopper under the forwarding block before every movement.  This is impossible since turtle have to arrive the "dangerous-position" to turtle.inspectDown() to avoid arriving the "dangerous-position".
2. Send a redstone signal to downside to disable hopper on each movement.  This is not a good solution since it have side effects which might break other redstone based mechanism.
3. Provide an entire world map so that our turtle can plan to move smartly. This is also not practical since there is no easy way for us to get the entire world map.

So I think maybe disable interaction between turtle and hopper will be a good solution.

And when we indeed want to put items into hopper, we can call turtle.drop() by ourself.

Solution candidates:

1. Disable interaction between turtle and hopper by default
2. Provide some mod setting option like "disable-turtle-backpack-sucked-by-hopper"
3. Provide a new API like turtle.setHopperInteractionMode()

**Comment by Lemmmy** [comment]
I'd say it'd be nice to make it a per-computer setting using the `settings` API but those are shell-specific unfortunately

**Comment by SquidDev** [comment]
Sorry for the slow response. As the tags indicate, I'm pretty reluctant to add side configuration to turtles in any form.

I can see the appeal, but I'm afraid this is where my sense of ["fun"][fun] and minimalism win over any sense of practicality.

[fun]: https://dwarffortresswiki.org/index.php?title=DF2014:Fun "Fun"
