### ISSUE TITLE
turtle.inspect() returning different values for flowing water

### ISSUE THREAD

**Issue by fatboychummy** [SquidDev-CC/CC-Tweaked#391]
So I placed my turtle to offset a source block by 1x, 1z, and created a program which turns to face the flowing water block

The problem is, I set it to face `minecraft:water` (as that is what opening the `lua` prompt and typing `turtle.inspect()` returned), but for some reason directly after startup it returns `minecraft:flowing_water`.  Every other call returns `minecraft:water`.

 - Minecraft version: 1.12.2
 - CC: Tweaked version: 1.86.2

To reproduce:
![image](https://user-images.githubusercontent.com/39929480/78327795-ee03c980-753a-11ea-92ef-15a4db93d285.png)

![image](https://user-images.githubusercontent.com/39929480/78327823-f825c800-753a-11ea-9625-335537b060c4.png)

![image](https://user-images.githubusercontent.com/39929480/78327836-fcea7c00-753a-11ea-932a-6fc59d76a86b.png)

**Comment by fatboychummy** [comment]
![image](https://user-images.githubusercontent.com/39929480/78327969-463acb80-753b-11ea-8afd-50cb5fa7cfe6.png)
And screenshot of the setup

**Comment by SquidDev** [comment]
Minecraft returns `minecraft:flowing_water` when a block is undergoing block updates, and `minecraft:water` when it is stationary. For better or worse, this is part of Minecraft's game engine, rather than a bug with CC:T itself.
