### ISSUE TITLE
Can not import gradle project in IntelliJ IDEA

### ISSUE THREAD

**Issue by luochen1990** [SquidDev-CC/CC-Tweaked#394]
Got following message when trying to import project in IntelliJ IDEA

> Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> \> Could not create service of type FileHasher using BuildSessionScopeServices.createFileSnapshotter().

## Useful information to include:
 - CC: Tweaked version:  0ffd5fc (latest master branch)
 - IDE version:  IntelliJ IDEA 2019.3.4 x64
 - Detailed reproduction steps:
    1. git clone this repo
    2. open the repo directory inside IntelliJ IDEA
    3. wait for popup "Gradle projects need to be imported" and click "Import Changes"
    4. **got the error** message about "Could not create service ..."
    5. execute `./gradlew setupDecompWorkspace` as README telled.
    6. reopen IntelliJ IDEA and retry to import, and still **got the same error**

**Comment by lupus590** [comment]
There is a gradle task for making the intellij idea project, have you tried running that?

**Comment by luochen1990** [comment]
@lupus590 Thank you, but I'm new to gradle and don't know how to run it, could you please tell me how?

**Comment by SquidDev** [comment]
@luochen1990 Open the CC:T directory in a command prompt, and run the following:

```
> ./gradlew build
> ./gradlew idea
```

**Comment by lupus590** [comment]
If you are using git bash as your command line on windows then I would suggest that you use `./gradlew.bat` instead of `.gradlew` or './gradlew.sh`. Note that this won't auto-complete but the bat file will run in git bash like any native bash script.
