### ISSUE TITLE
Pastebin get failure, no .cfg 

### ISSUE THREAD

**Issue by AceSkym** [SquidDev-CC/CC-Tweaked#397]
Minecraft Version 1.15.2
CC: Tweaked version: 1.152-1.86.2
Steps: Typed into turtle: pastebin get CODE NAME 

I've tried multiple codes from multiple people to check if it is an issue with a particular program, but I get the same issue. 

After searching these forums and others I went looking for the .cfg file but could not locate it anywhere in the .Minecraft, the config, or my computer. I attempted to add the .cfg manually but nothing's changed so I'm unsure if I even did it correctly (I deleted my .cfg assuming it was wrong). 

Because of this I can't use the mod, any recommendations or links to the .cfg? I've downloaded and redownloaded and it's never given me the .cfg file. 

Thanks!

**Comment by SquidDev** [comment]
Minecraft  1.13 and later use `.toml` files instead. However, the default config file should be correct - what error is pastebin giving?

**Comment by AceSkym** [comment]
When I type in the pastebin get command it will state:

Connecting to pastebin.com … Failed.
Could not connect

But I do not crash and I don't get any other errors.

**Comment by SquidDev** [comment]
Hrmr, that's very odd. If you're getting a "Could not connect" error, it's not a problem with your configuration file, but some other reason can't connect to the server.

I'm afraid this is going to have to be something you'll need to debug yourself. The best way to do this is perform the http request manually, using `ok, error, response = http.get("https://pastebin.com/raw/PASTEBIN_CODE")`, and inspecting the `response` to see if there's any information of use there.

**Comment by AceSkym** [comment]
Do I input this into the turtle, computer, or somewhere else? It's been a while since I've used the mod so I'm uncertain. 

When I input it into the turtle or computer it states "No such program"

**Comment by lupus590** [comment]
you want to put it into the lua program

**Comment by AceSkym** [comment]
I put that into the lua and a popup appeared in my antivirus (kaspersky), I allowed the exception and now it works fine. So my assumption would be that it has something to do with antivirus blocking pastebin. Thanks for the help!

**Comment by SquidDev** [comment]
Huh, that's interesting - not seen an antivirus blocking pastebin before. Gad you've got it working though!
