### ISSUE TITLE
getType() conflicts 1.14.4 API

### ISSUE THREAD

**Issue by Edivad99** [SquidDev-CC/CC-Tweaked#398]
The getType() method conflicts with the getType() in the TileEntity class
![Screenshot (205)](https://user-images.githubusercontent.com/25778604/79044529-eb256a80-7c05-11ea-838c-c291126e5571.png)

**Comment by SquidDev** [comment]
I think the general recommendation here is not to implement `IPeripheral` on your tile entity itself. This means you have a hard dependency on CC, which is _generally_ not what you want.

Instead, implement `IPeripheral` in a separate class and register an `IPeripheralProvider` for your actual TE.

**Comment by Edivad99** [comment]
Do you know any mods that did it?

**Comment by SquidDev** [comment]
Not on 1.14 - I'm not aware of any mods using CC so far. However, the API is pretty much identical in previous versions. On 1.12, there's [Computronics][computronics], which is a pretty good model.

[computronics]: https://github.com/Vexatos/Computronics/blob/1.12/src/main/java/pl/asie/computronics/cc/CCPeripheralProvider.java
