### ISSUE TITLE
/computercraft dump doesn't work via command computers and console

### ISSUE THREAD

**Issue by Lemmmy** [SquidDev-CC/CC-Tweaked#40]
`/computercraft dump` output is slaughtered when run from the console, or from command computers:

![](https://you.wouldnot.download/a-linen.png)
![](https://you.wouldnot.download/a-bowler.png)
![](https://you.wouldnot.download/a-teacher.png)

**Comment by SquidDev** [comment]
I actually just need to rewrite the entire text-table system to handle players and non-players separately - it's rather ugly as is
