### ISSUE TITLE
Narrator enables when terminating program

### ISSUE THREAD

**Issue by AlexProGear** [SquidDev-CC/CC-Tweaked#401]
- Minecraft version: 1.14.4
 - CC: Tweaked version: 1.86.2
 - Detailed reproduction steps: press and hold ctrl+t to terminate program. As a result, narrator enables, even if narrator key (which is ctrl+b by default) is unbound in settings.
Also, I saw the same issue for other player in curseforge comment section.

**Comment by SquidDev** [comment]
This is very odd - I'm unable to reproduce with Forge 28.1.71. I've also had a prod through the code, and can't see any code path which would enable the narrator.

Would you be able to post your mod list and latest.log file? I'm assuming there's something else which touches key bindings, as AFAIK the narrator isn't rebindable within vanilla.

**Comment by AlexProGear** [comment]
So, I've done some testing aand...
It's not your mod causing this issue.
The problem is with mod called RandomPatches, which lets rebind narrator key and for whatever reason also makes ctrl+t work as narrator key no matter what.
Gotta report that to their issues page.
Sorry for bothering, have a great time :)

**Comment by SquidDev** [comment]
Ahh, that's good to know. Thank you very much for the followup!
