### ISSUE TITLE
Maven issue

### ISSUE THREAD

**Issue by LotuxPunk** [SquidDev-CC/CC-Tweaked#405]
Hello ! I'm the author of a little addon for the "TARDIS Mod", "Handles", it's a ComputerCraft integration of the "TARDIS Mod".

I'm trying to use your maven to start the port of Handles on 1.14.4, but I'm stuck.

1. I think you have a mistake in your README.md, because you put :
```
dependencies {
  maven { url 'https://squiddev.cc/maven/' }
}

dependencies {
  implementation "org.squiddev:cc-tweaked-${mc_version}:${cct_version}"
}
```

I think the first one should be `repositories`, but even with that I get that when I try to sync my Gradle :
```
Could not find org.squiddev:cc-tweaked-1.14.4:1.86.2_mapped_snapshot_20200119-1.14.4.
Searched in the following locations:
  - https://squiddev.cc/maven/org/squiddev/cc-tweaked-1.14.4/1.86.2_mapped_snapshot_20200119-1.14.4/cc-tweaked-1.14.4-1.86.2_mapped_snapshot_20200119-1.14.4.pom
  - https://squiddev.cc/maven/org/squiddev/cc-tweaked-1.14.4/1.86.2_mapped_snapshot_20200119-1.14.4/cc-tweaked-1.14.4-1.86.2_mapped_snapshot_20200119-1.14.4.jar
  - file:/C:/Users/LotuxPunk/.gradle/caches/forge_gradle/bundeled_repo/org/squiddev/cc-tweaked-1.14.4/1.86.2_mapped_snapshot_20200119-1.14.4/cc-tweaked-1.14.4-1.86.2_mapped_snapshot_20200119-1.14.4.pom
  - file:/C:/Users/LotuxPunk/.gradle/caches/forge_gradle/bundeled_repo/org/squiddev/cc-tweaked-1.14.4/1.86.2_mapped_snapshot_20200119-1.14.4/cc-tweaked-1.14.4-1.86.2_mapped_snapshot_20200119-1.14.4.jar
  - https://files.minecraftforge.net/maven/org/squiddev/cc-tweaked-1.14.4/1.86.2_mapped_snapshot_20200119-1.14.4/cc-tweaked-1.14.4-1.86.2_mapped_snapshot_20200119-1.14.4.pom
  - https://files.minecraftforge.net/maven/org/squiddev/cc-tweaked-1.14.4/1.86.2_mapped_snapshot_20200119-1.14.4/cc-tweaked-1.14.4-1.86.2_mapped_snapshot_20200119-1.14.4.jar
  - https://libraries.minecraft.net/org/squiddev/cc-tweaked-1.14.4/1.86.2_mapped_snapshot_20200119-1.14.4/cc-tweaked-1.14.4-1.86.2_mapped_snapshot_20200119-1.14.4.jar
  - https://repo.maven.apache.org/maven2/org/squiddev/cc-tweaked-1.14.4/1.86.2_mapped_snapshot_20200119-1.14.4/cc-tweaked-1.14.4-1.86.2_mapped_snapshot_20200119-1.14.4.pom
  - https://repo.maven.apache.org/maven2/org/squiddev/cc-tweaked-1.14.4/1.86.2_mapped_snapshot_20200119-1.14.4/cc-tweaked-1.14.4-1.86.2_mapped_snapshot_20200119-1.14.4.jar
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

```

I'm already sorry for my English, I'm a french native speaker ! 😅 

Thanks in advance for the help !

**Comment by SquidDev** [comment]
Ahh, sorry! I spent this afternoon migrating things across servers, and apparently forgot to copy the maven repository when doing so. Can you try now, and check if it works?

**Comment by LotuxPunk** [comment]
It seems to be working! Thank you for your promptness!

I take this opportunity to ask you if you have documentation for addons?

**Comment by SquidDev** [comment]
> I take this opportunity to ask you if you have documentation for addons?

As far as documentation goes, the the `dan200.computercraft.api` package is pretty thoroughly commented, but I'm afraid there's not much in the way of tutorials.

I don't think it's changed much between 1.12 and 1.14, so the port should be pretty direct. However, if you get stuck, do ping me here or on IRC and I'll see if I can help out.

**Comment by LotuxPunk** [comment]
> As far as documentation goes, the the dan200.computercraft.api package is pretty thoroughly commented, but I'm afraid there's not much in the way of tutorials.

Indeed.

I wouldn't hesitate, thank you very much!

**Comment by Lemmmy** [comment]
@SquidDev perhaps once we've sorted the wiki situation out, we could add 'Using the CC:Tweaked API' to the to-do list

**Comment by SquidDev** [comment]
> once we've sorted the wiki situation out

Hahahahahahahahah.

Though yes, entirely agree. Especially as the API is going to change a fair bit for 1.15 or 1.16, so I at least need to do something for that.

**Comment by jmc529** [comment]
Sorry to hit a dead thread, but it seems the readme was never updated.

**Comment by SquidDev** [comment]
Sorry, entirely forgot to do that. Should be correct now.
