### ISSUE TITLE
function variable preview

### ISSUE THREAD

**Issue by antrobot1234** [SquidDev-CC/CC-Tweaked#41]
it would be nice if, when writing functions from the lua terminal or when coding, the computer would display the next input variable name in grayed-out text until a character is typed (similar to the default values on most text inputs)

ex: foo(a,stuff,bar)
and when you type:
foo(_a_
foo(1,_stuff_
foo(1,'thi
foo(1,'thing',_bar_)

**Comment by redfast00** [comment]
@antrobot1234 this can be done with a Lua program, there is no need to change the mod.
