### ISSUE TITLE
textutils.unserializeJSON deos not support objects

### ISSUE THREAD

**Issue by JakobDev** [SquidDev-CC/CC-Tweaked#411]
This gave me a error:
`textutils.unserializeJSON('{"Hello":"World"}')`

**Comment by SquidDev** [comment]
![image](https://user-images.githubusercontent.com/4346137/79699890-2c62ed80-828a-11ea-8dd9-a43294a0c32e.png)

Odd, this works perfectly fine for me. The test suite also has something similar:

https://github.com/SquidDev-CC/CC-Tweaked/blob/c5f918ad9519db6040dd69daaff5eb34116d9b46/src/test/resources/test-rom/spec/apis/textutils_spec.lua#L101-L103

What's the exact error you're getting?

**Comment by JakobDev** [comment]
I had downloaded the API with wget, because it has only lua code in one file and not downloaded the full jar. Maybe this is the reason.

**Comment by SquidDev** [comment]
Ahh yes, if you're trying to use the API in older versions of CC:T it may not work. We rely on a couple of features from #363. 

You can try it out online using [copy-cat](https://copy-cat.squiddev.cc/gh/branch/master/), as that's built from the latest commit.

**Comment by JakobDev** [comment]
I use CCEmuX as my favourite emulator. Mybe we can craete a GitHub Action that builds a new Version of CCEmuX for every Coomit on CC-Tweaked.

**Comment by Lemmmy** [comment]
CCEmuX can update CC:Tweaked itself, no? copy-cat is CCEmuX, anyway.

**Comment by SquidDev** [comment]
I want to tie CCEmuX's CC:T version to the latest actual release. However, it might be possible to build development versions from master. I'd have to look into it - it'd definitely more tricky, but possible.

> copy-cat is CCEmuX, anyway.

Nah, copy-cat does entirely its own thing, due to its ... rather odd build process.

**Comment by SquidDev** [comment]
It occurs to me that I now maintain (to some extent) three emulators, and none of them share any code. Woops.
