### ISSUE TITLE
peripheral.isPresent only returns false for remote peripherals

### ISSUE THREAD

**Issue by xAnavrins** [SquidDev-CC/CC-Tweaked#415]
- Minecraft version: 1.12.2
 - CC: Tweaked version: 1.86.2

`peripheral.isPresent` only returns false for remote peripherals (wired network), despite them being connected to the network.
This started happening with the new rendering update on SwitchCraft (Before the blit fix), and was working fine the day before.

![javaw_AEYub1jA0n](https://user-images.githubusercontent.com/5376823/79830262-10874680-8373-11ea-8a01-f2c6d92898bc.png)
![javaw_HKA0VZNmo3](https://user-images.githubusercontent.com/5376823/79830288-1aa94500-8373-11ea-9d76-5cb8a9f30f79.png)

**Comment by SquidDev** [comment]
Whoops 

https://github.com/SquidDev-CC/CC-Tweaked/commit/ef8da8054f9b774d5f85b06c9a3f76de8be59b17#diff-0ab29439b11d01336c12756bdffbdfbcR57
