### ISSUE TITLE
Pocket computers not refreshing screen in map view

### ISSUE THREAD

**Issue by cooper-anderson** [SquidDev-CC/CC-Tweaked#42]
I love the feature added where it allows you to hold a pocket computer in your offhand of just in front of you and it shows the screen. This was working perfectly in the CC-Tweaks implementation of the feature, but in this version the screen does not refresh unless you manually open the computers gui. Not sure if anyone else is having this same issue.

Tested on commits:
18429c50f9813bae676f945be43344f0b9db2c4e (the latest release)
81aaead032f0639e1bc557d20d55a5062e2b010d (the latest commit)

Tested on Forge versions:
`14.23.2.2634`
`14.23.4.2709`

Hopefully this can be sorted out relatively soon!

**Comment by SquidDev** [comment]
Thanks for the report (and the amount of testing you did on it <3). Awfully sorry about this: stupid mistake on my part.

Most of these features are developed against CC, then just merged into CC:T. Apparently there were a couple of new features which interacted rather badly with each other but I never noticed as they worked in isolation. Woops!
