### ISSUE TITLE
Mining Turtle command issues

### ISSUE THREAD

**Issue by captcookie** [SquidDev-CC/CC-Tweaked#421]
Forge 31.1.47 1.15.2
CC Tweaked version 1.87.0

Problem 1) Refuses to Tunnel <length>
Problem 2) Disappears when using a pickaxe

First turtle was crafted in survival. Tested, looked up programs and tunnel did not work. I typed "tunnel 20" Enter
Nothing happened.
I broke the turtle when pickaxe and poof, only my coal popped and stayed.

Second turtle was spawned in creative, the advance mining turtle. 
"tunnel 50" Enter
Nothing happend.
It also disappeared when trying to pick up and replace.

Question: are the simple commands removed for tunnel and excavate?

Also tested, gray mining turtle

**Comment by captcookie** [comment]
[https://cdn.discordapp.com/attachments/703253532090040330/703253626428325928/2020-04-24_09.34.47.png](url)

**Comment by captcookie** [comment]
https://cdn.discordapp.com/attachments/703253532090040330/703254900066353172/2020-04-24_09.43.47.png

**Comment by SquidDev** [comment]
Oh goodness, that turtles not dropping items is very serious. It appears to happen to normal computers too, so thank you for reporting!

I was unable to reproduce the problem with turtles not breaking blocks. Would you be able to run `turtle.dig()` within the Lua interpreter (when there's a block in front) and see what it displays. I'd expect something like this:

![image](https://user-images.githubusercontent.com/4346137/80226718-a1e10c00-8644-11ea-99b2-ef19cbafed9c.png)

**Comment by captcookie** [comment]
https://cdn.discordapp.com/attachments/703253532090040330/703261465611599953/2020-04-24_10.09.49.png

**Comment by captcookie** [comment]
Im going to make a new world with just cc and test the tunnel 20 command. I've always been able to use this and need to see if it s a mod conflict issue.

**Comment by SquidDev** [comment]
`turtle.dig()` - note the parenthesis, but not passing 20 to it!

**Comment by captcookie** [comment]
wow, so its being weird. on one gray turtle it worked. then after trying the yellow advanced one, nothing happened. then i tried another gray mining one, and nothing happens.

**Comment by captcookie** [comment]
https://cdn.discordapp.com/attachments/703253532090040330/703264065375567943/2020-04-24_10.19.40.png

**Comment by captcookie** [comment]
So after it completed and i retyped the command tunnel 20, nothing happens. just buggy i guess.

**Comment by captcookie** [comment]
I also updated the forge to 48 with this test.

**Comment by captcookie** [comment]
https://cdn.discordapp.com/attachments/703253532090040330/703264663961338398/2020-04-24_10.22.33.png

**Comment by captcookie** [comment]
Ok I figured out my problem on my end. I didnt realize the command is tunnel 20 insert a space then enter. Now its working with the extra space behind the numbers.
