### ISSUE TITLE
Accessing monitors on a per-pixel level

### ISSUE THREAD

**Issue by nift4** [SquidDev-CC/CC-Tweaked#423]

**Comment by SquidDev** [comment]
If you need to access the contents of a terminal, my recommendation is to redirect to a window first, and then use [`Window.getLine`](https://tweaked.cc/module/window.html#ty:Window:getLine). I don't have plans to add support for reading directly from the terminal or monitor.

**Comment by nift4** [comment]
This was not meant to get data, this was meant to draw pixels and not characters, like CCLights.
