### ISSUE TITLE
Can't use the Miner program.

### ISSUE THREAD

**Issue by SerIousFaceOP** [SquidDev-CC/CC-Tweaked#438]
I'm currently using Minecraft 1.15.2 and Using CraftOS 1.8    but when I use 6qmBBlpz Miner then type in Miner and select how many parallel tunnels, width, height, and length. Afterwards it allows me to choose if I want to use torches and chest but it won't let me press C or T to do so.

**Comment by SquidDev** [comment]
In Minecraft 1.13+, the codes returned by the `key`/`key_up` events have changed - [see this page for more information](https://github.com/SquidDev-CC/CC-Tweaked/wiki/Incompatibilities-between-versions#minecraft-112-to-113). Therefore any comparisons against numeric values (such as line 192 and 479) will no longer be correct.

You'll need to replace the hard-coded literals with those using the `keys` API. This way they'll correctly work across all versions.
