### ISSUE TITLE
Delete referes to itself as rm in its usage

### ISSUE THREAD

**Issue by Lupus590** [SquidDev-CC/CC-Tweaked#439]
I can easily make a pull request to make it and the other programs use `shell.getRunningProgram`, I'm just wondering if it's worth it

## Useful information to include:
 - Minecraft version: whatever master branch builds
 - CC: Tweaked version: commit 17b7727 on master branch
 - Detailed reproduction steps: on any computer run the command `delete` with no args, note that the printed usage is `rm <paths>` not `delete <paths>`

**Comment by SquidDev** [comment]
This is also true for `copy`, `move` and `rs`. Honestly, I don't mind - if you want to put a PR together, I'll merge it, but it's not a bug I'm especially worried about :p.

**Comment by SquidDev** [comment]
Also worth noting that the "correct" thing to do is `arg[0]`<sup>1</sup>, rather than `shell.getRunningProgram()`. The former returns the actual command entered, the latter just the path.

[1]: Some terrible shells, such as mbs, don't correctly provide `arg`, which makes things much worse!
