### ISSUE TITLE
PDAs and computers can be mounted in disk drives, but turtles can't

### ISSUE THREAD

**Issue by steamp0rt** [SquidDev-CC/CC-Tweaked#44]
Happened on Switchcraft. Tried to mass produce turtles with a certain program, but it turns out, turtles in disk drives _can_ be labeled, but not have files copied to them

**Comment by SquidDev** [comment]
Cannot reproduce on a turtle or computer which has been assigned an ID.

It's worth noting that CC (and thus CC:T) will not provide a mount for computers which do not have an ID: one must place them and label them first. Changing this would be nice, but is something better suited to the CC issue tracker as it'd probably require some API changes.

For the time being, I'd suggest placing the turtle next to a disk drive with a `startup` file. You can then turn the turtle on (using another turtle), the startup file will be run, which can install whatever files you like.

**Comment by steamp0rt** [comment]
Ok, thanks. That's the workaround me and valithor used last night
