### ISSUE TITLE
GPUs

### ISSUE THREAD

**Issue by devomaa** [SquidDev-CC/CC-Tweaked#444]
A while back, someone made a add-on mod that puts "GPU"s in to the game, and your asking, what this does? It adds a way to run OpenGL Actions in-game, unfortunately, this mod has died a long time ago, It's also outdated (1.7.10). Could you add these "GPU"s?

**Comment by Lignum** [comment]
So what's the issue?

**Comment by devomaa** [comment]
..damn it, didn't add the actual feature request, sorry

**Comment by SquidDev** [comment]
While CCLights2 and CCGPU were very cool mods, I don't think they really fit within CC:T itself. Monitors are enough as a headache as-is!
