### ISSUE TITLE
Forge Multipart CBE bundled cables not connecting to computers.

### ISSUE THREAD

**Issue by fatboychummy** [SquidDev-CC/CC-Tweaked#448]
Minecraft version 1.12.2

CC:T version: 1.85.2 (tests in latest pending)

![Computer not connecting](https://i.imgur.com/UNdEKCO.png)

**Comment by fatboychummy** [comment]
[More information starts here in the MCCM discord, I'd add it myself but all I've got is my phone and about 5% battery.](https://discordapp.com/channels/477910221872824320/477911902152949771/709590968969592882)

**Comment by SquidDev** [comment]
Install the ProjectRed - Compat.
