### ISSUE TITLE
Can't place any modems on Mekanism energy cells

### ISSUE THREAD

**Issue by darki73** [SquidDev-CC/CC-Tweaked#449]
## Useful information to include:
 - **Minecraft version:** 1.15.2
 - **CC: Tweaked version:** 1.87.1
 - **Mekanism version:** 9.10.5.418
 - Detailed reproduction steps: Just place any energy cell from Mekanism (Elite Energy Cube) for example and try to attach modem (wired/wireless) to it. Nothing happens.

**Comment by lupus590** [comment]
It might be a transparent block. Full block modems exist to fix this, just place the small modem in your crafting grid on 8ts own to convert it. You can convert back the same way.

Also, unless you have plethora or mekanism provides its own integration, the cell will not be seen as a peripheral.

**Comment by darki73** [comment]
Problem is, [Plethora](https://github.com/SquidDev-CC/plethora) is not updated to the latest game version.
Also, just tried to use full block modem, and as you have said, Mekanism does not provides integration out of the box. So the only way is to wait for [Plethora](https://github.com/SquidDev-CC/plethora) upgrade

**Comment by lupus590** [comment]
feel free to [contibute](https://github.com/SquidDev-CC/plethora/pull/246)

**Comment by SquidDev** [comment]
In previous versions Minecraft versions (1.12.2 and before), integration was provided by Mekanism. However, it appears that has been dropped in recent versions.

I'll have a look at adding it back once #447 is merged - that's rather the blocker for any other mods integrating with CC:T right now.
