### ISSUE TITLE
Computers do not power on during chunk load

### ISSUE THREAD

**Issue by clienthax** [SquidDev-CC/CC-Tweaked#456]
## Useful information to include:
 - Minecraft version: 1.12.2
 - CC: cc-tweaked-1.12.2-1.86.2.jar

I have a rules board at spawn which is setup via an advanced computer / monitors.
More often than not, this setup ends up being powered off when the server restarts, requiring the PC to be interacted with manually for it to boot back up.

**Comment by SquidDev** [comment]
Well this is delightfully bizarre - I thought we'd fixed all of these. Can you try the following:

 - Update to CC:T 1.88.0. Shouldn't really change anything, but just in case.
 - Enable `log_computer_errors` in the config.

Then test again. If it's still happening, can you upload your logs?

**Comment by SquidDev** [comment]
Closing for now due to lack of user response. Happy to reopen if someone can reproduce this.
