### ISSUE TITLE
Game crashes when turtle get blown up

### ISSUE THREAD

**Issue by MoarDm** [SquidDev-CC/CC-Tweaked#462]
- Minecraft version
1.15.2
 - CC: Tweaked version
1.87.1
 - Detailed reproduction steps
Turtle was running custom excavation program
*most likely* Then it attacks creeper and get blown up in response
It happened 3 times. 
The last thing I heard before the game crashed was the sound of an explosion.
I tried to reproduce it in creative but without proper result

- Crashlog
`java.lang.IllegalArgumentException: Cannot get property DirectionProperty{name=facing, clazz=class net.minecraft.util.Direction, values=[north, south, west, east]} as it does not exist in Block{minecraft:air}`
https://gist.github.com/MoarDm/f00f8f433cb28a4237f0da9899062ee0

**Comment by SquidDev** [comment]
Very odd - turtles shouldn't be blown up by explosions. And the tile should most definitely not be being ticked if the block is gone.

**Comment by MoarDm** [comment]
I found the explosion cause. It is not creepers.
This is Stella Arcanum ore block from mod Forbidden & Arcanus.
It explodes when mined.

**Comment by SquidDev** [comment]
Sorry for the delay with this. Just sat down and tried to reproduce it - I'm unable to recreate the crash using Forbidden Arcanus 1.3.1 and CC:T 1.88.1. Stella explodes and destroys the turtle, but doesn't cause any further issue.

Could you try with just those two mods, and see if it still occurs on your end?
