### ISSUE TITLE
When i place a MiningTurtle the game crashes.

### ISSUE THREAD

**Issue by cyberpunkbln** [SquidDev-CC/CC-Tweaked#463]
#85  Useful information to include:
 - 1.15.2
 - cc-tweaked-1.15.2-1.88.1
 - I create a turtle with a diamond pickaxe and want to place it and then the game crashes.
[debug.log](https://github.com/SquidDev-CC/CC-Tweaked/files/4715373/debug.log)
[crash-2020-06-02_09.00.38-server.txt](https://github.com/SquidDev-CC/CC-Tweaked/files/4715376/crash-2020-06-02_09.00.38-server.txt)

**Comment by SquidDev** [comment]
This appears to be a bug in Silents Mechanisms. They are depending on the 1.14.2 version of CC: Tweaked, and so aren't implementing the API correctly.

Can you report it to them instead?

**Comment by cyberpunkbln** [comment]
[https://github.com/SilentChaos512/Silents-Mechanisms/issues/83#issue-628959951](https://github.com/SilentChaos512/Silents-Mechanisms/issues/83#issue-628959951)
