### ISSUE TITLE
Ability to return Functions from peripherals.

### ISSUE THREAD

**Issue by BastouP411** [SquidDev-CC/CC-Tweaked#466]
Hey I tried something like that but it didn't work.
```java
@LuaFunction
public final Function<String, String> test() {
    return (t) -> {
        return "Test " + t;
    };
}
```
So I assume that it is impossible to return functions.
Would it be possible to add such a feature ?
Thanks ^^

**Comment by SquidDev** [comment]
I guess it would be possible to allow returning something similar to a `ILuaCallback`, but one which accepts `IArguments`. Handling the more generic `Function<_, _>` (and other functional interfaces like `Consumer<_>`) is much harder to do.

Just curious as to what the use-case is here? I guess it's not something we've really needed before, so rather curious.

**Comment by BastouP411** [comment]
I would use it for defining functions in Prepared SQL request-like system with object oriented lua with a Database peripheral.

**Comment by BastouP411** [comment]
Like you'd do:
`local r = db.prepareTableCreation()`
and then 
`r.executeRequest()`
or

**Comment by SquidDev** [comment]
If you just need a table of objects, you can just return another object with `@LuaFunction`. For instance,

```java
public final TableBuilder prepareTableCreation() {
  return new TableBuilder();
}

public static class TableBuilder {
  @LuaFunction
  public final Object executeRequest() { return null;  } 
}
```

**Comment by BastouP411** [comment]
That's like, exactly what I needed, thanks ^^
