### ISSUE TITLE
[1.15.2] PC crashes entire server

### ISSUE THREAD

**Issue by mcjojo3** [SquidDev-CC/CC-Tweaked#468]
Soo whenever i place a CC pc in the world it automaticly crashes the game which isn't that nice. Here is the Crash Report: https://pastebin.com/DSaxSVjZ

**Comment by SquidDev** [comment]
Duplicate of #463. This is an issue with Silent Mechanisms, but should be fixed now.

**Comment by mcjojo3** [comment]
Ohh alright im sorry to waste your time but one hella fast support!

**Comment by SquidDev** [comment]
No worries! Just checked - Silent mechanisms 0.7.2 should include the fix :).
