### ISSUE TITLE
Forge cc-tweaked-1.15.2-1.88.1.jar computercraft-common.toml missing

### ISSUE THREAD

**Issue by GamesArsenal96** [SquidDev-CC/CC-Tweaked#469]
I was gonna go edit some features for the mod like turtles not requiring fuel or other things but the config file "computercraft-common.toml" won't generate anymore on version 1.88.1
Latest.log:
[latest.txt](https://github.com/SquidDev-CC/CC-Tweaked/files/4755396/latest.txt)

**Comment by GamesArsenal96** [comment]
If more info is needed please let me know

**Comment by GamesArsenal96** [comment]
![explorer-06-43-43 PM](https://user-images.githubusercontent.com/24835664/84211568-3d0d3400-aa81-11ea-93de-daa2f96e4450.png)

All generated config files + Mods Installed

![explorer-06-44-59 PM](https://user-images.githubusercontent.com/24835664/84211617-5f9f4d00-aa81-11ea-939a-2a5f615b4646.png)

**Comment by GamesArsenal96** [comment]
Tried version 1.87.1 and it generated it again
So 1.88.0 and 1.88.1 are broken

**Comment by SquidDev** [comment]
The common config is no longer used - it's now split between the client and server config. The latter can be found in each world directory.
