### ISSUE TITLE
Add ability to read NBT with turtle.getItemDetail()

### ISSUE THREAD

**Issue by Naheulf** [SquidDev-CC/CC-Tweaked#471]
## Useful information to include:
 - Explanation of how the feature/change should work :
When use turtle.getItemDetail() on a item(stack) the return should also include NBT data
To keep compatibility with previous version an optional arg "includeNBT = false" can be added.

 - Some rationale/use case for a feature. My general approach to designing new features is to ask yourself "what issue are we trying to solve" and _then_ "is this the best way to solve this issue?".
This would be very usefull to sort items based on they enchantments (to only keep enchants we don't already have)
Currently the only way to deal with the combinatorial explosion of enchantments is to use a very large amounts of NBT filters from other mods.

**Comment by lupus590** [comment]
What about having it as a config option? Maybe with backlist and whitelist?

**Comment by Egyember** [comment]
A white / black list woud be better in my opinion because it would have better compatibility with other mods.
