### ISSUE TITLE
disk.lua:155: No such method ejectDisk

### ISSUE THREAD

**Issue by Assile** [SquidDev-CC/CC-Tweaked#472]
Hi,

I'm running into this error when trying to use the command 'eject left' on my drive when it has a disk in it. When it is empty it let's me know there is no disk, as it should. However with a disk in it I get 'disk.lua:155: No such method ejectDisk'.

Additional info
- Minecraft version: 1.15.2
- CC: Tweaked version: cc-tweaked-1.15.2-1.88.1.jar
- Forge version: 31.2.0
- Other mods:
  - jei-1.15.2-6.0.0.4.jar
  - MixinBootstrap-1.0.3.jar
  - OptiForge-MC1.15.2-0.1.22.jar
  - preview_OptiFine_1.15.2_HD_U_G1_pre23.jar
- The only other thing I've tried to do so far is running LuaIDE, which had several severe bugs, so I removed it again.
- From my turtle it also gives the error when trying 'eject bottom'. (Turtle is place on top of drive)
- I'm trying to run the command 'eject left' from an advanced computer with a disk drive placed to its left.

![2020-06-11_21 45 59](https://user-images.githubusercontent.com/7506207/84432447-1ab81980-ac2d-11ea-94ff-210f72f2cb73.png)
![2020-06-11_21 46 36](https://user-images.githubusercontent.com/7506207/84432449-1be94680-ac2d-11ea-9de2-a5168e429c06.png)
![2020-06-11_21 46 39](https://user-images.githubusercontent.com/7506207/84432450-1be94680-ac2d-11ea-935d-41cda02422bf.png)

Best regards,
Assile

**Comment by SquidDev** [comment]
And fixed. Thank you for the report!

**Comment by Assile** [comment]
You're welcome! Thanks for continuing to support this amazing mod!
