### ISSUE TITLE
Question: Command Computer usage in Survival?

### ISSUE THREAD

**Issue by GamesArsenal96** [SquidDev-CC/CC-Tweaked#479]
I have been seeing in update release notes that a new config option to allow this has been added but I can't find it

CC-Tweaked: cc-tweaked-1.15.2-1.89.1.jar
Mc: 1.15.2

**Comment by Kan18** [comment]
It seems like the configuration option is "command_require_creative":
https://github.com/SquidDev-CC/CC-Tweaked/blob/2a8efb3fd53409acf23e8610ddc024f374868267/src/main/java/dan200/computercraft/shared/Config.java#L124
Here's an image:
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/24967425/85240617-c409c700-b406-11ea-95ab-9c1de6ab9f63.png">
(you can find this menu in Esc Menu -> Mod Options -> CC: Tweaked -> Config)

**Comment by GamesArsenal96** [comment]
@Kan18 Yes I seem to be missing that functionality
![javaw-12-40-20 AM](https://user-images.githubusercontent.com/24835664/85252518-8cf4df00-b421-11ea-8ae3-e451d5f33534.png)

**Comment by GamesArsenal96** [comment]
Ah hah so I may not be an idiot for once, it may be a bug

**Comment by Lupus590** [comment]
Configs are different between 1.12 and 1.15. in 1.15 some server side configs live in the world folder.

**Comment by GamesArsenal96** [comment]
That config sadly isn't in the world-side folder, I looked

**Comment by SquidDev** [comment]
Yep, apparently this got lost when merging into the 1.15 branch.

**Comment by GamesArsenal96** [comment]
When roughly will the next update come out for the commit so I can download a fix?

**Comment by SquidDev** [comment]
There's not really a schedule for these, so it'll happen when it happens. Minecraft 1.16 comes out today, so they'll probably be another set of releases once Forge is out for that.

In the meantime, you can [download the mod from our CI server][download].

[download]: https://github.com/SquidDev-CC/CC-Tweaked/actions/runs/143488038
