### ISSUE TITLE
Non [a-z0-9_.-] character in namespace of location data.lua.treasure

### ISSUE THREAD

**Issue by EP1CSAUC3** [SquidDev-CC/CC-Tweaked#481]
Minecraft version: 1.14.4 
Forge version: 28.1.71
CC: Tweaked version: 1.89.0-1.89.1
Mods: 
- CraftTweaker 5.0.1.162
- CC: Tweaked
- JEI 6.0.0.27

After attempting to run it 2 possible crashes can occur:

**1)** _Non [a-z0-9_.-] character in namespace of location data.lua.treasure_
Which is caused by the capital letters of directories/files inside _data.lua.treasure_
**Replication**: running the treasure disk program **'alongtimeago'**
**Solution**: copy program contents from mod files to a program within your word/computercraft

**2)** _Rendering Block Entity/Tesselating Block model_
Caused by adding another monitor or removing one
**Replication**: running the treasure disk program on more than 1 monitor then break one of the monitors beside the computer
**Solution**: World edit computer + all peripherals out of the game or break the computer 

If neither happen another error might occur while running _alongtimeago_ in either disk or local programs: 
**bios.lua:503 bad argument #1 to 'load' (expected function or string, got nil)**

I was able to replicate this with source code and fix the namespace problem but not "bios.lua:503 bad argument #1". **I have attached images and a log below**. This is my first bug report, hopefully it helps and sorry if I have made any mistakes

Error while loading it from disk/moving it in source code to **src\main\resources\data\computercraft\lua\rom\programs\fun**
![image](https://user-images.githubusercontent.com/8611095/85365279-e3bdef80-b4d9-11ea-9c7f-dfa5d178ffc2.png)

Working after copying contents of alongtimeago to "test" program on pc. _"monitor left test"_
![image](https://user-images.githubusercontent.com/8611095/85365256-d6a10080-b4d9-11ea-9f37-c46789f049a1.png)

**Log:**
[crash-2020-06-22_01.28.16-client.txt](https://github.com/SquidDev-CC/CC-Tweaked/files/4817349/crash-2020-06-22_01.28.16-client.txt)

**Comment by SquidDev** [comment]
> **1)** Non `[a-z0-9.-]` character in namespace of location `data.lua.treasure._`

Treasure disks have been deprecated for a long time now (since 1.79) so I'm afraid this is probably not going to be fixed. In 1.15 they were torn out entirely, and [replaced with a datapack](https://github.com/SquidDev-CC/treasure-disks) which _does_ fix this issue.

> **2)** Rendering Block Entity/Tesselating Block model
> Caused by adding another monitor or removing one

This has been fixed in 1.89.1 (see #476) - from the crashlog it appears you were running 1.89.0 at the time. I see you're now running 1.89.1, so hopefully this shouldn't happen again - if it does, please say!
