### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by xVodkaX** [SquidDev-CC/CC-Tweaked#483]
thermal expansion with CC:Tweaked not have command getMaxStored() from cache, and command getMetadata(), hardness == 10 and 10 for cache upgrade hardened and reinforced

modpack direwolf 1.12.2

**Comment by SquidDev** [comment]
Mod integration issues are generally a problem with [plethora](https://github.com/SquidDev-CC/plethora) - that's what adds most integration code. That said, the Direwolf20 pack doesn't include either CC: Tweaked or Plethora, so I've no idea how you've placed a computer.
