### ISSUE TITLE
Turtle move command causes server crash - possibly caused by CarryOn mod

### ISSUE THREAD

**Issue by PieceOfSteel** [SquidDev-CC/CC-Tweaked#485]
CC version: 1.86.2
Minecraft version: 1.12.2

This might be the responsibility of the CarryOn author, but I'll post here just in case it happens to be fixable on this end. Apologies if it's already been fixed in a newer version. If a turtle has been moved with the CarryOn mod, issuing a movement command causes a server crash due to a NullReferenceException in the TurtleBrain class (see attached crash log). 

Reproduction steps:
Pick up turtle using the shift + right click feature from CarryOn
Put the turtle down on a different block
Enter lua command mode
Enter a movement command, such as forward() or back()

Putting the turtle down on the same block that it was picked up from, breaking and replacing the turtle or restarting the server prevents the crash. So the issue seems to be that ComputerCraft still stores the old position of the turtle even after it's been moved this way. 

[crash-2020-06-29_16.01.27-server.txt](https://github.com/SquidDev-CC/CC-Tweaked/files/4846053/crash-2020-06-29_16.01.27-server.txt)

**Comment by SquidDev** [comment]
I'm afraid the 1.12 version of CC:T is no longer being maintained.

Once #643 has been fixed on Carry On's end, turtles should work as expected.
