### ISSUE TITLE
Possible item duplication on melee attack kill

### ISSUE THREAD

**Issue by calculusrobotics** [SquidDev-CC/CC-Tweaked#486]
To start off, thanks for maintaining ComputerCraft! It's one of my favorite mods and it's great to see it's still maintained by someone.

Minecraft: v1.12.2
CC: Tweaked: v1.12.2 1.89.1
Other mods, if needed: Mr Crayfish's furniture, Galacticraft + ExtraPlanets, Just Enough Items, Opifine

When I place a melee turtle and have it constantly attack and kill me, every time it kills me all my items in my inventory are duplicated. When I come back to the turtle once I've respawned, the items it picked up + the overflow on the floor combined have twice the inventory I had before I was killed. I did make some minor changes to the code to make turtle animations last 4 ticks and make turning also use up fuel, but I don't think this is affecting anything since I tried it with the original version and got the same result too.

Program used:
```Lua
while true do
    turtle.attack();
end
```

Thanks in advance!

**Comment by SquidDev** [comment]
Should be fixed in 1.89.2. Thank you for spotting and reporting this - rather worried it's been in the code for so long!
