### ISSUE TITLE
turtle.compareTo always returns true

### ISSUE THREAD

**Issue by neumond** [SquidDev-CC/CC-Tweaked#489]
## Useful information to include:
 - Minecraft version: 1.15.2
 - CC: Tweaked version: 1.89.2

With any slot index, any block (or lack of) in front of turtle, any inventory content, always returns true.
`compare`, `compareUp`, `compareDown` seem to be working correctly.

**Comment by SquidDev** [comment]
`turtle.compareTo` operates on two different stacks, IIRC? It compares the currently selected slot to the one given as an argument.

**Comment by neumond** [comment]
> Compare the current selected slot and the given slot to see if the items are the same. Returns true if they are the same, false if not. 

My bad.
