### ISSUE TITLE
Monitors are see-through and bg colors don't show in console

### ISSUE THREAD

**Issue by HydrantHunter** [SquidDev-CC/CC-Tweaked#492]
#85  Useful information to include:
 - Minecraft version: 1.12.2
 - CC: Tweaked version: 1.89.2

I can see through monitors in my test world as seen in these screen shots...

![2020-07-04_14 23 01](https://user-images.githubusercontent.com/6239915/86521246-0ec21080-be03-11ea-9ab7-33a2a82b7399.png)
![2020-07-04_14 23 22](https://user-images.githubusercontent.com/6239915/86521252-1aadd280-be03-11ea-990c-79d908b06dee.png)
![2020-07-04_14 23 48](https://user-images.githubusercontent.com/6239915/86521254-213c4a00-be03-11ea-9574-22ab38981e32.png)

and background colors don't show in the console...

![2020-07-04_14 23 53](https://user-images.githubusercontent.com/6239915/86521263-37e2a100-be03-11ea-9e80-13ffcd9054e5.png)

**Comment by SquidDev** [comment]
This is a problem with the resource pack you are using - the font texture was changed slightly and you'll need to update it. 

The fix is to draw a white square in the bottom right of `term_font.png`. I believe 64x64 pixel should be enough, but tended refer to the one in the repo for reference!
