### ISSUE TITLE
Monitor Viewing Range Restricted

### ISSUE THREAD

**Issue by joshiwoshi2005** [SquidDev-CC/CC-Tweaked#494]
Hi,

A group of us run a server where we build virtual stages. We have installed the CCTweaked plugin and tried to use some monitors on stage as a video wall. Is there any way we can extend the maximum size of the monitos and when we walk a certain distance away, the inner part of the monitor (That displays the video feed) dissapears, is there any way we can stop that happening?

Thanks in advance for your help,
Josh

**Comment by SquidDev** [comment]
>  Is there any way we can extend the maximum size of the monitors

This has recently been added (#475) but has not yet been released - should be available in the next few days.

> is there any way we can stop that happening?

I'm afraid not currently. Monitors use the same render limits as any tile entities, so that's entirely controlled by Minecraft. It might be possible to configure, I'll have a prod.

**Comment by joshiwoshi2005** [comment]
Thanks for your reply.

I'm looking forward to that update!

Thanks for your help,
Josh
