### ISSUE TITLE
IPeripheral.getType() collides with upsteam TileEntity.getType()

### ISSUE THREAD

**Issue by LemADEC** [SquidDev-CC/CC-Tweaked#496]
## Useful information to include:
 - Minecraft version 1.15.2
 - CC: Tweaked version 1.15.2-1.89.1.
 - Detailed reproduction steps:
Since at least Minecraft 1.14, TileEntity class has an existing getType() method that crashes with CC IPeripheral getType() method.
Historically, this method name is pretty generic and "sub-optimal"; it should probably be called getPeripheralType() or getPeripheralName().

Currently, the API still says it's a valid option to implement IPeripheral at the tile level (through it's no longer recommended). Above issue makes it impossible.

Since no other mods are depending on CC for 1.15+, I suggest to rename getType() to something more specific.

**Comment by LemADEC** [comment]
On similar note, the MethodResult methods are taking `arguments` parameters that are actually `results`. I suggest to rename them for clarify.

**Comment by SquidDev** [comment]
See #398.
