### ISSUE TITLE
Mod Freeze on server

### ISSUE THREAD

**Issue by Alexon100** [SquidDev-CC/CC-Tweaked#497]
Hey, today I decided to test CC:Tweaked on my server. Nice mod, but the mod freezes after a few hours and i can't use the computers, the screens also freeze. The server is still running fine, but the processor increases to 100% on the server when the mod freezes. Only restarting the server helps, but it will probably crash again after a few hours. The problem is not on the server side.

Mod version: 1.89.2, Minecraft version: 1.12.2, and Forge version 14.23.5.2854 (client and server)

How i can repair this bug? 

Thanks in advance for your help!

ps. sorry for my bad English

**Comment by Lemmmy** [comment]
allocate more deditated wam

**Comment by Alexon100** [comment]
> allocate more deditated wam

Wam or RAM? I allocate 4 GB of RAM, and just 2GB is used on server.

**Comment by SquidDev** [comment]
Hrmr, I can't think of anything within CC's code which would cause 100% CPU usage. It might be worth installing [Spark](https://github.com/lucko/spark) or using [VisualVM](https://visualvm.github.io/) to profile your server, and see if there's any obvious performance hotspots.
