### ISSUE TITLE
[1.16.1] java.lang.NoSuchMethodError:

### ISSUE THREAD

**Issue by realTIMematrix** [SquidDev-CC/CC-Tweaked#498]
Hi,

the game crash with the latest 1.16.1 forge version

Minecraft: 1.16.1
Forge: 32.0.69
cc-tweaked-1.16.1-1.90.0.jar

Steps to reproduce:

1. Start game
2. Create new single player game in creative
3. Crash when the game reaches nearly 100% and try to join the world

[Minecraft Crash Report](https://pastebin.com/ypQCUx1F)

[Latest Log](https://pastebin.com/XsibDEiv)

**Comment by SquidDev** [comment]
Haha, of course Forge changed things in the last few days.

**Comment by SquidDev** [comment]
Fixed in the next release, which should be up in a few minutes.
