### ISSUE TITLE
Unable to use generics peripherals

### ISSUE THREAD

**Issue by Naheulf** [SquidDev-CC/CC-Tweaked#501]
### Description of the Issue

Unable to use the new generics peripherals. Even with vanilla stuff.

### Steps to Reproduce the Issue

1. Create a new world (or use a existing one)
2. Close the world
3. Open <worldFolder>/serverconfig/computercraft-server.toml
4. Turn "generic_peripherals" to true
5. Save change
6. Run the world
7. Place a computer or a turtle
8. Place a chest or furnace above the computer
9. Try to wrap/use the chest/furnace as peripheral

### Expected Behavior

The chest should appear as generic inventory peripheral.

### Actual Behavior

Do nothing. As if there air/dirt block.
- peripheral.names() doesn't list this tile entity.
- peripheral.wrap("top") return nil
- no event was fired when the chest/furnace is placed or removed

### Debug Information
 - Minecraft 1.15
 - CC: Tweaked 1.90.0
 - Related to #452

**Comment by SquidDev** [comment]
Well, that's very odd. It works perfectly in development but not at all in actual Forge.
