### ISSUE TITLE
1.16.1 not working, needing "language provider javafml:31"

### ISSUE THREAD

**Issue by LilZcrazyG** [SquidDev-CC/CC-Tweaked#503]
When trying to launch forge, the only mod to have a problem on 1.16.1 is this one, so from my (limited) knowledge of mods I think I may be missing a file or a supporting mod? 

[17:05:16] [Render thread/FATAL]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod File cc-tweaked-1.15.2-1.90.0 (1).jar needs language provider javafml:31 or above, and below 32 to load
§7We have found 32.0

this line right here is where I think the most info of the problem is, ill attach the log anyway for someone to read. Thank you!!

[latest.log](https://github.com/SquidDev-CC/CC-Tweaked/files/4944759/latest.log)

**Comment by lurr** [comment]
>cc-tweaked-1.15.2-1.90.0 (1).jar
Download a newer version of CC Tweaked for 1.16.1 instead of 1.15.2, such as https://www.curseforge.com/minecraft/mc-mods/cc-tweaked/files/3008226

**Comment by LilZcrazyG** [comment]
> > cc-tweaked-1.15.2-1.90.0 (1).jar
> 
> Download a newer version of CC Tweaked for 1.16.1 instead of 1.15.2, such as https://www.curseforge.com/minecraft/mc-mods/cc-tweaked/files/3008226

Thank you so much!
