### ISSUE TITLE
Disk audio playing doesn't affect parrots.

### ISSUE THREAD

**Issue by devomaa** [SquidDev-CC/CC-Tweaked#507]
## Useful information to include:
 - Minecraft version: 1.12.2
 - CC: Tweaked version: SC (3.29)
 - Detailed reproduction steps: sometimes I can spot a bug pretty easily, but often it's much more obscure. The more information I have to help reproduce it, the quicker it'll get fixed
    1. Get a MC parrot and tame it.
    2. Get a disk drive
    3. Get any "positive" Music Disc (things like cat, etc)
    4. Put disc in Disk Drive
    5. Get a computer
    6. Play the disc.
    7. Profit.

**Comment by SquidDev** [comment]
Parrots do an explicit check for jukeboxes within the area - it's doesn't provide any way to have other music sources. I believe any modded sound system has the same issue. 

Sadly this one is impossible to fix without a core mod, and it doesn't seem worth the PR to forge.
