### ISSUE TITLE
Computercraft folder being generated in main game folder instead of save folder

### ISSUE THREAD

**Issue by GamesArsenal96** [SquidDev-CC/CC-Tweaked#509]
Versions:
  Minecraft: 1.16.1
  Forge: 1.16.1-forge-32.0.75
  CC-Tweaked: 1.16.1-1.90.2

Mods:
   CC-Tweaked
   Optifine

The 'computercraft' folder where all computers save their data is now generating in the main game folder instead of the save folders. This is now not allowing per world id # sets. So the next world you create won't reset the computer id it will just add into it
![explorer-09-06-50 PM](https://user-images.githubusercontent.com/24835664/88496883-2153e380-cf84-11ea-8537-24e5143d3d36.png)

Recreating:
  Make a world
  Place down a pc
  Open it and type: `edit test`
  Press enter
  Save it
  Then go into your main game folder and it will be there instead of the save

**Comment by SquidDev** [comment]
Heh, woops. I thought I'd fixed this, but apparently not - there's still a big fat TODO sticking in `IDAssigner`.
