### ISSUE TITLE
Some sort of indicator lights in the bottom of the GUI

### ISSUE THREAD

**Issue by Lemmmy** [SquidDev-CC/CC-Tweaked#51]
Perhaps in the bottom left of the terminal border? The purpose of it should be to indicate if the computer is on/off, as well as a brief flash when the computer is restarting (as it is currently impossible to tell if a computer rebooted when a startup program draws nothing)

Here's a very crude mockup of what I'm thinking of:
![](https://i.imgur.com/friE68H.png)

It could be green when on, dark grey when off, and ensure a brief flash (0.25s?) when rebooting.

**Comment by vpontin** [comment]
@rolandoislas But would a gradient like this be compatible with the retro-like design of CC?

**Comment by SquidDev** [comment]
There's a bit of me which would like to add more of a GUI to computers (buttons to shutdown (and reboot?) as well as indicator light), but I'm really not sure if it's possible to add it while looking aesthetically pleasing. 

I suspect you'd have to make the bottom fatter, or add some additional sidebar or something. If people have mockups or ideas, I'd love to see them

**Comment by Lemmmy** [comment]
![](https://you.wouldnot.download/a-selective-dory.png)

**Comment by SquidDev** [comment]
I do quite like that. I'm not sure about the gradient on the buttons, though that's definitely me nitpicking.

There's a bit of me which wonders if it'd be better to flip that around, so the power button is on the RHS. Computer monitors _generally_ have their buttons there, so it'd kinda make sense.

I'd almost want to put the label at the top (as that's where it goes in other GUIs), but that's not going to look especially nice. Alas.

**Comment by Lemmmy** [comment]
![](https://you.wouldnot.download/a-fellow-confirmation.png)

**Comment by Lemmmy** [comment]
Here is one with turtles, with smaller buttons etc:

![](https://you.wouldnot.download/an-accused-smoke.png)

It looked very bizarre with the large buttons from before, this looked a little better. This is just slightly smaller than the chest header.

**Comment by Jummit** [comment]
I think the design in the OP looks the best, because its just a little detail instead of the whole bottom bar of the computer being buttons.

**Comment by 1vannn** [comment]
I'm sorry for bringing up an old topic, but what about instead of just a power light, perhaps an indicator light, like when it's waiting for something or gets stuck in a loop (also could be waiting). So if a computer is waiting for a user to enter a password, or an event to happen, it's yellow, indicating that the computer is busy and isn't just "available" and when it is "available", it turns green again. So it's multipurpose and an indicator.

**Comment by SquidDev** [comment]
No worries about bumping this - it's still very much in a "let see what people think" stage, as I'm not entirely sure the best way to approach this.

A computer's state in-world does change depending on whether it is waiting for user input (well, namely if `term`'s cursor is blinking or not), so it would be possible to integrate that into the indicator. However, I'd be a little more reluctant to do something about whether it's waiting for _any_ event as you'll end up with something which blinks a lot (and really, computers should be waiting for events almost all the time anyway).

**Comment by hugeblank** [comment]
How about instead of explicitly saying "POWAH" and "REBOOT" (kinda obnoxious), we just use their respective icons: 
<img src="https://user-images.githubusercontent.com/16393543/52531593-8d795380-2ccc-11e9-846f-26fcac5df140.png" width="100"> <img src="https://user-images.githubusercontent.com/16393543/52531603-af72d600-2ccc-11e9-92fa-c9b2f42ae0a6.png" width="100">

**Comment by nevercast** [comment]
If we are adding an indicator, surely it should be programmble RGB from Lua, right? 😁 

Imo, I like smaller graphics/less chrome. Somewhere between the Turtle screenshot and hugeblank's images. The OP but slightly bigger, and on the right hand side. I don't think we need seperate buttons for power and reboot, since reboot is functionality equivilent to a power off/on cycle. This makes the UI simplier. I also think the button can be shared with the indicator.

Excuse my rushed MSPaint job.

![image](https://user-images.githubusercontent.com/834342/57259753-cd29be80-70b4-11e9-8830-4bc1c4f015f7.png)

**Comment by SquidDev** [comment]
Revisiting this issue as I'd quite like to add shutdown and terminate buttons to the computer GUI, and had a go at adding buttons down the side. Little did I account for my inability to do pixel art:

![image](https://user-images.githubusercontent.com/4346137/119734909-85c92300-be73-11eb-8dc9-f465fc53ec64.png)

Not sure if the iconography or actual concept is flawed.

I don't know if other people have thoughts on having buttons down the side instead? IMO it gives us a little more flexibility in terms of what can go there, but I have no clue how well it works.

**Comment by fatboychummy** [comment]
IMO a restart button isn't required if you have a power button -- just click it twice.

> ![image](https://user-images.githubusercontent.com/4346137/119734909-85c92300-be73-11eb-8dc9-f465fc53ec64.png)

I like this, though I'm unsure what the `?` button will do. Is it just a placeholder?
I believe doing it this way would also simplify adding more buttons like that. Addon mods could even hook into it and insert their own side-buttons.

**Comment by Lupus590** [comment]
Maybe take the icons from OC for testing purposes? Just so that you can tell if it's the icons or the concept.

**Comment by SquidDev** [comment]
> I like this, though I'm unsure what the ? button will do. Is it just a placeholder?

Very much placeholder. Notionally this is a "view documentation" button, but given that functionality doesn't exist, somewhat moot.

> Maybe take the icons from OC for testing purposes? Just so that you can tell if it's the icons or the concept.

The trouble here is that OC's icons are an entirely different dimension (16x16) to what I've got in the screenshot above (9x9 or something weird).

**Comment by SkyTheCodeMaster** [comment]
> Very much placeholder. Notionally this is a "view documentation" button, but given that functionality doesn't exist, somewhat moot.

Well, CC: Tweaked can use HTTP, why not have it be a browser for https://tweaked.cc/ ?

**Comment by Lupus590** [comment]
I like the idea of locally stored docs, it means that you can know that the local docs are relevant to the version of the mod that you are using.

**Comment by fatboychummy** [comment]
Isn't there that in-game-wiki mod? Could it be possible to hook the `?`
button into that somehow (if it still even exists in 1.16, iirc it was a
1.12 mod)

**Comment by Merith-TK** [comment]
fabric has `patchouli`, which gives player a handbook to a mod when they do something (craft an itme, enter a biome, etc)

**Comment by SquidDev** [comment]
In-game documentation was discussed in depth during #133, including locally stored docs and patchouli.

I'm open to it being discussed, but it's probably offtopic for this issue

**Comment by SquidDev** [comment]
Fixed in #809
