### ISSUE TITLE
NoSuchMethodError when loading mod.

### ISSUE THREAD

**Issue by RobotLeopard86** [SquidDev-CC/CC-Tweaked#521]
- 1.15.2
 -1.90.0 and 1.90.2

##IMPORTANT: I had two other mods on when trying to load this one, so ignore things like that. I am also playing on a Mac, if that messes things up.

- Other Mods (potentially error sources):
LeopardCraft (my own mod, which you probably didn't know about until now)
SecurityCraft (you might've heard about this, and maybe you've played it)

 - Bug Notes: Happens in common_event phase,
bug appears to be a missing method in the proxies and network handlers for the mod.

- Notes: I have played this mod for 1.12.2, and it worked fine. So it might be local to 1.15.2 versions.

-Logs:
I have attached both the latest.log and debug.log files, in case you need to look at both:
[debug.log](https://github.com/SquidDev-CC/CC-Tweaked/files/5047430/debug.log)
[latest.log](https://github.com/SquidDev-CC/CC-Tweaked/files/5047431/latest.log)

Also, this mod is amazing, keep up the good work.

**Comment by SquidDev** [comment]
Thanks for the report! Can you include logs and a crash report please? It's very hard to determine _which_ method is not found without any additional information :).

**Comment by RobotLeopard86** [comment]
Sure. Here they are: 
[debug.log](https://github.com/SquidDev-CC/CC-Tweaked/files/5048348/debug.log)
[latest.log](https://github.com/SquidDev-CC/CC-Tweaked/files/5048349/latest.log)

If that doesn't work. I don't know what will.

**Comment by RobotLeopard86** [comment]
Note: That will provide a download.

**Comment by SquidDev** [comment]
Are you sure those are the correct logs? Neither of them appear to include the crash you've mentioned.

**Comment by RobotLeopard86** [comment]
It did not crash. Keep that in mind.

**Comment by SquidDev** [comment]
Right, OK. However, the error doesn't appear to occur in these logs - I can't see any trace of `NoSuchMethodError` within them.

**Comment by RobotLeopard86** [comment]
Looks like that log was overwritten. I'll get the right ones to you tomorrow.

**Comment by RobotLeopard86** [comment]
I had been playing my redstone testing world.

**Comment by RobotLeopard86** [comment]
I've got the new logs and a quick note: my forge version was 31.1.14, if that helps.

[debug.log](https://github.com/SquidDev-CC/CC-Tweaked/files/5048366/debug.log)
[latest.log](https://github.com/SquidDev-CC/CC-Tweaked/files/5048367/latest.log)

Also, just a quick reminder, I have SecurityCraft and my own mod, LeopardCraft on. Also, LeopardCraft is in progress, so if you see errors like missing model for something, that is probably why.

**Comment by SquidDev** [comment]
Right - it appears I were missing a version constraint inside `mods.toml`. We require a later version of Forge than you're using, but I'd failed to declare that. Updating to `31.1.41` (or later) should  resolve this.
