### ISSUE TITLE
Crash when increasing MipMap value to 4 from 0

### ISSUE THREAD

**Issue by EddwardR** [SquidDev-CC/CC-Tweaked#523]
##  Useful information to include:
 - Minecraft version: 1.16.1
 - CC: Tweaked version: 1.90.3
 - Crashlog:
[crash-2020-08-11_09.05.18-client.txt](https://github.com/SquidDev-CC/CC-Tweaked/files/5055964/crash-2020-08-11_09.05.18-client.txt)

 - Detailed reproduction steps: Load up pack with MipMaps set to 0, once loaded go into Options, set mipmaps straight to maximum and let resources reload.

**Comment by SquidDev** [comment]
Can you update to Forge 32.0.108? I believe this hs been fixed in the latest Forge version.

**Comment by EddwardR** [comment]
Sure, going to check

**Comment by EddwardR** [comment]
Yeah, that fixed it.

**Comment by SquidDev** [comment]
Great! Forge recently changed how model loaders were handled, and I think they're still working out the kinks.
