### ISSUE TITLE
[Aesthetic] Custom characters

### ISSUE THREAD

**Issue by R93950X** [SquidDev-CC/CC-Tweaked#524]
I'm not entirely sure of how defining a character would work, but I think a custom 5x7 character could be stored as a variable.
maybe defined with a table storing 1s and 0s like images are stored but only 2 characters rather than 16

Use case: custom fonts or uncommon characters

**Comment by SquidDev** [comment]
I'm not opposed to this on a thematic level - after all, computers of the retro era that CC draws from often had character sets whose graphical representations could be changed.

However, I'd want to see a substantially more concrete proposal before even thinking properly about this. Like with unicode (see #435), there's a lot of problems which I can't see any elegant way to avoid.
