### ISSUE TITLE
Turtle is skipping world interactions

### ISSUE THREAD

**Issue by dimaguy** [SquidDev-CC/CC-Tweaked#526]
## Useful information to include:
 - Minecraft version-1.12.2 (Multiplayer)

 - CC: Tweaked version-1.88 (on latest SwitchCraft modpack)

 - Logs: These will be located in the `logs/` directory of your Minecraft instance. Please upload them as a gist or directly into this editor.- https://gist.github.com/dimaguy/38de59c0c748091e35543fb6438fa64f

 - Detailed reproduction steps: sometimes I can spot a bug pretty easily, but often it's much more obscure. The more information I have to help reproduce it, the quicker it'll get fixed:
This bug occurs on SwitchCraft multiplayer server, 

I leave a turtle shoveling snow automatically with statistics of how much snow was obtained (https://pastebin.com/MPJrBUwF the UX is written in portuguese, but the logic is understandable, please tell me if you need me to translate anything).
The turtle is kept loaded using a weirding gadget while I go offline. When I come back my turtle is still counting snow even though it is not getting anything (like as if it skips the digging instruction).
(I was told turtles stop interacting once they are 16 blocks away from the player, but even when I am one block away from the turtle it still doesnt pick anything up until I break the turtle and place it back on)

I also have a turtle that has a similar issue, but with placing concrete powder to make concrete, which makes me believe the same bug happens with any kind of placing/breaking blocks interations.

Everything the turtles interact with is within the same chunk, I used f3+G to confirm so.

**Comment by SquidDev** [comment]
SwitchCraft runs Sponge, which ~breaks~ changes lots of block handling code and sometimes causes problems. Could you try to reproduce this in a fresh single player world, running CC:T 1.89.2?

**Comment by dimaguy** [comment]
I was unable to reproduce this in single player world. the turtle always worked correctly

**Comment by SquidDev** [comment]
Great, thanks for testing. I'm going to close this, as this is most likely a Sponge bug. I'm afraid no longer really supporting 1.12, but you might have some luck asking around on the Sponge discord.
