### ISSUE TITLE
Server crash with Mining Turtles

### ISSUE THREAD

**Issue by TheCoolestPaul** [SquidDev-CC/CC-Tweaked#531]
## Useful information to include:
 - Minecraft 1.16.2
 - CC: Tweaked 1.91.0
 - Logs: These will be located in the `logs/` directory of your Minecraft instance. [gist](https://gist.github.com/TheCoolestPaul/5d641cc9beb3d014afe2af4a44528ea5)
 - Detailed reproduction steps: I have a mining turtle that makes a mine shaft by places stone and mines every block that isn't stone, then replaces it with cobblestone.

**Comment by SquidDev** [comment]
Thank you for the report! Should be fixed in the next release.
