### ISSUE TITLE
Mining Turtle code not working

### ISSUE THREAD

**Issue by Xandersmash** [SquidDev-CC/CC-Tweaked#538]
I have used this exact code in the past but for some reason in the pack im playing it doesn't work anymore I followed the instructions just like normal but when it asked to press c for chest and other commands it wouldn't work I even just tried skipping the step by just pushing enter and that didn't work either. heres the pastebin code: 6qmBBLpz

**Comment by Xandersmash** [comment]
This Pastebin works instead: bfJuxUgn

**Comment by xAnavrins** [comment]
Whoever made this script was not aware of the `keys` api and hardcoded their key values instead of using `keys.c` and `keys.enter`.
A somewhat recent update to LWJGL changed those value, the `keys` api was updated accordingly, but any script that uses hardcoded values will break because of it.

**Comment by SquidDev** [comment]
As Anavrins mentioned, [there were several unavoidable changes in the 1.12 → 1.13 update](https://github.com/SquidDev-CC/CC-Tweaked/wiki/Incompatibilities-between-versions#minecraft-112-to-113), one of which changed the key codes.

It should be fairly easy to fix on your end - just replace them with the appropriate `keys.$whatever` values.
