### ISSUE TITLE
Allow whitelisting specific ports on IP

### ISSUE THREAD

**Issue by alxpettit** [SquidDev-CC/CC-Tweaked#540]
It would be nice to have the option to whitelist ports on IPs.

Current implementation allows you to block or allow the entirety of 127.0.0.1 -- either giving computer full access to your loopback device, or no access at all. In my use case, I want to build a local wireless shell for debugging/development, that doesn't require giving the turtle access to your entire machine. Allowing a specific port dedicated to this purpose would make this a lot easier.

**Comment by SquidDev** [comment]
I have a feeling I meant to do this as part of the original reimplementation of HTTP filtering, or at least discussed it as a future enhancement.

Either way, should be possible to specify rules to match specific ports, and thus allowing specific ones.

**Comment by alxpettit** [comment]
Pretty awesome of you to add it so quickly, regardless. Thank you! :D
