### ISSUE TITLE
OreDictionary Dyes in the printer

### ISSUE THREAD

**Issue by Tomodachi94** [SquidDev-CC/CC-Tweaked#541]
Hi GitHub,
I was playing a modpack the other day, and noticed there isn’t support for oredictionary dyes in the printer! A tiny suggestion, but one that can enhance the feel of CC:T!

**Comment by Lemmmy** [comment]
What MC version? Looks like it does in 1.15:

https://github.com/SquidDev-CC/CC-Tweaked/blob/275ca58a82c627128a145a8754cbe32568536bd9/src/main/java/dan200/computercraft/shared/peripheral/printer/TilePrinter.java#L303-L306

Whereas in 1.12, it did not:

https://github.com/SquidDev-CC/CC-Tweaked/blob/37a447e745a27b66b670c756e8209d3127fce556/src/main/java/dan200/computercraft/shared/peripheral/printer/TilePrinter.java#L342-L345

**Comment by SquidDev** [comment]
@Lemmmy Nah, that just checks if it's a vanilla dye. The point of the tag system (ore dictionary in 1.15) is that people can register arbitrary items as dyes.

We already do this for the dye recipes, so should be very easy to do for printers as well.

https://github.com/SquidDev-CC/CC-Tweaked/blob/275ca58a82c627128a145a8754cbe32568536bd9/src/main/java/dan200/computercraft/shared/util/ColourUtils.java#L41-L50

**Comment by Tomodachi94** [comment]
Ah, I was playing on 1.12.2, is that no longer supported?

**Comment by Tomodachi94** [comment]
Yeah, I was playing with Botania and Thermal Expansion, which both have variants of the vanilla dyes (flower petals and "pigments," respectively.)

**Comment by SquidDev** [comment]
> Ah, I was playing on 1.12.2, is that no longer supported?

Yeah, I'm afraid 1.12.2 support was dropped [when 1.16 came out][drop], as I can't really manage 3 versions of Minecraft. It's fairly stable, and will receive critical fixes if needed, just not any new features.

[drop]: http://www.computercraft.info/forums2/index.php?/topic/29161-mc112fork-cc-tweaked/page__view__findpost__p__279476

**Comment by Tomodachi94** [comment]
Thank you anyways for fixing this on such short notice!
