### ISSUE TITLE
FishyTurtle

### ISSUE THREAD

**Issue by alxpettit** [SquidDev-CC/CC-Tweaked#545]
Fishing is a very boring repetitive task. There are many mods that automate this, but they do so in uninteresting ways that don't tend to have much challenge. It should be possible to equip a turtle with a fishing rod and make a FishyTurtle, and automate it via programming! :D

**Comment by SquidDev** [comment]
I'm tagging this as "won't fix" for now, as I'm inclined to say it'd be better suited to an external mod, such as Plethora (hah, as if it'll ever be updated). As always, would like to hear other people's thoughts though.

From what I remember, fishing rods are nasty (see SquidDev-CC/plethora#116) and make lots of assumptions that don't hold up for turtles. There's a reason most mods just magic fish out of nowhere :p.

**Comment by alxpettit** [comment]
@SquidDev aww that's a real shame. Seems like it'd be possible to do with Fabric mixins... I'd offer to contribute code, but the Fabric version is downstream. :S

**Comment by alxpettit** [comment]
I could contribute the mixin code to the [downstream Fabric-based project,](https://github.com/mystiacraft/cc-tweaked-fabric) and then maybe you could consider up-porting it using [MixinBootstrap](https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap)?

**Comment by SquidDev** [comment]
I think the upstream one is actually [this project](https://github.com/Zundrel/cc-tweaked-fabric) :p.  I'd definitely recommend opening an issue there too - they've got a couple of other features which aren't in CC, so might be receptive to this too.

Forge has native support for Mixin now, so one shouldn't need to depend on MixinBootstrap. That said, I'm pretty reluctant to make CC:T a core mod. I've done enough [core mod hackery](http://github.com/SquidDev-CC/CCTweaks) in the past, and while it's safer nowadays, it's still something I'd rather not do.

**Comment by alxpettit** [comment]
@SquidDev whoops! Sorry about that. Really shouldn't github when I just woke up.

**Comment by alxpettit** [comment]
In Forge-land, everything that manipulates game code is considered core mods? In Fabric mixins are just kinda standard. You just do them in ways that maximize compatibility.

**Comment by alxpettit** [comment]
You'll have to forgive my lack of familiarity. I never modded with Forge.

**Comment by SquidDev** [comment]
Yeah, literally anything which "modifies the core of the game". Forge's preference is that any (major) hooks belong in Forge, as that way they can ensure things work with each other and make it much easier to debug things.

Obviously the issue with that model is that it's much harder to get these changes in, but when they're there for everyone.

**Comment by alxpettit** [comment]
With Fabric mixins, it's pretty powerful and it's usually possible to do it in a sneaky way that shouldn't mess up anyone else's code. I could try to implement this with the Fabric version after talking to some veteran Fabric modders ... maybe a separate optional coremod library for making fishing by fake players easier in general could be created, for the Forge solution?

**Comment by Devan-Kerman** [comment]
it's Sponge's mixin not Fabric's*

**Comment by alxpettit** [comment]
@Devan-Kerman They didn't make any changes from upstream code? :P

**Comment by Devan-Kerman** [comment]
some minor tweaks to make it work for fabric, it used to have some changes but they're gone now

**Comment by alxpettit** [comment]
Ah. So it's basically just copied and pasted straight from Sponge. Very interesting!
