### ISSUE TITLE
On Lua and development environment

### ISSUE THREAD

**Issue by alxpettit** [SquidDev-CC/CC-Tweaked#550]
So I'm still trying to write code for ComputerCraft in VSCode. I'm using the recommended extension pack. My biggest frustration so far is that I'm not shown if members are unknown/nonexistent. Is there a way to get my IDE to detect and warn me of these things?

**Comment by Lupus590** [comment]
People have said that you can mount the ROM in the Lua sever exstention, I've never done it so I don't know if it will fix your issues. FatBoyChummy, on the Discord, I believe is one of the people who has done it.

**Comment by SquidDev** [comment]
I'm afraid I don't use the Lua server extension so can't comment on it. As Lupus says, you're probably better off asking folks on the Discord about that.

CC: Tweaked itself is linted [using illuaminate](https://github.com/SquidDev/illuaminate/), which catches a reasonable number of problems. It's still a long, long way from feature complete - it doesn't have a proper type checker, so only really tracks members on the module level. It's on the road map, ... so PRs welcome I guess????

That said, I haven't actually got it working with CC:T as an external module. Again, something which needs to be done, but a) haven't figured out a nice way to do it and b) not an immediate priority right now. I have too many projects on the go :).
