### ISSUE TITLE
Water shows through pocket computers

### ISSUE THREAD

**Issue by Pechu317** [SquidDev-CC/CC-Tweaked#557]
<img width="460" alt="Screen Shot 2020-10-16 at 9 37 11 AM" src="https://user-images.githubusercontent.com/51034477/96265229-304e9e80-0f93-11eb-999a-3b0dfa7aa4bb.png">

water shows through pocket computers. using 1.12.2-1.89.2
using shaders right now, but it shows without them as well.

**Comment by SquidDev** [comment]
I'm afraid the 1.12 version of CC:Tweaked is no longer maintained. This doesn't appear to be an issue on 1.15:

![image](https://user-images.githubusercontent.com/4346137/96306136-ff07ba00-0ff6-11eb-9ba2-e9733e74e761.png)
