### ISSUE TITLE
Logging out of the game and logging back in again causes turtles to stop executing their current commands.

### ISSUE THREAD

**Issue by ultranine** [SquidDev-CC/CC-Tweaked#558]
## Useful information to include:
 - Minecraft version: 1.16.3
 - CC: Tweaked version: 1.93.0
 - Logs: These will be located in the `lo gs/` directory of your Minecraft instance. Please upload them as a gist or directly into this editor.
 - Detailed reproduction steps: sometimes I can spot a bug pretty easily, but often it's much more obscure. The more information I have to help reproduce it, the quicker it'll get fixed.

-Open a world and run a turtle.
-Close out of the game.
-Rejoin the world. The turtle will have stopped executing the command you gave it.

**Comment by SquidDev** [comment]
This is expected behaviour. ComputerCraft/CC:Tweaked has never saved a program's state. See #535 for some discussion on the technical challenges, and some future plans on making it possible.
