### ISSUE TITLE
running script blocks getting advancements

### ISSUE THREAD

**Issue by DanielJutz** [SquidDev-CC/CC-Tweaked#564]
Having a turtle in a loaded chunk that is running the script
`while true do turtle.suck() end`
prevents the user from getting any achievements. This includes granting an achievement via in-game command

minecraft version 1.16.3
cc version 1.93.1
forge version 34.1.35 (issue identical on previous versions)

video shows in detail how to reproduce issue
https://youtu.be/jaRnpXFLC5I

**Comment by SquidDev** [comment]
Sorry for the delay in responding, but just wanted to say thank you for the report! Very useful reproduction step.s

This has definitely lain dormant in CC for a wee while, so impressed you managed to spot it (and narrow it down to CC). Thanks!

**Comment by DanielJutz** [comment]
My pleasure. Thanks for your work, it is fun learnung lua!
