### ISSUE TITLE
Multiple Ink Colors in Printer

### ISSUE THREAD

**Issue by Tomodachi94** [SquidDev-CC/CC-Tweaked#573]
Hey CC:T,
Thought of the limitations of the printer, namely ink. Ink is always limited to one color, perhaps we should consider changing that?

**Comment by Lupus590** [comment]
You can have several printers and reprint on top of pages to apply new colours onto them, the previous content is preserved if it is not overwritten (kinda like terminals). This is a bit more anoying than one block that could do all of it but one could plauseably make an API which moves the page through several printers with different inks.

**Comment by Lemmmy** [comment]
Using turtles/inventory transfer methods you can easily swap out ink colours, so personally I don't think any additional changes are necessary in the mod

**Comment by SquidDev** [comment]
As others have mentioned, this is possible to do already. I know it's a bit more of a faff, but I'm not sure it's worth adding a more complex printer given their already pretty niche use-cases.
