### ISSUE TITLE
Read-only Floppy Disks

### ISSUE THREAD

**Issue by Tomodachi94** [SquidDev-CC/CC-Tweaked#574]
Hey CC:T,
Perhaps make a ROM Disk?

**Comment by Lupus590** [comment]
Treasure disks had this behaviour. Personally I think it would be cool if users could right-click disks or maybe craft them to convert them back and forth from read-only to read and write.

**Comment by Tomodachi94** [comment]
Or, perhaps have a "signing" feature similar to that of the Book and Quill?

**Comment by KlutzLament** [comment]
Something like the old practices of punching out the write protect notch or taping over it to make it writable.

**Comment by SquidDev** [comment]
This was somewhat discussed in #254, and there wasn't much discussion of the use-cases. What sort of things are people wanting to do with r/o floppies?

**Comment by Tomodachi94** [comment]
Perhaps they want a ROM signed by a trusted in-game developer so that there is evidence there is no tampering (unless the author tampered with it...)
