### ISSUE TITLE
Add documentation pages for CC: Tweaked's Java API

### ISSUE THREAD

**Issue by MCJack123** [SquidDev-CC/CC-Tweaked#578]
Now that tweaked.cc is pretty solid with Lua documentation, it might be a good idea to add Java docs as well. I noticed that the API files have Javadocs already in the source, but I haven't found anywhere they are actually used to generate documentation. It would be helpful to mod authors to also have this documentation available on tweaked.cc, possibly under a separate page for the Java API. It would also consolidate the descriptions scattered around the source files into one central set of doc pages.

This should essentially require two (or three) things:
* Add Javadoc generation when building the tweaked.cc doc source
* Add links in the HTML sources to the newly-created Java documentation
* Possibly stylize the Java pages differently? (It might look neat to have the background or something be a different color to indicate that this is the Java documentation, not the Lua documentation.)

**Comment by Seniorendi** [comment]
Sounds good.

**Comment by SquidDev** [comment]
The documentation is now available at https://tweaked.cc/javadoc/ - I've added a link to the README.
