### ISSUE TITLE
Digging turtles don't dig grass blocks

### ISSUE THREAD

**Issue by bradyakent** [SquidDev-CC/CC-Tweaked#581]
- Minecraft version: 1.16.3
- CC: Tweaked version: 1.93.1 (the default for 1.16.3 on CurseForge)

It seems that when using any of the dig methods with a digging turtle, the turtle uses the shovel to make a grass path instead of picking up the block. If the turtle is on top of the grass block and you run `turtle.digDown()`, nothing will happen as the path block can't be made with another block on top of it.

To reproduce, place a digging turtle facing a grass block, then run `turtle.dig()`.

**Comment by SquidDev** [comment]
This is working as intended. In the same way hoes on dirt make farmland, shovels on grass make paths. 

See https://github.com/dan200/ComputerCraft/issues/127 for the original feature request

**Comment by bradyakent** [comment]
ah, gotcha.
