### ISSUE TITLE
[Question]API PeripheralProvider

### ISSUE THREAD

**Issue by Seniorendi** [SquidDev-CC/CC-Tweaked#587]
Hey, I want to be able to connect my block to a modem, but I have the problem that I can now connect every block in Minecraft to a modem.

![image](https://user-images.githubusercontent.com/67484093/99878600-ff533080-2c06-11eb-9986-cd823b85b5ff.png)

Here's my code: https://hasteb.in/junixina.java

Thanks for any help

## Useful information to include:
 - Minecraft version: 1.16.4
 - CC: Tweaked version: 1,94.0

**Comment by SquidDev** [comment]
Your peripheral provider basically looks like this:
```java
@NotNull
@Override
public LazyOptional<IPeripheral> getPeripheral(@NotNull World world, @NotNull BlockPos blockPos, @NotNull Direction direction) {
    return LazyOptional.of(() -> new AdvancedPeripheral("lightSensor"));
}
```

This doesn't contain any checks, which means it'll return an `AdvancedPeripheral` for _every_ block, not just `LightSensor`. You probably want something like:

```java
@NotNull
@Override
public LazyOptional<IPeripheral> getPeripheral(@NotNull World world, @NotNull BlockPos blockPos, @NotNull Direction direction) {
    BlockState block = world.getBlock(blockPos);
    return block.getBlock() instanceof LightSensor
      ? LazyOptional.of(() -> new AdvancedPeripheral("lightSensor"))
      : LazyOptional.empty();
}
```

**Comment by Seniorendi** [comment]
Thank you!
