### ISSUE TITLE
Server Optimisation

### ISSUE THREAD

**Issue by seagemgames** [SquidDev-CC/CC-Tweaked#59]
This runs horribly on servers, even if there is 1 player online. If it ran better I could see myself using it a lot more. This is very useful for private chatrooms/servers, but it just isn't all there... :/

**Comment by SquidDev** [comment]
I've not noticed any performance issues, and know of several servers where it is used mostly without issue. 

It would be very useful if you could provide numbers to show the problem, such as a visualvm sampler session, or TPS comparisons with vanilla CC/no CC.

**Comment by seagemgames** [comment]
Well, when I am hosting a server on my own pc, or my friend does on his (Note that I have enough ram and my CPU is barely being tasked), we get large ping between typing and the text appearing inside the computer. No other mods installed, 1.12.2

**Comment by SquidDev** [comment]
That's strange, I've definitely not had that problem on my local servers. Not quite sure what's going on. 

Can you try with vanilla ComputerCraft to check it's not a regression.

**Comment by seagemgames** [comment]
Not sure what you mean by vanilla CC, but as singleplayer, it works fine.

**Comment by SquidDev** [comment]
> Not sure what you mean by vanilla CC

ComputerCraft from https://minecraft.curseforge.com/projects/computercraft instead of the CC:T page.

**Comment by Lemmmy** [comment]
Is this a fresh world?

Can you share the output of `/forge tps` after your server has been running for about 5 minutes, and you 
have at least one player online?

**Comment by seagemgames** [comment]
Well, it's just input delay. I didn't even mean to fork as well lol.

Regular forge server, official build. Will show output, it's a bearable amount of ping, just unwanted.

**Comment by seagemgames** [comment]
Alright, it _was_ a fresh world, but upon loading my gps map, the issue seems to have faded... not sure why, but it did, thanks for all the help, and sorry for the useless issue.

**Comment by Lemmmy** [comment]
If you're done with this issue, please click the close button.
