### ISSUE TITLE
Paper Server Support

### ISSUE THREAD

**Issue by JPGlaser** [SquidDev-CC/CC-Tweaked#590]
Hey @SquidDev , 

Just a curiosity here. Paper and Fabric have overtaken Forge in terms of stability, performance and modularity with the vanilla Java client. I was curious if there was any plans to push for a fork of CC-Tweaked for these types of server backsides?

~ Joe G.

**Comment by SquidDev** [comment]
Fabric support is currently handled by the [CC: Restitched](https://www.curseforge.com/minecraft/mc-mods/cc-restitched) project. I do not have plans to handle Fabric support myself, as one mod loader is quite enough :).

AFAIK, Paper is server-side only, which doesn't work for mods which require client-side content (such as blocks, GUIs, etc...).
