### ISSUE TITLE
Player parameter to monitor touch event

### ISSUE THREAD

**Issue by terickson001** [SquidDev-CC/CC-Tweaked#596]
## Useful information to include:
 - Add an extra parameter to the `monitor_touch` giving the entity (Or player name) that triggered the event
 - Allows for more possibilities when multiple players are interacting with the same monitor

**Comment by SquidDev** [comment]
This is one of those issues which is awkward, because I get that they're useful, but I don't think they fit with one of CC's main design choices - "don't break the fourth wall".

I think it's hard in this case to argue that monitor would know who is touching it.

**Comment by Lupus590** [comment]
All monitors have fingerprint scanners built into the screen? My phone has one, granted it doesn't cover the whole screen but it is in the screen.

**Comment by terickson001** [comment]
Understandable, I was just thinking about it usability-wise, not design-wise
