### ISSUE TITLE
Add back ComputerCraft.cfg

### ISSUE THREAD

**Issue by PeterM5** [SquidDev-CC/CC-Tweaked#598]
I can't find the ComputerCraft.cfg that was in the original ComputerCraft mod.

Is there still a config file for this fork?

I tried adding a ComputerCraft.cfg to the config directory, to set 'turtlesNeedFuel' to false. 

Is there a way to do this with this fork? If not, I suggest there should be a method for doing this.

**Comment by PeterM5** [comment]
Found how to accomplish what I wanted to do.
I wanted to prevent turtles for needing fuel.
There is now a different config file called computercraft-client.toml
You can accomplish the desired effect of turtles not needing fuel by adding the following line
```TurtlesNeedFuel=false```

I have noticed bug that when I add ```TurtlesNeedFuel=false``` and start the game, the config file is reset (with the new changes active).

**Comment by Lupus590** [comment]
Newer MC or forge changed how configs work, they are now toml files and server side stuff is not in the world folder.

**Comment by SquidDev** [comment]
As @Lupus590 mentioned, the location of configuration files has changed a bit in recent versions of ComputerCraft. See [this bit of the wiki](https://github.com/SquidDev-CC/CC-Tweaked/wiki/Incompatibilities-between-versions#minecraft-114-to-115) for where the new files are located.
