### ISSUE TITLE
Game crashes when getDirection and other methods are called on a CC Monitor

### ISSUE THREAD

**Issue by Rusettsten** [SquidDev-CC/CC-Tweaked#600]
- Minecraft version **1.16.4**
 - CC: Tweaked version **1.94.0**
 - Logs: [https://pastebin.com/qRXSZa8j](https://pastebin.com/qRXSZa8j)
 - Detailed reproduction steps: Happens randomly. I do not know how to reproduce the error, but I go maybe 30min-1hr playing and then the game always crashes with this same error.

**Comment by SquidDev** [comment]
Well this is fun - looks like a monitor tile is present, but a block isn't. I'd guess there's some weird race condition where a monitor is rendered just as it's unloaded on the client. Either that or the world is corrupted in some funky way :).
