### ISSUE TITLE
Not able to pull items from a chest to a turtle using peripheral

### ISSUE THREAD

**Issue by iridiumlynx** [SquidDev-CC/CC-Tweaked#601]
I can't transfer items from/to a wrapped chest peripheral using pullItem() or pushItem(). These methods just move items in the same inventory, without a possibility to transfer items between multiple inventories. If it was an intended behavior, please make a method of transferring items between _specific_ slots of _multiple_ inventories (including turtle's inventory).

 - Minecraft version: 1.16.4
 - CC: Tweaked version: 1.94.0
 - Logs: there is no runtime exception, just weird behavior.

Detailed reproduction steps: 
  1. Wrap a storage block, i.e. a chest, as a peripheral
  2. Execute pullItem() on any slots in that storage block.
  3. Watch the item being transferred from a slot in inventory to another slot in the same inventory instead of being transferred to the turtle.

**Comment by SquidDev** [comment]
Can you post the code you're running, as well as a screenshot of your question? I tested this fairly recently, so am pretty sure it works.

**Comment by Lupus590** [comment]
@SquidDev I think they are trying to have the turtle be the target of the generic peripheral method. I don't think you added support for that.
