### ISSUE TITLE
Turtles interacting with beehive causes crash

### ISSUE THREAD

**Issue by coolkaja** [SquidDev-CC/CC-Tweaked#607]
## Useful information to include:
 - Minecraft version
 - CC: Tweaked version
 - Logs: These will be located in the `logs/` directory of your Minecraft instance. Please upload them as a gist or directly into this editor.
 - Detailed reproduction steps: sometimes I can spot a bug pretty easily, but often it's much more obscure. The more information I have to help reproduce it, the quicker it'll get fixed.

Minecraft version: 1.16.4
CC: Tweaked version: 1.94.0
-I believe the crash is caused by the turtles interacting with beehives in some way. In my world I have a turtle that chops down trees. The trees ocasionally generate beehives. Breaking the beehives, attempting to move into a space occupied by one, or calling turtle.inspect() on beehives spawned in creative doesn't seem to cause a crash. The crashes only seem to occur when beehives are present in the treefarm. 

[crash-2020-12-13_20.06.16-server.txt](https://github.com/SquidDev-CC/CC-Tweaked/files/5685236/crash-2020-12-13_20.06.16-server.txt)
[crash-2020-12-13_19.49.34-server.txt](https://github.com/SquidDev-CC/CC-Tweaked/files/5685237/crash-2020-12-13_19.49.34-server.txt)
[crash-2020-12-13_18.20.55-server.txt](https://github.com/SquidDev-CC/CC-Tweaked/files/5685238/crash-2020-12-13_18.20.55-server.txt)

**Comment by SquidDev** [comment]
So the problem here is that beehives attempt to get a list of all nearby players when broken. This is safe normally, as a player will be within range. However, as turtles aren't players, the list is empty and so code blows up later on.

Sadly there's nothing which can be done on CC's end. I imagine this'll require a patch to Forge.

**Comment by SquidDev** [comment]
I've submitted a patch to Forge with a fix for the above issue.

**Comment by SquidDev** [comment]
This should now be fixed in the latest Forge version.
