### ISSUE TITLE
Computer/Turtle/Pocket not working in SinglePlayer

### ISSUE THREAD

**Issue by Shiranuit** [SquidDev-CC/CC-Tweaked#61]
I haven't seen this issue before, i don't know if i'am the only one to have it
- [x] Minecraft 1.12.2
- [x] CC-Tweaked 1.80pr1.7
- [x] Forge 14.23.4.2730

Everything work well in multiplayer, but when i go in singleplayer, computer/turtle/pocket nothing works, the computer seems to be On but seems to not be booting up when trying to open a computer, the computer GUI is locked on this:
![image](https://user-images.githubusercontent.com/19224148/43676865-36625b90-97f9-11e8-9364-0da8cf6079ba.png)
![image](https://user-images.githubusercontent.com/19224148/43676913-212f4138-97fa-11e8-8959-bc884fc8dfbc.png)

Am i doing something wrong ?

**Comment by Shiranuit** [comment]
Plethora V1.1.12
Peripheral+1 V1.1 Build-T58
nbtperipheral-1.1

**Comment by SquidDev** [comment]
It appears the fix is still on their develop branch, and so hasn't been put out as a stable release. Could you try [Build T65](https://minecraft.curseforge.com/projects/peripheralsplusone/files/2590463) instead - that _should_ have the fixes.

**Comment by Shiranuit** [comment]
I tested with only CC-Tweaked and Plethora installed and i still have the issue

**Comment by SquidDev** [comment]
OK, that is curious. Would you mind enabling `logPeripheralErrors`, restarting and retrying and then attaching the resulting logs? CC should log any issues which might stop the computer from booting correctly.

**Comment by Shiranuit** [comment]
Where are the CC logs stocked ? I enabled logPeripheralErrors but couldn't find them

**Comment by SquidDev** [comment]
Should just be the main logs directory. If you're on a recent Forge version, should be `logs/latest.log` and `latest/debug.log` - if in doubt just delete the directory, rerun and then copy everything.

**Comment by Shiranuit** [comment]
Here they are
[latest.log](https://github.com/SquidDev-CC/CC-Tweaked/files/2259519/latest.log)
[debug.log](https://github.com/SquidDev-CC/CC-Tweaked/files/2259520/debug.log)

**Comment by SquidDev** [comment]
Hrmr, this is very curious. There's definitely an issue with the computer _block_ appearing to be off until it receives a block update, but I cannot manage to produce anything where the GUI doesn't display.

There's nothing in the logs, which is even stranger. If the Lua VM was crashing, I'd be expecting to see something there. 

I'm not really sure what else to suggest here - any other information you can think of would be incredibly useful. It may be worth running `/computercraft dump`, or `/computercraft view #<computer id>` to see if you can interface with it that way.

Sorry!.

**Comment by Shiranuit** [comment]
I've tried `/computercraft dump` and `/computercraft view #<computer id>` but nothing worked

Quick update, CC was working but not CCTweaked so i cleaned up my Minecraft folder, and now CCTweaked seems to work well in singleplayer, i still do not know what was the reason that make the computers did not worked correctly

**Comment by Lemmmy** [comment]
I think Peripherals+1 had left something over in your minecraft folder, quite possibly in your world folder, that was preventing CC:Tweaked from working. If you need to try Peripherals+1 again in the future, make sure to try with Build T65 first (where this issue is patched).

**Comment by SquidDev** [comment]
I tried adding P+1 and then removing it, and it didn't seem to cause any major issues. They do some weird things, but nothing which should cause damage like this...

**Comment by Shiranuit** [comment]
Peripherals+1 Build-T58 work with this version of CC-Tweaked

I Think some mods have let some residues between version 1.11.2 et 1.12.2 but i don't know how it has affected CC-Tweaked but not ComputerCraft, could this have something to do with Cobalt, because in 1.11 i had CCTweaks wich has Cobalt too, have you changed something with Cobalt ?

**Comment by seagemgames** [comment]
PPO had the same issue with the computers freezing like that for someone else. Will edit with link, but if you fly ~32 chunks away and come back does it fix?
