### ISSUE TITLE
Turtle disk loading side

### ISSUE THREAD

**Issue by PhobiaBrixia** [SquidDev-CC/CC-Tweaked#617]
I've tried to replicate a program made by Michael Reeves, only to find out that in this version you cannot do a disk drive startup script loading it from the right side as with old computercraft (where people would choose to put a pickaxe on the right side as to allow the turtle to load the disk), but apparently only from the slit side. Is it intended? And also there's the problem with turtle stacking but there's already another thread open about it.

**Comment by Lupus590** [comment]
When a turtle looks for a peripheral on one of its sides it first checks what's attached to it and attempts to use those. If what it has got attached is not a peripheral or it has nothing attached on that side then it will instead attempt to use the block on that side as a peripheral instead. Tools do not count as peripherals, and so wrapping that side will attempt to wrap the block.
