### ISSUE TITLE
Unable to craft Wireless Advanced Pocket Computer.

### ISSUE THREAD

**Issue by EmeraldImpulse7** [SquidDev-CC/CC-Tweaked#619]
I can't craft a Wireless Advanced Pocket computer, whenever I put it and the wireless modem in the crafting table, it doesn't work. I think it might be due to the ID, but I'm not sure.

I am on the MC version 1.16.4, Forge version 35.1.13, CC Tweaked version: 1.94.0

**Comment by EmeraldImpulse7** [comment]
Nevermind looks like I just had to put them in specific spots.

**Comment by Lupus590** [comment]
Yeah, JEI hasn't been placing the items in the right places for a few people now. Might still be worth looking into.
