### ISSUE TITLE
[Issue] Computers die in singleplayer when you die [with OpenBlocks]

### ISSUE THREAD

**Issue by Shiranuit** [SquidDev-CC/CC-Tweaked#62]
~Hello, I've found a new issue with CC-Tweaked and OpenBlocks in singleplayer but I don't know if this can be fixed here~

- [x] Minecraft 1.12.2
- [x] CC-Tweaked 1.80pr1.7
- [x] Forge 14.23.4.2747
- [x] OpenBlocks 1.12.2-1.7.6

~So the issue is pretty simple, when you have CC-Tweaked (i haven't tested with ComputerCraft) and OpenBlocks installed, when you die in singleplayer with a PocketComputer that is turned on in your inventory, every computers died (they are still On but the Gui is not working, same as mouse and keyboard inputs), you need to unload them to make them working after that~

~This issue is appearing because of the OpenBlocks Grave that spawn when you die and that contain your inventory~

**Comment by Shiranuit** [comment]
Here they are, i haven't tested without plethora so maybe it change something, maybe plethora has somethng to do with this
[debug.log](https://github.com/SquidDev-CC/CC-Tweaked/files/2267449/debug.log)
[latest.log](https://github.com/SquidDev-CC/CC-Tweaked/files/2267450/latest.log)

**Comment by Shiranuit** [comment]
Sorry for this bad issue, im going to investigate wich mod do that, i will reply when found it

**Comment by Shiranuit** [comment]
I'm really sorry for bothering you, in fact the issue was my mod ... I was doing some hacks in the NetHandlerPlayServer (I was just canceling the message of player connection) but for some weird reasons this has an impact when player dies so I removed it and it works perfectly this time

I'm sorry for making you waste your time

**Comment by SquidDev** [comment]
No worries! Glad it's all resolved.
