### ISSUE TITLE
Allow different Gem-based Tools for Turtles

### ISSUE THREAD

**Issue by Flexico** [SquidDev-CC/CC-Tweaked#622]
In older versions of Minecraft and Computercraft, it was possible to equip turtles with Ruby, Sapphire, or Emerald tools from the mod Redpower. The only difference from diamond tools is that the pickaxes couldn't mine obsidian (though I'm open to giving them other debuffs). I really like this feature, as it not only allows for personalization of your mining turtles but can be economical for when you're low on diamonds! A remake of Redpower, called Bluepower, currently [1.16.4] adds Rubies, Sapphires, Amethyst, and Malachite gems that can all be crafted into tools. I'd love to be able to equip them onto turtles!

**Comment by Lupus590** [comment]
There are already ways to do this via craft tweaker integration.

**Comment by SquidDev** [comment]
IIRC, those turtles used to be registered by Redpower itself - it might be worth asking on their issue tracker if they'd be prepared to add it back.

If not, as Lupus says, it's pretty easy to add it using craft tweaker. I'll probably look into kubejs support too, as that seems to be the new thing. I think that's a more sensible apporach than adding per-mod integrations, as it provides much greater flexibility.

**Comment by Flexico** [comment]
Craft Tweaker, huh? I'll have to check this out!

**Comment by Flexico** [comment]
I can't seem to find anything about how to actually code this in!

**Comment by Lupus590** [comment]
See the or it was implemented in: https://github.com/SquidDev-CC/CC-Tweaked/pull/327

**Comment by SquidDev** [comment]
There's also some documentation for how to use it at https://github.com/SquidDev-CC/CC-Tweaked/wiki/CraftTweaker.

**Comment by Flexico** [comment]
I'm trying to use it to add a netherite pickaxe using the code:
[code]dan200.computercraft.turtle.addTool("minecraft:netherite_pickaxe", <minecraft:netherite_pickaxe>);[/code]
but it's saying, "Invalid bracket expression: no prefix minecraft". What does that even mean? It gives a similar response when I try to add the gem tools I'm really aiming for, but says instead, "no prefix bluepower". So of course I tested it with a vanilla MC item to test.
