### ISSUE TITLE
local host not permitted

### ISSUE THREAD

**Issue by PotaytoPrograms** [SquidDev-CC/CC-Tweaked#626]
## Useful information:
 - Minecraft version: 1.16.4
 - CC: Tweaked version: 1.94.0
 
I have a startup file to connect to a websocket server running in Java
*startup.lua*  ` ws, err = https.websocket("ws://localhost:43509")`
*error* `Domain not permitted`
the sever doesn't even receive the websocket

this is probably a very obvious fix but hey it's my first experience with websockets

**Comment by GuimilXD** [comment]
It's not a bug, local IP addresses are not permitted due to security issues. You can disable this by removing 127.0.0.1
from the computercraft-server file located in the serverconfig folder of your save.

**Comment by PotaytoPrograms** [comment]
thanks :)

**Comment by PotaytoPrograms** [comment]
that ip isn't in the config

**Comment by xAnavrins** [comment]
That IP is in there by default, you only need to change `action = "deny"` to `action = "allow"`
It should look like this.
```
[[http.rules]]
	host = "127.0.0.0/8"
	action = "allow"
```

**Comment by PotaytoPrograms** [comment]
yes I tried that but it was just changed back when I re launched the game

**Comment by PotaytoPrograms** [comment]
Oh, i tried it again and it worked, why it didn't work the first time idk but yay :)
