### ISSUE TITLE
Rendering issue when holding printed page in left hand and pocket computer in right hand

### ISSUE THREAD

**Issue by BTCTaras** [SquidDev-CC/CC-Tweaked#63]
![](https://i.imgur.com/b8pFAW0.png)
If you hold printed pages in your left hand, and a pocket computer in your right hand, the printed page will appear to be dark black. It seems to always use this black colour regardless of anything on the pocket computer's screen. You can see that this black rectangle extends behind the frills along the paper's edges. It does not matter if the pocket computer is turned on or not, but there is no problem if the hands are switched. This is on SwitchCraft, CC:T 1.80pr1.6.

**Comment by Lemmmy** [comment]
Looks like someones forgetting to close some gl state
