### ISSUE TITLE
Headphones

### ISSUE THREAD

**Issue by EmeraldImpulse7** [SquidDev-CC/CC-Tweaked#635]
Headphones, everyone knows what they do.
You can put them in the head armor slot or in the hat slot with trinkets.
You can wire them up to a computer if you are close to one, and you can wire them up to a mobile computer as well.
You can also add both Wireless and Ender Modems to them to connect them to a device wirelessly, or the wireless way could be the only way for them to work.

I came up with headphones because I wanted to think of a way to play sounds that only one person can hear.

**Comment by GamesArsenal96** [comment]
Ye maybe they use the Wireless modem like bluetooth or something, and the headphones can maybe have some interaction like some new keybind controls when wearing them so you can send rednet msgs when using them?

**Comment by SquidDev** [comment]
I think this would be a neat feature, but I'm not sure it fits well within CC itself. It might be better suited to a peripheral mod.
