### ISSUE TITLE
Improvement of serializeImpl-function

### ISSUE THREAD

**Issue by magiczocker10** [SquidDev-CC/CC-Tweaked#636]
Change the beginning of the serializeImpl-function to the following
![grafik](https://user-images.githubusercontent.com/59317952/103306468-eb70ca80-4a0d-11eb-93e0-0b5f96910f9b.png)

This would allow the user to use the same table within a table without triggering the recursive table errormessage. But a table within it self would still trigger the error.

Without change:
![grafik](https://user-images.githubusercontent.com/59317952/103306591-34288380-4a0e-11eb-8544-22645e5573c9.png)

With change:
![grafik](https://user-images.githubusercontent.com/59317952/103306728-984b4780-4a0e-11eb-8951-c9f1f5e3f2b4.png)

**Comment by SquidDev** [comment]
I'm afraid I'm probably not going to change this. I think my stance is that unserialization should return a semantically identical table<sup>1</sup> to the original one.

That said, I guess `serialize` could accept an option table like `unserializeJSON` does (possibly also an option to specify whether we emit whitespace or not). I'd definitely accept a PR for that.

[1] Well, ignoring metatables. IMO this was a mistake, but can't change it now :).
