### ISSUE TITLE
Mining turtle dupe

### ISSUE THREAD

**Issue by RoxasLamprunge** [SquidDev-CC/CC-Tweaked#643]
mining turtles seem to duplicate when moved with the carry on mod in valhasia 3  after placing it the turtle is invisible right clicking it will cause a duped turtle to spawn on the block next to the invisible turtle right clicking fast causes a crash. oddly enough after reloading the save i was carrying a turtle instead of a mining turtle. also it dupes what ever is in its inventory when you pick it up

https://user-images.githubusercontent.com/67304114/103455056-6c45f580-4c9e-11eb-93b6-4498acef2a95.mp4

**Comment by SquidDev** [comment]
I've filed a bug on carry on (see above), which should resolve this when fixed. Tracking the cleanup I need to do in #658.
