### ISSUE TITLE
[Feature Request] Renderable item icons on monitors

### ISSUE THREAD

**Issue by uecasm** [SquidDev-CC/CC-Tweaked#646]
The `paint` program and `paintutils` API allow drawing images on Advanced Monitors.  Currently this has to be an image in a custom lua format.

What would be really cool is if in addition to the above, some special table value could be specified that represented a Minecraft item (or block?), most likely containing the content from `inventory.getItemDetail` within some boilerplate that specifies a scale as well as the simple fact that it's an item icon rather than a server-side image.

When a lua program tries to paint this to a monitor, the actual monitor rendering client-side looks up the correct image for the player's current texture pack and draws it (similar to how it would appear in inventory), so it's always the "right" image (and not something rendered server-side... since I don't think the server has access to even the default textures anyway).

Supporting animated icons would be nicer still, but even a static image would go a long way.

I suggest that the "scale" be defined by specifying a coordinate rectangle to draw within (similar to `paintutils.drawBox`) and have it automatically scale the render to fit.  Alternatively, a scale number based on text lines could be used, such that 1.5 is 1.5x the height of a line of text on that particular monitor.

**Comment by SquidDev** [comment]
I'm afraid I think this is one of those issues which I think are cool and useful, but don't fit within CC itself. CC generally tries to emulate a retro aesthetic<sup>1</sup> (hence the limited colour palette, etc...), and I don't think drawing items really fits with that. Having a separate layer of textures on top of the existing "pixel/character grid" also feels a little clunky.

One day Plethora will be updated and we'll have the [neural interface](https://plethora.madefor.cc/items/module-glasses.html) back - that used to provide a system for drawing items in-world.

[1] Perhaps to dubious success at times :).
