### ISSUE TITLE
Minecraft crash

### ISSUE THREAD

**Issue by signormorte** [SquidDev-CC/CC-Tweaked#655]
https://gnomebot.dev/api/guild/file/166630061217153024/254806806516203520/796689053931798529/crash-2021-01-07_11.21.56-client.txt

**Comment by SquidDev** [comment]
Thank you for the report! Would you be able to fill out the information in [this template](https://github.com/SquidDev-CC/CC-Tweaked/blob/mc-1.15.x/.github/ISSUE_TEMPLATE/bug_report.md).

It's a bit hard to work out what you did to reproduce this bug, as the error doesn't occur within CC's code.

**Comment by signormorte** [comment]
Minecraft version: 1.16.4 
Forge version: 1.16.4 - 35.1.32
Mod version: 1.16.4-1.95.0
[2021-01-07-3.log](https://github.com/SquidDev-CC/CC-Tweaked/files/5781337/2021-01-07-3.log)
I only started minecraft from MultiMC but it doesn't even open and immediately crashed error

**Comment by SquidDev** [comment]
Ahh, I see. I'm fairly sure this isn't a CC:Tweaked issue, as we don't touch key binds during the loading process.

There's not really an easy way to debug these issues. I suspect the easiest way would be to remove some mods each time until you can work out the minimal set of mods which causes it.
