### ISSUE TITLE
Startup does not work

### ISSUE THREAD

**Issue by Spacelord09** [SquidDev-CC/CC-Tweaked#659]
> ## Useful information to include:
- Minecraft version: 1.16.4 (AllTheMods6)
- CC: Tweaked version: 1.95.0
- Logs: nothing interesting ;/ (I´m uploading it if necessary or wanted.)

I have a reactor controll computer for BiggerReactors(1.16.4 BigReactors).
Im using [THIS](http://www.computercraft.info/forums2/index.php?/topic/26019-big-reactors-automatic-control-program/) program.
My problem is now that the computer doesnt autostart its startup programm. The reactor is a multichunk build but the computer parts and port(reactor) are in one single chunk thats force loaded with FTBchunks.
If im going to restart the computer manually with "STRG+R" everything works as expected until the next server restart.

Is this problem known? Or does anyone have an idea?

**Comment by SquidDev** [comment]
When you say the startup doesn't work, what happens? Does the computer not turn on at all? I can't think of a reason it'd boot to shell but not run its startup program.

**Comment by LoganDark** [comment]
> I can't think of a reason it'd boot to shell but not run its startup program.

What does `set shell.allow_startup` say?

**Comment by Spacelord09** [comment]
> 
> 
> > I can't think of a reason it'd boot to shell but not run its startup program.
> 
> @Spacelord09 What does `set shell.allow_startup` say?
https://spacecdn.de/img/2021/01/08/2021-01-08_14-55-53-85eb9ddd-19b2-411b-be45-a863e95dbed6.png




> 
> 
> When you say the startup doesn't work, what happens? Does the computer not turn on at all? I can't think of a reason it'd boot to shell but not run its startup program.

I´m going to check that in the evening.

**Comment by Wojbie** [comment]
If it don't start / crashes if only part of reactor is loaded then its possible that it don't have valid peripheral when multichunk multiblock is not properly loaded. IF you were able to catch the error it would be best. Program you linked is not build to handle such case.

Would it be possible to move reactor all into one chunk to remove possibility that is the cause?

**Comment by Spacelord09** [comment]
> 
> 
> If it don't start / crashes if only part of reactor is loaded then its possible that it don't have valid peripheral when multichunk multiblock is not properly loaded. IF you were able to catch the error it would be best. Program you linked is not build to handle such case.
> 
> Would it be possible to move reactor all into one chunk to remove possibility that is the cause?

Thanks ;D thats what I just found out.
I fixed it with the following code:

![image](https://spacecdn.de/img/2021/01/09/2021-01-09_00-34-33-365cbd86-c250-45bd-b3d7-d2c99703fa30.png)

**Comment by Lupus590** [comment]
I'm thinking of the 1.12 big reactors, but there was a method to check if the multiblock was valid, using that might be better than sleeping and hopeing.

**Comment by Spacelord09** [comment]
> 
> 
> I'm thinking of the 1.12 big reactors, but there was a method to check if the multiblock was valid, using that might be better than sleeping and hopeing.

Do you have some reference documentation for me?

**Comment by Lupus590** [comment]
There's a bunch of methods starting with mb for dealing with the multiblock, tested with a reactor in 1.12 and I believe that the same ones will on a turbine. Hopefully, you find something similar for 1.16 I did find that my reactor program for 1.12 didn't work in 1.16.

```lua
mbGetMaximumCoordinate = function: 161d8e8,
mbGetMinimumCoordinate = function: d2650cc,
mbGetMultiblockControllerTypeName = function: 4fbaec45,
mbIsAssembled = function: 582bf02,
mbIsConnected = function: a2b81c2,
mbIsDisassembled = function: 35b4107b,
mbIsPaused = function: 2df40a4c,
```
