### ISSUE TITLE
Turtle don't discover peripheral on side after unequipping internal peripheral.

### ISSUE THREAD

**Issue by Wojbie** [SquidDev-CC/CC-Tweaked#660]
Reproduction steps:
 - Place turtle next to disk drive.
![obraz](https://user-images.githubusercontent.com/5893536/104012320-e222f300-51af-11eb-9351-f1f1ea39466c.png)
- Turtle sees peripheral.
 - Equip internal peripheral (modem/tool) on side disk drive is.
 - Turtle sees internal peripheral.
 - Unequp internal peripheral.
 - Turtle now don't see any peripherals despite disk drive still being there.

Causing any kind of update will make turtle see peripheral again. Turning turtle / removing or adding disk to disk drive ect.

 - Minecraft version: 1.16.4
 - CC: Tweaked version: cc-tweaked-1.16.4-1.95.0

I was also able to reproduce it on Switchcraft CC:T version on 1.12

**Comment by Ronan-H** [comment]
Able to reproduce in:
- MC 1.15.2
- CC 1.95.3

**Comment by SquidDev** [comment]
Fixed in #743.
