### ISSUE TITLE
Could not parse command: java.lang.String cannot be cast to java.util.Collection

### ISSUE THREAD

**Issue by LoganDark** [SquidDev-CC/CC-Tweaked#661]
- Minecraft version: 1.16.4
 - CC: Tweaked version: 1.95.0
 - Logs: Command parsing does not create logs
 - Detailed reproduction steps: `/computercraft queue 1` => runs with no issues. `/computercraft queue 1 something` => fails; since most verification is done client-side, this command is not even sent to the server.
  
    ![](https://user-images.githubusercontent.com/4723091/104022103-ab7bb700-5174-11eb-828b-10ab86e91c62.png)

    Crucially, **this only happens on dedicated servers**, not in singleplayer. That's probably the reason it was missed - because there are very few servers running 1.16.

**Comment by SquidDev** [comment]
Thank you for the report! A little worrying to see how long this has been broken.

**Comment by LoganDark** [comment]
> A little worrying to see how long this has been broken.

Yeah, well hopefully you will be able to iron out more bugs since there is finally a public 1.16 server.
