### ISSUE TITLE
[1.16.4] Crash when used with Create (and/or possible Easy Villagers)

### ISSUE THREAD

**Issue by NillerMedDild** [SquidDev-CC/CC-Tweaked#665]
## Useful information to include:
 - Minecraft 1.16.4
 - CC: Tweaked 1.16.4-1.95.0

Crash report: https://gist.github.com/NillerMedDild/e6145b7b79e00fd1bfb1055cfc6c6616

I am relaying from https://github.com/henkelmax/easy-villagers/issues/32, because [the dev of Easy Villagers stated that this fix would be needed in CC: Tweaked](https://github.com/henkelmax/easy-villagers/issues/32#issuecomment-756644178) as well, see referenced comment and the one below.

I am not certain how to reproduce the issue, but it sounds to me like it's a simple change in Forge that requires a small change from CC: Tweaked.

**Comment by SquidDev** [comment]
Thank you for the report! Should be fixed in the next version.

There's a certain beauty in me bumping the Forge version just as easy-villagers decrements it.
