### ISSUE TITLE
Crash on mining Stella Arcanum 

### ISSUE THREAD

**Issue by Netail** [SquidDev-CC/CC-Tweaked#667]
## Related Issues
#462, #585, #301, #600 

## Useful information to include:
 - **Minecraft version**: v1.15.2
 - **CC: Tweaked version**: v1.94.0
 - **Logs**: [Gist](https://gist.github.com/Netail/13c3eba3c572da60d92406058dd4f096)
 - **Detailed reproduction steps**:
1. Start Mining Turtle's custom mining program
2. Place a Stella Arcanum in the next row, right where the mining turtle has to turn. When the mining turtle has to go straight it does not occur. (See attachment for better understanding)
3. Observe
 - **Attachments**: [Video](https://www.youtube.com/watch?v=LYxqK8T3JvQ)
 - **Possible cause**: The mining turtle gets the command to turn, while the mining turtle does not exist anymore. (Exploded)
 - **Possible solution**: Check if the mining turtle exists before turning.

**Comment by SquidDev** [comment]
Can you try updating to 1.95.0? I'm fairly sure it was fixed in that version.

**Comment by Netail** [comment]
Ah yes, it was resolved in v1.95.0 - None of the issues contained something about the bug being resolved nor did any commits. (As far as I searched) Sorry for bothering. - Happy coding!
