### ISSUE TITLE
BiblioCraft Inventory Errors

### ISSUE THREAD

**Issue by shelbykauth** [SquidDev-CC/CC-Tweaked#67]
## Mods (just the relevant ones)
 - BiblioCraft[v2.4.5][MC1.12.2]
 - cc-tweaked-1.80pr1.7
 - plethora-1.12.2-1.1.12
 - PeripheralsPlusOne-1.12.2-1.2-build-T65

Hello again!  So I decided to make a jukebox with all the records sitting on a BiblioCraft disc rack.  When I try to use any of the functions to actually look at the items (inventory.list(), inventory.getItem(slot), inventory.getItemMeta(slot)), I get "Java Exception Thrown: java.lang.AbstractMethodError"
I tested this with another BiblioCraft item, with the same result.  Although the shelf displays 16 instead of 4 on inventory.size()

That about sums up the bug.  Not sure what else to say.

**Comment by Lemmmy** [comment]
Duplicate of https://github.com/SquidDev-CC/plethora/issues/143 ?

**Comment by SquidDev** [comment]
Sorry, there's absolutely nothing I can do about this. See the issue Lemmmy has linked for a more complete explanation.
