### ISSUE TITLE
.bat equivalen

### ISSUE THREAD

**Issue by RuboGubo** [SquidDev-CC/CC-Tweaked#670]
## Useful information to include:
 - Explanation of how the feature/change should work.
 - Some rationale/use case for a feature. My general approach to designing new features is to ask yourself "what issue are we trying to solve" and _then_ "is this the best way to solve this issue?".

**Comment by Lupus590** [comment]
You can edit these, btw. The title can be edited with the button in the upper right and the body from the three dots in the upper right of the comment.
