### ISSUE TITLE
Http section of the config file is broken in 1.16

### ISSUE THREAD

**Issue by ralphgod3** [SquidDev-CC/CC-Tweaked#684]
## Useful information to include:
 - Minecraft version
 - CC: Tweaked version
 - Logs: These will be located in the `logs/` directory of your Minecraft instance. Please upload them as a gist or directly into this editor.
 - Detailed reproduction steps: sometimes I can spot a bug pretty easily, but often it's much more obscure. The more information I have to help reproduce it, the quicker it'll get fixed.

**Comment by SquidDev** [comment]
![image](https://user-images.githubusercontent.com/4346137/104815164-d5834800-580a-11eb-9573-6677134ed055.png)

Works for me :).

**Comment by ralphgod3** [comment]
for some reason after restarting minecraft a couple of times it works i have no idea why.
i am assuming but i have no way to proof it is that for some reason minecraft doesnt reload configs when you enter a world again. and you need to close it completely to get it to work.

sorry for the bad report.
