### ISSUE TITLE
Terminal contents is not sent on chunk watching

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaked#687]
- Minecraft version: 1.15.2
 - CC: Tweaked version: 1.92.2

## Reproduction steps
 - Place a computer and a monitor to the right
 - Run a program on the monitor (e.g. `monitor right paint a`)
 - Teleport 2000 blocks away, and then 2000 blocks back.
 - The monitor is now blank

I'm not entirely sure why this is. We're meant to send monitor updates when a player starts watching a chunk, so I assume that event is not being fired when it should be.

**Comment by cZollo** [comment]
Yes they seem to be related.
