### ISSUE TITLE
New Texture for Crafty Upgrade?

### ISSUE THREAD

**Issue by Flexico** [SquidDev-CC/CC-Tweaked#689]
![turtle_crafty_face_16x](https://user-images.githubusercontent.com/5751770/105167499-cb04cf00-5ae6-11eb-8222-3a353c83508a.png)
It's always kinda bugged me that the crafting table upgrade is gray when a crafting table is tan/brown! So I made a little replacement texture that I've been using for a while, and I wanted to see if you would want to include it in the official mod~

**Comment by Lupus590** [comment]
You could make this a Pull Request by editing the texture in the repo, it will save SquidDev some time of having to implement the change themself.

**Comment by Flexico** [comment]
Oh, I've never done that before! Lemme try that~

**Comment by Flexico** [comment]
Oh -- it says I don't have push permission?

**Comment by Lupus590** [comment]
You need to clone the repo, make an edit in the clone and then create a pull request.

**Comment by Lupus590** [comment]
I should have said fork the repo not clone. And make the edit in the fork.

**Comment by Flexico** [comment]
Ok I'll try that~

**Comment by SquidDev** [comment]
[GitHub already have a pretty good guide](https://guides.github.com/activities/forking/) which I'd recommend reading, but basically to give a quick set of instructions specific to CC: Tweaked:

 - Fork the repository and clone _your forked repository_ (using GitHub desktop or the like).
 - Replace the texture at `src/main/resources/assets/computercraft/textures/block/turtle_crafty_face.png` with your texture.
 - Make a commit, and push it up to GitHub.
 - Make a PR!

In this case, I wouldn't worry too much about doing though - I'm happy to apply this manually.

**Comment by Flexico** [comment]
Awesome, thank you! I'll be sure to read up before trying again~

**Comment by Flexico** [comment]
> In this case, I wouldn't worry too much about doing though - I'm happy to apply this manually.
Have you added it in yet? I don't see the new texture in v1.95.3!

**Comment by Jummit** [comment]
I made a quick mock up texturepack that just replaces the texture with the crafting table top:

![image](https://user-images.githubusercontent.com/28286961/112754732-b0b30a00-8fdd-11eb-8557-e3480ff0b65b.png)

**Comment by Flexico** [comment]
Oh heck, that's better than my idea! Awesome~

**Comment by Flexico** [comment]
I notice this hasn't been included in the 1.96.0 release! Is there a reason for that?

**Comment by Lupus590** [comment]
Because the PR was not merged due to license issues. This issue would be closed if it was merged.

**Comment by Flexico** [comment]
Oh, because of using the vanilla texture? Could we just use mine instead?

**Comment by SquidDev** [comment]
> I notice this hasn't been included in the 1.96.0 release! Is there a reason for that?

Haven't got round to looking at it yet I'm afraid.

**Comment by Flexico** [comment]
> In this case, I wouldn't worry too much about doing though - I'm happy to apply this manually.

**Comment by SquidDev** [comment]
The two statements are not mutually exclusive :p

**Comment by Flexico** [comment]
Sorry, I interpreted your first statement as you were doing it immediately! XD

**Comment by SquidDev** [comment]
I had a fiddle with using both `minecraft:block/crafting_table_top` and the provided texture, and while I like them, I'm still a little unsure. I think I'm not going to change this for now.
