### ISSUE TITLE
Sending binary websocket frames

### ISSUE THREAD

**Issue by osmarks** [SquidDev-CC/CC-Tweaked#69]
I'd like to be able to send binary messages over websockets. In the absence of any real difference between byte arrays and strings in CC Lua, this would probably involve giving websockets a `sendBinary` method or making `send` take an optional second argument indicating binary mode.

**Comment by nevercast** [comment]
I had to find this feature in the java source, where is good documentation for this?

**Comment by Lemmmy** [comment]
[On the wiki, where everything else is](https://github.com/SquidDev-CC/CC-Tweaked/wiki/http-library#websocketsendmesssage-string-binary-boolean)

**Comment by nevercast** [comment]
Great, thanks @Lemmmy, I was looking for a wiki website and didn't consider Github's wiki.

**Comment by nevercast** [comment]
That's the original computercraft though, correct? Which is outdated and mostly forelorn?

**Comment by SquidDev** [comment]
Nah, [this one](http://www.computercraft.info/wiki/Main_Page) is the ComputerCraft one. Though the CC:T one is somewhat outdated in places (no binary flag there for instance!) - hence #133.
