### ISSUE TITLE
Monitor turns off but computer stays on with the program running.

### ISSUE THREAD

**Issue by cZollo** [SquidDev-CC/CC-Tweaked#692]
I have a program which output things to monitors and the code works well. Only problem is if a player gets too far away the monitor turns off however even with a chunk loader to keep the computer and monitors active the monitor still turns off.

In my code it requires an input so if you put an input to the computer which sends another signal to the monitor it turns back on however the monitor never fully went off because it overlays the information if I don't put a .clear() in. It only turns off as a visual thing.

**Comment by Lupus590** [comment]
related? https://github.com/SquidDev-CC/CC-Tweaked/issues/687
if so then this is already fixed and we might be waiting for a new release

**Comment by cZollo** [comment]
Yes they seem to be related
