### ISSUE TITLE
Mod latest curseforge update does not support 1.16.5

### ISSUE THREAD

**Issue by ModernGamingWorld** [SquidDev-CC/CC-Tweaked#694]
As the title shows, we cant use this mod on 1.16.5

**Comment by SquidDev** [comment]
Ahh, right. It should work, I just haven't marked it as compatible.

**Comment by ModernGamingWorld** [comment]
@SquidDev Could u mark it as compatible so it syncs with curseforges api for 1.16.5, I have an addon for CC Tweaked and till just today I did not know your mod had an update

**Comment by SquidDev** [comment]
Yep, done so. Will also fix up the build script so new releases are marked as such.
