### ISSUE TITLE
Can't push/pull to/from inventories on cable from adjacent inventories

### ISSUE THREAD

**Issue by RGFTheCoder** [SquidDev-CC/CC-Tweaked#697]
## Useful information to include:
 - 1.16.4 Forge 35.1.37
 - CC: Tweaked 1.95.2
 - Logs: [latest.log](https://github.com/SquidDev-CC/CC-Tweaked/files/5868488/latest.log)
 - Detailed reproduction steps: 
 * Place a chest with an item (slot 1) on a wired modem block and connect it 
 * Place a chest left of the computer
 * Run `peripheral.wrap("left").pullItems("minecraft:chest_0",1)`
 * Error: `Target 'minecraft:chest_0' does not exist`

Images:
![Screenshot_20210125_124440](https://user-images.githubusercontent.com/24970643/105744577-588f5700-5f0b-11eb-8ff4-a27d13308922.png)
![Screenshot_20210125_124502](https://user-images.githubusercontent.com/24970643/105744578-5927ed80-5f0b-11eb-95ea-5ce7d96a0e7b.png)
![Screenshot_20210125_124509](https://user-images.githubusercontent.com/24970643/105744579-59c08400-5f0b-11eb-92bf-c017bc99680b.png)
![Screenshot_20210125_124515](https://user-images.githubusercontent.com/24970643/105744581-59c08400-5f0b-11eb-9f98-749fac16a599.png)
![Screenshot_20210125_124523](https://user-images.githubusercontent.com/24970643/105744582-59c08400-5f0b-11eb-88f2-09c6397a6d68.png)
![Screenshot_20210125_124528](https://user-images.githubusercontent.com/24970643/105744584-5a591a80-5f0b-11eb-9709-e2da0fc901d4.png)

**Comment by RGFTheCoder** [comment]
Issue happens on computers and turtles

**Comment by SquidDev** [comment]
As [per the documentation](https://tweaked.cc/generic_peripheral/inventory.html)

>  This allows you to push an item in an inventory to another inventory on the same wired network. Both inventories must attached to wired modems which are connected via a cable.

You can't call `pushItems`/`pullItems` from peripherals wrapped with `left`/`top`, etc... I guess we should probably detect when peripherals aren't on a wired network and produce a more helpful error message.

**Comment by RGFTheCoder** [comment]
I'm able to call pushItems/pullItems of `peripheral.wrap("left")` but can only move to another adjacent inventory. Is that intentional?

**Comment by Wojbie** [comment]
It does seem a bit inconsistent.
![obraz](https://user-images.githubusercontent.com/5893536/105746679-0ae11180-5f40-11eb-944b-a2ce483f6a4c.png)
![obraz](https://user-images.githubusercontent.com/5893536/105746708-13d1e300-5f40-11eb-9e05-23c2c85c71dd.png)
Considering there is no proper way to move items into a turtle from sides other then sucking I am surprised computer can move things between sides. I am guessing unintended feature?

**Comment by SquidDev** [comment]
Basically the sides of a computer form their own network  - hence being able to push from the left to the right. Very much intentional, but probably a mistake as it's not really documented and awkward to describe and reason about. 

Oh well, people are probably relying on this behaviour somewhere, so too late to change it now.

**Comment by RGFTheCoder** [comment]
Cool. I was able to differentiate between all my chests and the adjacent one by using a barrel instead. Thanks for the clarification. Now if anyone has a similar issue they'll be able to figure it out quicker :)
