### ISSUE TITLE
speaker.playSound returns true when it should not

### ISSUE THREAD

**Issue by Jeuvke** [SquidDev-CC/CC-Tweaked#698]
```
local speaker = peripheral.find("speaker")
print(speaker.playSound("notasound"))
```

will return true.
`playSound` will never return false, and only throws when using capital letters, some special characters, or spaces in the sound name.

**Comment by SquidDev** [comment]
This is sadly unavoidable. We've got to choose between playing modded sounds (see https://github.com/dan200/ComputerCraft/pull/578) or returning something useful, and we went for the former.
