### ISSUE TITLE
Byte arrays possible method input

### ISSUE THREAD

**Issue by BastouP411** [SquidDev-CC/CC-Tweaked#699]
Hello ! Would it be possible to allow byte[] as an input for a lua string in a peripheral function.
Like for example:
```java
@LuaFunction
public final byte[] encodeAES128(byte[] data, byte[] key, byte[] iv) throws LuaException {
  ...
}
```
Directly converting the LuaString to a byte array without the possible imprecisions with working with string and encodings.

I hope it is possible, thanks ^^

**Comment by SquidDev** [comment]
I _think_ you can use `ByteBuffer` instead of `byte[]` and it should all just work. Or alternatively use `IArguments.getBytes`.

Basically we want to expose a ByteBuffer instead of a raw array, as it works better with the implementation of strings within the VM.

**Comment by BastouP411** [comment]
Yup, it works like a charm !
Thank you, I didn't know about this :)
