### ISSUE TITLE
Error mounting lua/rom in 1.8.0pr1.9

### ISSUE THREAD

**Issue by Brycey92** [SquidDev-CC/CC-Tweaked#70]
**Versions**
Minecraft version: 1.12.2
CC: Tweaked version: 1.80pr1.9

**Detailed reproduction steps:**
- Place a computer
- Right click it
- This happens:

![image](https://user-images.githubusercontent.com/666399/47477012-0a052680-d7f1-11e8-99dd-b7e51f588bae.png)

**Comment by SquidDev** [comment]
Curious, I've definitely tested this in obfuscated environments and not had issues. Can you check the following: 

 - Does anything occur in the logs when starting a computer? 
 - Do you have any peripheral mods installed? 
 - Do you have any resource packs which may have a custom rom inside? 
 - What operating system are you on. Little strange, but there may be some OS specific code I'm unaware of.

**Comment by Brycey92** [comment]
**Does anything occur in the logs when starting a computer?**
No, there are no messages at all generated by starting a computer, errors or otherwise.

**Do you have any peripheral mods installed?**
No

**Do you have any resource packs which may have a custom rom inside?**
No

**What operating system are you on. Little strange, but there may be some OS specific code I'm unaware of.**
Windows 7 x64

It's worth noting that this issue is not present when 1.8.0pr1.8 is use, with no other changes to the pack or config.

**Comment by SquidDev** [comment]
> It's worth noting that this issue is not present when 1.8.0pr1.8 is use

I did a bit of a rewrite to how the ROM is mounted, to allow a couple of other features to be added. I've not seen anyone else having issues, so not sure if this is a Win 7 issue or Java issue.

I've [put together another build][download] with some more logging code in, which should help me pinpoint the issue. If you've got a moment, would you be able to run it and upload your log file (should be `latest.log`)?

Really sorry for the issues here :/.

[download]: https://www.dropbox.com/s/vvpkzmi8ahb1qml/cc-tweaked-1.80pr1.9-logging.jar?dl=1

**Comment by Brycey92** [comment]
Here's latest.log and debug.log: [logs.zip](https://github.com/SquidDev-CC/CC-Tweaked/files/2523636/logs.zip). Based on my very cursory glance, it seems not to like the path separator you used.

Also, don't worry about the issues, I'm just glad someone is maintaining and improving ComputerCraft!

**Comment by SquidDev** [comment]
Thanks, that was a massive help in tracking down the issue. Can you try [this jar](https://www.dropbox.com/s/wemnx5tfdc4w2u0/cc-tweaked-1.80pr1.9-maybe-fixed.jar?dl=1) and see if it fixed your issue at all?

**Comment by Brycey92** [comment]
That worked! Thanks for the help!
