### ISSUE TITLE
[1.12.2] turtle.place() doesn't work with forge universal bucket

### ISSUE THREAD

**Issue by kosakriszi** [SquidDev-CC/CC-Tweaked#702]
Hello, it seems that because Forge's [UniversalBucket ](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fluids/UniversalBucket.java) doesn't extend ItemBucket, [this check fails](https://github.com/SquidDev-CC/CC-Tweaked/blob/master/src/main/java/dan200/computercraft/shared/turtle/core/TurtlePlaceCommand.java#L370
), resulting in turtles not being able to place liquids in packs that use the universal bucket.
I've also been having difficulty using place to fill buckets from in-world tanks but I'm not sure if universal buckets break that as the empty bucket just seems to be a regular vanilla bucket item. I may be wrong though, honestly not sure.

This looks like it might be an issue for modern versions of the mod as well.

- MC: 1.12.2
- CC: Tweaked: 1.89.2

**Comment by SquidDev** [comment]
I'm afraid Minecraft 1.12 is no longer supported, so this won't be fixed.
