### ISSUE TITLE
Event documentation shadows API documentation in index

### ISSUE THREAD

**Issue by MCJack123** [SquidDev-CC/CC-Tweaked#705]
There are some names that exist both as events and APIs, including `peripheral`, `redstone`, and `disk`. This is causing a collision in the index at https://tweaked.cc/index.json, and the events are being prioritized. A consequence of this is that the FAQ bot for the CC Discord no longer works with the aforementioned APIs. My suggestion is to add `(event)` after each event in the index to disambiguate the events and APIs with the same names, as it's more likely someone's looking up the API instead of the event.

**Comment by Lupus590** [comment]
This might be the actual cause to this bug then: https://github.com/SquidDev-CC/FAQBot-CC/issues/25

**Comment by SquidDev** [comment]
This is a problem with illuaminate. I guess you'd need to change the `index.json` file to support duplicate keys, if someone wants to work on that.
