### ISSUE TITLE
Rendering Issues - CC + Shaders

### ISSUE THREAD

**Issue by AimUprr** [SquidDev-CC/CC-Tweaked#707]
I added shaders to ATM 6 and tested if I could play with em on. But it turns out your mod is the only one having issues with it.
The rendering bug has happened to me before in 1.12 with Botania + Shaders,  But after correcting Botania found out it wasn't it this time. Then after 2-3 hours of testing and changing configs in various mods I found out it was the Monitors ( and Advanced Monitor ), from this mod, that were causing the bug.
I have looked at the other issues people had, especially to #95 but It is different.

## Useful information to include:
 - Minecraft version -> 1.16.5
 - CC: Tweaked version  -> 1.95.2
 - Shaders -> Sildul's Extreme Volumetric ( Including all the Sildul's versions )
                      BSL 7.1
                      CYBOXshaders V4 ULTRA MotionBlur
                      SEUS Renewed 1.9.9
                      Chocapic13 V6 Ultra

 

 - Detailed reproduction steps: 
   1. Add Shaders;
   2. Place a Monitor down;
   3. Connect that monitor with a modem;
   4. Voila.
 
## Images ( It only happens with some blocks )
![image](https://user-images.githubusercontent.com/59490875/107056314-1ea33800-67ca-11eb-9332-85b836b0789e.png)

##------------
![image](https://user-images.githubusercontent.com/59490875/107056611-6aee7800-67ca-11eb-8a23-b7573f87d190.png)

**Comment by Lupus590** [comment]
The monitors' screens being transparent might be fixable by changing to the monitor renderer in the client config file, I'm fairly sure that the config has a comment about which one is best for a misbehaving shader.

Mentioning the shader misbehaving, chests should not look like that with the shader on.

**Comment by AimUprr** [comment]
_> The monitors' screens being transparent might be fixable by changing to the monitor renderer in the client config file, I'm fairly sure that the config has a comment about which one is best for a misbehaving shader._
I didn't find a client side config side. Ence why I made this thread.


_> Mentioning the shader misbehaving, chests should not look like that with the shader on._
Thats what the "Render Issue" is, rendering the Screens makes them and other blocks whiteish

**Comment by AimUprr** [comment]
Yep that fixed it.
I couldn't find the cc config bcs I was looking for the Bigger Reactors config. _**Wops**_

**Comment by AimUprr** [comment]
Yep that fixed it.
I couldn't find the cc config bcs I was looking for the Bigger Reactors config. _**Wops**_
