### ISSUE TITLE
rs.getBundledInput actually returns bundled output

### ISSUE THREAD

**Issue by malte0811** [SquidDev-CC/CC-Tweaked#708]
https://github.com/SquidDev-CC/CC-Tweaked/blob/7514cf7320bbee1ab8cd7bf9642e0e863d82461e/src/main/java/dan200/computercraft/core/apis/RedstoneAPI.java#L192-L195

I hope it's ok that I'm ignoring the issue template here :) See also BluSunrize/ImmersiveEngineering#4634.

**Comment by GamesArsenal96** [comment]
When will this fix be available for a 1.16.5 version?
