### ISSUE TITLE
Issue with shape program after updating to 1.80pr1.9

### ISSUE THREAD

**Issue by vpontin** [SquidDev-CC/CC-Tweaked#71]
**Useful information:**
 - Minecraft version: 1.12.2
 - CC: Tweaked version: 1.80pr1.9
 - Forge version: b2772

Well, after updating CC:Tweak i begin to get some issues trying to run [this program](https://gist.github.com/vpontin/19eedf96147ed9153bf664b21e3dc10a). Before that the program was interactive and i could type every argument according to instructions.

But after the update the program simply crash in the first screen. Print with the error:

![2018-10-27_21 07 25](https://user-images.githubusercontent.com/3485505/47610531-c8ad8a80-da2d-11e8-89e0-bf6e9d0d183a.png)

What could be the problem? Thanks!

**Comment by hugeblank** [comment]
This may be helpful 
<img width="274" alt="image" src="https://user-images.githubusercontent.com/16393543/47610935-2635dd00-da16-11e8-827b-628bbc5ec629.png">

**Comment by hugeblank** [comment]
@vpontin for now just use `read` while squid debugs the weird stdin issues, or if you use `io.read` frequently you could just do `io.read = read` at the very top of the program.

**Comment by vpontin** [comment]
Oh! I will try to edit the program to reflect this changes. Thanks!

**Comment by hugeblank** [comment]
mmm, I wouldn't have closed this issue because that's an actual problem...

**Comment by SquidDev** [comment]
Fixed in 7e334bd4a5ef0866176dc3e3c93d27ff50f6ede2. Thanks for the report!
