### ISSUE TITLE
Note block to be opened on the side of a computer

### ISSUE THREAD

**Issue by Arteneko** [SquidDev-CC/CC-Tweaked#711]
When I work on a script, which usually ends up being multiple files / hundred lines long, interacting with tons of peripherals at the same time (e.g. right now, building one to automate crude oil processing from pneumaticcraft), I always must keep tab on peripheral IDs, positions, and such.

It's either done on paper IRL, on a floating terminal instance on my second screen, or by mashing my head on the keyboard.

My idea, if possible, would be to have an item (some kind of note block).

If worn / in inventory, when opening a terminal window, this item would show up on the side, acting as a notepad in which we would have the ability to write stuff (basically like a book and quill, but right into the CC interface).

What are your thoughts on that?

**Comment by SquidDev** [comment]
I think this is a pretty neat idea, but afraid I'm not sure if it fits within CC:T itself.
