### ISSUE TITLE
Crash with Advanced Peripherals

### ISSUE THREAD

**Issue by FriendlyJoee** [SquidDev-CC/CC-Tweaked#720]
When i place a Block(e.g. the Chat Box) from Advanced Peripherals with a turtle, the game crashes. I just used "turtle.place()"

## Useful information to include:
 - Minecraft version: 1.16.5
 - CC: Tweaked version: 1.95.2
 - Logs: https://paste.gg/p/anonymous/4631ce5cc56841ab87d82e20166dfc62
 - Detailed reproduction steps: 
 1. Place a turtle and put a Chat Box in it
 2. Create a program and use turtle.place()
 3. Game will crash.

**Comment by SquidDev** [comment]
This is a bug with AdvancedPeripherals, I recommend you report it to them.
