### ISSUE TITLE
[1.16.5] CraftTweaker Errors Spam the Screen

### ISSUE THREAD

**Issue by Flexico** [SquidDev-CC/CC-Tweaked#721]
MC 1.16.5
CCT 1.95.2
The only script I have running is the one I wrote to add turtle compatibility with other mods' tools, and it does work, but I get spammed with "a tool with the name xyz already exists" when I load a singleplayer world. This didn't happen when I first added the script, but I'm not sure what I might have changed before it started happening. It took me a while to report it because it's not game-breaking, it's just annoying.
![image](https://user-images.githubusercontent.com/5751770/108209792-b3763180-70f8-11eb-8b83-9d771946e0d2.png)
[turtletools.zs.txt](https://github.com/SquidDev-CC/CC-Tweaked/files/5995879/turtletools.zs.txt)

**Comment by SquidDev** [comment]
Sorry for taking so long to look at this!
