### ISSUE TITLE
Start and stop of furnace cooking causes periperal reconnects. 

### ISSUE THREAD

**Issue by kepler155c** [SquidDev-CC/CC-Tweaked#73]
When a furnace begins and ends cooking, the peripheral events are fired several times for connects and disconnects. I assume this is due to block updates.

**Comment by Lemmmy** [comment]
Furnace peripherals are part of [Plethora](https://github.com/SquidDev-CC/plethora), not CC-Tweaked. Issues should be reported there.

**Comment by SquidDev** [comment]
As mentioned elsewhere, there is nothing I can do about this. This will be resolved in 1.13.
