### ISSUE TITLE
Allow letting the turtle be a source for inventory methods

### ISSUE THREAD

**Issue by GamesArsenal96** [SquidDev-CC/CC-Tweaked#731]
Methods:
INVENTORY.pushItems("turtle",slotInChest,Count,slotInTurtle)

or

Could just add an optional SLOT param to turtle.suck methods
turtle.suckDown(Count,chestSlot)

Would allow more flexibility for inventory management with turtles

**Comment by SquidDev** [comment]
The inventory transfer methods are very much tied to peripheral and wired networks. I don't think it makes sense to start adding new magic identifiers.

If you just need to transfer items to the current turtle, you can use `peripheral.getNameLocal` to get its name on the network.

**Comment by LoyaltyGamer72** [comment]
But in the case the turtle is not a network, that makes this way impossible, i just want to have a turtle going back and forth between chests but be able to use trhe chest methods instead of turtle.suck() because of the better control.

**Comment by Lupus590** [comment]
You can wrap the chest and move the target item to the first slot of the chest and then use `turtle.suck()`.
