### ISSUE TITLE
Add event for chat messages

### ISSUE THREAD

**Issue by aMerryElk** [SquidDev-CC/CC-Tweaked#732]
I'd like to suggest a way to read global chat output. Currently, there is no way to do that - even with commands.

It could be useful in a number of situations. The one I'm currently trying to use it for is coding a discord bot from inside the game. But it also could be used for example to add custom "commands"  or even to trigger complex logic in custom maps.

In my opinion, the best way to add this feature is through an event similar to `rednet_message`, where the sender, protocol and content are separated into different strings.

Even if you fell like this feature could be unbalanced in survival, it would still be immensely useful for command computers.

Thank you ^ ^

**Comment by SquidDev** [comment]
I'm afraid this is not something I really want to add to CC: Tweaked. IMO it doesn't really fit well with the rest of the mod.

Generally my stance is these sorts of things should be implemented by other peripheral mods. I know [Plethora](https://plethora.madefor.cc/) (MC ≤1.12) and [AdvancedPeripherals](https://github.com/Seniorendi/AdvancedPeripherals) (MC 1.16) both have chat-listening functionality.
