### ISSUE TITLE
Inteface don't work whith canvas shader mod (fabric) (1.6.5)

### ISSUE THREAD

**Issue by jorge1b3** [SquidDev-CC/CC-Tweaked#736]
When the canvas mod are working, cc mod work, but the interface are broken and the turtle animation is weird

**Comment by SquidDev** [comment]
CC: Tweaked doesn't support Fabric at all, so I'd be surprised if the interface being broken is the only problem!

You probably want to report this to [CC: Restitched](https://github.com/Zundrel/cc-tweaked-fabric), though looks like there's an open issue already - https://github.com/Zundrel/cc-tweaked-fabric/issues/23.
