### ISSUE TITLE
Turtle passing by networked blocks causes all sorts of issues.

### ISSUE THREAD

**Issue by kepler155c** [SquidDev-CC/CC-Tweaked#74]
I have a network with a wireless modem attached to a wired modem. If another turtle touches the block with the wireless modem, the wireless modem closes and I am forced to reboot the main computer controlling the wired network in order to get it functioning again.

If another turtle touches any wired modem, other issues arise (although the resulting issues are inconsistent).

I can demonstrate on the switchcraft server.

My setup is this:    turtle (controlling the network)->wired modem->wireless modem

**Comment by SquidDev** [comment]
> If another turtle touches any wired modem, other issues arise (although the resulting issues are inconsistent).

I really need more information than this in order to tell what's happening. Some screenshots + detailed reproduction steps, or a video would be very useful.

**Comment by kepler155c** [comment]
Gray turtle:
`Lua> peripheral.wrap('modem_2209').open(18)`
Green turtle:
`Lua> turtle.forward() turtle.forward() turtle.back() turtle.back()`

Green turtle moves along side the wired modem and returns to starting point.

The light on the wireless modem goes out and a reboot is needed (or break and replace the wireless modem).

Modem still says that channel 18 is open - but it will be unusable.

![2018-11-09_16 28 27](https://user-images.githubusercontent.com/16342516/48289328-08686f00-e43d-11e8-92da-db021bbae684.png)

**Comment by kepler155c** [comment]
Another related issue:

2 computers placed against a wired modem block. Connected to that wired modem block is a wireless modem.

First computer opens a channel on the wireless modem (light comes on). Reboot second computer and the wireless modem light goes off. First computer has no indication that the wireless modem has been reset.
