### ISSUE TITLE
Fork the Haxe types for CC

### ISSUE THREAD

**Issue by RGFTheCoder** [SquidDev-CC/CC-Tweaked#744]
Could you make a fork of https://github.com/dmarcuse/computercraft-haxelib for cc: tweaked? I'll be willing to actually make the changes in a pr, but I'd rather it be hosted on your github org for consistency. It seems to have most apis already implemented, but a few of the CC: tweaked specific ones aren't there.

**Comment by RGFTheCoder** [comment]
I'll make the fork, and if you do wish to pull this in, then we can move the fork.

**Comment by SquidDev** [comment]
SquidDev-CC is rather reserved for projects that I maintain. I don't really have any interest in maintaining haxe bindings, so I don't think me forking it makes sense. I'd recommend submitting a PR (though not sure how much CC Dana is doing nowadays) or just forking it yourself :).

**Comment by RGFTheCoder** [comment]
ok
