### ISSUE TITLE
drawLine sortCoords not working

### ISSUE THREAD

**Issue by lilyzeiset** [SquidDev-CC/CC-Tweaked#747]
The following code should draw a line from the bottom-left to top-right
![code](https://user-images.githubusercontent.com/56274881/112103345-fd32bb80-8b7f-11eb-8949-444396027aa2.png)
![result](https://user-images.githubusercontent.com/56274881/112103352-002dac00-8b80-11eb-9c59-2895645603ef.png)

drawLine(1,1,w,h) [correctly] and drawLine(1,h,w,1) [incorrectly] draw the same line.

**Comment by lilyzeiset** [comment]
@Lemmmy

**Comment by Lemmmy** [comment]
This is rather embarassing 😓 I looked over the code a few times even now and I can't see what could've caused this, so guess I should try and wake up a little more first

**Comment by SquidDev** [comment]
Lem, it's 7am. Stop looking at GitHub.

**Comment by Lemmmy** [comment]
I remember when I originally wrote #570, I stared at this code for a VERY long time trying to figure out what it does:

![](https://i.lemmmy.pw/Rg5h.png)

I think that the confusion comes from the fact that the old code only actually attempts to swap the X coordinates, swapping the Y simultaneously. My code swaps both independently (which is the way I think it should work). The line drawing function probably relies on this behaviour implicitly, causing the line to draw upside down?

**Comment by SquidDev** [comment]
Yeah that makes sense. The new logic is fine for boxes, where there isn't a direction, but doesn't work for lines. 

Woops, should have property tested the pre and post refactoring code.
