### ISSUE TITLE
Add GUI Device

### ISSUE THREAD

**Issue by RGFTheCoder** [SquidDev-CC/CC-Tweaked#750]
Note: This might be very off scope

This would add a block or upgrade for computers which allows the OS to draw different ui elements (like item slots).
When the player clicks an item on an item slot, or when they click on the item slot, the comptuer would get an event, and they'd be able to use the inventory api to move the item from the players cursor, or move an item into the players cursor. This would have scrolling components and similar, but would not allow too complex of a layout.

The layout could possibly be defined by nesting components, but not allowing them to be programatically moved (only through scrollable panels). 

I will once again say, that this would probably fit better as an addon, but I wanted to put the idea here if it interested you.

**Comment by Lupus590** [comment]
> the comptuer would get an event, and they'd be able to use the inventory api to move the item from the players cursor, or move an item into the players cursor

Computers can have multiple simultaneous users and the computer has no way of knowing what interactions are from which user. So in the event of a user clicking on the item while there are other users how does the computer know which user's cursor to attach the item to?

**Comment by RGFTheCoder** [comment]
hmm; maybe the gui only allows 1 person to use it at a time?

**Comment by SquidDev** [comment]
> Note: This might be very off scope

Correct :).
