### ISSUE TITLE
Add a Smaller Font Option? (0.25)

### ISSUE THREAD

**Issue by Flexico** [SquidDev-CC/CC-Tweaked#751]
## Useful information to include:
 - Explanation of how the feature/change should work.
The current smallest font you can use on monitors is 0.5, but I'd like to be able to go to 0.25.
 - Some rationale/use case for a feature. My general approach to designing new features is to ask yourself "what issue are we trying to solve" and _then_ "is this the best way to solve this issue?".
The main reason I want this is that I've been writing programs that make graphics by changing the bg color and printing a space character, effectively coloring pixels. I have some more ambitious ideas than what I've made so far, and higher resolution via a smaller font would be very helpful!
Example fractal program:
![2021-03-19_08 12 38](https://user-images.githubusercontent.com/5751770/112245433-3f630800-8c27-11eb-9080-22c6c80faf75.png)

**Comment by SquidDev** [comment]
Monitors are already quite expensive. We need to send them over the network (can be a packet up to 25kb) and then render them (pretty cheap if using the TBO renderer, expensive if using VBOs). Doubling the resolution makes this problem 4x worse - definitely something I want to avoid!

> changing the bg color and printing a space character, effectively coloring pixels.

Have you seen [blittle]? This uses the teletext characters to draw much higher resolution images (each character can draw a 2x3 image).

[blittle]: http://www.computercraft.info/forums2/index.php?/topic/25354-cc-176-blittle-api/

**Comment by Flexico** [comment]
Oh, I have not seen that! I'm-a go check it out~
