### ISSUE TITLE
Scripts navigation broken

### ISSUE THREAD

**Issue by xXTomeroXx** [SquidDev-CC/CC-Tweaked#758]
MC version 1.16.5
CC version: 1.95.3
The Script i used was "https://pastebin.com/gkz5sgZ8" ore Collecting Miner

Steps to reproduce: install and open the mod.
Placing a Mining turtle.
Put in the pastebin from above,
Start it, 
And the navigation is not working.

The navigation for Scripts like auto mining are broken on Tweaked, i tested the script on CC for MC 1.12.2 and it worked fine.  or did i something wrong, like a setting?

**Comment by SquidDev** [comment]
Could you link to the script in question? I imagine [it's due to the key codes changing](https://github.com/SquidDev-CC/CC-Tweaked/wiki/Incompatibilities-between-versions), but hard to confirm from your description.

**Comment by xXTomeroXx** [comment]
The Script i used were "https://pastebin.com/gkz5sgZ8" ore Colecing Miner

**Comment by xXTomeroXx** [comment]
I edited it, and thank you for the fast Reply :D

**Comment by SquidDev** [comment]
Ahh. I'm afraid there's nothing I can do here. The original script author was a little lazy when writing this and hard coded key values rather than using the `keys` API.

These values changed in MC 1.13, which means this no longer works. I'm afraid there's not much I can do here :/.

**Comment by Lupus590** [comment]
You could go through the old keys file and replace the numbers in the script with the keys api.

**Comment by xXTomeroXx** [comment]
whe is the old key file?

**Comment by Lupus590** [comment]
It's only changed once (according to the wiki) and this is the original from source control. https://github.com/SquidDev-CC/CC-Tweaked/blob/50a4a961e5d1f98ec231f69b0611c59fbd438302/src/main/resources/assets/computercraft/lua/rom/apis/keys

**Comment by xXTomeroXx** [comment]
but i stilll dont know how to do it. i dont reallly know how to programm. but im learning

**Comment by Lupus590** [comment]
Find where the program seems to be using keycodes (they will be pulled from events) and replace the hard coded number's with the number's entry in the file I linked above.
