### ISSUE TITLE
[1.16.5] Dedicated server lockup - 

### ISSUE THREAD

**Issue by ProsperCraft** [SquidDev-CC/CC-Tweaked#765]
## Useful information to include:
 - Minecraft version 1.16.5 forge-1.16.5-36.1.2
 - CC: Tweaked version - cc-tweaked-1.16.4-1.95.3
 - Logs: Stacktrace from lockup- https://gist.github.com/ProsperCraft/ea7066b285507d7710b8eb1e461f4585

A player had just copied this code in and had the turtles mining for about 15 mins - https://pastebin.com/rpXRAZs4

From this website-  https://www.computercraft.info/forums2/index.php?/topic/5681-variable-size-quarry-now-with-super-ore-quarry%e2%84%a2/

**Comment by SquidDev** [comment]
Was there anything else going on on the server at the time? I can't see anything especially worrying in CC's stack threads.

Rather annoying that the main server thread doesn't appear within that crash at all. I don't suppose you still have the full logs?

**Comment by ProsperCraft** [comment]
Here are the full debug logs - https://gist.githubusercontent.com/ProsperCraft/f03454c56fbe6a070060ea53dc4cc169/raw/65f0c7ff6c66fb06c4217a6e751312294ee061e8/gistfile1.txt

**Comment by ProsperCraft** [comment]
We had this crash an hour before - https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5158

**Comment by SquidDev** [comment]
Are you sure those are the right logs? That ends with the same CME crash as the AE crash you've linked above.

**Comment by ProsperCraft** [comment]
More investigation shows that the server discord link never showed the server going down and coming up between the AE2 crash and the hard lockup, so it must have crashed and not rebooted, then the watchdog kicked in and rebooted the server.
