### ISSUE TITLE
Missing cursor in edit mode

### ISSUE THREAD

**Issue by Lennart4711** [SquidDev-CC/CC-Tweaked#766]
When closing  the "save, run, exit" menu in advanced devices (advanced computer, advanced turtle and advanced pocket computer) with a mouse click, the cursor blink isn't set to true. I am not sure if that is because of my cc-tweaked version(1.16.4-1.95.3), because this issue was already mentioned and solved in [https://github.com/SquidDev-CC/CC-Tweaked/pull/742](url). Otherwise it has something to do with the advanced devices menu.

**Comment by SquidDev** [comment]
#742 hasn't been released yet, so you probably won't have the fix. You could try downloading the latest version (`wget https://raw.githubusercontent.com/SquidDev-CC/CC-Tweaked/mc-1.15.x/src/main/resources/data/computercraft/lua/rom/programs/edit.lua`) and see if that fixes your issue.

**Comment by Lennart4711** [comment]
Ok, then I'm going to download the mentioned version and close this issue.
