### ISSUE TITLE
After saving and exiting script, it places automatically an "end" at end of the script 

### ISSUE THREAD

**Issue by TheNewbie99** [SquidDev-CC/CC-Tweaked#77]
Hello,
I'm writing on my script and everytime I want to save and run my program it gives me an error at the last codeline. Everytime when I scroll down the script I see the program wrotes itself an "end" or mostly a "nd" and I have no reason why.
Sometimes it just works after deleting these letters, but most of the time it just appear again and ruins my script. 

I hope someone can help me with this issue.

Version cc-tweaked-1.80pr1.8

**Comment by SquidDev** [comment]
This sounds suspiciously like #75. Are you sure you're on 1.80pr1.8 - that but would have only been introduced in 1.80pr1.9.

**Comment by SquidDev** [comment]
One other thing to add: can you try with 1.80pr1.11? This should have fixed #75, so it's worth a shot.

**Comment by SquidDev** [comment]
I'm going to close this for now, as I'm pretty sure it's fixed and haven't heard anything back. If @TheNewbie99 (or anyone else) is able to reproduce, I'll reopen.
