### ISSUE TITLE
Shift right click to insert disk into disk drive

### ISSUE THREAD

**Issue by Jummit** [SquidDev-CC/CC-Tweaked#770]
Allow inserting disks by shift right clicking on the disk drive.
Similar to shift right clicking to equip armor, just for a container block.

**Comment by Lupus590** [comment]
I remember this being a feature, what if you right-click without the shift?

**Comment by Jummit** [comment]
It' doesn't work on the fabric port I'm running, but I can't confirm that it doesn't on forge.
