### ISSUE TITLE
Clean dyed turtles and disks in a cauldron

### ISSUE THREAD

**Issue by Jummit** [SquidDev-CC/CC-Tweaked#771]
In vanilla you can clean dyed items in a cauldron, removing one level of water as a result. This should be possible with dyed turtles and disks.

**Comment by Lupus590** [comment]
I know that a water bucket on turtles works. Also, there is no undyed version of disk drives I think.

**Comment by Jummit** [comment]
Right, disks have the blue color by default. So cleaning it should either make it blue again, or maybe white.

**Comment by SquidDev** [comment]
Fairly sure if you put a floppy disk in a pot of water, it's gonna remove a lot more than just its colour.

Which I guess would be a solution to #504 :thinking: <sub><sup>(/s before someone gets on my back about this)</sup></sub>.

**Comment by sir-maniac** [comment]
@SquidDev I'm sorry if I overstepped my bounds on that bug.

**Comment by SquidDev** [comment]
Oh, I've got that one muted, so hadn't even seen your comments. Don't worry, no out of bounds here!
