### ISSUE TITLE
More red integration

### ISSUE THREAD

**Issue by Seniorendi** [SquidDev-CC/CC-Tweaked#772]
Add integration for more red to connect bundled cables to computers.

## Useful information to include:
 The bundled cables should work like in 1.7.10
 Link to curseforge: https://www.curseforge.com/minecraft/mc-mods/more-red
 
 Should i request this at the more red repository?

**Comment by Lupus590** [comment]
CC historically didn't do integration with other mods. That said SquidDev has made [crafttweaker and jei intergration](https://github.com/SquidDev-CC/CC-Tweaked/tree/mc-1.15.x/src/main/java/dan200/computercraft/shared/integration).

**Comment by SquidDev** [comment]
We also had Charset integration in the 1.12 days, so it's something I'm less adverse to now.

**Comment by Flexico** [comment]
Oh yes please! =D The Redpower/ProjectRed/MoreRed wires fit so well with the ComputerCraft theme! =D

**Comment by RazorBladeGamer** [comment]
I know I'm a little late to the party but reintegrating the Bundled cable for MoreRed and others would be amazing!!!

**Comment by Commoble** [comment]
I guess I should've checked to see whether you were working on integration on your end before I did it on mine, lol

https://i.imgur.com/LgoeDiv.png

I implemented it as an adapter block in a separate mod (one side interfaces with More Red stuff, the other side with computercraft stuff) that implements IBundledRedstoneBlock and uses the bundled cable capability, I'm not sure if this is better or worse then your own implementation but I'll probably just archive the addon mod if CC:Tweaked's builtin integration goes live (I uploaded the addon mod on thursday night so it's already in curseforge's weekend approval backlog)

**Comment by SquidDev** [comment]
> I guess I should've checked to see whether you were working on integration on your end before I did it on mine, lol 

Sorry! I also didn't check your issue tracker, so equally my fault! This is one of those things easier to do from within CC as the current API is not very capability-friendly - joys of something which hasn't changed since Minecraft 1.6 or so.

That said, not planning on doing a release for another month or so, so I still think there's utility in the integration mod existing, even if it's not maintained long term.

**Comment by Flexico** [comment]
> I guess I should've checked to see whether you were working on integration on your end before I did it on mine, lol
> 
> https://i.imgur.com/LgoeDiv.png
> 
> I implemented it as an adapter block in a separate mod (one side interfaces with More Red stuff, the other side with computercraft stuff) that implements IBundledRedstoneBlock and uses the bundled cable capability, I'm not sure if this is better or worse then your own implementation but I'll probably just archive the addon mod if CC:Tweaked's builtin integration goes live (I uploaded the addon mod on thursday night so it's already in curseforge's weekend approval backlog)

Where might I find this temporary compatibility mod? =D
