### ISSUE TITLE
Computer GUI UV Errors

### ISSUE THREAD

**Issue by SyndiShanX** [SquidDev-CC/CC-Tweaked#776]
Minecraft version: 1.16.5
CC: Tweaked version: 1.16.4-1.95.3

The Border of the Computer GUIs grab small UV's despite having enough to work with within the texture

Ingame:
![2021-04-28_09 47 00](https://user-images.githubusercontent.com/23367120/116414709-b1ba9f80-a806-11eb-9c0e-c48a6538f373.png)

Source Texture:
![corners_command](https://user-images.githubusercontent.com/23367120/116414654-a1a2c000-a806-11eb-8f00-8434597d0e35.png)

**Comment by SyndiShanX** [comment]
Pocket computers are only broken on the top and sides
![2021-04-28_09 48 55](https://user-images.githubusercontent.com/23367120/116415020-05c58400-a807-11eb-8b2e-51b40d7a529d.png)

**Comment by SquidDev** [comment]
This is mostly working as intended - I believe it changed in 514db30fb1d40c5a73e70c191120513166f356ea. As computer terminals are now resizable (of sorts), we need to handle larger areas than the texture supports.

I'm open to changing how this is implemented a little bit, but until 1.17 drops (and we might be able to do something with shaders), there's probably a limit of how much can be changed.
