### ISSUE TITLE
Tool to Change Name of Network Peripherals

### ISSUE THREAD

**Issue by shelbykauth** [SquidDev-CC/CC-Tweaked#78]
A tool, like a wrench but please for the love of god don't call it a wrench.
When you right click on anything that could be considered a peripheral (chest, TConstruct smeltery, etc), it brings up a little GUI to let you name the peripheral.

If something else has already been named that, it won't let you name it that.
But you could name the peripherals all sorts of things,
"minecraft:chest_1337",
"ShelbysChest",
"SmelterSouth",
"Bob",
"A","B","C",
"SpeakerE",
"Redstone_Door_CargoBay_5"

And then in the code, you can do `peripheral.wrap("SmelterSouth") instead of trying to remember if the south smelter was "minecraft:tconstruct_smeltery_component_24" or "minecraft:tconstruct_smeltery_component_42", and whether Smeltery is spelled "smeltry" or "smeltery"
Or which of the 82 Nesting Pens contains your ender pearl chicken.  Or which door is hooked up to which redstone integrator.

Side Note: You say that we should try posting it on the main CC repo.  But Dan says that he doesn't want feature requests on his issue page.  So... yeah... I'm putting it here...

**Comment by SquidDev** [comment]
I definitely agree that more could be done to make wired networks more user friendly, especially when you have the ridiculous names that Plethora tends to generate.

However, I'm not quite sure whether allowing custom names is the way forward here: I definitely have some concerns about how uniqueness of names would be handled. It's going to have to be something I need to think about more.

For the time being, I've added the ability to copy peripheral names from the attachment/detachment chat messages. It doesn't make them any more memorable, but at least means you don't have to write them out yourselves:

![Copy to clipboard for peripheral names](https://user-images.githubusercontent.com/4346137/49224535-96e76500-f3d9-11e8-8605-64d7d1d6edc6.png "🙌")

**Comment by shelbykauth** [comment]
Oooooooh.  Okay, that alone is excellent.  Still have to disconnect and
reconnect to get the names.  But that is a big improvement in and of
itself.  I will have to go update my pack...

As for uniqueness of names, I was thinking that either it wouldn't let you
name it the same thing as a previous peripheral, or it would append a
base-10, hexadecimal, or base-64 string to the end of anything with the
attempted same name (base-64 being [a-zA-Z\-\_0-9]), before saving the name.

Or maybe even being able to get just a plain integer in addition to the
ridiculous string.  Maybe not memorable for most people, but I can remember
2047 far easier than something_something_speaker_23
(I am not hooked into MC right now, so I legit can't remember the prefix
for speakers.

**Comment by SquidDev** [comment]
> Still have to disconnect and reconnect to get the names. 

Yeah, this is definitely something I'd like to get improve on, I'm just not sure the best approach. I'd really like to have it so shift-clicking would display a list of attached peripherals, but really shift-click should be reserved for placing.

This is where something like a wrench would come in useful, though I would like to avoid adding an item just for this.

> As for uniqueness of names, I was thinking that either it wouldn't let you name it the same thing as a previous peripheral, or it would append a string to the end of anything with the attempted same name

Half the issue is keeping track of which names have been used - or rather, when names are no longer used. I guess a compromise here would be allowing allowing changing the prefix, so you could get the modem to call the attached peripheral `smeltery_[0-9]+` instead of `minecraft:tcon.smeltery_controller[0-9]` or whatever. Could do something like right-clicking with a nametag changes the peripheral's prefix - I'm not sure, I'm rather spitballing here.

**Comment by shelbykauth** [comment]
>This is where something like a wrench would come in useful, though I would like to avoid adding an item just for this.

Agreed.  However, I notice you saying this a lot.  What if you added a computer wrench (or a computer screwdriver, haven't seen a 'screwdriver' in a long time) that does a lot of the stuff you don't want to add an item "just for that".  Left click could turn the block, Right click could open up a multi-purpose GUI with name, connected peripherals, physical location, and more.

>I'm not sure, I'm rather spitballing here.

Yup.  Spitballing is the game here.  If the id naming was changed from incrementing for just that type to incrementing for all peripherals, then it wouldn't matter what the prefix was.  Because you would have "minecraft:tcon.smeltery_controller_0", "mincraft:chest_1", "bob_2", etc.  It would make the ids stack up faster, but I think anyone who uses CC enough for that to be an issue would find use in what that allows.  And then we could call `peripheral.wrap("minecraft:chest_1")` or `peripheral.wrap(1)` to wrap the same peripheral.  But `peripheral.getNames()` would return what each prefix is.  And the type is still available so it doesn't break that.

**Comment by StefanJanssen95** [comment]
Personally I think this issue can be solved ingame by making a DNS like server. You send the server a request for the actual name of ``mainSmelterMine``. The server then replies with ``minecraft:tconstruct_smeltery_component_42`` which can be used to connect with. 

A similar system I've used a few years back on a server with some programmer friends. We mapped each network peripheral including it's location in a server. Then we could send our turtles to that location directly after sending commands to that peripheral. It's a bit more work, but when you have so many peripherals around you don't lack the resources for a system like that either.

**Comment by lupus590** [comment]
You could do your own peripheral alias names like this:
```lua
local p = peripheral.getNames()
local peripheralAlias = {}
local aliasIndex = {}
for _, v in pairs(p) do
  peripheralAlias[v] = v
  aliasIndex[v] = v
end

local handlePeripheralAttachDetach(event, side)
  if type(event) == "table" then
    side = event[2]
    event = event[1]
  end

  if event == "peripheral" then
    peripheralAlias[side] = side
    aliasIndex[side] = side
  elseif event == "peripheral_detach" then
    peripheralAlias[aliasIndex[side]] = nil
    aliasIndex[side] = nil
  end
end

local pipeableHandlePeripheralEvent(...)
  handlePeripheralAttachDetach(...)
  return ...
end

local setAlias(side, alias)
  peripheralAlias[alias] = side
  aliasIndex[side] = alias
end

return {
  peripheralAlias = peripheralAlias
  aliasIndex  = aliasIndex
  handlePeripheralAttachDetach = handlePeripheralAttachDetach
  pipeableHandlePeripheralEvent = pipeableHandlePeripheralEvent
  setAlias = setAlias
```
License: Public Domain, Unlicense and MIT (you get to pick which you want to use it under)

**Comment by SquidDev** [comment]
[Related work done in OC2](https://twitter.com/SangarWasTaken/status/1368980835248992256), and the commit implementing it: https://github.com/fnuecke/oc2/commit/40a2c5fa256bcabfa00612b311cb62493be46677.

Basically peripherals have a unique ID as well as a user-given one. Though probably less easy to do in CC:T, as not clear what `peripheral.list` should return.

**Comment by blackcatwithpurpleeyes** [comment]
I kinda like the idea of having a ID&Label system like what the computers have. You have a ID for the peripheral upon first place or connection to a modem and then you can use a computer and do something like this `peripheral.setName([peripheral_ID],[new_peripheral_name])` This would also change `peripheral.getNames()` to return both peripheral ID and Name. And when it comes to wrapping you can use Directions, ID's, or the Label.

**Comment by Lordfirespeed** [comment]
This feature not being implemented is what always stops me from reaching for CC in a kitchen sink pack. 
Dealing with peripherals in CC is just a bit miserable, and I don't really understand why it has to be this way?

Super Factory Manager does labelling really well. Sadly its language isn't expressive enough for certain niche tasks, so I reach for CC and am each time reminded why it isn't my first choice.

**Comment by SirEdvin** [comment]
Use [UPW](https://www.curseforge.com/minecraft/mc-mods/unlimitedperipheralworks)! I personally use it for GTCeu modpack runs and it serve me quite well. 

It has [peripheral proxy](https://docs.siredvin.site/UnlimitedPeripheralWorks/peripherals/peripheral_proxy/) for slightly better way of connecting peripherals together as well as network manager. 

Network manager not only allows to visualize peripherals in network it is connected to, but also allows to define groups for peripherals and attach them to this groups. 

Looks like this, with ability to coloring groups, change or hide text, or use box overlays

<img width="1920" height="1009" alt="Image" src="https://github.com/user-attachments/assets/ae2807a3-569a-4adf-9eaa-947c723c3657" />

<img width="1920" height="1009" alt="Image" src="https://github.com/user-attachments/assets/28da9e08-d5b8-4bdb-b470-c32dd6618ed9" />

Groups definition is also quite nice, and can be done in world or inside menu. Menu itself for network manager is also quite nice 

<img width="1920" height="1009" alt="Image" src="https://github.com/user-attachments/assets/4a37fb5d-6121-4adc-93d5-bd1366e25173" />

<img width="1920" height="1009" alt="Image" src="https://github.com/user-attachments/assets/c0d25aae-30d9-45ec-94da-45eb4f47784e" />

You can store network managers as favorites inside configurator to switch between them.

<img width="1920" height="1009" alt="Image" src="https://github.com/user-attachments/assets/4d4a72af-415f-4e03-a5da-168ca0eec701" />

<img width="1920" height="1009" alt="Image" src="https://github.com/user-attachments/assets/a48d58fd-c895-496f-86e5-2cb9612126a3" />

Sorry for this shameless self-advertisement....
