### ISSUE TITLE
/computercraft queue doesn't seem to work

### ISSUE THREAD

**Issue by vindictivolence** [SquidDev-CC/CC-Tweaked#783]
- Minecraft 1.16.5
 - CC: Tweaked 1.95.3
 - Using Create 0.3.1c, Windowlogging 0.0.4, WorldEdit 7.2.5
 
1. Pull event "computer_command".
2. Do /computercraft queue 
3. Nothing happens.

EDIT: I didn't use a command computer

**Comment by hatkidchan** [comment]
Wait, where does it say that it only works with command computers? I checked on https://tweaked.cc/event/computer_command.html and it doesn't say anything about it.
Sorry for necrobumping but I'm really confused.

Looking at the source it gets even more confusing, `/computercraft queue` accepts `[computer]` and `[<args>]` ([src](https://github.com/cc-tweaked/CC-Tweaked/blob/5f76d42e4d307f405966fbd0d22e05bd3ded2664/projects/common/src/main/java/dan200/computercraft/shared/command/CommandComputerCraft.java#L90-L93)) which suggests that it should queue that event on a specific computer, but [`queue()` implementation](https://github.com/cc-tweaked/CC-Tweaked/blob/5f76d42e4d307f405966fbd0d22e05bd3ded2664/projects/common/src/main/java/dan200/computercraft/shared/command/CommandComputerCraft.java#L242-L247) looks like it accepts list of computers, even though it only gets one from arguments?

I know it's kinda a niche command and it also makes complete sense for it to be command-computer-only, but it all just looks strange to me.
It would be nice to have it available on all computers via config option (something like `queue_command_computer_only`?) or at least have it documented that it is, in fact, only available for command computers (and also at least send a warning if player tries to queue it for a regular one)

**Comment by Wojbie** [comment]
> Wait, where does it say that it only works with command computers? 

https://tweaked.cc/reference/computercraft_command.html#queue
You can find that in /computercraft command documentstion

**Comment by SquidDev** [comment]
Ahh, this is mentioned on the [docs for the command itself](https://tweaked.cc/reference/computercraft_command.html#queue), but not on the event (nor do we cross-link the two pages). I will fix that. 

> , but `queue()` implementation looks like it accepts list of computers, even though it only gets one from arguments?

One of the slightly awkward things about CC is that computer IDs are not guaranteed to be unique (e.g. if a computer is duped in creative mode). So when you run `/computercraft queue #3`, that queues the event on *every* computer with ID 3, not just the first. 

> It would be nice to have it available on all computers via config option

This feature is mostly meant to be used from other admin-only features (e.g. text components, the new dialog system). I don't really want to expose such a fourth-wall breaking feature for normal computers, even behind a config. For that use-case, I think you're much better off using modems!

**Comment by hatkidchan** [comment]
> computer IDs are not guaranteed to be unique

ahh, completely forgot about that! 

> For that use-case, I think you're much better off using modems!

ended up doing that with pocket computer and ender modems in the end, thanx!
