### ISSUE TITLE
digital miner isn't listed as a peripheral 

### ISSUE THREAD

**Issue by leElvyn** [SquidDev-CC/CC-Tweaked#785]
## Useful information to include:
 - Minecraft version : 1.16.5
 - CC: Tweaked version : 1.95.3

 ### Detailed reproduction steps: 
 
 - use with the mod Mekanism 10.0.21.448
 - place a digital miner
 - place a computer on any sides 
 - use `peripheral.getNames()`

### expected behavior : 

the digital miner appear, as it would do in previous versions of the game, and allow us to use it's methods

### actual behavior : 

the digital miner doesn't appear 

#### notes : 

i'm not sure if this is a cc or mekanism problem, since i don't know how 3rd party peripherals are handled

**Comment by SquidDev** [comment]
Third party peripherals are largely handled by other mods. We have some support for generic methods on inventories/energy storage, but nothing else.

I believe there's an issue open on the Mekanism end already - https://github.com/mekanism/Mekanism/issues/6445. I think it's in dev builds, just hasn't been released.

**Comment by Lupus590** [comment]
I'm fairly sure that mekanism is providing their own peripherals, I would make the issue over on their repo.

In fact, [this issue](https://github.com/mekanism/Mekanism/issues/6445) is still open about adding CC integration so I assume that it's still in progress.
