### ISSUE TITLE
Open data folder by clicking on id part of the output of `/dump`

### ISSUE THREAD

**Issue by Jummit** [SquidDev-CC/CC-Tweaked#786]
I often find myself searching for the folder of a specific computer. Maybe the clicking the `(id X)` part of the output of `/dump` could open the folder.

![image](https://user-images.githubusercontent.com/28286961/118271128-2f4a0500-b4c1-11eb-8b48-0ca8043258a4.png)

Of course this would only work in a single player world.

**Comment by SquidDev** [comment]
Added in 9f7cc00fcbbc7516def382168c6ef5e5d6ed2c06. The implementation is a little ugly, but we need to work around some limitations in the chat system.
