### ISSUE TITLE
add monitor tool

### ISSUE THREAD

**Issue by zaze06** [SquidDev-CC/CC-Tweaked#789]
## Useful information to include:
 - Explanation of how the feature/change should work. A tool that can "reset" the state of a computer screen or fore two screens to connect (most not be between advanced and normal)
 - Some rationale/use case for a feature. My general approach to designing new features is to ask yourself "what issue are we trying to solve" and _then_ "is this the best way to solve this issue?". This whole salve the issue of two screens not connecting even though its the same height, this may not be the best way but it is one way to solve this problem if you don't add a feature that fixes this automatically

**Comment by SquidDev** [comment]
> This whole salve the issue of two screens not connecting even though its the same height

This sounds like a bug? Do you have any information (screenshots, etc...) and steps to reproduce?

**Comment by zaze06** [comment]
no, i ran into the width limit i think because when o removed one row it worked so I have found out way it happened

**Comment by zaze06** [comment]
steps to reproduce
build a monitor 8x4 and add a row so it would become 9x4

**Comment by SquidDev** [comment]
Right, yes. Monitors (by default - it can be changed in the config) are limited to 8x6.
