### ISSUE TITLE
Peripherals not working

### ISSUE THREAD

**Issue by Nathan1852** [SquidDev-CC/CC-Tweaked#79]
Minecraft version: 1.12.2
CC: Tweaked version: 1.80pr1.11

Peripherals connected via cables and modem aren't listed in a peripherals.getNames() call.
They also can't be wrapped with peripheral.wrap.

Additionally, when wrapping a peripheral by the side they are on ( which works ) every call just returns the error: "lua:1: Not attached to this computer"
Although this may be an issue with plethora, I don't know

Finally, calling any methods except for getDocs via a modem and callRemote returns "unsupported operation"

**Comment by Nathan1852** [comment]
This seems to be fixed with newer versions of PeripheralsPlusOne.
Sorry for bothering you

**Comment by SquidDev** [comment]
Ahhh, no worries. Peripherals+1 does some rather weird things, which has definitely caused issues in the past. I think they're fixed mostly fixed in the latest betas though.
