### ISSUE TITLE
Crash with turtles

### ISSUE THREAD

**Issue by Seniorendi** [SquidDev-CC/CC-Tweaked#791]
## Useful information to include:
 - Minecraft version: 1.16.5
 - CC: Tweaked version: 1.95.3
 - Logs: https://gist.github.com/Seniorendi/008168af7190821947b2590d39f4e8e3
 - Forge version: 36.1.17
 - Detailed reproduction steps: I destroyed a chunky turtle from advanced peripherals and the game crashed. But I can't find any issue with advanced peripherals itself, so I ask here.
 
 Modlist:
- Advanced Peripherals
- CC:T
- Mekanism
- Botania
- Patchouli
- AE2

**Comment by Seniorendi** [comment]
I can't reproduce it again... but when I try to join my world, my game crashes. And I have no clue in which chunk my chunky turtle is.

**Comment by Seniorendi** [comment]
Weird. It was an issue with the item itself in my inventory. I deleted it and it was fixed. But I will leave this issue open.

**Comment by SquidDev** [comment]
This appears to be a problem which only occurs in a deobfuscated/ForgeGradle environment. I suspect this is an issue with Forge - I'm afraid there's nothing I can do on my end.

**Comment by Seniorendi** [comment]
Kay. Thank you anyways. It works with the Forge version 36.0.46
