### ISSUE TITLE
Make lua shell scrollable

### ISSUE THREAD

**Issue by Seniorendi** [SquidDev-CC/CC-Tweaked#792]
## Useful information to include:
I think, the lua prompt should be scrollable.
![image](https://user-images.githubusercontent.com/67484093/118702954-d6a69f00-b815-11eb-9ea8-a1f9f47b4961.png)
I really need to scroll here... 😅

**Comment by SquidDev** [comment]
While this is possible to do (see mbs), it ends up being a lot of complexity that I'm not comfortable including in CraftOS right now. For the time being, I think this is best handled by user programs.

**Comment by KlutzLament** [comment]
Isn't there a paginator like more or less?

**Comment by Lupus590** [comment]
> Isn't there a paginator like more or less?

There's something in textutils, pagedPrint I think.
