### ISSUE TITLE
[1.16.5] Turtle Duplication Crafting Recipe

### ISSUE THREAD

**Issue by Flexico** [SquidDev-CC/CC-Tweaked#793]
## Useful information to include:
 **- Minecraft version** 1.16.5
 **- CC: Tweaked version** 1.95.3
 **- Logs:** Pretty sure not needed
 **- Detailed reproduction steps:** Craft a stack of more than one turtle (it happened to me with mining turtles) and craft it in your inventory with a dye, and you will receive more than one turtle per turtle input.
![2021-05-18_18 12 24](https://user-images.githubusercontent.com/5751770/118731892-5da04b00-b807-11eb-8c63-6a04a4d2e603.png)
![2021-05-18_18 12 29](https://user-images.githubusercontent.com/5751770/118731895-609b3b80-b807-11eb-9cee-a3c5198592cc.png)

**Comment by SquidDev** [comment]
Wojbie pointed out that this is very similar to a bug Plethora also had, so the fix should be the same - https://github.com/SquidDev-CC/plethora/commit/42e615e337a691fb7a197cc9c13d9e377a095f5c. I should probably write a test for this, and verify that none of the other recipes have similar issues.
