### ISSUE TITLE
[Documentation] Dark theme

### ISSUE THREAD

**Issue by Merith-TK** [SquidDev-CC/CC-Tweaked#797]
[Tweaked.cc](https://tweaked.cc)

is a flashbang to developers who use dark theme

add an option to make it not

plz

(this is made at 930 pm, tired, been coding all day, dealing with stress of having to do a server roll back)

**Comment by SquidDev** [comment]
[I'm just looking after your wellbeing](https://pubmed.ncbi.nlm.nih.gov/23654206/).

**Comment by Merith-TK** [comment]
> [I'm just looking after your wellbeing](https://pubmed.ncbi.nlm.nih.gov/23654206/).

Thanks for the concern, just It is difficult for me to read black text on white background, considering im near sighted and my display is, for all intents and purposes, always sitting at the maximum non-blurry distance from my face for me to read a standard size 12 font, on a 1920x1080 display, (it is a laptop)

Black on White, on windows, gets blurry for me unfortunately, and also it is jarring to go back and fourth between editors and documentation, constantly having to adjust to the sudden blast of visual light,

**Comment by Merith-TK** [comment]
not a bad dark theme!

**Comment by SkyTheCodeMaster** [comment]
There needs to be a switch to force it to light mode, the dark mode is barely readable (for example, when jumping to a function, the white on yellow is literally invisible)
![image](https://user-images.githubusercontent.com/34724753/120085733-944c5000-c0a8-11eb-931c-7b901cc49599.png)
