### ISSUE TITLE
commands.exec() returns an empty table if sendCommandFeedback is false

### ISSUE THREAD

**Issue by Sandgunslinger** [SquidDev-CC/CC-Tweaked#799]
- Minecraft version: 1.16.5
 - CC: Tweaked version: 1.96.0
 - Reproduction steps: 
1. Make sure gamerule sendCommandFeedback is set to true.
2. Place a command computer and open the interactive lua prompt.
3. Type "success, table = commands.exec("/data get entity @p Rotation")" and hit enter.
4. Type "print(table[1])" and hit enter.
5. Set gamerule sendCommandFeedback to false.
6. Repeat steps 3 and 4. It should print nil instead of the player data that is expected.

**Comment by SquidDev** [comment]
I've fixed this as it was simple enough, though curious as to the use case here. Genuinely never seen `sendCommandFeedback` used before!
