### ISSUE TITLE
[Suggestion] Track who placed turtles and use it with the FakePlayer

### ISSUE THREAD

**Issue by Eufranio** [SquidDev-CC/CC-Tweaked#8]
Actually, the GameProfile of the TurtlePlayer is a generic one (ComputerCraft). By using this generic player on events, mods listening to them will have inconsistent data and won't be able to proccess it as it would do for real players. 

My suggestion is that the turtles should track who placed them (UUID, nickname) and build a GameProfile based on it. This GameProfile would be used to construct the FakePlayer of that turtle, that would be used to fire the events they need. By passing the correct info to the events, mods listening to them would be able to proccess correctly what is happening, since they expect player events to have a **real** player assigned.

**Comment by SquidDev** [comment]
Implemented in 41cce78fcbeb2dd7c208196ef2c10b5a66700cfb.
