### ISSUE TITLE
Put .jar in releases

### ISSUE THREAD

**Issue by TamaMcGlinn** [SquidDev-CC/CC-Tweaked#802]
I was expecting to see the .jar file listed under the assets for each release. Instead, there's a copy of the source code repository, which doesn't seem useful since, if you are using the source code you should git clone the repository.

**Comment by SquidDev** [comment]
We used to do this for a bit but, as jars are available on CurseForge and my maven, and it was a bit of a pain to get working with the build system, there didn't seem much point.

Ideally we'd link to the jar on Curse from the releases, but I don't think that's easy to do in an automated fashion.
