### ISSUE TITLE
Specify Computer ID in `computercraft view` command

### ISSUE THREAD

**Issue by Merith-TK** [SquidDev-CC/CC-Tweaked#805]
when you run `/computercraft view` it should have an option that extends the current command like so

`/computercraft view computerid <insert computer id> <number if multiple of the same ID are running>`

`/computercraft view computerid 69` for one computer of that ID existing
`/computercraft view computerid 69 0` for multiple of that id existing

**Comment by SquidDev** [comment]
You should already be able to do `/computercraft view #123` to view a computer with a particular ID.
