### ISSUE TITLE
Maven Release Request - 1.16.5 Version

### ISSUE THREAD

**Issue by 50ap5ud5** [SquidDev-CC/CC-Tweaked#808]
Hello! I'm a mod author of the "Tardis Mod" and I was looking into adding your mod as a dependency for my mod.

I see that your mod only has maven releases for Minecraft 1.16.4 but not 1.16.5.

My mod is made for 1.16.5 and cannot downgrade to a lower 1.16 minor version because I need specific Forge features in the 1.16.5 versions. Hence, I cannot add your mod as a dependency at the moment.

I was wondering, would it be possible for CC:Tweaked to be released for Minecraft 1.16.5?

Thanks in advance!

**Comment by SquidDev** [comment]
I was under the impression that 1.16.4 and 1.16.5 were compatible with each other - does it not correctly deobfuscate when you depend on the 1.16.4 version?

That said, at this point we're probably safe to bump to 1.16.5 - I don't think anyone is still running 1.16.4.

**Comment by 50ap5ud5** [comment]
No, unfortunately I cannot deobsfucate the 1.16.4 version. When I attempt to do so I receive the following error:
`
Cause 1: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find net.minecraftforge:forge:1.16.4-35.1.16_mapped_official_1.16.4_at_39999aed721af97b3d3eb3bf9da33ec57588dc62.
Required by:
    project : > org.squiddev:cc-tweaked-1.16.4:1.96.0
`

**Comment by SquidDev** [comment]
Ah. That's an issue with my pom file - I think I fixed that for 1.15 but not 1.16. If you depend on 1.95.3 instead, it should behave a little better.

**Comment by 50ap5ud5** [comment]
Alright. I'll give that a try. Thank you very much!

**Comment by SquidDev** [comment]
Right, next release should be for 1.16.5 only (and hopefully will have a fixed maven :) ).
