### ISSUE TITLE
[Community] Possible "ComputerCraft" github orginization where all the core computercraft stuff is?

### ISSUE THREAD

**Issue by Merith-TK** [SquidDev-CC/CC-Tweaked#812]
So you know how CC:R and CC:T are under seperate Devs? I propose a unified "originization" here on github, where we can have both our repositories easily accessible to everyone, and even include other mods that help out new comers, such as [Toad-Dev's Example Peripheral for Fabric](https://github.com/Toad-Dev/cc-peripheral-test) and maybe even an example peripheral for CC:T, along wiht various other mods that arnt standalone, but enhance computercraft, 

I propose the name "ComputerCraft United" (because "ComputerCraft" is taken by a almost decade old porting the original CC to the sprout plugin system)

**Comment by Lupus590** [comment]
This is something that would be better as a discussion than as an issue.

**Comment by Merith-TK** [comment]
> This is something that would be better as a discussion than as an issue.

Yeah well... I dont know how to open as a discussion somewhere where Squid will see it

**Comment by Lupus590** [comment]
There should be a button to convert it to one, somewhere on the right side bar thing.

**Comment by Merith-TK** [comment]
yeah i dont have that button

**Comment by Lupus590** [comment]
Eh, you can just close the issue and make one here then: https://github.com/SquidDev-CC/CC-Tweaked/discussions

**Comment by Merith-TK** [comment]
https://github.com/SquidDev-CC/CC-Tweaked/discussions/814
