### ISSUE TITLE
Use .gitattributes to fix fetching on windows converting to CRLF by default.

### ISSUE THREAD

**Issue by fatboychummy** [SquidDev-CC/CC-Tweaked#813]
From some quick googling, it looks like we can use the `.gitattributes` file to fix windows converting things (by default) to CRLF unless they were already in CRLF format.

Appending something like the following I believe would work?
```
# Ignore changes in generated files
src/generated/resources/data/** linguist-generated
src/test/server-files/structures linguist-generated

# Fix windows downloading as CRLF
* text=auto
```
I'm not exactly sure if this'd work though, it may mess with other files.

Alternatively, we could pull in some gitattributes from [this helpful repo](https://github.com/alexkaratarakis/gitattributes) which contains attributes for all sorts of files to be downloaded properly.

**Comment by SquidDev** [comment]
I'm afraid I'm probably going to have to leave this to someone who uses Windows - I don't really have an easy way to test that this works.
