### ISSUE TITLE
[1.14] Crash on startup

### ISSUE THREAD

**Issue by Boomflex** [SquidDev-CC/CC-Tweaked#82]
https://pastebin.com/kLZk7PZT

**Comment by SquidDev** [comment]
I'm going to be honest, I'm not quite sure why this is happening. I've not had any issues in a dev or obfuscated environment. What mappings version were you using?

**Comment by D4rknessKing** [comment]
Same error here using fabric-18w49a.1-0.2.0.60 and the fabric api 0.1.0.36

**Comment by D4rknessKing** [comment]
If it helps, this is what the log shows right before minecraft crashes 
https://pastebin.com/1iKd3E8N

**Comment by SquidDev** [comment]
I released a new beta today, which targets 18w50a. Can you confirm (or deny) the issue is fixed?

**Comment by D4rknessKing** [comment]
![javaw_hci5xugwpl](https://user-images.githubusercontent.com/21957862/50103357-38f2b400-0206-11e9-947c-07833672dacb.png)
