### ISSUE TITLE
os.queueEvent/os.pullEvent do not keep table pointers

### ISSUE THREAD

**Issue by fatboychummy** [SquidDev-CC/CC-Tweaked#831]
## Useful information to include:
 - Minecraft version: 1.16.4
 - CC: Tweaked version: 1.95.3

## Expected

When you pass a specific table to `queueEvent`, you should end up with the same table (as a pointer) in `pullEvent`.

## Actual

When you pass a specific table to `queueEvent`, you get a clone of the object when you `pullEvent`

## Reproduction steps
```lua
local tbl = {}

os.queueEvent("some_event", tbl)

local _, tbl2 = os.pullEvent("some_event")

print(tbl == tbl2)
```

1. Run the above code inside of CC.
2. Observe when it prints `false`.

**Comment by SquidDev** [comment]
This is working as expected.
