### ISSUE TITLE
Small grammar mistake in README.md

### ISSUE THREAD

**Issue by Robogoogol** [SquidDev-CC/CC-Tweaked#84]
On line 17 of [`README.md`](https://github.com/SquidDev-CC/CC-Tweaked/blob/master/README.md)
![5268849bf29a64fe21e3cd1157204d16](https://user-images.githubusercontent.com/29505620/50059482-587dd400-0155-11e9-94b3-405de8a91eef.png)
This should instead say "all the features" rather than "the all features."

**Comment by Lemmmy** [comment]
For future reference, you can just pull request a fix yourself, you can even edit it inside GitHub yourself. Took 8 seconds.
