### ISSUE TITLE
turtel chunkloades new chunks

### ISSUE THREAD

**Issue by zaze06** [SquidDev-CC/CC-Tweaked#850]
## Useful information to include:
 - Explanation of how the feature/change should work. when a turtle moves into an unloaded chunk the chunk gets loaded
 - Some rationale/use case for a feature. My general approach to designing new features is to ask yourself "what issue are we trying to solve" and _then_ "is this the best way to solve this issue?". the issue that can be salved is whit mining programs for example the mining programs in cc: tweked get stopt and the turtle doesn't know where it is and it just stops where it is so if the chunk is loaded then that problem doesn't become a problem so yes this can be fix whit the turtel saving location but other programs may not be like that so then it cant know ware it is. it may not be the best way but it may be idk sorry

**Comment by SquidDev** [comment]
I'm personally not a fan of chunk loading, and so won't be adding this to CC: Tweaked.

[Advanced Peripherals does have a chunky turtle](https://docs.srendi.de/turtles/chunky_turtle/), which may be worth looking at as an alternative.

**Comment by zaze06** [comment]
ok thx
