### ISSUE TITLE
Computer #0 hard to read

### ISSUE THREAD

**Issue by SimonFJ20** [SquidDev-CC/CC-Tweaked#851]
On the web document computer emolator window, the text at the bottom left besides the power button is bare visible,
because the text color is nearly the same as the background color.

The sugestion here is just to add a css rule:
```css
.styles_terminalInfo__4UlYr {
    color: #282828;
}
```
I found that `#282828` is a nice color, matcing the power button

### Original:
![Original](https://user-images.githubusercontent.com/28040410/124691328-f8e6a000-dedb-11eb-8a3e-c77081d1c931.PNG)
### Sugestion
![Sugestion](https://user-images.githubusercontent.com/28040410/124691330-f8e6a000-dedb-11eb-926b-be330de331b7.PNG)

**Comment by Lupus590** [comment]
I believe that this is more accurately an illuminate issue. Probably a side-effect of darkmode.

**Comment by SquidDev** [comment]
This looks to be an issue with `cc-web-term`. We've got a style for this label, but the class isn't actually used within the component:

https://github.com/SquidDev-CC/cc-web-term/blob/706bd41e272cf878278eb50a5e5d300291499013/src/styles.css#L57-L60

Maybe I need to start using a shadow DOM for this, so CSS styles from the main page don't leak through to the terminal :D:.
