### ISSUE TITLE
Server Crash Caused by TilePrinter.updateBlockState

### ISSUE THREAD

**Issue by BryanHaley** [SquidDev-CC/CC-Tweaked#856]
### Minecraft Version

1.16.x

### Version

1.97.0

### Details

Crash occurs in both 1.96.0 and 1.97.0. Server crash logs:
https://drive.google.com/drive/folders/1biKEBtPyarzWRD9vYxWQdwJUeSp_-xgp?usp=sharing

During most of the crashes, there was only one computercraft entity in the world (a turtle), and it was sitting idle not running any code the entire time. The crashes seem completely random and not related to anything happening in-game.

**Comment by SquidDev** [comment]
It looks like something (I assume Advanced Peripherals) is placing printers during world generation. The full world isn't available at this point, and printers don't handle this gracefully. 

In might be worth looking for a config option in AP to see if their world generation can be disabled until this is fixed.

**Comment by BryanHaley** [comment]
Sounds right. We later found out a player was exploring when it suddenly crashed and then it would crash every time he tried to join. We've removed Advanced Peripherals and refreshed the chunk for the time being.
