### ISSUE TITLE
Alternative controller-style GUI for pocket computers.

### ISSUE THREAD

**Issue by Wojbie** [SquidDev-CC/CC-Tweaked#861]
### Pocket Controller GUI
I would like to suggest that if pocket is opened in off-hand then it should not show the pocket GUI. Instead it should just get focus from user and generate key events like in normal open GUI state but keep screen empty. This would allow for using pocket as a wireless controller for CC creations. For example as remote control for turtle or a game-pad for gigantic monitor playing snake. It would basically make pockets into slightly more versatile tools.

#### Example:
I have bodged together a prototype via some slightly dodgy java use to showcase the idea:

![2021-07-17_17-35-45](https://user-images.githubusercontent.com/5893536/126042102-d33a392f-74ad-47f5-b0aa-9a1951fe1344.gif)
https://user-images.githubusercontent.com/5893536/126041780-abb84574-232f-4cdf-93ac-c679b9d5e522.mp4
https://user-images.githubusercontent.com/5893536/126042277-6898871d-fae2-476e-846a-b1d6ba8aebfd.mp4

#### Prototype:
If anyone want to play with it (Or make it proper) code can be found here: https://github.com/Wojbie/CC-Tweaked/tree/PocketControllerPrototype . Simply clone it and use `gradlew runClient` to play with it.

##### Plethora keyboard?
Also yes i realize this is similar to keyboards from Plethora but it would be more powerful then plethora keyboard because pocket can run its own internal code and user will still have view of pocket terminal in the off-hand so they can see many kind of user interfaces in there. If one wanted to compare it would be a bit like combination of keyboard, neural interface and overlay at once.

**Comment by Lupus590** [comment]
Personally, I'm not a fan, but it could be a fun config option. The client-side configs do look quite empty with just the monitor rendering stuff there.

**Comment by Peekofwar** [comment]
> Personally, I'm not a fan, but it could be a fun config option. The client-side configs do look quite empty with just the monitor rendering stuff there.

I agree that it should be optional, but personally I like this idea. The game already renders the pocket computer when you hold it. 

Though, I think when enabled, this should also apply when holding the pocket computer with both hands (holding it in your primary hand without anything in your off-hand).

That said, I'm wondering how you could add a visual queue to indicate to the user that they are in fact in the terminal interface... Is it possible to get the hand holding the pocket computer to move slightly to the right to indicate you're in its interface?

**Comment by fatboychummy** [comment]
> Though, I think when enabled, this should also apply when holding the pocket computer with both hands 

Hmm, can you get mouse click events when it's not full screen? If not, it may not be ideal to do it always.

**Comment by Wojbie** [comment]
> Hmm, can you get mouse click events when it's not full screen? If not, it may not be ideal to do it always.

I have disabled mouse events in prototype cause there is no reliable way to get they atm. Also i am unsure if that is actually something that would be required or how it should work at all. While i guess it might be nice thing to have it don't feel like necessity to me.

**Comment by Peekofwar** [comment]
> > Though, I think when enabled, this should also apply when holding the pocket computer with both hands
> 
> Hmm, can you get mouse click events when it's not full screen? If not, it may not be ideal to do it always.

What if you catch the mouse movements, and move a dummy-mouse on the pocket computer screen, then reset the OS mouse position to the center of the screen?
