### ISSUE TITLE
Broken text wrapping for textutils.slowWrite()

### ISSUE THREAD

**Issue by jig487** [SquidDev-CC/CC-Tweaked#865]
### Minecraft Version

1.16.x

### Version

1.97.0

### Details

wrapped to a monitor and slowWrite'd "I'm an agent of vengeance. An avatar of justice. A righteous conduit of terrible purpose."

![Capture](https://user-images.githubusercontent.com/72327373/126203374-626b3a33-5be3-4a88-bbe1-c22de378bf58.PNG)

**Comment by SquidDev** [comment]
Issue here is that `avat` doesn't need a new line but `avatar` _does_. The fix here is probably to pre-wrap the text (`cc.strings.wrap`) and then write it character-by-character instead.

**Comment by jig487** [comment]
Awesome, works perfectly. Thanks!
