### ISSUE TITLE
Game crashed while breaking a speaker

### ISSUE THREAD

**Issue by NullLikesNothing** [SquidDev-CC/CC-Tweaked#866]
As the title says, my game will crash whenever I break a speaker peripheral, I don't know if this is a single player issue because I join my server for CC Tweaked.

**Comment by SquidDev** [comment]
Thank you for the report! Would you be able to fill out the information in [this template](https://github.com/SquidDev-CC/CC-Tweaked/blob/mc-1.15.x/.github/ISSUE_TEMPLATE/bug_report.md)?

**Comment by NullLikesNothing** [comment]
> Thank you for the report! Would you be able to fill out the information in [this template](https://github.com/SquidDev-CC/CC-Tweaked/blob/mc-1.15.x/.github/ISSUE_TEMPLATE/bug_report.md)?

it shows a 404 error

**Comment by SquidDev** [comment]
Oh sorry - I've updated my template but not the macro. Should be [this link](https://github.com/SquidDev-CC/CC-Tweaked/blob/mc-1.16.x/.github/ISSUE_TEMPLATE/bug_report.yaml)

**Comment by NullLikesNothing** [comment]
so should i redo this bug report?

**Comment by SquidDev** [comment]
If it's easier yes. You should have seen the template when creating the issue - just curious which link you followed to create one?

**Comment by NullLikesNothing** [comment]
i didnt see any template links should i close this and say to check a different post?

**Comment by SquidDev** [comment]
That's very odd. When I press the "New issue" button, I get taken to [this page](https://github.com/SquidDev-CC/CC-Tweaked/issues/new/choose):


![image](https://user-images.githubusercontent.com/4346137/126566242-cbb733a5-c418-417b-9514-580d7e04b7e3.png)

Where do you end up? Just would like to know for future reference!

But yes, probably worth closing this and that link instead.

**Comment by NullLikesNothing** [comment]
it just took me to the issue thing where you type it it

**Comment by SquidDev** [comment]
Hrmr. What OS and browser are you running? I can't get that to happen on mobile or desktop!

**Comment by NullLikesNothing** [comment]
i was using windows 10 on edge. i got off andbim on android chrome right now

**Comment by NullLikesNothing** [comment]
also it was my first ever issue report

**Comment by SquidDev** [comment]
OK, I've pushed a change which should fix things now. Would you be willing to try again?

**Comment by NullLikesNothing** [comment]
yeah

**Comment by SquidDev** [comment]
Thanks :).
