### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by NullLikesNothing** [SquidDev-CC/CC-Tweaked#867]
### Minecraft Version

1.16.x

### Version

1.97.0

### Details

Place a speaker down anywhere in the world and break it, if it doesn't work on single player try multiplayer, I did it on a server.

**Comment by SquidDev** [comment]
Would you be able to attach your crash log?

**Comment by NullLikesNothing** [comment]
i can later but not right now because i cant get on my laptop because another family member is using it

**Comment by NullLikesNothing** [comment]
[crash-2021-07-21_16.50.56-client.txt](https://github.com/SquidDev-CC/CC-Tweaked/files/6859198/crash-2021-07-21_16.50.56-client.txt)
heres the latest crash report

**Comment by SquidDev** [comment]
And fixed! Thank you for the report.
