### ISSUE TITLE
Monitors Break Shader Shadows

### ISSUE THREAD

**Issue by Simmotipo** [SquidDev-CC/CC-Tweaked#869]
### Minecraft Version

1.16.x

### Version

1.97.0 and 1.96.0

### Details

**Description**
Attaching monitors to a computer breaks shadows in any Optifine shader until the _monitors_ are broken. This occurs with any combination of Advanced/Regular computers and Advanced/Regular monitors, both connected directly and via modem (note: reproducing this via modem does not require a computer, only for a wired modem connected to the monitor and then enabled (via right click).

[Here's a short video demonstration unlisted on YT](https://youtu.be/MlVqrS-cOKs)

I didn't show it in the video, but breaking the computer (as opposed to the monitor) doesn't fix the shadows; only breaking the monitor does.

**Logs**
Here's the [latest.log](https://github.com/SquidDev-CC/CC-Tweaked/files/6869445/latest.log) file here for your reference*, and here's the specific [Log Excerpt.txt](https://github.com/SquidDev-CC/CC-Tweaked/files/6869444/Log.Excerpt.txt) for when the monitor is placed and the monitor shader info is loaded.

*Ignore all the "failed to load missing recipe" etc. etc.; I originally recorded the test video with all my mods on, then went back and tested again with just CC and Optifine to make sure it wasn't another mod causing a conflict (it was not), hence all the missing stuff lol

**Test Information**
- Tested in MC 1.16.5, using Forge 36.1.0
- Tested in CC-Tweaked 1.97.0 and 1.96.0
- Tested with Optifine 1.16.5 HD U G6, G7 and G8, and present in all three.
- Present with all shaders (Tested with a bunch of shaders to verify, namely: Continuum 1.3, Continuum 2.0, Robobo1221s Shaders, SEUS, SEUS PTGI E12 and SEUS PTGI HRR Test 2.1)
- Tested with OpenGL 4.6.0; and NVIDIA driver version 471.41

**Comment by SquidDev** [comment]
I'm afraid this a know bug and one I've no interest in fixing - I lost patience with optifine a long time ago. 

There's a workaround documented on the wiki (https://github.com/SquidDev-CC/CC-Tweaked/wiki/Monitor-renderers#monitors-are-partially-whitetransparent-with-shaders)whigh should fix things for you.

**Comment by Lupus590** [comment]
I would ~~talk to~~ ~~complain at~~ talk to the optifine developers about improving their mod compatibility. Releasing their source code and using a mod framework will help.

I might have a personal gripe against optifine's developer/developers and the way they license their mod and interact with the wider modding community.
