### ISSUE TITLE
Crashes when opening(or is it closing?) the neural connector

### ISSUE THREAD

**Issue by KingIonTrueLove** [SquidDev-CC/CC-Tweaked#87]
https://pastebin.com/RxX4PDg1
https://pastebin.com/6UpgxuMK

Pack: Enigmatica 2 Expert 1.46, which also uses CC:Tweaked
Version of Plethora: 1.1.13
Version of CC:Tweaked: 1.80

Tried to Ctrl-T to shutdown a program with the neural interface. Game crashed.
Tried taking off the neural interface bauble and putting it back on, then used the neural interface. Game crashed.

Edit: It's possible that just using the neural connector causes the crash.
Edit2: Yeah, it has nothing to do with trying to force-close a program. I was able to cause the crash just by trying to close out of a neural interface soon after opening it. (it may have been about to crash anyway)

Hard to do tests because the pack takes forever to load XD

**Comment by SquidDev** [comment]
This was a silly oversight on my part - sorry! It's a tad confusing remembering which bits of CC:T I need to preserve backwards compatibility on.

Anyway, I'll try to get a release out in a few days, but [this](https://www.dropbox.com/s/oxsz2b5czutcu9i/cc-tweaked-1.80pr1.12.jar?dl=1) should work for now.
