### ISSUE TITLE
Dynamic Peripheral update in-flight support.

### ISSUE THREAD

**Issue by SirEdvin** [SquidDev-CC/CC-Tweaked#871]
## What I want

Some way for CC: Tweaked addons to notify core system, that Dynamic Peripheral method list was changed. 
Currently only way you can do this in invalidate peripheral capability and make sure then previous peripheral are not equals to new one (which is lead us to dirty tricks). And even with this trick peripheral still need rewrap from lua code. 

## Use case

Pluggable architecture for peripherals without some cave-outs for users.

**Comment by SquidDev** [comment]
Can you not just return a different peripheral object, rather than mutating the existing one?

**Comment by SirEdvin** [comment]
oh, this seems correct ( Will try

**Comment by SirEdvin** [comment]
Main problem that peripheral are not mutated, tile entity are, but I guees, I need to review my architecture to avoid such problem
