### ISSUE TITLE
update to 1.17.1?

### ISSUE THREAD

**Issue by lostopkk** [SquidDev-CC/CC-Tweaked#878]
I know, this question can be very selfish because of the way it is seen by the entire mod community, but this question is very important to me who want to move a lot of mods from 1.16.5 to 1.17.1, I'm here more to know the Mod progress that seems to be going great!

(google translate brazilian to english)

**Comment by SquidDev** [comment]
Yes, eventually. Forge is still not in a production-ready state, so there's a few things I'm waiting for there.
