### ISSUE TITLE
A lot of server crash after the last update

### ISSUE THREAD

**Issue by LotuxPunk** [SquidDev-CC/CC-Tweaked#88]
- 1.12.2 - Forge 2768
 - CC: Tweaked version : 1.80pr1.12
 - No way to really reproduce this, I have just a crash report : https://pastebin.com/iy9dF0tB

**Comment by SquidDev** [comment]
That particular crash looks like the result of the server lagging too much. I'm not aware of any recent changes that would affect performance, so I'm not sure CC:T is to blame here.

**Comment by Lemmmy** [comment]
Also, if this is shortly after server startup, try setting `max-tick-time=-1` in `server.properties`.
