### ISSUE TITLE
Sidecar peripheral provided for block

### ISSUE THREAD

**Issue by SirEdvin** [SquidDev-CC/CC-Tweaked#884]
As I understand current system, there is only three ways to provide peripheral:
- Add capability to tile entity
- Implemented `IPeripheralProvider`
- Add generic capability for tile entity as side-car

Maybe, it is possible to add ability to provide peripheral for blocks?

**Comment by SquidDev** [comment]
`IPeripheralProvider` should allow you to do that already, no?

**Comment by SirEdvin** [comment]
Ah yes, shame on me. For some reason I think, that `IPeripheralProvider` is bound to tile entity.
