### ISSUE TITLE
[1.14] CC-Tweaked refuses to launch serverside... again.

### ISSUE THREAD

**Issue by Yoghurt4C** [SquidDev-CC/CC-Tweaked#89]
https://pastebin.com/NUGdLc98 (edit: had the wrong log attached)

18w50a, CC-Tweaked compiled from https://github.com/SquidDev-CC/CC-Tweaked/commit/c85493b3e0d866657db7da56d014ee50b3f11af3

**Comment by SquidDev** [comment]
Hopefully fixed in 378f0ae50550a01a5abeffc1bd9a09a758ee8312.
