### ISSUE TITLE
textutils.serialize recursion check has an edge-case.

### ISSUE THREAD

**Issue by fatboychummy** [SquidDev-CC/CC-Tweaked#898]
### Minecraft Version

1.16.x

### Version

1.98.0

### Details

An edge case exists in `textutils.serialize` currently where if you have two pointers to the same table inside a table, it will cause the `recursive entries` error -- even though it isn't recursive.

For example,
```lua
local x = {x = {}}
x.y = x.x

textutils.serialize(x) -- error!
```
In the above, it isn't actually recursive, however it causes the "Cannot serialize table with recursive entries" error.

**Comment by Kan18** [comment]
This might be intentional because there is an [`allow_repetitions` option](https://github.com/SquidDev-CC/CC-Tweaked/blob/mc-1.16.x/src/main/resources/data/computercraft/lua/rom/apis/textutils.lua#L658) that is set to `nil` by default, maybe it should be set to `true` by default?

**Comment by SquidDev** [comment]
Yep. See #636 for why the current behaviour is what it is.

**Comment by fatboychummy** [comment]
Ah, okay this makes a lot more sense now.
