### ISSUE TITLE
Limit HTTP API usage on Computers and Turtles

### ISSUE THREAD

**Issue by West7780** [SquidDev-CC/CC-Tweaked#905]
Being able to connect to the internet when you can't connect to other turtles or computers feels a bit like cheating. I believe it makes sense to limit connecting to the internet. Perhaps instead of just a Modem there could be a relatively expensive peripheral called a Gateway that a player could make to enable usage of the HTTP API on all computers with a Rednet connection to it. So as a player you would have to have a computer with a Gateway and then also a Modem which it could use to "share" the internet connection over Rednet. This would have the effect of encouraging players to either make a network or use more floppy discs. On top of all that it could be an optional feature.

**Comment by West7780** [comment]
I meant to use the feature request label, but my flight is boarding, I'll change it later if I remember.

**Comment by SquidDev** [comment]
While I do like to encourage people to build infrastructure around CC rather than having everything be magic, I do think http is the wrong thing to do it for.
