### ISSUE TITLE
Tweakable Turtle Commands

### ISSUE THREAD

**Issue by SirEdvin** [SquidDev-CC/CC-Tweaked#910]
Personally, I would suggest make most of turtle commands tweakable.

For example, TurtlePlaceCommand now can be used only to place block around turtle and if I want to improve this command to place block elsewhere, I need to copy and rewrite it,

**Comment by SquidDev** [comment]
> Some rationale/use case for a feature. My general approach to designing new features is to ask yourself "what issue are we trying to solve" and then "is this the best way to solve this issue?".

Please. :)

Sorry, just right now I'm not exactly clear what you want to be doing differently and thus what additional hooks you need. Are you working on an upgrade which allows turtles to place blocks anywhere??

**Comment by SirEdvin** [comment]
Something like this. In my case, this is upgrade that allow to execute batch place actions. Like, place on 3x3 area.

**Comment by SquidDev** [comment]
Looking at your `TurtlePlaceAction`, it feels like it might be more useful to provide some hooks for turtle permission stuff (though the events are gone in 1.17, so that'll be simpler soon) rather than the whole place command - you've got very little shared logic with CC:T there.

**Comment by SirEdvin** [comment]
I have implemented TurtlePlaceAction in such ugly way mostly because I don't quite understand what going on in TurtlePlaceCommand) 

So I consider just to make it simple place command, but I guess, this is quite temporary solution

**Comment by SquidDev** [comment]
Honestly, there's not anything I'd do differently. There's not much directly applicable from TurtlePlaceCommand:

 - Setting sign text doesn't really make much sense when placing multiple signs!
 - I don't _think_ you want to duplicate the place-on-to-entity code. That doesn't map well to multiple items.
 - Trying different place directions is something you _definitely_ don't want to be doing here, as that's going to make whatever ends up being placed incredibly inconsistent.
