### ISSUE TITLE
Draconic Energy Core

### ISSUE THREAD

**Issue by Giehek** [SquidDev-CC/CC-Tweaked#914]
Is there any way to get info about energy in draconic energy core because when im trying to connect wired modem to pylon it shows me energy in pylon, not in energy core. And my suggestion is: when you connect wired modem to pylon it should show informations about energy core because energy in pylon is useless

**Comment by SquidDev** [comment]
I'm afraid I'm don't currently have plans to add mod-specific integrations. It _might_ be worth filing an issue on AdvancedPeripherals and seeing if they're willing to have a look - not 100% sure how feasible it is on their end though.

**Comment by SirEdvin** [comment]
Hi, AP dev here. 

Please, take a note, that AP supports **only** 1.16 and 1.17 forge currently.

Issue tracker: https://github.com/Seniorendi/AdvancedPeripherals/issues
