### ISSUE TITLE
Player inventory does not update when interacting with terminal-less pocket computer

### ISSUE THREAD

**Issue by MAGGen-hub** [SquidDev-CC/CC-Tweaked#915]
### Minecraft Version

1.16.x

### Version

Future 1.99.1

### Details

When you open poket computer with no terminal and then pick up an item from ground - you can see it in player slots only after closing computer.
Here is a video:
P.S. (if item is new you can't see it to (i mean if I use non countable item in video i dot the same result))

https://user-images.githubusercontent.com/56871670/131585538-50cfda6e-8bb1-463e-8235-826fa1abc300.mp4

**Comment by Lupus590** [comment]
Could it be this feature? https://github.com/SquidDev-CC/CC-Tweaked/issues/861

**Comment by MAGGen-hub** [comment]
I don't think so. For some reason when ps is open picked up items won't be rendered... It's strange case when you use other guis (work bench) there is no such problem. Oh! I need to say that this problem appears when any terminals is open (even with gui). Strange... I need to dig deeper, case I saw this problem in other mods. May be it's just Screen.java problem?

**Comment by SquidDev** [comment]
Worth noting that this happens with any computer GUI (and amusingly the lectern in vanilla CC). 

It's just more obvious in this case as the hotbar is more visible. I suspect the fix here is that we add the player's hotbar slots to the base container, which will force them to be synced when the change.
