### ISSUE TITLE
Failed loading config file computercraft-client.toml of type CLIENT for modid computercraft

### ISSUE THREAD

**Issue by madmangenius5** [SquidDev-CC/CC-Tweaked#923]
### Minecraft Version

1.16.x

### Version

1.98.2

### Details

The game crashed whilst rendering overlay
Error: net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException:Failed loading config file computercraft-client.toml of type CLIENT for modid computercraft 
Exit Code: -1

[latest.log](https://github.com/SquidDev-CC/CC-Tweaked/files/7157903/latest.log)

**Comment by madmangenius5** [comment]
Also using forge 1.16.5 36.2.0

**Comment by SquidDev** [comment]
Can you try deleting the config file and restarting the game? It sounds like it's been corrupted.

**Comment by madmangenius6** [comment]
> Can you try deleting the config file and restarting the game? It sounds like it's been corrupted.

(I am in school replying to this on an alt) Where would I find the config?

**Comment by SquidDev** [comment]
Should be within `<your minecraft profile>/config/computercraft-config.toml`.

**Comment by madmangenius6** [comment]
(Still in school on alt) thanks!

> Should be within `<your minecraft profile>/config/computercraft-config.toml`.
