### ISSUE TITLE
Peripheral API ignores peripherals connected via non-adjacent modem

### ISSUE THREAD

**Issue by osmarks** [SquidDev-CC/CC-Tweaked#93]
If you have a modem on a peripheral network exposing some peripherals only accessible by `callRemote` etc. on that modem, and it's not adjacent to a computer, the peripheral API entirely ignores the peripherals connected to it - you can only access them by using `callRemote` on that modem, and can't directly `peripheral.call` or wrap them.

I don't think this comes up in CC on its own, but there appears to be some OpenComputers integration involving being able to remotely call OC peripherals via its Relay, which acts as a CC modem making available some peripherals. If a Relay is placed directly beside a computer its connected peripherals are detected and work fine, but if it's further away and connected by networking cable it itself will be detected but peripherals connected to it won't.

**Comment by SquidDev** [comment]
Can you provide some screenshots and/or example code. I'm really struggling to visualise what you're describing here.

**Comment by osmarks** [comment]
I was worried about that. Here are some screenshots, then.

Here, a peripheral is connected via a modem directly beside the computer. It works fine, you can wrap it directly, etc.

![2018-12-30_16 46 10](https://user-images.githubusercontent.com/10486993/50549324-bf6db380-0c52-11e9-8720-0515605b56d1.png)
![2018-12-30_16 46 12](https://user-images.githubusercontent.com/10486993/50549330-d9a79180-0c52-11e9-9c9d-38361ffb54e7.png)

But if I have a modem only connected to the computer via another modem, you can't - you can wrap the modem itself and call its functions, but the stuff connected to it's not available.

![2018-12-30_16 46 17](https://user-images.githubusercontent.com/10486993/50549343-14112e80-0c53-11e9-8aae-1ebf598d82b4.png)
![2018-12-30_16 46 14](https://user-images.githubusercontent.com/10486993/50549341-f6dc6000-0c52-11e9-900a-3c017dca6b15.png)
