### ISSUE TITLE
crashes when i load up world with the mod in the mod folder

### ISSUE THREAD

**Issue by EeriShimi** [SquidDev-CC/CC-Tweaked#933]
### Minecraft Version

1.16.x

### Version

1.98.2

### Details

well basically it crashes everytime i actually try and load up a world
[crash-2021-10-03_14.07.41-server.txt](https://github.com/SquidDev-CC/CC-Tweaked/files/7273410/crash-2021-10-03_14.07.41-server.txt)
l

**Comment by SquidDev** [comment]
Can you try uninstalling jmt-mcmt and trying again?
