### ISSUE TITLE
Modems disappear when moved by create

### ISSUE THREAD

**Issue by Schattengaenger** [SquidDev-CC/CC-Tweaked#948]
### Minecraft Version

1.16.x

### Version

1.98.2

### Details

Hi,

I play a modpack and wanted to make an elevator programm with this mod using creates contraptions.
I ran into a bug that only happens when it meets some unknown conditions but they are reproducable.
I reportet the bug to the modpack's maker and he asked me to relay it to here and creates issue report system.

Below you will see a picture of a contraption able to reproduce the bug. The green stuff is super glue which create uses to attach blocks to a contraption. It enters the moving block state fine and displays everything right until it stops again where it delets the same modems every time while keeping others. I placed the modems all around (except top, but I believe the results would be similar there, too) and every place you can see the glue is a modem deleted, not even broken and on the floor, but vanishing from existance. The picture was taken in a singleplayer world with a forge profile ONLY containing create (, it's nessesary fly wheel mod) and CC: Tweaked as mods, but the results don't differ on a server either. 

I hope you can help here,
Sincerely, Manny
![2021-10-28_00 55 12](https://user-images.githubusercontent.com/92960783/139159774-8733ac1f-a701-4d9c-bd6f-ac993a567cc9.png)

[latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/7429829/latest.log)

**Comment by Schattengaenger** [comment]
> I guess, you can try to move full-block modem

Are you refering t the wired modem? If yes, than yeah it doens't break, but I need a wireless modem there and not a wired one. And while there are workarounds like mirroring the design in a way where it doesn't break in the direction I want to attach a modem to, It's still a bug that should be fixed eventually or do you disagree?

**Comment by Flexico** [comment]
As workaround, I place the modem on either the top or bottom of the computer. They only disappear when on the side!

**Comment by luigistyle** [comment]
> As workaround, I place the modem on either the top or bottom of the computer. They only disappear when on the side!

This doesn't seem to work for me. As soon as the contraption stops moving, the modem immediately disappears. I've tried placing it on the front, top, and bottom of the computer to no avail. Is there any update to this issue on either the CC or Create side of things?

EDIT: Putting it on the back works nvm lmao

**Comment by getertext** [comment]
This issue is not just for Create, it's for WorldEdit as well. It happens when an object is rotated, (With World edit it's with //rotate [angle] and with create is mechanical bearing) thus it might be a CCT issue or the other way around: they both have inconsistent rotation issues (which might be more likely), however, it's most likely to be a CCT side of issues due to strange metadata infrastructure (Proper: `/setblock ~ ~ ~ minecraft:dispenser[facing=west]`, Improper: `/setblock ~ ~ ~ jimsmod:laucher[direction=left, open=left]`).

**Comment by Plite7067** [comment]
Just made a datapack to fix this: https://github.com/Plite7067/CreateCCModemFix
It adds the tag "#create:brittle" to them, which seems to fix the issue.

**Comment by SquidDev** [comment]
Thank you for looking into this, that was very helpful! I have added a similar fix to CC itself.
