### ISSUE TITLE
Flickering issue with Shaders

### ISSUE THREAD

**Issue by PortalInTime** [SquidDev-CC/CC-Tweaked#95]
When playing with CC Tweaked installed, I keep seeing a flickering effect with rendered shadows. Removing CC Tweaked gets rid of this effect. The problem persists when switching through other shaders, I've tried 5 or so total. Additionally, the monitor screens are brown, too. The brown tint varies from shader to shader.

Important information:
- Minecraft 1.12.2
- CC Tweaked 1.80pr1.12
- Windows 8.1
- Java 8 update 191 (64 bit)
- Graphics card is NVIDIA GeForce GTX 1060 6GB
- [My Mod List (I apologize for the lengthy list)](https://github.com/PortalInTime/Mod-List/blob/master/1.12.2)

**Comment by SquidDev** [comment]
Just a couple of other things worth trying:

 - Does it occur with just CC, Optifine and shaders?
 - Is the flickering related to when specific blocks are in the viewport, or does it occur just when installing the mod?
 - Can you provide a list of shaders you've tried?

> Additionally, the monitor screens are brown, too. The brown tint varies from shader to shader.

Nothing I can do about that sadly. There's a bit more of an explanation in dan200/ComputerCraft@b7950a4209ef8b50a73f2ba2be8bea9baa90c23a and dan200/ComputerCraft#534, but we have to do some weird things to get monitors to render at all under shaders, which has the side effect of tinting them orange.

I'm afraid I'm rather reliant on the community fixing shader bugs - I'm using Intel Integrated Graphics, which means a good portion of shader packs just don't run on my computer, which rather makes it impossible to test anything. Sorry!

**Comment by PortalInTime** [comment]
Does it occur with just CC, Optifine and shaders?
Is the flickering related to when specific blocks are in the viewport, or does it occur just when installing the mod?
Can you provide a list of shaders you've tried?

- Yes, the problem persists with only Optifine, CC Tweaked, and Shaders.

- The problem persists with the mod installed but no CC Tweaked blocks in the world.

- The problem DOESN'T persist when CC Tweaked isn't installed.

List of Shaders Used:

1. BSL 7.1

2. CYBOXshaders V4 ULTRA MotionBlur

3. SEUS Renewed 1.9.9

4. Chocapic13 V6 Ultra

5. Continuum 2.0.2

**Comment by SquidDev** [comment]
> The problem persists with the mod installed but no CC Tweaked blocks in the world.

Gah. This makes absolutely no sense. CC:T doesn't do any additional rendering outside of its own blocks/tiles, so I can't think of what would be causing the flicker at all.

**Comment by SquidDev** [comment]
I'm going to flag this as "Cannot reproduce" for now, as I'm physically incapable of running the shaders required and I don't think it's occurred to anyone else.

If anyone else has this issue, and/or is able to help out, comment and I'll reopen.

**Comment by Lana-chan** [comment]
I can still confirm a similar issue using:
Minecraft 1.16.5
Forge 36.0.1
CC:Tweaked 1.95.2
Sildur's Vibrant shaders v1.283 Medium

Whenever monitors are active (after displaying something on them such as `monitor top motd` for example) and within the render frame (even through walls), all entities (monitor screen, chests, signs, etc) appear very light. The entities return to normal as soon as I look away from the monitor.

I have some very basic understanding of GLSL and I'm a programmer by trade, though I've never tried Minecraft development. I'm willing to volunteer to try helping troubleshoot the issue if I can.

**Comment by SquidDev** [comment]
@Lana-chan Just to check, are you using the VBO or TBO renderer (see https://github.com/SquidDev-CC/CC-Tweaked/wiki/Monitor-renderers)? Switching to VBO _should_ fix most shader issues. 

If you're still having the bug, could you open a new issue with screenshots. That sounds like a bit of a different issue to the OP, so probably worth tracking separately.

**Comment by Lana-chan** [comment]
Switching to VBO worked perfect, thanks!

Sorry, I got here from issue #37 and figured I'd comment here since it was newer, without fully reading through the issue to notice it was different, my bad.
