### ISSUE TITLE
[Request] Configurable Harvest Levels for the Turtle

### ISSUE THREAD

**Issue by NillerMedDild** [SquidDev-CC/CC-Tweaked#97]
Hello!

I would like to suggest a config for adjusting the harvest levels of mining Turtles. One of my packs adds a lot of new harvest levels, making the max level 14. As a side effect, the Advanced Mining Turtle with it's harvest level of 4 is nearly useless, as it can only harvest Stone and low tier ores.

I imagine it would work be something like
`# Set the harvest level of Turtles [default: 4]`
 `turtle_harvest_level=int`

**Comment by SquidDev** [comment]
I'm going to have to think a little bit about how this'd work. CC doesn't actually consider harvest levels directly - it calls `Block.canHarvestBlock`, which will then compare the upgrade's item harvest level (so a diamond pick) with the block's.

I'm not really sure of a nice alternative here, though a couple spring to mind:

 - Overwrite the upgrade item's harvest level/material while the turtle breaks a block. This is a rather grim solution, so I'd rather avoid it where at all possible.

 - Allow specifying which tools are used to actually perform the breaking. So if there's a better pickaxe in your pack, it could be deferred to. This could end up being quite messy as far as configuration goes though.

I'd appreciate any comments on this - I've not really looked into higher harvest levels, so really not sure how they're expected to behave across various mods.

**Comment by NillerMedDild** [comment]
The latter might work - Could the Turtle be able to tell the harvest level of a Tinkers' Construct Pickaxe, if it was upgraded with it?

However, if those two options are the only ones available to you, I don't think you should go through with it. Turtles respecting which blocks it may actually harvest is more important than not being able to harvest some, imo.
